### ISSUE TITLE
Installing new packages without rebuilding docker

### ISSUE THREAD

**Issue by fleverest** [gibiansky/IHaskell#1000]
It takes several hours to rebuild a docker container after updating the stack.yaml file to install packages, so it would be very convenient if it were possible to do so within a running container.

Specifically what I would like to be able to do on my notebook is to add a package using only a terminal in the notebook itself (New>Terminal in the iHaskell notebook 'index' page).

I can navigate to ihaskell and edit the stack.yaml file in the notebook app easily enough, and then I can open a terminal and run `stack solver` and `stack install` without any issues at all. Even after running `ihaskell install --stack` I cannot seem to import any of the modules I thought I'd just installed to my notebooks. Any ideas on how to get this approach to work? 

EDIT: I also noticed that one package I was trying to install (random-1.1) was already in the ihaskell dependencies but cannot be imported in the notebook. I'm not sure if this is by design or not so any insight would be appreciated.

**Comment by vaibhavsagar** [comment]
Try this:

1. Open a new terminal.
2. `stack new foo` in the terminal.
3. Edit `foo.cabal` to add dependencies.
4. Run `stack build` in the terminal from within the `foo/` directory.
5. Navigate to the `foo/` directory and open a new IHaskell notebook there.
6. The dependencies you added should be in scope.

I just tried this with `fgl` and it seemed to work fine.

**Comment by fleverest** [comment]
I'll give it a shot when I'm back home - thanks for the help, I appreciate it!

**Comment by fleverest** [comment]
So I've encountered an issue unrelated to the original question I posed. I access my notebook remotely, so I have it running in a docker container on a server which I can't access from outside my home network. Therefore I really don't want to stop the container from running, and I also want my notebook to be port 8888.

Because of this, I can't really open a new notebook from the terminal. If I close the first notebook, the docker container will stop regardless of what I do (my first attempt was to run `pkill jupyter && jupyter notebook --ip 0.0.0.0`) but as soon as the first instance closed the docker container exited immediately before running the second notebook. I will try to play around with the dockerfile later to see if I can make it work for my particular situation.

**Comment by vaibhavsagar** [comment]
You can open a new terminal and edit files from within Jupyter, without closing your original notebook. That's how I did it on mybinder.org.

**Comment by fleverest** [comment]
Right, I misinterpreted your instruction - sorry!

Now that I try what you really suggested, it seems to fail to start the kernel. On the server I'm seeing the following:

`[I 13:36:24.648 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
ihaskell: Bad interface file: /home/jovyan/.stack/programs/x86_64-linux/ghc-8.6.3/lib/ghc-8.6.3/base-4.12.0.0/Prelude.hi
    mismatched interface file versions (wanted "8044", got "8063")
Bad interface file: /home/jovyan/.stack/programs/x86_64-linux/ghc-8.6.3/lib/ghc-8.6.3/directory-1.3.3.0/System/Directory.hi
    mismatched interface file versions (wanted "8044", got "8063")
Bad interface file: /home/jovyan/.stack/programs/x86_64-linux/ghc-8.6.3/lib/ghc-8.6.3/unix-2.7.2.2/System/Posix/IO.hi
    mismatched interface file versions (wanted "8044", got "8063")
Bad interface file: /home/jovyan/.stack/programs/x86_64-linux/ghc-8.6.3/lib/ghc-8.6.3/base-4.12.0.0/System/IO.hi
    mismatched interface file versions (wanted "8044", got "8063")
Bad interface file: /home/jovyan/.stack/programs/x86_64-linux/ghc-8.6.3/lib/ghc-8.6.3/template-haskell-2.14.0.0/Language/Haskell/TH.hi
    mismatched interface file versions (wanted "8044", got "8063")
`

**Comment by fleverest** [comment]
This is really curious, I did what you suggested on Mybinder.org and it was a perfect solution (so you've solved my initial problem - thank you very much!), but for some reason I can't open any kernels in directories aside from the jovyan/ihaskell/ directory. In the latter, everything works exactly how you would expect it to (I can import the packages listed as dependencies in ihaskell.cabal)

**Comment by vaibhavsagar** [comment]
With the error you're seeing, it looks like that's because you're running a GHC 8.4 IHaskell and your project resolver is `lts-13`, i.e. GHC 8.6 and you're running into [this](https://github.com/gibiansky/IHaskell#the-kernel-keeps-dying-ihaskell--stack). If you change the resolver to e.g. `lts-12.26` it shoudl continue to work again.

**Comment by fleverest** [comment]
Alright, well as soon as I've rebuilt iHaskell I'll give that a go. For now I think you've helped me more than enough, considering there were no real technical issues but more my poor understanding of how the notebook actually works. Cheers!
