### ISSUE TITLE
problem reading ~/.ihaskell/.last-req-header

### ISSUE THREAD

**Issue by MMesch** [gibiansky/IHaskell#1002]
I tried to use the funflow library with IHaskell and Jupyterlab that I installed through nix. Funflow causes IHaskell to crash because it tries to access some file in the home folder:

```
ihaskell: getInputLine: Failed reading /home/mat/.ihaskell/.last-req-header
CallStack (from HasCallStack):
  error, called at src/IHaskell/IPython/Stdin.hs:93:27 in ihaskell-0.9.1.0-AVDiOp5Zr4HIOqgOKi8hL:IHaskell.IPython.Stdin
```

is it possible to change this directory somehow? How can it happen that this file doesn't exist?

here is the notebook and the shell.nix that is required to set things up: https://github.com/tweag/jupyterWith/tree/master/example/Haskell/Funflow

here are the lines that define this directory
https://github.com/gibiansky/IHaskell/blob/master/src/IHaskell/IPython.hs#L88-L95

here are some lines that write file `.last-req-hdr` which is different to `.last-req-header`:
https://github.com/gibiansky/IHaskell/blob/051e889ade344a40347b2db9e24c5226b58299d/src/IHaskell/IPython/Stdin.hs#L104-L106

here this file is called `/.last-req-header`:
https://github.com/gibiansky/IHaskell/blob/051e889ade344a40347b2db9e24c5226b58299d2/src/IHaskell/IPython/Stdin.hs#L90-L98

**Comment by vaibhavsagar** [comment]
Sure, you can change the directory by setting `$HOME` differently:

https://github.com/gibiansky/IHaskell/blob/13632726fe004db0e2869b8666a48da1be79d5f6/src/IHaskell/IPython.hs#L89-L92

**Comment by vaibhavsagar** [comment]
I see that you found the same lines, so I'm not sure what the issue is here. What needs to be different?

**Comment by MMesch** [comment]
maybe there is some inconsistency with the name of `.last-req-hdr` and `.last-req-header` (see above). Any idea?

**Comment by vaibhavsagar** [comment]
Good sleuthing! The contents seem to be subtly different though:

```
[vaibhavsagar@nixos:~/repos/IHaskell]$ cat ~/.ihaskell/.last-req-hdr 
MessageHeader {mhIdentifiers = ["f5018e9e9e0b41c196766b1e4b04091d"], mhParentHeader = Nothing, mhMetadata = Metadata (fromList []), mhMessageId = UUID {uuidToString = "f37c9c615bd548eb9c8c62c774e8e6a6"}, mhSessionId = UUID {uuidToString = "f5018e9e9e0b41c196766b1e4b04091d"}, mhUsername = "username", mhMsgType = ExecuteRequestMessage}
[vaibhavsagar@nixos:~/repos/IHaskell]$ cat ~/.ihaskell/.last-req-header
MessageHeader {identifiers = ["dd5acf5d02e24d578894a06ed2f3ca04"], parentHeader = Nothing, metadata = fromList [], messageId = UUID {uuidToString = "6550179eb24741b598f6ed21a36d31dd"}, sessionId = UUID {uuidToString = "dd5acf5d02e24d578894a06ed2f3ca04"}, username = "username", msgType = ExecuteRequestMessage}
```

Maybe we broke something recently?

**Comment by vaibhavsagar** [comment]
Looks like this might have changed when we tried to fix all warnings: https://github.com/gibiansky/IHaskell/commit/196ccac96d6164637d830c7afc9c6dcb13b9db4b

**Comment by MMesch** [comment]
yea that looks like it! Do you want to fix it?

**Comment by MMesch** [comment]
it seams that `.last-req-header` was the original name ...

**Comment by MMesch** [comment]
cool thanks. I'll try it immediately. I am not sure why I only saw this error with funflow and not with other libs ...

**Comment by MMesch** [comment]
seems to be fixed, even though I have a different problem now with funflow ...

**Comment by MMesch** [comment]
I accidentally used readLine and therefore StdIn through funflow. I think that's why this error suddenly appeared.

**Comment by vaibhavsagar** [comment]
Good to know! Does funflow work in IHaskell otherwise?
