### ISSUE TITLE
Backpack support

### ISSUE THREAD

**Issue by imalsogreg** [gibiansky/IHaskell#1012]
It seems that libraries using backpack can't be used in ihaskell notebooks.

https://github.com/imalsogreg/backpack-regex-example/tree/ihaskell has a library called `str-impls` that exports `Str.String`. I would expect that running `nix-shell ihaskell.nix --run "ihaskell-notebook", then creating a Haskell notebook and running `import Str.String` would work. However I get the error:
```
<interactive>:1:1: error:
    Could not find module `Str.String`
    Perhaps you meant Data.String (from base-4.11.1.0)
    Use -v to see a list of the files searched for.
```
In a private project, I got a similar error for a backpack'd library _on a module that is listed in the tab-completion selector_! I wasn't able to reproduce that behavior here, though.

**Comment by vaibhavsagar** [comment]
I think this has been fixed after https://github.com/gibiansky/IHaskell/pull/1280 for GHC 9.0. Using that commit and https://github.com/danidiaz/really-small-backpack-example at `1c693c287949b49d5df53630075ad656933fd4bb` I was able to run:

```
vaibhavsagar@nixos-t480:~/repos/IHaskell$ nix-build release-9.0.nix
<...>
/nix/store/ayaq1jl8nzcl7wg1b6p03ydb12fgn7q3-ihaskell-with-packages
vaibhavsagar@nixos-t480:~/repos/IHaskell$ cd ../really-small-backpack-example/
vaibhavsagar@nixos-t480:~/repos/really-small-backpack-example$ nix-shell -p haskell.packages.ghc901.ghc cabal-install
[nix-shell:~/repos/really-small-backpack-example]$ cabal build all
<...>
[nix-shell:~/repos/really-small-backpack-example]$ cabal exec -- /nix/store/ayaq1jl8nzcl7wg1b6p03ydb12fgn7q3-ihaskell-with-packages/bin/jupyter-notebook
<...>
```
and execute these commands: 
![backpack_siggy](https://user-images.githubusercontent.com/1525767/135746156-a3947eaf-3115-46dd-b4e8-279506502ed9.png)

If you are still having issues, please reopen this or create a new issue.
