### ISSUE TITLE
JupyterHub / Docker integration requires some undocumented steps

### ISSUE THREAD

**Issue by cburschka** [gibiansky/IHaskell#1013]
(Sorry if this is not the right project to report it to, or if it's caused by something I'm doing incorrectly in my own setup.)

In order to add a Haskell kernel to my JupyterHub setup, I added the following to my Docker file, as derived from the Readme. (My base Docker image is `jupyter/datascience-notebook`, which is why I can't simply use the provided `ihaskell` image instead of building it.)

```Dockerfile
USER root
RUN apt-get update && apt-get install -y \
        python3-pip \
        git \
        libtinfo-dev \
        libzmq3-dev \
        libcairo2-dev \
        libpango1.0-dev \
        libmagic-dev \
        libblas-dev \
        liblapack-dev
RUN curl -sSL https://get.haskellstack.org/ | sh

USER jovyan
ENV PATH=$HOME/.local/bin:$PATH
RUN git clone https://github.com/gibiansky/IHaskell
RUN cd IHaskell && pip3 install -r requirements.txt
RUN cd IHaskell && stack install --fast
RUN ihaskell install --stack
```

However, the resulting Docker image's Haskell kernel doesn't yet work. The first issue is that it can't find `ghc-pkg` in its PATH. This is because stack installs the ghc binaries in `$HOME/.stack/x86_64-linux/programs/ghc-8.6.3/bin` - I used a (very brittle) workaround of adding 

```Dockerfile
ENV PATH=$PATH:$HOME/.stack/x86_64-linux/programs/ghc-8.6.3/bin
```

The second problem is that starting the kernel (by opening a Haskell notebook) creates a new `.stack/global-project/stack.yaml` from scratch, defaulting to a newer build plan (13.11) than the IHaskell one (13.6), and downloading ghc 8.6.4 even though the ihaskell kernel was already compiled with 8.6.3. I'm currently working around this by first copying the IHaskell `stack.yaml` to `$HOME/.stack/global-project/stack.yaml`, to ensure the same compiler is used.

**Comment by cburschka** [comment]
Update: I now suspect that whatever is starting ihaskell should have been using `stack exec ihaskell` instead of `ihaskell` in order to run it in the correct environment, but I'm not sure where this happens or where the change must be made.

**Comment by vaibhavsagar** [comment]
Have you looked at https://github.com/gibiansky/IHaskell/blob/master/Dockerfile? It sets the `PATH` so that `stack exec` is not required. The other issue is because the Stackage LTS has been updated to use GHC 8.6.4, which I've opened https://github.com/gibiansky/IHaskell/blob/master/Dockerfile to fix. For the `IHaskell.Display` modules you have to open an IHaskell notebook in the `ihaskell/` directory.

**Comment by cburschka** [comment]
Thanks so much! I overlooked that the Dockerfile to build the image was right here in the same repository :) I can check this for what else I need to do in my own Dockerfile to get a working image.

Is there a way to make the IHaskell modules available in any working directory? Data stored outside `$HOME/work` is not persistent in JupyterHub.

**Comment by vaibhavsagar** [comment]
Sure, you can create a new project with `stack new` and put whatever modules you want in your `stack.yaml`.

**Comment by vaibhavsagar** [comment]
Closing this, please reopen if necessary.

**Comment by jamesdbrock** [comment]
See also https://github.com/jamesdbrock/ihaskell-notebook
