### ISSUE TITLE
Completion does not work under JupyterLab?

### ISSUE THREAD

**Issue by ttylec** [gibiansky/IHaskell#1017]
I managed to make ihaskell work with jupyterlab (I really need the vega support), with current master from github. So that syntax coloring works. But code completion does not. Is it only me (i.e. I messed something), or is it totally unsupported for jupyterlab? 

And if so, can someone give some guidance where to start if I would like to add it?

**Comment by vaibhavsagar** [comment]
I don't think it's you, I couldn't seem to get it working either. @MMesch might know how to fix this.

**Comment by MMesch** [comment]
I don't have it working either. I never tried to get it working and unfortunately I don't even know where to start out of my head. It might be easy.

**Comment by vaibhavsagar** [comment]
I tried this recently and code completion seems to work for me. Please reopen if this is still an issue with the latest version of JupyterLab.
