### ISSUE TITLE
How to install for all users on macOS?

### ISSUE THREAD

**Issue by wstomv** [gibiansky/IHaskell#1018]
I installed IHaskell on my admin account (in macOS), and want to use it under other accounts as well. But the IHaskell kernel does not seem to be available for other users.

How can I install IHaskell for all users on macOS?

Or must it be installed for each user separately?

How can I uninstall it (from my admin account)?

**Comment by vaibhavsagar** [comment]
How did you install it? Stack puts the `ihaskell` executable in `~/.local/bin`, and `ihaskell install` puts `kernel.json` in `~/.local/share/jupyter/kernels/haskell/kernel.json` so you can move the executable to some other location on your `$PATH` and `stack exec -- ihaskell install` for each user you want IHaskell to be available for. 

To uninstall, it's enough to remove the `~/.local/share/jupyter/kernels/haskell` directory, IIRC that's the only thing `ihaskell install` does.

**Comment by wstomv** [comment]
I installed as per the macOS instructions in the readme on the IHaskel repo.

My jupyter was installed in `/anaconda3/share/jupyter/` (not `~/.local/share/jupyter/`), but there in `kernels/`, I only find `python3/` (no `haskell/`). In fact, I cannot find any `kernel.json` for Haskell (they are all for `python3`. Still, IHaskell works.

In summary, for uninstalling, you remove
* the clone of the IHaskell git repo
* the `haskell/` directory in `.../share/jupyter/kernels/` (though, I wasn't able to find that)
* the executable `~/.local/bin/haskell`

**Comment by vaibhavsagar** [comment]
The `kernel.json` has to exist for IHaskell to work. Maybe it's in a different location? Otherwise your list of things to uninstall seems correct to me.

**Comment by vaibhavsagar** [comment]
Closing this.
