### ISSUE TITLE
Kernel keeps dying

### ISSUE THREAD

**Issue by tmcdonell** [gibiansky/IHaskell#1019]
# Description

I'm trying to get Accelerate running with IHaskell but am running into the problem that _some_ functions from `llvm-hs` are causing the kernel to crash. I attach a minimal reproducible test case, but I'm new to IHaskell and Jupyter notebooks and don't know how to debug this further.

# Expected behaviour

The repository [here](https://github.com/tmcdonell/ihaskell-bug) contains a minimal project which demonstrates the bug. The included notebook should run without error, but the last cell always crashes for me. The notebook contains a few notes to explain what is going on.

# Steps to reproduce

  1. Clone repository https://github.com/tmcdonell/ihaskell-bug
  1. `stack build` to build dependencies. You'll need llvm-8 installed.
  1. `stack install ihaskell` (it's just the version from HEAD)
  1. `ihaskell install --stack`
  1. `jupyter notebook --debug Bug.ipynb`
  1. run all cells

The kernel will die executing the last cell, but I don't get any error message printed to console (despite --debug)

# Environment

  1. stack version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1
  1. macOS 10.14.3
  1. jupyter version 4.4.0 (via Anaconda distribution 2018.12)

I tried a few other configurations (installing jupyter via homebrew, ghc-8.4.4, llvm-7...) but the result is unchanged.

**Comment by vaibhavsagar** [comment]
I primarily use NixOS, so it'll be a bit involved for me to reproduce this, but it's definitely on my radar.

**Comment by vaibhavsagar** [comment]
Thanks for your patience! I wasn't able to reproduce this, and `llvm-hs` worked correctly for me: https://gist.github.com/vaibhavsagar/378115ea003f037c7f4c3fbe237bbf65

**Comment by vaibhavsagar** [comment]
I'm going to go ahead and close this, please feel free to reopen if necessary!

**Comment by tmcdonell** [comment]
"Install nix" is not a practical solution. I understand that you don't have time to work on this, but it is still an open problem.

**Comment by vaibhavsagar** [comment]
I agree, but my inability to reproduce it suggests that there isn't a problem with IHaskell. What would you like me to do?

**Comment by tmcdonell** [comment]
> What would you like me to do?

As I said: nothing. But it's a comment left in case somebody else runs into this problem, they can see it was not solved.

It indeed might not be an IHaskell problem. But I also did ask you to help me debug it, so if you have actual suggestions I'm willing to listen.

**Comment by vaibhavsagar** [comment]
Did you try using Nix?

**Comment by vaibhavsagar** [comment]
Suggestion: does this work correctly in GHCi?

**Comment by tmcdonell** [comment]
I haven't had a chance to install nix yet to try, but the original test program works through docker, so I would expect this to work in nix as well. Still, I really don't want to have to tell my users to install nix (or docker) in order to use IHaskell.

The code works when run directly in ghci, yes. Most of my Accelerate development happens in ghci; I haven't had any problems running in ghci vs. compiled. Is IHaskell using ghci-as-a-library in order to run expressions? Is there an easy/simplified way I can replicate by hand what IHaskell would do to run a snippet?

**Comment by vaibhavsagar** [comment]
Unfortunately not, as IHaskell essentially reimplements most of GHCi (e.g. [`Evaluate.hs`](https://github.com/gibiansky/IHaskell/blob/cce4cb466095104d4a30cc23dd1b8ff3042b3a0f/src/IHaskell/Eval/Evaluate.hs)). Conda has definitely been the source of issues in the past though, so would you be able to try installing Jupyter a different way and seeing if that leads to a different result?

**Comment by vaibhavsagar** [comment]
I'm closing this, happy to debug further if we meet in person.
