### ISSUE TITLE
Dockerfile ENV PATH

### ISSUE THREAD

**Issue by jamesdbrock** [gibiansky/IHaskell#1022]
This line in the `Dockerfile`:

https://github.com/gibiansky/IHaskell/blob/60fceecc7edb76645d158dce1c801cfc59fb6d70/Dockerfile#L59

Results in this `PATH` in the container. I think these bash command substitution arguments don't get evaluated in `PATH`, so this will not have the intended effect on the `PATH`.

I don't know of any good way to set a `Dockerfile ENV` with a command from the container context, so I'm not sure what should be done instead. The notebook container still seems to work, though, even with this `PATH`.

```
jovyan@dbd2de6954af:~$ echo $PATH | tr ':' '\n'
/opt/conda/bin
$(stack path --local-install-root)/bin
$(stack path --snapshot-install-root)/bin
$(stack path --compiler-bin)
/home/jovyan/.local/bin
/opt/conda/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
```

**Comment by vaibhavsagar** [comment]
Thanks for pointing this out! This is definitely different from what I expected, and it's especially strange that it continues to work. As you can probably tell, my understanding of Docker is fairly limited. I'll leave this open until I (or someone else) can fix this.

**Comment by vaibhavsagar** [comment]
I tried:

- surrounding the value in double quotes
- replacing the parentheses with curly braces

but neither of those approaches worked.

**Comment by vaibhavsagar** [comment]
Closing as this doesn't appear to be an issue in practice.
