### ISSUE TITLE
Stackage LTS resolver > lts-12.26

### ISSUE THREAD

**Issue by jamesdbrock** [gibiansky/IHaskell#1023]
`ihaskell` stopped appearing in Stackage snapshots after __lts-12.26__ on 2018-12-20. Let's talk about that.

https://www.stackage.org/package/ihaskell/snapshots

**Comment by jamesdbrock** [comment]
Oh, the next LTS is __lts-13.1__, which upgraded to from __GHC 8.4.4__ to __GHC 8.6.3__. Probably that minor version bump is the cause.

The `IHaskell/stack.yaml` specifies resolver __lts-13.12__, which works fine, so this is probablly some minor maintenance issue.

**Comment by vaibhavsagar** [comment]
I haven't pushed a new release to Hackage that's compatible with GHC 8.6 yet.

**Comment by jamesdbrock** [comment]
Thank you @vaibhavsagar , for all the time and effort that you're spending on IHaskell. I know you're super busy. Your work on IHaskell has helped me personally a lot, and I especially appreciate your quick responses on GitHub.

The current `stack.yaml` specifies `resolver: lts-13.12` which is a __GHC 8.6.4__ resolver, and I'm running IHaskell built with that resolver and it works great. I'll try to figure out why IHaskell build failed on Hackage.

http://hackage.haskell.org/package/ihaskell-0.9.1.0/reports/2

**Comment by vaibhavsagar** [comment]
Thanks for the kind words :smile:. I expect to have time to push a new release this weekend. The code on `master` is several months ahead of `ihaskell-0.9.1.0`, and so far nobody has asked for a new release on Hackage so I've put off doing it. There have also been a few bigger changes so I'm unsure what the version number of the next release should be, which is another reason that I haven't just gone ahead and done it yet.

**Comment by vaibhavsagar** [comment]
I've pushed new releases of [`ihaskell`](http://hackage.haskell.org/package/ihaskell-0.10.0.0), [`ipython-kernel`](http://hackage.haskell.org/package/ipython-kernel-0.10.0.0), and [`ghc-parser`](http://hackage.haskell.org/package/ghc-parser-0.2.0.3).

**Comment by vaibhavsagar** [comment]
I've opened https://github.com/commercialhaskell/stackage/pull/4503

**Comment by vaibhavsagar** [comment]
Merged! I'm closing this.
