### ISSUE TITLE
IHaskell overwrites "autoCloseBrackets" setting

### ISSUE THREAD

**Issue by eschnett** [gibiansky/IHaskell#1025]
I like to switch off `autoCloseBrackets` in JupyterHub, using a setting such as this in my `~/.jupyter/nbconfig/notebook.json`:
```JSON
  "CodeCell": {
    "cm_config": {
      "autoCloseBrackets": false
    }
```

This does not work with IHaskell since IHaskell unconditionally overwrites this setting in its `html/kernel.js` files:
```JavaScript
                IPython.CodeCell.options_default['cm_config']['autoCloseBrackets'] = '()[]{}';
```
```JavaScript
                            c.code_mirror.setOption('autoCloseBrackets', '()[]{}');
```

I confirmed that removing these two lines, then re-instaling IHaskell makes my `autoCloseBrackets` setting work.

I assume that these two lines try to set which characters should be auto-close brackets, excluding the quote characters that would otherwise have the same behaviour. (... why?) I think (but am not sure) that these lines are setting the wrong variable. Maybe they should be setting `closeBrackets` instead (no `auto` prefix?) See also <https://codemirror.net/addon/edit/closebrackets.js>.

**Comment by vaibhavsagar** [comment]
Closed by a8931ad7c19e25a5f31ef69fcb5521b8d6e65134.
