### ISSUE TITLE
Freebsd

### ISSUE THREAD

**Issue by devosalain** [gibiansky/IHaskell#1026]
Is it possible to make it work on Freebsd ? Yes,no,how ?
[PS: IJulia works nice on Freebsd]

**Comment by vaibhavsagar** [comment]
I don't expect there to be any issues. You can install the system dependencies, install `stack`, and follow the rest of the instructions.

**Comment by devosalain** [comment]
Managed to get ihaskell correctly installed after taking stack from the freebsd and not the stack as it can be installed with cabal.
In my current setup pip is run by a local user and cabal by root . Giving seemingly some problems.

**Comment by vaibhavsagar** [comment]
I don't think the latest version of Jupyter works with Python 2, can you try Python 3? Also, what is the console output when the kernel dies?

**Comment by vaibhavsagar** [comment]
I'm closing this because I don't know how to test this with our current infrastructure and we've never stated that we support FreeBSD. Please reopen if you find a way.
