### ISSUE TITLE
Hiding packages

### ISSUE THREAD

**Issue by Magalame** [gibiansky/IHaskell#1028]
Importing a module I ran into an `ambiguous module` error:

```
Ambiguous module name ‘Statistics.Matrix’: it was found in multiple packages: dense-linear-algebra-0.2.0.0 statistics-0.14.0.2
```

I was wondering how I could hide a package in IHaskell? 

Thanks!

**Comment by vaibhavsagar** [comment]
You can use the [`PackageImports`](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#ghc-flag--XPackageImports) language extension for this.

**Comment by Magalame** [comment]
Thanks!
