### ISSUE TITLE
Official up to date Docker Hub Image

### ISSUE THREAD

**Issue by ad-si** [gibiansky/IHaskell#1030]
There should be an official, up-to-date, and supported IHaskell docker image on https://hub.docker.com. The https://hub.docker.com/r/gibiansky/ihaskell one hasn't been updated for 3 (!) years and none of the others seems to be regularly maintained either.

As this repo already has continuous integration, it should be easy to add a step to deploy to Docker Hub, right?

**Comment by vaibhavsagar** [comment]
I unfortunately don't have the requisite access to deploy to that namespace. How would you propose adding this step, and can you tell me more about your use case that requires up-to-date Docker images for each commit to this project?

**Comment by gibiansky** [comment]
FYI I am happy to update that one (and a different namespace can also be created, up to you @vaibhavsagar). Is the Dockerfile on master up to date? If so, I can build and push it to `gibiansky/ihaskell`.

**Comment by vaibhavsagar** [comment]
Is there any way I can get access to that particular namespace (`gibiansky/ihaskell`)? I think this would be ideal since it matches the name of this repo. The current `Dockerfile` works but is not up-to-date with the latest Stackage LTS, which can cause weird issues launching a notebook outside the `ihaskell` folder.

**Comment by gibiansky** [comment]
What's your docker id? I can add you as a collaborator.

**Comment by vaibhavsagar** [comment]
Thanks! My Docker ID is `vaibhavsagar`.

**Comment by gibiansky** [comment]
You should be able to push to it now.

**Comment by ad-si** [comment]
Well, I try to run as much code as possible in Docker and most things work really well nowadays. Jessie Frazelle has been running **all** her apps in Docker for years: https://blog.jessfraz.com/post/docker-containers-on-the-desktop/

E.g. to start the official data science Jupyter Lab i simply have to run:

```sh
docker run \
  --rm \
  -p 8888:8888 \
  -e JUPYTER_ENABLE_LAB=yes \
  -v "$PWD":/home/jovyan/work \
  jupyter/datascience-notebook
```

Actually it's very functional. No side effects and when I kill the server it's gone :grin:. I want to be able to do the same for IHaskell!

**Comment by ad-si** [comment]
Of course the best thing would be if it became a real official image => https://docs.docker.com/docker-hub/official_images/#creating-an-official-image
But there aren't any other "i*" images among those, so that's probably beyond their scope…

**Comment by jamesdbrock** [comment]
Hi, I've been doing some work on IHaskell Docker.

I'm working on a branch for Docker-based development:

https://github.com/jamesdbrock/IHaskell/tree/docker-dev

And I've also made a Jupyter Community Docker Stack, and I see that you've found it @ad-si , in fact you're the only person who's starred it.

https://github.com/jamesdbrock/ihaskell-notebook

**Comment by kyagrd** [comment]
@jamesdbrock Your image works great for me. I once rolled my own but had a lots of garbage in it. This is nice!

I also made a template `pwd` directory https://github.com/hnu-pl/ihaskell-pwd as a quick start point for beginners. It's basically a poor man's Docker volume for the LTS snapshot directory to repeated installation of packages due to sandbox clear-up.

**Comment by vaibhavsagar** [comment]
I've set up https://github.com/vaibhavsagar/ihaskell-docker which uses GitHub Actions to build a new Docker image for IHaskell every day based on the most current `master`. It just successfully completed for the first time.

**Comment by vaibhavsagar** [comment]
In case anyone is wondering why I made my own repo, it's because this repo doesn't currently support GitHub Actions. If this changes, I'm happy to roll my changes into our CI process and get rid of my repo.
