### ISSUE TITLE
Build fails in my Travis but succeeds in Andrew's

### ISSUE THREAD

**Issue by jamesdbrock** [gibiansky/IHaskell#1034]
I've cloned IHaskell and triggered my own Travis build of the master branch and the build failed.

Build fails in my Travis:
https://travis-ci.org/jamesdbrock/IHaskell/builds/539096282

Build succeeds for the same master commit in Andrew Gibiansky's Travis:
https://travis-ci.org/gibiansky/IHaskell/builds/535209695

I am puzzling through this and I would appreciate any advice. Something different about the Travis account settings? Something different about the build cache state?

**Comment by vaibhavsagar** [comment]
This is because we test that the output of `:hoogle` is the same as our reference notebook, but this breaks pretty often because the Hoogle database is updated at least daily. If you regenerate `notebooks/IHaskell.ipynb` with the newest documentation I would expect the build to pass.

**Comment by vaibhavsagar** [comment]
More generally we have this issue because our tests have an external dependency, and I haven't figured out a good solution to this yet.

**Comment by vaibhavsagar** [comment]
I've opened https://github.com/gibiansky/IHaskell/pull/1035 to update the notebook for now.

**Comment by vaibhavsagar** [comment]
I've also gone ahead and changed the type signature we're `:hoogle`ing, hopefully this leads to less breakage. If not I'll go ahead and remove that cell until I can think of a more robust solution.

**Comment by vaibhavsagar** [comment]
I've merged that PR, so it should work now on the latest `master`.

**Comment by vaibhavsagar** [comment]
Closing this, please reopen if required.

**Comment by jamesdbrock** [comment]
Oh yeah that works, thanks @vaibhavsagar .
