### ISSUE TITLE
travis.yml and stack.yaml

### ISSUE THREAD

**Issue by jamesdbrock** [gibiansky/IHaskell#1043]
Can we talk about `.travis.yml` and `stack.yaml`? It seems like they need attention.

Is there a reason why `.travis.yml` is written as a list of repetitive `include`s rather than as a normal Travis build matrix? The difference between the `include`s seems to be only the `USE_STACK_YAML` which specifies a `stack.yaml` file?

The `stack.yaml` files are different, but those differences don't look meaningful, except for the resolver. It seems like we could have only one `stack.yaml`, and then test with a build matrix with different resolvers, specified by the `stack --resolver` command line argument?

Historical research:
#398 #400

**Comment by jamesdbrock** [comment]
Ah here is the commit where we expanded the Travis matrix so that we could add the Nix build.

d5c6272390f8eaf5260bf593414ff70b1c362d35

**Comment by jamesdbrock** [comment]
Looks like separate `.travis.yml` files are not a thing.

https://github.com/travis-ci/travis-ci/issues/3540

**Comment by shide1989** [comment]
This support could be a great improvement for monorepos containing multiple projects. I really hope they will support it in the future

**Comment by jamesdbrock** [comment]
Should IHaskell switch from Travis to Github Actions?

**Comment by vaibhavsagar** [comment]
I haven't had time to look into GitHub Actions yet, but I'd gladly consider a PR if you have one!

**Comment by vaibhavsagar** [comment]
Closing this as the current `.travis.yml` and `stack.yaml` files work correctly.
