### ISSUE TITLE
"FlexBox is gone"

### ISSUE THREAD

**Issue by jamesdbrock** [gibiansky/IHaskell#1045]
Hello @abarbu , can I ask you about this commit from 2017?

16d38400945f6184d58bb8bb562653b68cf5a929

Why did we delete [`FlexBox`](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Styling.html#The-Flexbox-layout)? Do you remember the circumstances around this?

**Comment by jamesdbrock** [comment]
Was it support GHC 8?

**Comment by abarbu** [comment]
I did it with the GHC 8 upgrade, but it's unrelated. I had a newer version of jupyter and this widget was removed from jupyter a long [time ago in widgets version 6](https://github.com/jupyter-widgets/ipywidgets/commit/b2ef61db6b06273b88cf97bac75ad2ff884568f9). It's been gone from the API for two years now.

**Comment by jamesdbrock** [comment]
Oh I see, thank you very much @abarbu .
