### ISSUE TITLE
ihaskell command not found

### ISSUE THREAD

**Issue by codyliuANU** [gibiansky/IHaskell#1047]
Hi, I got the same issue as #627. But I tried all method that it suggests and it still does not work. Is there any possible way to fix this?

**Comment by vaibhavsagar** [comment]
Which method are you using to install IHaskell, and which directory are you running this command from?

**Comment by vaibhavsagar** [comment]
Completely unrelated: I studied at the ANU too! If you ever make it to a CanFP please say hi to Alex Mason for me :smile:.

**Comment by davidcorbin** [comment]
@codyliuANU Had the same issue on macOS. Apparently the command `stack install --fast` is installing to `~/.local/bin`. To fix the issue, I added that directory to my PATH:

```bash
export PATH=~/.local/bin:$PATH
```

**Comment by vaibhavsagar** [comment]
Closing, please open if necessary.
