### ISSUE TITLE
ihaskell binary from `stack install` not independent of .stack root, not destroot'd

### ISSUE THREAD

**Issue by essandess** [gibiansky/IHaskell#1061]
I'm trying to create a MacPorts build of IHaskell here: https://github.com/macports/macports-ports/pull/4706

The `ihaskell` binary produced by `stack install` does not appear to be independent of the `.stack` directory, as I believe it should be.

When I launch `jupyter notebook` and initiate a Haskell kernel, `stack` jumps in and starts downloading `ghc`, and the kernel fails.

Is it possible to produce a binary independent of the `.stack` directory?

The build is [produced](https://github.com/macports/macports-ports/pull/4706/files#diff-039a3b878c0a62a118725172573632f4) with:
```
stack install --system-ghc …
```

and the file `/opt/local/share/jupyter/kernels/haskell/kernel.json` says:
```
{"display_name":"Haskell","argv":["/opt/local/bin/ihaskell","kernel","{connection_file}","--ghclib","/opt/local/lib/ghc-8.6.5","+RTS","-M3g","-N2","-RTS","--stack"],"language":"haskell"}
```

The broader reason for this is that all MacPorts installs are done through a destroot, and destrooting a common `.stack` for many independent stack projects won't work.

The strategy that works for other stack projects is to build the binary with a temporary `.stack`, then throw it away after the working binary is created.

This strategy isn't working with IHaskell for the reasons above.

**Comment by essandess** [comment]
Also, I tried this per the `README.md`, and see the same issue:
```
stack exec jupyter-3.7 --system-ghc -- notebook-3.7
```

**Comment by vaibhavsagar** [comment]
What happens if you remove `--stack` from the `kernel.json`?

**Comment by vaibhavsagar** [comment]
AFAICT the relevant code that is causing your issue is at https://github.com/gibiansky/IHaskell/blob/555a6501324762ea8f04eabb5091f4d00c3e74a0/main/Main.hs#L118-L134

**Comment by essandess** [comment]
What does this do?
```
ihaskell install --stack
```

Should I leave out the `--stack` for the install? I don't think that's it because the binary already exists at this point…

**Comment by essandess** [comment]
Progress:

Deleting `"--stack"` from `/opt/local/share/jupyter/kernels/haskell/kernel.json` stops a `ghc` download.

But delivers this error:
```
ihaskell: user error (Failed to read YAML configuration file /opt/local/var/macports/build/_opt_local_ports_devel_ihaskell/IHaskell/work/.stack/snapshots/x86_64-osx/8a7fee4b9fddfe6f98892bdfc223931ed3e92e341b5b6eef91c049411a58c457/8.6.5/share/x86_64-osx-ghc-8.6.5/hlint-2.1.11/hlint.yaml
  YAML exception:
Yaml file not found: /opt/local/var/macports/build/_opt_local_ports_devel_ihaskell/IHaskell/work/.stack/snapshots/x86_64-osx/8a7fee4b9fddfe6f98892bdfc223931ed3e92e341b5b6eef91c049411a58c457/8.6.5/share/x86_64-osx-ghc-8.6.5/hlint-2.1.11/hlint.yaml)
```

That `.stack` directory is the temporary one tha after the build.

I thought that `stack install` produced a standalone binary, and don't understand why the binary is trying to access stuff in `.stack`.

**Comment by essandess** [comment]
What about the flag `kernelSpecUseStack`?

There’s a few places in the code that invoke stack: https://github.com/gibiansky/IHaskell/search?q=stack&unscoped_q=stack

https://github.com/gibiansky/IHaskell/blob/ac478079dcbd6f947bac34bf190ad2f9d1e6891d/src/IHaskell/IPython.hs#L44

**Comment by vaibhavsagar** [comment]
The code I linked to above is the only place where `stack` is invoked.

**Comment by vaibhavsagar** [comment]
It seems like your issue isn't with IHaskell and instead is Stack-related. Have you considered using something like `cabal sandbox`? I had to use it to get IHaskell deployed on [CoCalc](https://cocalc.com/) because I ran into similar issues with using Stack myself.

**Comment by essandess** [comment]
Thanks again for your help. I think I see the issue now, and mischaracterized the problem in my initial post.

First, the `stack install` build is doing exactly what it should be doing: it makes a standalone `ihaskell` binary that runs independently of the original `.stack` directory.

**However**, that standalone `ihaskell` binary then calls `stack` as a system call because it needs a `ghc` kernel to run behind the Jupyter notebook. Calling `stack` for the Haskell kernel, rather than `ghc` or `ghci`, causes the behavior.

Then I come along and say, no I don’t want to call `stack` from the MacPorts port, thank you very much, I want to call the system `ghc` or `ghci`.

Can you recommend a straightforward way to run the system `ghc` that’s found in `PATH` for the Haskell kernel, rather than running `stack`?

**Comment by vaibhavsagar** [comment]
That's exactly what IHaskell does without `--stack` in `kernel.json` :smile:. The issue you're seeing is because we integrate with HLint, which expects an `hlint.yaml` in the directory where the `hlint` package was installed. This is in the `.stack-work` directory, because you built it with `stack`.

**Comment by essandess** [comment]
> This is why I recommended `cabal sandbox`

Thanks, that route may be necessary. I wonder if HLint cant be installed independently. Running `cabal` often leads to a snake pit of dependencies, which is why `stack` was developed…

> You'll notice that none of the stack documentation recommends doing a stack build and copying the resulting binary as a reliable way to package software, and that is because this doesn't work in general.

I don’t believe that this is correct. Even stack’s main documentation [page](https://docs.haskellstack.org/en/stable/README/) recommends:

> **How to uninstall**
>
> Removing `~/.stack` and `/usr/local/bin/stack` should be sufficient. You may want to delete ` .stack-work` folders in any Haskell projects that you have built.

All the `stack` install projects I’ve ever built produce standalone binaries, and I always just delete `.stack` after the build. Here’s one example:
```
otool -L `which adblock2privoxy`
/usr/local/bin/adblock2privoxy:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libcharset.1.dylib (compatibility version 2.0.0, current version 2.0.0)
```

I recall reading in the docs that this is the purpose of `stack install`.

**Comment by essandess** [comment]
Also FWIW, `emacs $(which ihaskell)` says that HLint is the only thing with a dependency on the `.stack` directory:
```
hlint_datadir^@/opt/local/var/macports/build/_opt_local_ports…
```

**Comment by essandess** [comment]
And I see that [HLint](https://github.com/ndmitchell/hlint) only uses `cabal` for its build, so everything points to just doing what you say and use `cabal`. I’ll try that next. Thanks again.

**Comment by vaibhavsagar** [comment]
You can do something like this from the project root:

1. `wget https://www.stackage.org/lts-13.26/cabal.config`
1. Edit `cabal.config` to remove the version bound on `ipython-kernel`
1. `cabal update`
1. `cabal sandbox init`
1. `cabal sandbox add-source ./ipython-kernel`
1. `cabal sandbox add-source .`
1. `cabal install`

The resulting binary will be at `.cabal-sandbox/bin/ihaskell`.

**Comment by essandess** [comment]
Thanks—getting close. If you don't mind, I need a few more pointers. These build steps take me right up to `cabal install`.

```
cabal update
cabal install cpphs happy
cabal sandbox init
cabal sandbox add-source ./ipython-kernel
cabal sandbox add-source .
cabal install --only-dependencies
cabal configure
cabal install
```

Questions:

1. I had to add that `cabal install cpphs happy` step because `cabal` doesn't find and install these two packages automatically. Do you know the fix?

2. `cabal`-newbie question: Do you know how to I specify a different cabal root path other than `~/.cabal`? I'll have to do this when I translate the build into the MacPorts `Portfile` and will want it independent of any specific user path. Does this go into some config file?

3. In the final `cabal install` step, I'm running into this annoying `iconv` [linking issue](http://blog.omega-prime.co.uk/2011/01/28/solving-ghc-iconv-problems-on-os-x-10-6/) on macOS. If you look at the currently [Portfile](https://github.com/macports/macports-ports/pull/4706/files#diff-039a3b878c0a62a118725172573632f4) draft, the solution is simple: append
```
extra-lib-dirs:
   - /usr/lib
```

to `stack.yaml`. Do you know the equivalent hack so that `cabal` finds the native-macOS `iconv` libs?

**Comment by vaibhavsagar** [comment]
1. `cpphs` and `happy` are build tools, I'm reasonably certain that you won't need them in your final package.
1. That's what `cabal sandbox` does, your new root path will be `./cabal-sandbox`.

1. Can you try `cabal configure --extra-lib-dir=/usr/lib`? See http://blog.omega-prime.co.uk/2011/01/28/solving-ghc-iconv-problems-on-os-x-10-6/.

**Comment by essandess** [comment]
These commands produce a successful build (keeping track as I go):
```
cabal update
cabal install cpphs happy
cabal sandbox init
cabal sandbox add-source ./ipython-kernel
cabal sandbox add-source .
cabal install --only-dependencies
cabal configure --extra-lib-dir=/usr/lib
cabal install --extra-lib-dir=/usr/lib
```

Now I see these two issues:

1. The `.cabal-sandbox` doesn't contain the ipython files (or cool svg logo!) `.cabal-sandbox/share/jupyter/kernels/haskell/kernel.json`, etc. Which command should produce/install these?

2. The binaries `.cabal-sandbox/ihaskell` and `.cabal-sandbox/hlint` both contain hard-coded links to the build directory ("`hlint_datadir^@/path/to/temporary/build/…`"), which will go away after the build directory is destroyed. If this were a simple linked library path, it would be easy to edit with `name_tool`, but I don't believe that it's wise to edit this path within the binary.

Are you aware of a way of configuring the (`hlint`?) build so that I can specify it's `hlint_datadir` path to the final destroot location?

**Comment by essandess** [comment]
There is an `hlint --data-dir` option:

https://github.com/ndmitchell/hlint/blob/c62b61696621cd5ebba408ec5bcc2fcdadb603cc/cc/Engine.hs#L65-L70

If there's a way to specify this option in the `ihaskell` kernel, then we're done! And the build would work with `stack` too.

**Comment by essandess** [comment]
Following  up on this [comment](https://github.com/ndmitchell/hlint/issues/699#issuecomment-508197400), these commands produce a successful build with the correct paths for all matador's in the binary (keeping track as I go):
```
wget https://www.stackage.org/lts-13.26/cabal.config
Edit cabal.config to remove the version bound on ipython-kernel
cabal update
cabal install cpphs happy
cabal sandbox init
cabal sandbox add-source ./ipython-kernel
cabal sandbox add-source .
cabal install --only-dependencies --datadir=/tmp/share
cabal configure --extra-lib-dir=/usr/lib --datadir=/tmp/share
cabal install --extra-lib-dir=/usr/lib --datadir=/tmp/share
```

The only issue left is that this `cabal` build doesn't create the IPython files like `kernel.json`.

**Comment by essandess** [comment]
Oh wait, the `--datadir` directive actually puts things in the specified directory, so destroot still won't work.

These appear to be fundamental limitations with the `stack` and `cabal` build tools.

**Comment by vaibhavsagar** [comment]
The kernel is created dynamically: https://github.com/gibiansky/IHaskell/blob/9612767a1b7fed859a26ef1d36e66a16eeab35f5/src/IHaskell/IPython.hs#L125-L169

Why can't you set `--datadir` to the eventual location of the installed program?

**Comment by essandess** [comment]
> Why can't you set `--datadir` to the eventual location of the installed program?

Because the package manager (MacPorts, brew, whatever) must be able to control installing and uninstalling package files. This is done by, first, creating all files in a in a temporary destroot directory, then second, the package manager installs from destroot to the final prefix location, keeping track of what it installed so it can uninstall or upgrade it.

Setting `--datadir` to the final location bypasses package manager control and makes uninstalls/upgrades a giant pain.

But if I set `--datadir` to destroot, the package manager will be happy, but the code won’t run because `cabal` hardcodes the datadir in the binary, and destroot is discarded after installation.

If `stack` and `cabal` had basic destroot capabilities like other compilers this woudn’t be a big detail.

**Comment by essandess** [comment]
I suppose I could hack this by building directly into prefix, then in the destroot stage copying the files I need from prefix into destroot, deleting the prefix files, and let the package manager install them all back into prefix.

That would work (I think), but it sure will generate some howls during the Portfile review.

**Comment by essandess** [comment]
Thanks again! It's all working now. See https://github.com/macports/macports-ports/pull/4706

I'll defer to you if you want to close this issue. I was able to work around it with a lot of hackery, but both upstream `cabal` and `stack` need destroy capability.

**Comment by vaibhavsagar** [comment]
Thanks for the update! I will go ahead and close this, but feel free to reopen if necessary.

**Comment by essandess** [comment]
@vaibhavsagar Sorry, we need to reopen this.Before I get to the issue, please let me recap the background:

* The `cabal` build if `ihaskell` hardcodes the build path into the binaries because of well-known issue with the way `cabal` handles `data-files`.
* This behavior breaks package managers like MacPorts and Brew because they cannot destroot properly.
* Brew has hacked around this by reluctantly modifying `prefix`. See https://github.com/Homebrew/homebrew-core/pull/1630#issuecomment-223244572.
* I hacked around this by adding a temporary symbolic link to `prefix` (https://github.com/gibiansky/IHaskell/issues/1061#issuecomment-508874776), and have been discussing this approach with the MacPorts painters for packages like this one that have the `data-files` issue. There's also been reasonable reluctance and push-back against this practice, which is one reason we haven't merged `ihaskell` yet.
* To address these reasonable concerns, I found a `cabal` approach for which no ugly `DESTDIR` hack is necessary. See https://github.com/commercialhaskell/stack/issues/5026
* Side note: `pandoc`'s author addressed this issue by using [file-embed](http://hackage.haskell.org/package/file-embed). See: https://github.com/commercialhaskell/stack/issues/848#issuecomment-528440793

Now that we have a working fix to `stack` and `cabal`'s `data-files` issues, I'd like to use it for the MacPorts port. The reason I am re-opening this issue is because I haven't gotten this working with `ihaskell`'s more complicated build, including its dependencies like `hlint`.

Would you please help figuring out an `ihaskell` build recipe that produces a relocatable, properly `prefix`-ed binary?

The [approach](http://neilmitchell.blogspot.com/2008/02/adding-data-files-using-cabal.html) described by [hlint](https://github.com/ndmitchell/hlint)'s author solves the issue of hardcoded `cabal` `data-files` in the binary. All that's required is to specify the path within a file called `Paths_packagename.hs`, which is normally automatically generated by `cabal` with its own paths. 

I've put a copy of `Paths_ihaskell.hs` both in `src` and `src/IHaskell`, without success. Would you be able to give this a try and let me know what you think the issue is? I've also unsuccessfully played around with `--enable-relocatable`, which I believe tickles that `reloc` guard in https://github.com/haskell/cabal/blob/master/Cabal/Distribution/Simple/Build/PathsModule.hs.

Current build recipe (including `cabal.config` as above):
```
cabal update
cabal install cpphs happy
cabal sandbox init
cabal sandbox add-source . ./ghc-parser ./ipython-kernel
cabal install --only-dependencies
cabal configure --extra-lib-dir=/usr/lib
cabal install --extra-lib-dir=/usr/lib
```

Here's a`Paths_ihaskell.hs` that should work:
```
{-# Cabal data-files hardcoded path in binary fix.

This file replaces the Paths_*.hs automatically created by cabal.

See:
* https://github.com/commercialhaskell/stack/issues/848
* https://github.com/commercialhaskell/stack/issues/4857
* https://github.com/haskell/cabal/issues/462
* https://github.com/haskell/cabal/issues/3586

#-}
        
{-# LANGUAGE CPP #-}
{-# LANGUAGE NoRebindableSyntax #-}
{-# OPTIONS_GHC -fno-warn-missing-import-lists #-}
module Paths_ihaskell (
    version,
    getBinDir, getLibDir, getDynLibDir, getDataDir, getLibexecDir,
    getDataFileName, getSysconfDir
  ) where

import qualified Control.Exception as Exception
import Data.Version (Version(..))
import System.Environment (getEnv)
import Prelude

#if defined(VERSION_base)

#if MIN_VERSION_base(4,0,0)
catchIO :: IO a -> (Exception.IOException -> IO a) -> IO a
#else
catchIO :: IO a -> (Exception.Exception -> IO a) -> IO a
#endif

#else
catchIO :: IO a -> (Exception.IOException -> IO a) -> IO a
#endif
catchIO = Exception.catch

version :: Version
version = Version [2,0,1] []
bindir, libdir, dynlibdir, datadir, libexecdir, sysconfdir :: FilePath

bindir     = "/opt/local/bin"
libdir     = "/opt/local/lib/ihaskell"
dynlibdir  = "/opt/local/lib/ihaskell"
datadir    = "/opt/local/share/ihaskell"
libexecdir = "/opt/local/lib/ihaskell"
sysconfdir = "/opt/local/etc"

getBinDir, getLibDir, getDynLibDir, getDataDir, getLibexecDir, getSysconfDir :: IO FilePath
getBinDir = catchIO (getEnv "ihaskell_bindir") (\_ -> return bindir)
getLibDir = catchIO (getEnv "ihaskell_libdir") (\_ -> return libdir)
getDynLibDir = catchIO (getEnv "ihaskell_dynlibdir") (\_ -> return dynlibdir)
getDataDir = catchIO (getEnv "ihaskell_datadir") (\_ -> return datadir)
getLibexecDir = catchIO (getEnv "ihaskell_libexecdir") (\_ -> return libexecdir)
getSysconfDir = catchIO (getEnv "ihaskell_sysconfdir") (\_ -> return sysconfdir)

getDataFileName :: FilePath -> IO FilePath
getDataFileName name = do
  dir <- getDataDir
  return (dir ++ "/" ++ name)
```

**Comment by vaibhavsagar** [comment]
1. Where exactly is the current build hardcoding unsuitable paths, and how do you think your `Paths` module is going to fix this without creating problems for other installation methods?

1. Where did this `Paths` module come from? `base-4.0.0` dates back to 2008. Why did you choose those particular values for `bindir`, `libdir`, etc.? What makes these the correct defaults?

1. I really really want to avoid making changes to the codebase to support a niche use-case, especially one that is not tested as part of my CI infrastructure.

1. I don't own a Mac, or see myself ever personally using the MacPorts build of IHaskell, and so I'm not really willing to put much more effort into this myself. If you can come up with a build that works for you I will happily review a pull request.

You are welcome to reopen this issue if you like, but I'm not planning to spend any more time on it in the foreseeable future.

**Comment by essandess** [comment]
> 1. Where exactly is the current build hardcoding unsuitable paths, and how do you think your `Paths` module is going to fix this without creating problems for other installation methods?

`cabal` automatically generates a `Paths_ihaskell.hs` file somewhere deep within `.cabal-sandbox`  that hardcodes the build directory paths. If you provide this file yourself, `cabal` uses it instead. This works. See: http://neilmitchell.blogspot.com/2008/02/adding-data-files-using-cabal.html

> 2. Where did this `Paths` module come from? `base-4.0.0` dates back to 2008. Why did you choose those particular values for `bindir`, `libdir`, etc.? What makes these the correct defaults?

Run a `cabal` build, look in `.cabal-sandbox`, and you’ll see this file with build directories instead. These paths are just what an example fo what a relocatable binary would want.

> 3. I really really want to avoid making changes to the codebase to support a niche use-case, especially one that is not tested as part of my CI infrastructure.

That’s the beauty of this approach: no code changes. Just have the build recipe stick a `Paths_ihaskell.hs` etc. in the correct locations, populated with the correct values.

> 4. I don't own a Mac, or see myself ever personally using the MacPorts build of IHaskell, and so I'm not really willing to put much more effort into this myself. If you can come up with a build that works for you I will happily review a pull request.
> 
> You are welcome to reopen this issue if you like, but I'm not planning to spend any more time on it in the foreseeable future.

Thanks, I know this is a general problem within Haskell world, not specific to IHaskell. I’m just at the limit of my `cabal` knowledge and am hoping to use this approach to get a relocatable IHaskell build.

I actually think the best approach is not though `cabal`, but through `stack`.

Let me try addressing this limited first `stack` issue: when I build with `stack`, I only get the `ihaskell` binary, but not `hlint` or other dependencies. Do you know that flags to set to get everything built? If I have that, I can try a few tricks to get `cabal` underneath to use the correct paths, as I have successfully with other Haskell packages.

**Comment by vaibhavsagar** [comment]
IHaskell uses the `hlint` library, so there is no `hlint` executable.

**Comment by essandess** [comment]
> IHaskell uses the `hlint` library, so there is no `hlint` executable.

Thanks. My mistake. The `cabal` Build above create a separate `hlint` binary and I had assumed that that’s necessary. Is the only binary necessary `ihaskell`?

**Comment by vaibhavsagar** [comment]
I believe so, but I could be wrong since this has never come up before.

**Comment by essandess** [comment]
Actually, because `ihaskell`‘s `ihaskell_datadir` path gets builds correctly using the method described above, this issue really belongs upstream in https://github.com/ndmitchell/hlint/issues/699. Thanks again @vaibhavsagar—I’ll take it there.

**Comment by essandess** [comment]
@vaibhavsagar Thanks again for all your help. IHaskell is now merged into MacPorts and it works great. Instructions:

Installation:
```
sudo port install ihaskell
```

Use:
```
export hlint_datadir=/opt/local/share/hlint/datadir
jupyter-3.7 notebook-3.7
```

That environment variable is necessary to address the upstream cabal issue we've been discussing. After that's addressed, it won't be necessary and you can call jupyter without it.

**Comment by vaibhavsagar** [comment]
That's wonderful! Congratulations on getting it packaged and merged in 😃!
