### ISSUE TITLE
Installation under nix builds ghc!

### ISSUE THREAD

**Issue by idontgetoutmuch** [gibiansky/IHaskell#1072]
```
nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/2d575e31b8d39bf694268b1e640751d6101fcc13.tar.gz ~/IHaskell/release-8.8.nix --arg packages "haskellPackages: [ haskellPackages.lens ]"
```

seems to rebuild ghc! What am I doing wrong?

**Comment by vaibhavsagar** [comment]
`release-8.8.nix` bundles its own `nixpkgs` that uses https://github.com/hvr/head.hackage. You can use my binary cache at https://vaibhavsagar.cachix.org/ to avoid building GHC yourself.

**Comment by idontgetoutmuch** [comment]
Thanks - if only I were competent at nix - I might be brave and try - or perhaps I should fall back to 8.6.

**Comment by vaibhavsagar** [comment]
I forgot that you might be running macOS, in which case my binary cache won't help you!
