### ISSUE TITLE
Build Failure (8.8)

### ISSUE THREAD

**Issue by idontgetoutmuch** [gibiansky/IHaskell#1073]
After many hours I got

```
Configuring lens-4.17.1...
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:984:20 in Cabal-3.0.0.0:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:474:12 in Cabal-3.0.0.0:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:597:20 in Cabal-3.0.0.0:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:65:5 in Cabal-3.0.0.0:Distribution.Simple.UserHooks
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:65:5 in Cabal-3.0.0.0:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:180:19 in Cabal-3.0.0.0:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:125:42 in Cabal-3.0.0.0:Distribution.Simple
  defaultMainWithHooks, called at src/Distribution/Extra/Doctest.hs:144:27 in cabal-doctest-1.0.6-AfYAPdAzn4y7LRJnC56w0M:Distribution.Extra.Doctest
Setup: Encountered missing dependencies:
template-haskell >=2.4 && <2.15

Preprocessing library for tls-1.4.1..
Building library for tls-1.4.1..
builder for '/nix/store/mcld9gx81dg0l1qjandjms8g6qqff37x-lens-4.17.1.drv' failed with exit code 1
cannot build derivation '/nix/store/v2z140nk772da24v7ci8h1r71yyn9z5z-ghc-8.8.1.20190613-with-packages.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/h4ym8igmbw2bjisg2n7y14csb7925i2b-ihaskell-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/h4ym8igmbw2bjisg2n7y14csb7925i2b-ihaskell-with-packages.drv' failed
```

**Comment by vaibhavsagar** [comment]
It looks like `lens` has overly restrictive upper bounds, can you share the full expression you're building?

**Comment by vaibhavsagar** [comment]
I pushed 50116ade4ebeb93198a55b6b7f8e4a2e4ed008f8 to address this.

**Comment by idontgetoutmuch** [comment]
`nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/2d575e31b8d39bf694268b1e640751d6101fcc13.tar.gz release-8.8.nix --arg packages "haskellPackages: [ haskellPackages.random-fu ]"`

I changed this to 

`nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-19.03.tar.gz release-8.6.nix --arg packages "haskellPackages: [ haskellPackages.random-fu haskellPackages.my-random-fu-multivariate ]"`

and I working happily. I may try 8.8 again but not for a few days at least. Thanks for looking at this.

BTW I have my modified (working!) version of `random-fu-multivariate` working via overlays inside a Jupyter notebook so I think I have a good workflow now for me and my colleagues.

**Comment by vaibhavsagar** [comment]
That's great! I'm glad to hear you have a workflow you like :smiley:.

**Comment by idontgetoutmuch** [comment]
Although the workflow works for us, I am sure it is sub-optimal. Maybe I should write it up on reddit and get input on how it can be improved.

**Comment by vaibhavsagar** [comment]
Sure! I'm also happy to look at it (modulo macOS-specific issues) if you write it up here and reopen this issue (or create a new one).
