### ISSUE TITLE
inline-c does not work in IHaskell

### ISSUE THREAD

**Issue by idontgetoutmuch** [gibiansky/IHaskell#1078]
![image](https://user-images.githubusercontent.com/1550265/61862971-a23a5400-aec6-11e9-9fb8-3009cf763e62.png)

and see also https://github.com/fpco/inline-c/issues/94.

**Comment by vaibhavsagar** [comment]
Does this work in GHCi?

**Comment by idontgetoutmuch** [comment]
Ah no - ok forget this
