### ISSUE TITLE
nix: kernel complains "cannot satisfy -package-id HsOpenSSL-0.11.4.16-LYOI62EkAWe2BIzDG3VWh"

### ISSUE THREAD

**Issue by falsifian** [gibiansky/IHaskell#1080]
I built `release-8.6.nix`, ran `result/bin/ihaskell-notebook`, and opened a notebook. The kernel failed to start, showing messages like this:
```Loaded package environment from /home/james/.ghc/x86_64-linux-8.6.4/environments/default
ihaskell: <command line>: cannot satisfy -package-id HsOpenSSL-0.11.4.16-LYOI62EkAWe2BIzDG3VWh
    (use -v for more information)
[I 15:51:12.946 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
```

I'm not sure how to debug this. HsOpenSSL is a package I recently installed using something like `cabal new-install --lib HsOpenSSL`, so I am guessing the ihaskell kernel is somehow influenced by the ghc/cabal configuration in my home directory, rather than being a completely isolated configuration. If my guess is right, I can think of two kinds of solution: (a) tell ihaskell to ignore my local configuration, or (b) somehow make it so ihaskell can see the HsOpenSSL package and whatever else I've installed with cabal. 

Does my guess sound right? If so, could someone with more knowledge of ihaskell works and/or how ghc loads packages can shed some light on how to implement solution (a) or (b)?

---

Some more detail:

My computer is running NixOS 19.03. I built IHaskell with the command `nix-build release-8.6.nix --arg packages "haskellPackages: [ haskellPackages.repa ]"`. (I omitted the `-I nixpkgs=...` from `README.md` since my `NIX_PATH` already has `nixpkgs=` pointing to the 19.03 channel, but I can follow the instructions more exactly if someone thinks that's likely to help.)

Here's text from my terminal showing what happened when I started `ihaskell-notebook` and opened one of the example .ipynb files through the web interface:

```
james angel-nixos ~/big/track/IHaskell $ nix-build release-8.6.nix --arg packages "haskellPackages: [ haskellPackages.repa ]"
/nix/store/4zr3ifvcn0ak3i6vp6ka40jvz4s2jkys-ihaskell-with-packages
james angel-nixos ~/big/track/IHaskell $ result/bin/ihaskell-notebook 
[I 15:50:46.139 NotebookApp] JupyterLab extension loaded from /nix/store/0jsp65m193rys4jny9pzzp4j8c2q3scq-python3-3.7.4-env/lib/python3.7/site-packages/jupyterlab
[I 15:50:46.139 NotebookApp] JupyterLab application directory is /nix/store/hnqyd0205b8m849ibqmhsap5lj5x8fd9-python3.7-jupyterlab-0.35.4/share/jupyter/lab
[I 15:50:46.142 NotebookApp] Serving notebooks from local directory: /home/james/big/track/IHaskell
[I 15:50:46.142 NotebookApp] The Jupyter Notebook is running at:
[I 15:50:46.142 NotebookApp] http://localhost:8888/?token=af45dda0b50eb6235b923cf7e5e051a5556e2c6210eb5a3e
[I 15:50:46.143 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:50:46.223 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///run/user/1000/jupyter/nbserver-19763-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=af45dda0b50eb6235b923cf7e5e051a5556e2c6210eb5a3e
[W 15:51:08.548 NotebookApp] Notebook notebooks/Homophones.ipynb is not trusted
[I 15:51:09.949 NotebookApp] Kernel started: 10b6c628-e238-4f61-8fe1-d222a1459870
[W 15:51:09.978 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190726155045 (::1) 13.19ms referer=http://localhost:8888/notebooks/notebooks/Homophones.ipynb
Loaded package environment from /home/james/.ghc/x86_64-linux-8.6.4/environments/default
ihaskell: <command line>: cannot satisfy -package-id HsOpenSSL-0.11.4.16-LYOI62EkAWe2BIzDG3VWh
    (use -v for more information)
[I 15:51:12.946 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Loaded package environment from /home/james/.ghc/x86_64-linux-8.6.4/environments/default
ihaskell: <command line>: cannot satisfy -package-id HsOpenSSL-0.11.4.16-LYOI62EkAWe2BIzDG3VWh
    (use -v for more information)
[I 15:51:15.956 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports```

**Comment by vaibhavsagar** [comment]
I'm not aware of a way to tell IHaskell (or anything else built with Nix) to ignore your locally installed `.cabal` packages. In general you can't mix and match. I'm going to close this issue, because this isn't an issue with IHaskell.

**Comment by falsifian** [comment]
Thanks for the quick response. Is there a simple way to find out how IHaskell is invoking ghc? Even though I now know this is not an IHaskell issue, I unfortunately don't know how to reproduce the error in any way other than by running IHaskell. Having a simple ghc command that fails would help me know where to look next to understand what's wrong with my setup.

**Comment by vaibhavsagar** [comment]
IHaskell uses the GHC API directly, so it doesn't invoke `ghc` in the way I think you mean.

**Comment by vaibhavsagar** [comment]
Actually, I was too hasty and didn't properly read your error message. Can you try removing `/home/james/.ghc/x86_64-linux-8.6.4/environments/default` and see if this resolves your issue?

**Comment by falsifian** [comment]
Thanks, yes, after I remove that file, IHaskell is able to start a kernel, and I can import a module from the package (`repa`) that I listed when I built IHaskell.

**Comment by vaibhavsagar** [comment]
Good to know this worked! I'm really not a fan of `.ghc.environment` files.

**Comment by falsifian** [comment]
A couple more questions:

* Is there a flag I can pass to IHaskell to tell it to ignore the default environment? Unfortunately I'm relying on it for some things and would prefer not to just leave it deleted.
* Should IHaskell ignore the default environment? Or are there some circumstances under which IHaskell actually would be able to load a package listed there? Sorry, my understanding of this is still limited; all I know is that ghc and ghci 8.6.4 can load the packages in my default env, and IHaskell can't, even though I think it's also based on GHC 8.6.4.

(Why I'm relying on the default environment: I was trying to build environments with nix but gave up because so many hackage packages (including IHaskell) were marked as broken in nixpkgs. I switched to `cabal new-install` after reading [this comment](https://discourse.nixos.org/t/nix-and-the-haskell-eco-system-a-match-made-in-heaven-or-a-difficult-relationship/3314/3?u=falsifian). I haven't yet taken the time to learn what other options are available.)

**Comment by vaibhavsagar** [comment]
You can set `nixpkgs.config.allowBroken = true;` in `configuration.nix` to get around your issue with NixOS. I'm unfortunately not aware of any way to ignore the `.ghc.environment` file, as that's a core feature of GHC. If you come up with some way to do this, I'd happily accept a PR.

**Comment by falsifian** [comment]
Thanks for your answers! I will keep this issue in mind in case I find a solution.

(FYI I did try `allowBroken=true` and things genuinely don't build for various reasons. Maybe I will try to fix some of them.)
