### ISSUE TITLE
How to import a module?

### ISSUE THREAD

**Issue by stedi67** [gibiansky/IHaskell#1088]
This is probably something really trivial. I've just installed IHaskell on Ubuntu 18.04 as described in the Readme (using stack). Everything seems to work as intended. Now I'd like to use `import Data.Csv` in a notebook. When using ghci, I'd do something like
```
$ stack install cassava
$ stack ghci

> :set -package cassava
> import Data.Csv
```
How do I make `cassava` (or any other stack package) available in ihaskell?

**Comment by vaibhavsagar** [comment]
If you launch IHaskell from within a Stack project that includes `cassava` as a dependency, IHaskell will pick it up.

**Comment by vaibhavsagar** [comment]
Closing, please reopen if required.

**Comment by stedi67** [comment]
I guess I'm still missing something obvious. Here are my steps:

1. Install IHaskell according to https://github.com/gibiansky/IHaskell#linux (using a python virtual env)
2. I have a different directory with a stack project that is linked to all the modules I'm interested in. I can run `stack ghci` in there and do an `import Text.Csv`.
3. According to your suggestion, I run `stack exec jupyter -- notebook` in my projects directory.

I'm still getting an error message when trying to `import Data.Csv`.

I know, it's a lot to ask, but could you have another look on what I might do wrong?

**Comment by vaibhavsagar** [comment]
What does the `package.yaml` or `<project>.cabal` file look like for this project? Is `cassava` in there and have you done at least one `stack build` since you set it up?

**Comment by stedi67** [comment]
Here's a gist of the cabal file:
https://gist.github.com/stedi67/75c2ab7111598e9f3024ba602323c3db
I made sure that I've used the same stack lts and I've build the project (as I said, I can run stack ghci). I'd be happy to try a different approach if that would be easier.
