### ISSUE TITLE
Add support for user-supplied mimetypes

### ISSUE THREAD

**Issue by DougBurke** [gibiansky/IHaskell#1089]
I believe that the `MimeType` type should be extended with a constructor / type that allows a user to supply their own mimetype. This means that new / updated mime types can be used without a new release of IHaskell. So something like (untested, and open for bikeshedding)

```
data MimeType
   ...
    | MimeCustom T.Text


customMimeType :: T.Text -> MimeType
```

For instance, we currently don't have all of the mimetypes in https://github.com/jupyterlab/jupyter-renderers listed (my immediate concern is the vega/vega-lite related ones for `hvega` but it' generally applicable too when a new rendered is added).

I could come up with a PR if there's interest

**Comment by vaibhavsagar** [comment]
Sure, I'd be happy to accept a PR that implements this.

**Comment by vaibhavsagar** [comment]
Here's a first attempt: https://github.com/gibiansky/IHaskell/pull/1090.

**Comment by DougBurke** [comment]
Thanks. #1090 looks like what I was thinking (with the added change for supporting an "arbitrary" read). Apologies for the delay in responding.

**Comment by vaibhavsagar** [comment]
This has been implemented.
