### ISSUE TITLE
Kernel not detected by jupyter

### ISSUE THREAD

**Issue by yelircaasi** [gibiansky/IHaskell#1094]
I have the kernel installed in /usr/local/share/jupyter/kernels/ihaskell, which I did following the instructions for Mac OSX. The strange thing is that I didn't get any error messages, but the iHaskell kernel doesn't show up in the Jupyter Notebook navigator, nor is it listed when I run $ jupyter kernelspec list

For background, I have Haskell installed and can run it in terminal. I have multiple other Jupyter kernels installed (Julia, R, Scheme, etc.), and they all work fine.

Please help me figure out how to get Jupyter to recognize the kernel.

**Comment by vaibhavsagar** [comment]
Did you run `ihaskell install`?

**Comment by vaibhavsagar** [comment]
Closing this.
