### ISSUE TITLE
Running `pip3 install -r requirements.txt` breaks jupyter installation

### ISSUE THREAD

**Issue by jantonioperez** [gibiansky/IHaskell#1117]
I installed jupyter using pip3 following [these](https://jupyter.readthedocs.io/en/latest/install.html) instructions on an otherwise clean system running Ubuntu 19.10. I then attempted to install IHaskell, but when I reach the step 

```
pip3 install -r requirements.txt
```
it breaks my installation of jupyter notebook. When I try to start up a python kernel, I get the following message:
```
ModuleNotFoundError: No module named 'prompt_toolkit.formatted_text'
```
It repeatedly tries to start the kernel but fails to do so. 

**Update: Temporary fix by skipping `pip3 install -r requirements.txt`** 

I rolled my system back to it's state before I attempted to install IHaskell. My jupyter installation works again.

I went through the installation again, this time the only difference being that I skipped the `pip3 install -r requirements.txt` command. 

The install completed successfully and I'm able to properly use IHaskell, however I believe that `requirements.txt` needs to be fixed as it uninstalled `IPython` and left my jupyter notebook in a broken state.

**Comment by vaibhavsagar** [comment]
The instructions assume a clean system without Jupyter installed. I've updated `requirements.txt` and the `README` to reflect this.
