### ISSUE TITLE
Use of sqlite-simple kills kernel

### ISSUE THREAD

**Issue by DavSanchez** [gibiansky/IHaskell#1118]
Hi guys!

I'm currently using [this Docker image](https://hub.docker.com/r/crosscompass/ihaskell-notebook). It has installed `sqlite3` and I have previously executed `stack install sqlite-simple` on a terminal tab. With the following lines on a notebook, the last line makes the kernel die:

```haskell
import Data.List
import Database.SQLite.Simple
```

```haskell
db <- open "test.db"
```

Any ideas why this could be happening? Thanks!

**Comment by vaibhavsagar** [comment]
I tried this with my Nix setup and (as expected) it worked without any issues. I don't think this is an issue with IHaskell, but I'm downloading that Docker image to see if I can figure out what's going on.

**Comment by DavSanchez** [comment]
Sorry for posting it here, but I saw that this repo is more active and being something to do with the kernel, I assumed (perhaps wrongly) that it had to do with IHaskell itself.

I tried the same steps on the [mybinder.org link](https://mybinder.org/v2/gh/gibiansky/IHaskell/master) present in `README.md` and it seems to have worked, but I want to test a bit more. I'm also trying to build the `docker` image and run it locally as per the instructions, but apparently it runs out of memory on the compilation of some Haskell packages.

This is the message:

> [...]
> haskell-src-exts                 > [18 of 18] Compiling Language.Haskell.Exts
> haskell-src-exts                 > copy/register
> haskell-src-exts                 > Installing library in /home/jovyan/.stack/snapshots/x86_64-linux/f87768da5d9bcbe5706cb2a110555a2faab238bb6fafa433fdd13042ee7e1bfd/8.6.5/lib/x86_64-linux-ghc-8.6.5/haskell-src-exts-1.21.1-9jRJjiNfrEsGAa1mAVgSEM
> haskell-src-exts                 > Registering library for haskell-src-exts-1.21.1..
> 
> --  While building package ghc-lib-parser-8.8.0.20190424 using:
>       /home/jovyan/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 build --ghc-options ""
>     Process exited with code: ExitFailure (-9) (THIS MAY INDICATE OUT OF MEMORY)

**Comment by vaibhavsagar** [comment]
It looks to me like you need to provide more memory to your Docker daemon. I'm closing this as it isn't an IHaskell issue.
