### ISSUE TITLE
Syntax Highlighting doesn't work in Lab

### ISSUE THREAD

**Issue by AlexeyRaga** [gibiansky/IHaskell#1120]
Despite an open issue https://github.com/gibiansky/IHaskell/issues/1017 and a closed issue https://github.com/gibiansky/IHaskell/issues/885 in my case I see tab completion working but no syntax highlighting for the `lab`:

![image](https://user-images.githubusercontent.com/1394391/69046809-f822a100-0a4d-11ea-984c-4f0ec2a6c1e7.png)

I can dedicate some time to make it work if someone directs me to how it should be implemented / fixed.

**Comment by vaibhavsagar** [comment]
Were you able to install the IHaskell JupyterLab extension? IIRC that is what provides the syntax highlighting.

**Comment by AlexeyRaga** [comment]
@vaibhavsagar I am just running `$(nix-build)/bin/ihaskell-lab` hoping that the extension is installed/activated by that script/derivation.

I will try to activate it manually now...

**Comment by AlexeyRaga** [comment]
@vaibhavsagar OK, how do I do that? :)
When I try doing it manyally I get this error:

```
$(nix-build)/bin/jupyter-labextension install ihaskell_labextension
Node v10.16.0

Errored, use --debug for full output:
PermissionError: [Errno 13] Permission denied: '/nix/store/llkjd9yz8v47swmngwj56prvmra74zad-python3.7-jupyterlab-0.35.6/share/jupyter/lab/extensions'
```

Could you please advice how this should be done properly?

**Comment by vaibhavsagar** [comment]
Try using https://github.com/tweag/jupyterWith, which has instructions for including the extension.

**Comment by AlexeyRaga** [comment]
@vaibhavsagar I have managed to install the extension with these steps:
```
$(nix-build)/bin/jupyter-labextension install jupyterlab-ihaskell --app-dir="./jupyterlab" --no-build
$(nix-build)/bin/jupyter-lab build --app-dir="./jupyterlab"
$(nix-build)/bin/jupyter-lab --app-dir="./jupyterlab"
```

It would be nice if `release.nix` would expose a parameter for `--app-dir` so we could do:
```
import "${pkgs.ihaskell}/release.nix" {
  jupyterlabAppDir = "./jupyterlab"
  ...
}
```
Also, iIs there a reason that the extension is not installed by default?

**Comment by vaibhavsagar** [comment]
I'm glad you got it working! I can look into adding a parameter to `release.nix`.

The reason the extension isn't installed by default is that I don't know how to do this using just Nix and Nixpkgs, and frankly I was scared off by the instructions [here](https://github.com/tweag/jupyterWith/tree/ab6ad8e6e8245c4dbb5d579b15f813373196792d#using-jupyterlab-extensions) which seem to imply that there is no straightforward way to build this into the expression. If you can figure out how to do this I will happily accept a PR, but since I personally use the older notebooks it's not been a priority for me.

**Comment by AlexeyRaga** [comment]
Awesome, thanks!

I would be happy to make a PR, but I am on MacOS and when I clone the repo and build it with `release.nix` I get errors like broken packages, etc.
Somehow referencing it with `import "${pkgs.ihaskell}/release.nix"` is fine, I am not entirely sure why it is so.

I really hope that once we have `jupyterlabAppDir` exposed all we need to do is to add 
```
jupyter-labextension install jupyterlab-ihaskell --no-build --app-dir=....
jupyter-lab build
``` 
to `postBuild` [here](https://github.com/gibiansky/IHaskell/blob/master/release.nix#L77).

Tweag also removes `staging/node_modules` after `build`, so perhaps we can have it too...

**Comment by vaibhavsagar** [comment]
I don't think your suggested approach will work with sandboxing enabled (which it is by default), because it requires internet access.

**Comment by vaibhavsagar** [comment]
I've added support for `jupyterlabAppDir` as you suggested, and since syntax highlighting works, I'm closing this.
