### ISSUE TITLE
ihaskell_emacs_error:

### ISSUE THREAD

**Issue by zeta-00** [gibiansky/IHaskell#1129]
i am currently running ihaskell on nixos 19.09, in emacs when i run ein(emacs ipython notebook) i get an error:

Debugger entered--Lisp error: (error "ein:notebook-open--callback: notebook instantiation failed")
  signal(error ("ein:notebook-open--callback: notebook instantiation failed"))
  error("ein:notebook-open--callback: notebook instantiation failed")
  ein:notebook-open--callback(#s(ein:$notebook :url-or-port "http://127.0.0.1:8888" :notebook-id nil :notebook-path "Untitled62.ipynb" :kernel #s(ein:$kernel :url-or-port "http://127.0.0.1:8888" :path "Untitled62.ipynb" :kernelspec #s(ein:$kernelspec :name "haskell" :display-name "Haskell" :resources (:kernel\.js "/kernelspecs/haskell/kernel.js" :logo-64x64 "/kernelspecs/haskell/logo-64x64.svg") :spec (:argv ("/nix/store/7hnb3zg8r0d3ggb54g70i5yy4afdfv1q-ghc-8.6.5-with-packages/bin/ihaskell" "kernel" "{connection_file}" "--ghclib" "/nix/store/7hnb3zg8r0d3ggb54g70i5yy4afdfv1q-ghc-8.6.5-with-packages/lib/ghc-8.6.5" "+RTS" "-M3g" "-N2" "-RTS") :env nil :display_name "Haskell" :language "haskell" :interrupt_mode "signal" :metadata nil) :language "haskell") :events #<ein:events ein:events> :api-version 5 :session-id "bccb35d6-6e69-4b30-a123-edba31a3ea15" :kernel-id nil :shell-channel nil :iopub-channel nil :websocket nil :base-url "/api/kernels" :kernel-url nil :ws-url nil :stdin-activep nil :username "username" :msg-callbacks #<hash-table equal 0/65 0x177dfc5> :oinfo-cache #<hash-table equal 0/65 0x177dfa5> :after-start-hook ((ein:pytools-load-safely . #2)) :after-execute-hook nil) :kernelinfo nil :kernelspec #s(ein:$kernelspec :name "haskell" :display-name "Haskell" :resources (:kernel\.js "/kernelspecs/haskell/kernel.js" :logo-64x64 "/kernelspecs/haskell/logo-64x64.svg") :spec (:argv ("/nix/store/7hnb3zg8r0d3ggb54g70i5yy4afdfv1q-ghc-8.6.5-with-packages/bin/ihaskell" "kernel" "{connection_file}" "--ghclib" "/nix/store/7hnb3zg8r0d3ggb54g70i5yy4afdfv1q-ghc-8.6.5-with-packages/lib/ghc-8.6.5" "+RTS" "-M3g" "-N2" "-RTS") :env nil :display_name "Haskell" :language "haskell" :interrupt_mode "signal" :metadata nil) :language "haskell") :pager "*ein:pager http://127.0.0.1:8888/Untitled62.ipynb*" :dirty nil :metadata nil :notebook-name "Untitled62.ipynb" :nbformat 4 :nbformat-minor 2 :events #<ein:events ein:events> :worksheets (#<ein:worksheet ein:worksheet>) :scratchsheets nil :api-version 5 :autosave-timer nil :checkpoints nil :q-checkpoints nil) #f(compiled-function (&rest args2) #<bytecode 0x16a97b5>) t #s(ein:$content :url-or-port "http://127.0.0.1:8888" :notebook-version 5 :name "Untitled62.ipynb" :path "Untitled62.ipynb" :type "notebook" :writable t :created "2019-12-10T20:19:46.136083Z" :last-modified "2019-12-10T20:19:46.136083Z" :mimetype nil :raw-content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :session-p nil :checkpoints nil))
  apply(ein:notebook-open--callback (#s(ein:$notebook :url-or-port "http://127.0.0.1:8888" :notebook-id nil :notebook-path "Untitled62.ipynb" :kernel #s(ein:$kernel :url-or-port "http://127.0.0.1:8888" :path "Untitled62.ipynb" :kernelspec #s(ein:$kernelspec :name "haskell" :display-name "Haskell" :resources (:kernel\.js "/kernelspecs/haskell/kernel.js" :logo-64x64 "/kernelspecs/haskell/logo-64x64.svg") :spec (:argv ("/nix/store/7hnb3zg8r0d3ggb54g70i5yy4afdfv1q-ghc-8.6.5-with-packages/bin/ihaskell" "kernel" "{connection_file}" "--ghclib" "/nix/store/7hnb3zg8r0d3ggb54g70i5yy4afdfv1q-ghc-8.6.5-with-packages/lib/ghc-8.6.5" "+RTS" "-M3g" "-N2" "-RTS") :env nil :display_name "Haskell" :language "haskell" :interrupt_mode "signal" :metadata nil) :language "haskell") :events #<ein:events ein:events> :api-version 5 :session-id "bccb35d6-6e69-4b30-a123-edba31a3ea15" :kernel-id nil :shell-channel nil :iopub-channel nil :websocket nil :base-url "/api/kernels" :kernel-url nil :ws-url nil :stdin-activep nil :username "username" :msg-callbacks #<hash-table equal 0/65 0x177dfc5> :oinfo-cache #<hash-table equal 0/65 0x177dfa5> :after-start-hook ((ein:pytools-load-safely . #4)) :after-execute-hook nil) :kernelinfo nil :kernelspec #s(ein:$kernelspec :name "haskell" :display-name "Haskell" :resources (:kernel\.js "/kernelspecs/haskell/kernel.js" :logo-64x64 "/kernelspecs/haskell/logo-64x64.svg") :spec (:argv ("/nix/store/7hnb3zg8r0d3ggb54g70i5yy4afdfv1q-ghc-8.6.5-with-packages/bin/ihaskell" "kernel" "{connection_file}" "--ghclib" "/nix/store/7hnb3zg8r0d3ggb54g70i5yy4afdfv1q-ghc-8.6.5-with-packages/lib/ghc-8.6.5" "+RTS" "-M3g" "-N2" "-RTS") :env nil :display_name "Haskell" :language "haskell" :interrupt_mode "signal" :metadata nil) :language "haskell") :pager "*ein:pager http://127.0.0.1:8888/Untitled62.ipynb*" :dirty nil :metadata nil :notebook-name "Untitled62.ipynb" :nbformat 4 :nbformat-minor 2 :events #<ein:events ein:events> :worksheets (#<ein:worksheet ein:worksheet>) :scratchsheets nil :api-version 5 :autosave-timer nil :checkpoints nil :q-checkpoints nil) #f(compiled-function (&rest args2) #<bytecode 0x16a97b5>) t #s(ein:$content :url-or-port "http://127.0.0.1:8888" :notebook-version 5 :name "Untitled62.ipynb" :path "Untitled62.ipynb" :type "notebook" :writable t :created "2019-12-10T20:19:46.136083Z" :last-modified "2019-12-10T20:19:46.136083Z" :mimetype nil :raw-content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :session-p nil :checkpoints nil)))
  #f(compiled-function (&rest args2) #<bytecode 0x17eec11>)(#s(ein:$content :url-or-port "http://127.0.0.1:8888" :notebook-version 5 :name "Untitled62.ipynb" :path "Untitled62.ipynb" :type "notebook" :writable t :created "2019-12-10T20:19:46.136083Z" :last-modified "2019-12-10T20:19:46.136083Z" :mimetype nil :raw-content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :session-p nil :checkpoints nil))
  ein:content-query-contents--success("http://127.0.0.1:8888" "Untitled62.ipynb" #f(compiled-function (&rest args2) #<bytecode 0x17eec11>) :data (:name "Untitled62.ipynb" :path "Untitled62.ipynb" :last_modified "2019-12-10T20:19:46.136083Z" :created "2019-12-10T20:19:46.136083Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :symbol-status success :error-thrown nil :response #s(request-response :status-code 200 :history nil :data (:name "Untitled62.ipynb" :path "Untitled62.ipynb" :last_modified "2019-12-10T20:19:46.136083Z" :created "2019-12-10T20:19:46.136083Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :error-thrown nil :symbol-status success :url "http://127.0.0.1:8888/api/contents/Untitled62.ipynb" :done-p nil :settings (:type "GET" :timeout nil :parser ein:json-read :sync nil :complete #f(compiled-function (&rest args2) #<bytecode 0x17d7e55>) :success #f(compiled-function (&rest args2) #<bytecode 0x17d7e75>) :error #f(compiled-function (&rest args2) #<bytecode 0x17d7e95>) :headers (("User-Agent" . "Mozilla/5.0") ("X-XSRFTOKEN" . "2|fad4c223|cc4920dc571ad75a4b296ae1d3d0795d|1565668642")) :encoding binary :url "http://127.0.0.1:8888/api/contents/Untitled62.ipynb" :response #11) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nServer: TornadoServer/5.1\nContent-Type: application/json\nDate: Tue, 10 Dec 2019 20:19:46 GMT\nX-Content-Type-Options: nosniff\nContent-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report; default-src 'none'\nLast-Modified: Tue, 10 Dec 2019 20:19:46 GMT\nEtag: \"3d9fb55600094fb9cf535f16f5af2adc2ae529b6\"\nContent-Length: 310\n" :-timer nil :-backend curl :-tempfiles nil))
  apply(ein:content-query-contents--success ("http://127.0.0.1:8888" "Untitled62.ipynb" #f(compiled-function (&rest args2) #<bytecode 0x17eec11>) :data (:name "Untitled62.ipynb" :path "Untitled62.ipynb" :last_modified "2019-12-10T20:19:46.136083Z" :created "2019-12-10T20:19:46.136083Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :symbol-status success :error-thrown nil :response #s(request-response :status-code 200 :history nil :data (:name "Untitled62.ipynb" :path "Untitled62.ipynb" :last_modified "2019-12-10T20:19:46.136083Z" :created "2019-12-10T20:19:46.136083Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :error-thrown nil :symbol-status success :url "http://127.0.0.1:8888/api/contents/Untitled62.ipynb" :done-p nil :settings (:type "GET" :timeout nil :parser ein:json-read :sync nil :complete #f(compiled-function (&rest args2) #<bytecode 0x17d7e55>) :success #f(compiled-function (&rest args2) #<bytecode 0x17d7e75>) :error #f(compiled-function (&rest args2) #<bytecode 0x17d7e95>) :headers (("User-Agent" . "Mozilla/5.0") ("X-XSRFTOKEN" . "2|fad4c223|cc4920dc571ad75a4b296ae1d3d0795d|1565668642")) :encoding binary :url "http://127.0.0.1:8888/api/contents/Untitled62.ipynb" :response #13) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nServer: TornadoServer/5.1\nContent-Type: application/json\nDate: Tue, 10 Dec 2019 20:19:46 GMT\nX-Content-Type-Options: nosniff\nContent-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report; default-src 'none'\nLast-Modified: Tue, 10 Dec 2019 20:19:46 GMT\nEtag: \"3d9fb55600094fb9cf535f16f5af2adc2ae529b6\"\nContent-Length: 310\n" :-timer nil :-backend curl :-tempfiles nil)))
  #f(compiled-function (&rest args2) #<bytecode 0x17d7e75>)(:data (:name "Untitled62.ipynb" :path "Untitled62.ipynb" :last_modified "2019-12-10T20:19:46.136083Z" :created "2019-12-10T20:19:46.136083Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :symbol-status success :error-thrown nil :response #s(request-response :status-code 200 :history nil :data (:name "Untitled62.ipynb" :path "Untitled62.ipynb" :last_modified "2019-12-10T20:19:46.136083Z" :created "2019-12-10T20:19:46.136083Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :error-thrown nil :symbol-status success :url "http://127.0.0.1:8888/api/contents/Untitled62.ipynb" :done-p nil :settings (:type "GET" :timeout nil :parser ein:json-read :sync nil :complete #f(compiled-function (&rest args2) #<bytecode 0x17d7e55>) :success #f(compiled-function (&rest args2) #<bytecode 0x17d7e75>) :error #f(compiled-function (&rest args2) #<bytecode 0x17d7e95>) :headers (("User-Agent" . "Mozilla/5.0") ("X-XSRFTOKEN" . "2|fad4c223|cc4920dc571ad75a4b296ae1d3d0795d|1565668642")) :encoding binary :url "http://127.0.0.1:8888/api/contents/Untitled62.ipynb" :response #8) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nServer: TornadoServer/5.1\nContent-Type: application/json\nDate: Tue, 10 Dec 2019 20:19:46 GMT\nX-Content-Type-Options: nosniff\nContent-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report; default-src 'none'\nLast-Modified: Tue, 10 Dec 2019 20:19:46 GMT\nEtag: \"3d9fb55600094fb9cf535f16f5af2adc2ae529b6\"\nContent-Length: 310\n" :-timer nil :-backend curl :-tempfiles nil))
  apply(#f(compiled-function (&rest args2) #<bytecode 0x17d7e75>) (:data (:name "Untitled62.ipynb" :path "Untitled62.ipynb" :last_modified "2019-12-10T20:19:46.136083Z" :created "2019-12-10T20:19:46.136083Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :symbol-status success :error-thrown nil :response #s(request-response :status-code 200 :history nil :data (:name "Untitled62.ipynb" :path "Untitled62.ipynb" :last_modified "2019-12-10T20:19:46.136083Z" :created "2019-12-10T20:19:46.136083Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :error-thrown nil :symbol-status success :url "http://127.0.0.1:8888/api/contents/Untitled62.ipynb" :done-p nil :settings (:type "GET" :timeout nil :parser ein:json-read :sync nil :complete #f(compiled-function (&rest args2) #<bytecode 0x17d7e55>) :success #f(compiled-function (&rest args2) #<bytecode 0x17d7e75>) :error #f(compiled-function (&rest args2) #<bytecode 0x17d7e95>) :headers (("User-Agent" . "Mozilla/5.0") ("X-XSRFTOKEN" . "2|fad4c223|cc4920dc571ad75a4b296ae1d3d0795d|1565668642")) :encoding binary :url "http://127.0.0.1:8888/api/contents/Untitled62.ipynb" :response #10) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nServer: TornadoServer/5.1\nContent-Type: application/json\nDate: Tue, 10 Dec 2019 20:19:46 GMT\nX-Content-Type-Options: nosniff\nContent-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report; default-src 'none'\nLast-Modified: Tue, 10 Dec 2019 20:19:46 GMT\nEtag: \"3d9fb55600094fb9cf535f16f5af2adc2ae529b6\"\nContent-Length: 310\n" :-timer nil :-backend curl :-tempfiles nil)))
  apply(apply #f(compiled-function (&rest args2) #<bytecode 0x17d7e75>) (:data (:name "Untitled62.ipynb" :path "Untitled62.ipynb" :last_modified "2019-12-10T20:19:46.136083Z" :created "2019-12-10T20:19:46.136083Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :symbol-status success :error-thrown nil :response #s(request-response :status-code 200 :history nil :data (:name "Untitled62.ipynb" :path "Untitled62.ipynb" :last_modified "2019-12-10T20:19:46.136083Z" :created "2019-12-10T20:19:46.136083Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :error-thrown nil :symbol-status success :url "http://127.0.0.1:8888/api/contents/Untitled62.ipynb" :done-p nil :settings (:type "GET" :timeout nil :parser ein:json-read :sync nil :complete #f(compiled-function (&rest args2) #<bytecode 0x17d7e55>) :success #f(compiled-function (&rest args2) #<bytecode 0x17d7e75>) :error #f(compiled-function (&rest args2) #<bytecode 0x17d7e95>) :headers (("User-Agent" . "Mozilla/5.0") ("X-XSRFTOKEN" . "2|fad4c223|cc4920dc571ad75a4b296ae1d3d0795d|1565668642")) :encoding binary :url "http://127.0.0.1:8888/api/contents/Untitled62.ipynb" :response #11) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nServer: TornadoServer/5.1\nContent-Type: application/json\nDate: Tue, 10 Dec 2019 20:19:46 GMT\nX-Content-Type-Options: nosniff\nContent-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report; default-src 'none'\nLast-Modified: Tue, 10 Dec 2019 20:19:46 GMT\nEtag: \"3d9fb55600094fb9cf535f16f5af2adc2ae529b6\"\nContent-Length: 310\n" :-timer nil :-backend curl :-tempfiles nil)))
  request--safe-apply(#f(compiled-function (&rest args2) #<bytecode 0x17d7e75>) (:data (:name "Untitled62.ipynb" :path "Untitled62.ipynb" :last_modified "2019-12-10T20:19:46.136083Z" :created "2019-12-10T20:19:46.136083Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :symbol-status success :error-thrown nil :response #s(request-response :status-code 200 :history nil :data (:name "Untitled62.ipynb" :path "Untitled62.ipynb" :last_modified "2019-12-10T20:19:46.136083Z" :created "2019-12-10T20:19:46.136083Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :error-thrown nil :symbol-status success :url "http://127.0.0.1:8888/api/contents/Untitled62.ipynb" :done-p nil :settings (:type "GET" :timeout nil :parser ein:json-read :sync nil :complete #f(compiled-function (&rest args2) #<bytecode 0x17d7e55>) :success #f(compiled-function (&rest args2) #<bytecode 0x17d7e75>) :error #f(compiled-function (&rest args2) #<bytecode 0x17d7e95>) :headers (("User-Agent" . "Mozilla/5.0") ("X-XSRFTOKEN" . "2|fad4c223|cc4920dc571ad75a4b296ae1d3d0795d|1565668642")) :encoding binary :url "http://127.0.0.1:8888/api/contents/Untitled62.ipynb" :response #10) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nServer: TornadoServer/5.1\nContent-Type: application/json\nDate: Tue, 10 Dec 2019 20:19:46 GMT\nX-Content-Type-Options: nosniff\nContent-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report; default-src 'none'\nLast-Modified: Tue, 10 Dec 2019 20:19:46 GMT\nEtag: \"3d9fb55600094fb9cf535f16f5af2adc2ae529b6\"\nContent-Length: 310\n" :-timer nil :-backend curl :-tempfiles nil)))
  request--callback(#<killed buffer> :type "GET" :timeout nil :parser ein:json-read :sync nil :complete #f(compiled-function (&rest args2) #<bytecode 0x17d7e55>) :success #f(compiled-function (&rest args2) #<bytecode 0x17d7e75>) :error #f(compiled-function (&rest args2) #<bytecode 0x17d7e95>) :headers (("User-Agent" . "Mozilla/5.0") ("X-XSRFTOKEN" . "2|fad4c223|cc4920dc571ad75a4b296ae1d3d0795d|1565668642")) :encoding binary :url "http://127.0.0.1:8888/api/contents/Untitled62.ipynb" :response #s(request-response :status-code 200 :history nil :data (:name "Untitled62.ipynb" :path "Untitled62.ipynb" :last_modified "2019-12-10T20:19:46.136083Z" :created "2019-12-10T20:19:46.136083Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :error-thrown nil :symbol-status success :url "http://127.0.0.1:8888/api/contents/Untitled62.ipynb" :done-p nil :settings (:type "GET" :timeout nil :parser ein:json-read :sync nil :complete #f(compiled-function (&rest args2) #<bytecode 0x17d7e55>) :success #f(compiled-function (&rest args2) #<bytecode 0x17d7e75>) :error #f(compiled-function (&rest args2) #<bytecode 0x17d7e95>) :headers (("User-Agent" . "Mozilla/5.0") ("X-XSRFTOKEN" . "2|fad4c223|cc4920dc571ad75a4b296ae1d3d0795d|1565668642")) :encoding binary :url "http://127.0.0.1:8888/api/contents/Untitled62.ipynb" :response #23) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nServer: TornadoServer/5.1\nContent-Type: application/json\nDate: Tue, 10 Dec 2019 20:19:46 GMT\nX-Content-Type-Options: nosniff\nContent-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report; default-src 'none'\nLast-Modified: Tue, 10 Dec 2019 20:19:46 GMT\nEtag: \"3d9fb55600094fb9cf535f16f5af2adc2ae529b6\"\nContent-Length: 310\n" :-timer nil :-backend curl :-tempfiles nil))
  apply(request--callback #<killed buffer> (:type "GET" :timeout nil :parser ein:json-read :sync nil :complete #f(compiled-function (&rest args2) #<bytecode 0x17d7e55>) :success #f(compiled-function (&rest args2) #<bytecode 0x17d7e75>) :error #f(compiled-function (&rest args2) #<bytecode 0x17d7e95>) :headers (("User-Agent" . "Mozilla/5.0") ("X-XSRFTOKEN" . "2|fad4c223|cc4920dc571ad75a4b296ae1d3d0795d|1565668642")) :encoding binary :url "http://127.0.0.1:8888/api/contents/Untitled62.ipynb" :response #s(request-response :status-code 200 :history nil :data (:name "Untitled62.ipynb" :path "Untitled62.ipynb" :last_modified "2019-12-10T20:19:46.136083Z" :created "2019-12-10T20:19:46.136083Z" :content (:cells nil :metadata nil :nbformat 4 :nbformat_minor 2) :format "json" :mimetype nil :size 72 :writable t :type "notebook") :error-thrown nil :symbol-status success :url "http://127.0.0.1:8888/api/contents/Untitled62.ipynb" :done-p nil :settings #3 :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nServer: TornadoServer/5.1\nContent-Type: application/json\nDate: Tue, 10 Dec 2019 20:19:46 GMT\nX-Content-Type-Options: nosniff\nContent-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report; default-src 'none'\nLast-Modified: Tue, 10 Dec 2019 20:19:46 GMT\nEtag: \"3d9fb55600094fb9cf535f16f5af2adc2ae529b6\"\nContent-Length: 310\n" :-timer nil :-backend curl :-tempfiles nil)))
  request--curl-callback(#<process request curl> "finished\n")

**Comment by zeta-00** [comment]
here is my ihaskell installation expression in home.nix, not sure if its a problem at my end:

      # ihaskell package installation:
      (lib.lowPrio
      (let ihaskell = pkgs.fetchFromGitHub {
        owner = "gibiansky";
        repo = "IHaskell";
        rev = "a442c0b6d4cf1fb17eaa3bf2827f04b21ad334bf";
        sha256 = "0fprbj4g02wn8600siwy4wizz8qx4imsvlvkr36p2ndmrpsynbbl";
      };
       in import "${ihaskell}/release.nix" {
                                             compiler = "ghc865";
                                             nixpkgs = pkgs;
                                             packages = self: with self; [];
					                                 }))

**Comment by vaibhavsagar** [comment]
This looks like an Emacs package, possibly https://github.com/millejoh/emacs-ipython-notebook. We don't provide support for it here, please ask on the relevant project issue tracker instead.
