### ISSUE TITLE
Installation failure on macos 10.14.6 with zeromq4-haskell-0.8.0, glib-0.13.7.1 and cairo-0.13.6.0

### ISSUE THREAD

**Issue by angusdavisadobe** [gibiansky/IHaskell#1133]
I followed the installation steps in the readme but I keep getting this:
--  While building package zeromq4-haskell-0.8.0 using:
      /Users/angudavi/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.4.0.1 configure --user --package-db=clear --package-db=global --package-db=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/pkgdb --libdir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/lib --bindir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/bin --datadir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/share --libexecdir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/libexec --sysconfdir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/etc --docdir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/doc/zeromq4-haskell-0.8.0 --htmldir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/doc/zeromq4-haskell-0.8.0 --haddockdir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/doc/zeromq4-haskell-0.8.0 --dependency=async=async-2.2.2-EbxQ7tk0OFk9dJNMtaidSf --dependency=base=base-4.12.0.0 --dependency=bytestring=bytestring-0.10.8.2 --dependency=containers=containers-0.6.0.1 --dependency=exceptions=exceptions-0.10.3-E9jnqBFMcMW6cBEyBoWxPi --dependency=monad-control=monad-control-1.0.2.3-At5xRpwF2S6HGPjjUhSXZF --dependency=semigroups=semigroups-0.18.5-8pPnWqWrcWhEagTFf5Pnk2 --dependency=transformers=transformers-0.5.6.2 --dependency=transformers-base=transformers-base-0.4.5.2-9wmw9letGJgDNrnpTrMj47 --exact-configuration --ghc-option=-fhide-source-paths
    Process exited with code: ExitFailure 1

--  While building package glib-0.13.7.1 using:
      /private/var/folders/rc/05xmxx2d1z94wfq8gjy5g8640000gn/T/stack84578/glib-0.13.7.1/.stack-work/dist/x86_64-osx/Cabal-2.4.0.1/setup/setup --builddir=.stack-work/dist/x86_64-osx/Cabal-2.4.0.1 configure --user --package-db=clear --package-db=global --package-db=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/pkgdb --libdir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/lib --bindir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/bin --datadir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/share --libexecdir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/libexec --sysconfdir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/etc --docdir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/doc/glib-0.13.7.1 --htmldir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/doc/glib-0.13.7.1 --haddockdir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/doc/glib-0.13.7.1 --dependency=Cabal=Cabal-2.4.1.0-3JC906oWQ73Ah7bYkIcI4J --dependency=base=base-4.12.0.0 --dependency=bytestring=bytestring-0.10.8.2 --dependency=containers=containers-0.6.0.1 --dependency=gtk2hs-buildtools=gtk2hs-buildtools-0.13.5.4-FfuD6UPud4cCDbAMMHHwHX --dependency=text=text-1.2.3.1 --dependency=utf8-string=utf8-string-1.0.1.1-Geq8jdOv4Q3LkcQoEOWDVv -fclosure_signals --exact-configuration --ghc-option=-fhide-source-paths
    Process exited with code: ExitFailure 1

--  While building package cairo-0.13.6.0 using:
      /private/var/folders/rc/05xmxx2d1z94wfq8gjy5g8640000gn/T/stack84578/cairo-0.13.6.0/.stack-work/dist/x86_64-osx/Cabal-2.4.0.1/setup/setup --builddir=.stack-work/dist/x86_64-osx/Cabal-2.4.0.1 configure --user --package-db=clear --package-db=global --package-db=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/pkgdb --libdir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/lib --bindir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/bin --datadir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/share --libexecdir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/libexec --sysconfdir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/etc --docdir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/doc/cairo-0.13.6.0 --htmldir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/doc/cairo-0.13.6.0 --haddockdir=/Users/angudavi/.stack/snapshots/x86_64-osx/1c6cb3a584edc82087b134fc98289ebd76b21bafd8fc39b51e5ed691ff96a4db/8.6.5/doc/cairo-0.13.6.0 --dependency=Cabal=Cabal-2.4.1.0-3JC906oWQ73Ah7bYkIcI4J --dependency=array=array-0.5.3.0 --dependency=base=base-4.12.0.0 --dependency=bytestring=bytestring-0.10.8.2 --dependency=gtk2hs-buildtools=gtk2hs-buildtools-0.13.5.4-FfuD6UPud4cCDbAMMHHwHX --dependency=mtl=mtl-2.2.2 --dependency=text=text-1.2.3.1 --dependency=utf8-string=utf8-string-1.0.1.1-Geq8jdOv4Q3LkcQoEOWDVv -fcairo_pdf -fcairo_ps -fcairo_svg --exact-configuration --ghc-option=-fhide-source-paths
    Process exited with code: ExitFailure 1

running the first command, I get:
Configuring ihaskell-0.10.0.2...
Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5: Encountered missing dependencies:
aeson >=1.0,
base64-bytestring >=1.0,
cereal >=0.3,
cmdargs >=0.10,
directory -any,
filepath -any,
ghc >=8.0 && <8.9,
ghc-boot >=8.0 && <8.9,
ghc-parser >=0.2.1,
ghc-paths >=0.1,
haskeline -any,
haskell-src-exts >=1.18,
hlint >=1.9,
http-client >=0.4,
http-client-tls >=0.2,
ipython-kernel >=0.10,
mtl >=2.1,
parsec -any,
process >=1.1,
random >=1.0,
shelly >=1.5,
split >=0.2,
stm -any,
strict >=0.3,
text >=0.11,
time >=1.6,
unix >=2.6,
unordered-containers -any,
utf8-string -any,
vector -any

Any ideas on how to fix this? I have used "brew upgrade" to get the latest
 brew upgrade python3 zeromq libmagic cairo pkg-config haskell-stack pango
Warning: python3 3.7.6 already installed
Warning: zeromq 4.3.2 already installed
Warning: libmagic 5.38 already installed
Warning: cairo 1.16.0_2 already installed
Warning: pkg-config 0.29.2 already installed
Warning: haskell-stack 2.1.3 already installed
Warning: pango 1.44.7 already installed

**Comment by angusdavisadobe** [comment]
I also tried installing using the stack-8.4.yaml but got the same issue.

**Comment by vaibhavsagar** [comment]
Do you get the same error when you run `stack install zeromq4-haskell` from the project root directory?

**Comment by angusdavisadobe** [comment]
When running `stack build zeromq4-haskell` I get:
zeromq4-haskell> configure
zeromq4-haskell> Configuring zeromq4-haskell-0.8.0...
zeromq4-haskell> Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5: The program 'pkg-config' version
zeromq4-haskell> >=0.9.0 is required but it could not be found.
zeromq4-haskell>

**Comment by angusdavisadobe** [comment]
running `brew reinstall pkg-config` fixed things. I was able to install ihaskell.
Thanks for the nudge.

**Comment by vaibhavsagar** [comment]
Sure thing, glad I could help!
