### ISSUE TITLE
How do I run jupyter ihaskell from another folder?

### ISSUE THREAD

**Issue by angusdavisadobe** [gibiansky/IHaskell#1135]
Since IHaskell depends on the packages exposed in the stack.yaml file, I am forced to run jupyter inside the IHaskell folder using `stack exec jupyter -- notebook` which means the IHaskell folder is the root of my tree. 
How can I run jupyter from another folder or is there a way to navigate upwards in Jupyter?

**Comment by vaibhavsagar** [comment]
After IHaskell is installed, you can run it from any Stack project with a compatible resolver with `stack exec jupyter -- notebook`. See https://github.com/gibiansky/IHaskell/issues/792#issuecomment-349186483 for more details.

**Comment by vaibhavsagar** [comment]
Closing, please reopen if required.
