### ISSUE TITLE
MessageHeader buffers

### ISSUE THREAD

**Issue by jamesdbrock** [gibiansky/IHaskell#1144]
There is a way for the Jupyter frontend to communicate arbitrary binary blobs with the kernel, by the [`IMessage.buffers`](https://github.com/jupyterlab/jupyterlab/blob/b66bb79116285ccbd0876a6263ac2c0d6de27c33/packages/services/src/kernel/messages.ts#L277)

It would be nice if the IHaskell IPython kernel could send and receive `buffers`. I suppose they would be added here, in the [`IHaskell.IPython.Types.MessageHeader`](https://github.com/gibiansky/IHaskell/blob/9dd237ea0480302fd7a34c0eeef0fe97bca3ae1a/ipython-kernel/src/IHaskell/IPython/Types.hs#L149). 

 This new field would have the type `buffers :: [ByteString]`, just like `mhIdentifiers :: [ByteString]` which, by the way, stores the ASCII-encoded `mhSessionId` and `mhMessageId`.

Perhaps `buffers` was added in some latter Jupyter protocol version which IHaskell hasn't caught up with? I haven't investigated yet.

**Comment by jamesdbrock** [comment]
I guess IHaskell IPython is on [version 5.0](https://github.com/gibiansky/IHaskell/blob/9dd237ea0480302fd7a34c0eeef0fe97bca3ae1a/ipython-kernel/src/IHaskell/IPython/Types.hs#L166).

I don't see any mention of `buffers` in the Jupyter client changelog https://jupyter-client.readthedocs.io/en/stable/changelog.html

**Comment by jamesdbrock** [comment]
https://jupyter-client.readthedocs.io/en/stable/messaging.html#the-wire-protocol

I think we could add `buffers` handling [here in `receiveMessage`](https://github.com/gibiansky/IHaskell/blob/9dd237ea0480302fd7a34c0eeef0fe97bca3ae1a/ipython-kernel/src/IHaskell/IPython/ZeroMQ.hs#L281) and it might just work.

**Comment by jamesdbrock** [comment]
How do we [`receive`](https://hackage.haskell.org/package/zeromq4-haskell-0.6.5/docs/System-ZMQ4.html#v:receive) the optional buffers?

**Comment by vaibhavsagar** [comment]
I don't know that much about the new JupyterLab protocol, but if you make a PR I will happily review it.
