### ISSUE TITLE
ihaskell_labextension JupyterLab 2

### ISSUE THREAD

**Issue by jamesdbrock** [gibiansky/IHaskell#1159]
Regarding comments by in @GTrunSec in #1151

Hi @GTrunSec , yeah that's not working.

Have you tried installing __ihaskell_labextension__ from the Development install instructions? https://github.com/gibiansky/IHaskell/tree/master/ihaskell_labextension#development

The NPM package uploader https://www.npmjs.com/~m-ihaskell is @MMesch , who wrote the __ihaskell_labextension__ and also wrote https://github.com/tweag/jupyterWith/

What is this __ihaskell_labextension__ version 0.0.9 ? https://www.npmjs.com/package/jupyterlab-ihaskell 

I bumped __ihaskell_labextension__ to version 0.0.7 in #1151 . Does that conflict with some other branch of __ihaskell_labextension__ ? I hope @MMesch can advise us here.

**Comment by GTrunSec** [comment]
> Have you tried installing **ihaskell_labextension** from the Development install instructions? https://github.com/gibiansky/IHaskell/tree/master/ihaskell_labextension#development

Yes, I copied *ihaskell_labextension* to my own repo that makes sure I can using npm pack `ihaskell_labextension`.tar.gz to install it. Also, I did it.   https://github.com/GTrunSec/Jupyter-data-science-environment/blob/26d5d2715958091d6fc12ae9f974a7327ebf86a5/osx-env.nix#L85. from my snapshot image like you saw installation goes well, but the syntax highlight does not work.

**Comment by Yvee1** [comment]
Hello, I have been trying to get IHaskell working today with jupyterWith and the syntax highlighting from the labextension, and in the end I did get it working. So for future reference for myself and others I'm listing my steps here briefly:
- Install `jupyterWith` if not done so already
- Add `directory = ./jupyterlab;` to your `shell.nix` such that it looks something like below.
- Do `nix-shell` inside your project directory and do `generate-directory @bokeh/jupyter_bokeh`, or some other Jupyter lab extension. This generates all the necessary files in the `jupyterlab` folder
- Clone https://github.com/GTrunSec/ihaskell_labextension, follow the development instructions and do `npm pack`
- Place the resulting file `ihaskell_jupyterlab-0.0.7.tgz` in the `jupterlab/extensions` folder.

My `shell.nix`:
```nix
let
  jupyter = import (builtins.fetchGit {
    url = https://github.com/tweag/jupyterWith;
    rev = "";
  }) {};

  iPython = jupyter.kernels.iPythonWith {
    name = "python";
    packages = p: with p; [ numpy ];
  };

  iHaskell = jupyter.kernels.iHaskellWith {
    name = "haskell";
    packages = p: with p; [ diagrams ihaskell-diagrams Chart ];
  };

  jupyterEnvironment =
    jupyter.jupyterlabWith {
      kernels = [ iPython iHaskell ];
      directory = ./jupyterlab;
    };

in
  jupyterEnvironment.env
```

**Comment by GTrunSec** [comment]
@Yvee1  Thanks for helping. Fixed this issue by set `root` to build the extension. the command as following:
```
sudo generate-directory ./jupyterlab/extensions/ihaskell_jupyterlab-0.0.7.tgz 
```
my environment test: https://github.com/GTrunSec/Jupyter-data-science-environment/blob/f9bb5977ccd959c0a5a430914d62a7cf56394736/default.nix#L108

![image](https://user-images.githubusercontent.com/21156405/90356541-b5095480-e004-11ea-8de8-f32e9a4459fa.png)

**Comment by jamesdbrock** [comment]
Hey @GTrunSec and @Yvee1 there is news about this, see https://github.com/tweag/jupyterWith/pull/116

The  *jupyterWith* *Funflow* Haskell example shows how to build the JupyterLab 2 __ihaskell_labextension__ in a one-step Nix derivation.

https://github.com/tweag/jupyterWith/blob/48bd88ac0acb4aaa841debe5fb201c297f374101/example/Haskell/Funflow/shell.nix#L16-L26

**Comment by junjihashimoto** [comment]
This dockerfile(https://github.com/hasktorch/hasktorch-jupyter/blob/master/Dockerfile) doesn't use nix, but ihaskell_labextension is 0.7 with jupyter lab 2.2.5. hightlight works.
Is this issue solved with jupyter lab 2.2 instead of jupyter lab 2.1?
Is it a issue of jupyterWith not ihaskell?

**Comment by jamesdbrock** [comment]
> Is this issue solved with jupyter lab 2.2 instead of jupyter lab 2.1?

I believe the __ihaskell_labextension__ v0.0.7 will work for any JupyterLab 2.

> Is it a issue of jupyterWith not ihaskell?

At this point, the only remaining problem I'm aware of is that there is no JupyterLab 2 __ihaskell_labextension__ on NPM.

**Comment by GTrunSec** [comment]
> I believe the **ihaskell_labextension** v0.0.7 will work for any JupyterLab 2.
yeh, It works well with my stable Jupyterlab environment which is the version between 2.1 to 2.2 even 3.0xal also works well.
- 2.1x 
![image](https://user-images.githubusercontent.com/21156405/91370437-37430700-e7c3-11ea-8569-30d8bb697dda.png)

- 3.0x
![image](https://user-images.githubusercontent.com/21156405/91370353-f814b600-e7c2-11ea-9304-926d30546f5a.png)

**Comment by junjihashimoto** [comment]
@jamesdbrock 
These are in a personal account.
ihaskell_jupyterlab
jupyterlab-ihaskell
https://www.npmjs.com/~m-ihaskell

Should we create an organizational account and move these packages into it?
Do you have ihaskell organization?
![image](https://user-images.githubusercontent.com/2469618/92081576-3bdc7080-edfe-11ea-8d95-9d367f2bbc10.png)

**Comment by MMesch** [comment]
Hey all, I am back now and available, for example to transfer account rights. At the moment I have access and @vaibhavsagar . I am not really experienced with npm and don't know what it implies but maybe an organizational account is the right way forward. Any thoughts?

**Comment by MMesch** [comment]
@jamesdbrock @vaibhavsagar I have a suggestion: 

The reason we we need an extension for syntax highlighting is that the ihaskell kernel requests a codemirror mode that is called `ihaskell`: https://github.com/gibiansky/IHaskell/blob/master/main/Main.hs#L249 . This is different from the two Haskell codemirror modes `Haskell` and `Haskell (literate)` that are available by default.

The reason why these defaults aren't used are the `:` commands that are used in ihaskell: https://github.com/gibiansky/IHaskell/blob/master/ihaskell_labextension/src/codemirror-ihaskell.ts#L10-L14 and there is also a slightly strange feature to highlight [haskell-r](https://github.com/tweag/HaskellR) quasiquotes with r syntax: https://github.com/gibiansky/IHaskell/blob/master/ihaskell_labextension/src/codemirror-ihaskell.ts#L16-L21 .

We could make the ihaskell kernel configurable (`--codemirror ihaskell`) to use `--codemirror Haskell` by default. This would mean that no extension needs to be installed to use ihaskell which simplifies installation via nixpkgs. We could still provide an extension if we wanted to that provides extra syntax. I guess it would mostly affect highlighting the Language extensions. Maybe an `ihaskell` mode could even be added upstream in the codemirror repo. We wouldn't have to maintain this extension than anymore.

**Comment by MMesch** [comment]
This PR https://github.com/gibiansky/IHaskell/pull/1189 brings the extension up to date with the one used on npmjs. I'll investigate if we can get rid of it entirely as well.

**Comment by MMesch** [comment]
PR #1191 adds a new flag to chose the codemirror mode. The extension is not really necessary anymore. You can simply start the kernel with `--codemirror Haskell` to get syntax that is supported in jupyterlab.

I think this issue can be closed.
