### ISSUE TITLE
state of ihaskell in nixos 20.03 with ghc883?

### ISSUE THREAD

**Issue by zeta-00** [gibiansky/IHaskell#1160]
hello there, i was wondering if ihaskell works in nixos 20.03 with ghc883 ? i tried setting up ihaskell in a shell.nix file to use in a nix-shell, but i kept getting a broken package error, so if you have a shell.nix file with ihaskell that works, let me know, here's the shell.nix file that i'm using to try and setup ihaskell in a nix-shell and here's the error that it's throwing:

(note: i'm using (lorri+direnv+emacs-direnv), that's why i'm trying to get ihaskell working in buildInputs inside mkShell)

(also, thanks in advance for the help)

let
  pkgs = import <nixpkgs> {};
in
with pkgs;
mkShell
  {
    buildInputs = with pkgs;

      import "${pkgs.ihaskell}/release.nix"
        {
          nixpkgs = import pkgs.nixpkgs {};
          compiler = "ghc883";
          packages = self: with self;
            [
              ihaskell
            ];
        };
      
    shellHook =
      ''
         export EDITOR="$(emacs)";

         export HIE_HOOGLE_DATABASE="$(cat $(which hoogle) | sed -n -e 's|.*--database \\(.*\\.hoo\\).*|\\1|p')";
         export NIX_GHC="$(which ghc)";
         export NIX_GHCPKG="$(which ghc-pkg)";
         export NIX_GHC_DOCDIR="$NIX_GHC/../../share/doc/ghc/html";
         export NIX_GHC_LIBDIR="$(ghc --print-libdir)";
      '';
    
  } # end of mkShell

[zeta@nixos:/ihaskell]$ nix-shell 
error: Package ‘ihaskell-0.10.0.2’ in /nix/store/rfk5j99kh4ny0jfi0m88yapv3pbw19nr-nixos-20.03.1619.ab3adfe1c76/nixos/pkgs/development/haskell-modules/hackage-packages.nix:137028 is marked as broken, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
[zeta@nixos:/ihaskell]$

**Comment by vaibhavsagar** [comment]
The `release.nix` in this repository works and [is tested](https://github.com/gibiansky/IHaskell/blob/0ef1f37fcedb7146786638488d38b812ca41352e/.travis.yml#L424-L427).
