### ISSUE TITLE
ihaskell error: jupyter, ghc and ihaskell binaries are not being detected?

### ISSUE THREAD

**Issue by zeta-00** [gibiansky/IHaskell#1168]
hello there,
(note: i did not ask this in the emacs-ipython-notebook repository because this error has more to do with nix)
anyways, i decided to move my ihaskell `let in` expression(which works fine in home.nix) from home.nix to a shell.nix file to be used with my ((lorri+direnv+emacs-direnv) setup(which works with my other shell.nix projects)), but for some reason ihaskell is not working in this shell.nix file, and emacs is throwing these errors?

~/.ihaskell 
ein: [warn] ein:jupyter-default-kernel: (json-readtable-error 47)
ein:run: Command jupyter not found or not executable

i thought ihaskell's release.nix file( https://github.com/gibiansky/IHaskell/blob/2429f3560f3ff1e02278f38a15b93c1598e1779b/release.nix ) automatically installs all the needed dependencies and configures everything, or is there more stuff that i need to add to the shell.nix file?

pasted below is the shell.nix file that i'm using, thanks in advance for helping me fix this problem that i'm having:

let
  pkgs = import <nixpkgs> {};
in
with pkgs;
mkShell
  {
    inputsFrom = with pkgs;
      [
        (let
          ihaskell = fetchFromGitHub
            {
              owner = "gibiansky";
              repo = "IHaskell";
              rev = "36f0acdeaabf908265aed4ce7c5b0333db1ee815";
              sha256 = "18rcsxz6gsrpnapgfdiis1k376147bn2hk591isj22f6f0b9fhn6";
            };
         in import "${ihaskell}/release.nix"
           {
             compiler = "ghc883";
             nixpkgs = pkgs;
             packages = self: with self;
               [
                 ihaskell
                 ihaskell-aeson
                 # ihaskell-basic
                 ihaskell-blaze
                 # ihaskell-charts
                 # ihaskell-diagrams
                 # ihaskell-display
                 # ihaskell-gnuplot
                 ihaskell-graphviz
                 ihaskell-hatex
                 # ihaskell-hvega
                 # ihaskell-inline-r
                 ihaskell-juicypixels
                 ihaskell-magic
                 # ihaskell-parsec
                 # ihaskell-plot
                 # ihaskell-rlangqq
                 # ihaskell-widgets
               ];
           }
        )
      ];
    
    # shellHook ='''';
    
  } # end of mkShell

**Comment by zeta-00** [comment]
i also asked this as a stackoverflow question, so if you want to see the shell.nix file with better formatting, then here it is: https://stackoverflow.com/questions/61576103/nix-configuration-ihaskell-not-working-in-the-shell-nix-setup-used-for-lorri

**Comment by vaibhavsagar** [comment]
You can't stick `release.nix` into `inputsFrom` in your `shell.nix`. I don't understand how you were expecting that to work.

When I run the `shell.nix` file you provided, I don't see `jupyter` on the $PATH, which explains the error you're getting.

The way I intended `release.nix` to be used is that it creates some [`ihaskell-*` scripts](https://github.com/gibiansky/IHaskell/blob/2429f3560f3ff1e02278f38a15b93c1598e1779b/release.nix#L82-L85) that set some environment variables before launching e.g. `jupyter notebook`. My suggestion is to try putting it in `buildInputs` instead of `inputsFrom` (I commented out all the `ihaskell-*` packages so this would build quicker):

```nix
let
  pkgs = import <nixpkgs> {};
in
with pkgs;
mkShell
  {
    buildInputs = with pkgs;
      [
        (let
          ihaskell = fetchFromGitHub
            {
              owner = "gibiansky";
              repo = "IHaskell";
              rev = "36f0acdeaabf908265aed4ce7c5b0333db1ee815";
              sha256 = "18rcsxz6gsrpnapgfdiis1k376147bn2hk591isj22f6f0b9fhn6";
            };
         in import "${ihaskell}/release.nix"
           {
             compiler = "ghc883";
             nixpkgs = pkgs;
             packages = self: with self;
               [
                 ihaskell
                 # ihaskell-aeson
                 # ihaskell-basic
                 # ihaskell-blaze
                 # ihaskell-charts
                 # ihaskell-diagrams
                 # ihaskell-display
                 # ihaskell-gnuplot
                 # ihaskell-graphviz
                 # ihaskell-hatex
                 # ihaskell-hvega
                 # ihaskell-inline-r
                 # ihaskell-juicypixels
                 # ihaskell-magic
                 # ihaskell-parsec
                 # ihaskell-plot
                 # ihaskell-rlangqq
                 # ihaskell-widgets
               ];
           }
        )
      ];

    shellHook =
      ''
         export EDITOR="$(emacs)";
      '';

  } # end of mkShell
```

When I try this it seems to have `jupyter` in scope at least.

In any case, the IHaskell issue tracker isn't the right place for Nix questions, so I'm going to close this now.
