### ISSUE TITLE
the haskell kernel does not boot

### ISSUE THREAD

**Issue by Levovsky** [gibiansky/IHaskell#1174]
Hello. Sorry right away for your bad english. 
I have a problem. The kernel does not load when I create a notebook with a haskell kernel. What should I do? 
System: linux mint 19.3
I am still new to linux. Thank you for your attention.

**Comment by vaibhavsagar** [comment]
1. How did you install IHaskell?
2. How are you running IHaskell?
3. What is the output in the terminal when you try to create a notebook?

I suspect you might have to `mv stack-8.8.yaml stack.yaml` and reinstall for this problem to go away.
