### ISSUE TITLE
setting up ihaskell's auto-completion and all of it's other features in emacs?

### ISSUE THREAD

**Issue by zeta-00** [gibiansky/IHaskell#1175]
hello again,

after some tinkering and figuring out some edge cases, i finally got ihaskell working with my nix setup: (lorri+direnv+emacs-direnv), which works great, but for some reason i have not been able to get ihaskell's auto-completion and all of it's other features working with emacs-ipython-notebook, i followed the documentation for emacs haskell-mode( http://haskell.github.io/haskell-mode/manual/latest/ ) and setup my .emacs config, but the haskell auto-completion is still not working(i tried both .ipynb and .hs files, and auto-completion did not work for either).

for now i am using atom for ihaskell because of it's hydrogen package( ttps://atom.io/packages/hydrogen ), hydrogen comes with great built-in support for ihaskell, all i have to do is install the haskell-language(also hasklig for nice ligatures) and hydrogen packages, and setup the `language mapping option` in hydrogen's settings to: { "haskell": "haskell" }, and all of ihaskell's features work out-of-the-box, by hydrogen using ihaskell's kernel for the kernel's built-in functionality.

does emacs have a package that works similarly to atom's hydrogen? i already asked the the emacs-ipython-notebook devs, but they tell me that they do not understand haskell/ihaskell that well, i asked in #haskell and #emacs as well, but so far i have not been able to find someone that uses ihaskell with emacs, so that i can ask them for help setting it up.

i asked in reddit( https://www.reddit.com/r/emacs/comments/gh4jup/emacs_jupyter_support/ ), and some people mentioned a couple of alternatives, one that looks promising is emacs-jupyter( https://github.com/dzop/emacs-jupyter ).

hydrogren's `how it works` section mentions how it implements jupyter to use a messaging protocol to communicate with a language kernel, but i have no idea how difficult that would be to configure for ihaskell/emacs?

ihaskell is an amazing tool, which has greatly improved my workflow, but it is difficult to setup with text-editors/ides without any documentation specific to ihaskell. apologies for going off on a tangent.

anyways, thanks in advance for helping me fix this issue.

here is the elisp code in my .emacs  configuration, that i setup for ihaskell:

;;------------------------------------------------------------------
;; emacs-ipython-notebook configuration:
(setq ein:polymode t)
(add-hook 'haskell-mode-hook 'company-mode)
(setq ein:completion-backend 'ein:use-company-backend)
;;------------------------------------------------------------------
;; haskell-mode configuration:
(add-hook 'haskell-mode-hook 'haskell-indentation-mode)
(add-hook 'haskell-mode-hook 'interactive-haskell-mode)
;;------------------------------------------------------------------

here is my shell.nix file for ihaskell that i finally got working(here's a pastebin if github's formatting comes out messed up: https://dpaste.org/6JSM ):

let
  pkgs = import <nixpkgs> {};
in
with pkgs;
mkShell
  {
    buildInputs = with pkgs;
      [
        (let
          ihaskell = fetchFromGitHub
            {
              owner = "gibiansky";
              repo = "IHaskell";
              rev = "a1e415e45f6a1fe61a455459f9e6036591bc2c47";
              sha256 = "1ll27jqnssdxjsfcn2ll0x95kwjk6rhfnsxsdsh03izq95hxys1p";
            };
         in import "${ihaskell}/release.nix"
           {
             compiler = "ghc883";
             nixpkgs = pkgs;
             packages = self: with self;
               [
                 ihaskell
                 ihaskell-aeson
                 # ihaskell-basic
                 ihaskell-blaze
                 # ihaskell-charts
                 # ihaskell-diagrams
                 # ihaskell-display
                 # ihaskell-gnuplot
                 ihaskell-graphviz
                 ihaskell-hatex
                 # ihaskell-hvega
                 # ihaskell-inline-r
                 ihaskell-juicypixels
                 ihaskell-magic
                 # ihaskell-parsec
                 # ihaskell-plot
                 # ihaskell-rlangqq
                 # ihaskell-widgets
               ];
           }
        )
      ];
    
    shellHook =
      ''
         export EDITOR=emacs;
      '';
    
  } # end of mkShell

**Comment by zeta-00** [comment]
this jupyter messaging protocol looks like something useful, that could help fix ihaskell's functionality issue with emacs, hydrogen implements it as a front-end to communicate with the language kernels:

https://jupyter-client.readthedocs.io/en/latest/messaging.html

**Comment by vaibhavsagar** [comment]
IHaskell already [implements](https://github.com/gibiansky/IHaskell/blob/a992ad83702e55b774de234d77ffd2682d842682/ipython-kernel/src/IHaskell/IPython/Types.hs#L319-L509) and [uses](https://github.com/gibiansky/IHaskell/blob/a992ad83702e55b774de234d77ffd2682d842682/main/Main.hs#L167-L202) the messaging protocol, it would not work if we did not.

**Comment by zeta-00** [comment]
ok, according to ein's documentation, i need to setup company-mode ein in order to get the ihaskell kernel's built-in auto-completion:

http://millejoh.github.io/emacs-ipython-notebook/#ein:completion-backend

after setting up company-mode, auto-completion works great in regular haskell files(C-c C-l (to activate company-ghci)), but in ihaskell, the auto-completion is still not working:

;;------------------------------------------------------------------
;; haskell-mode configuration:
(with-eval-after-load 'company
  (push 'company-ghci company-backends))

(add-hook 'haskell-mode-hook 'company-mode)
(add-hook 'haskell-mode-hook 'interactive-haskell-mode)
(add-hook 'haskell-interactive-mode-hook 'company-mode)
(add-hook 'haskell-mode-hook 'haskell-indentation-mode)
;;------------------------------------------------------------------
;; emacs-ipython-notebook configuration:
(setq ein:polymode t)
(setq ein:completion-backend 'ein:use-company-backend)
;;------------------------------------------------------------------


i already asked a similar question to the ein devs, and i'm going to continue experimenting to see if i can make progress with this.

**Comment by zeta-00** [comment]
a lot of the online instructions require ghc-mod, which is outdated, especially for the newer versions of ghc, so that takes away a lot of problems.

on regular haskell projects, i use ghcide, so that would be great if someday ghcide would work with ihaskell.

**Comment by vaibhavsagar** [comment]
This is no longer an IHaskell issue.
