### ISSUE TITLE
Jupyter Lab error

### ISSUE THREAD

**Issue by gulfpearl** [gibiansky/IHaskell#1180]
With Jupyter lab, the kernel won't start and  I get the error:

` mismatched interface file versions (wanted "8065", got "8083")`

However, it works with Jupyter notebook.

**Comment by vaibhavsagar** [comment]
Do you have a GHC 8.8.3 installation on your computer that you could remove before trying again?

**Comment by vaibhavsagar** [comment]
Closing, please reopen if required.
