### ISSUE TITLE
kernel won't start...

### ISSUE THREAD

**Issue by sebeaumont** [gibiansky/IHaskell#1192]
ihaskell was installed with cabal (ghc-8.8.4/cabal-3.2.0.0):
```
cabal install ihaskell
ihaskell install
```
then tried to start ihaskell kernel from jupyter notebook...  
```
[I 21:01:56.194 NotebookApp] Kernel started: defd5bb4-e975-4ad4-aed7-877f738c2cf5
[W 21:01:56.437 NotebookApp] 404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js?v=20201004210147 (::1) 11.19ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=haskell
ihaskell: Not in scope: ‘IHaskell.Display.displayFromChanEncoded’
No module named ‘IHaskell.Display’ is imported.
```

**Comment by vaibhavsagar** [comment]
We don't support `cabal` as an installation method. It looks like what might be happening is that whatever package database you are using when you are running the notebook doesn't include the `ihaskell` package, which would explain the error you are seeing.

**Comment by sebeaumont** [comment]
Are you planning to support cabal? Maybe you can invoke ghc like `hie-bios`

**Comment by vaibhavsagar** [comment]
No, that won't work for us because of the way we use the GHC API. To be clear, IHaskell does work with `cabal-install` (or it did the last time I tried it), but it's fiddly and confusing to set up which is why I don't have instructions up for it and am not interested in officially supporting it.
