### ISSUE TITLE
Code cell shell exit code non-zero format

### ISSUE THREAD

**Issue by jamesdbrock** [gibiansky/IHaskell#1196]
In JupyterLab 2.2.9 (and prior versions), the IHaskell kernel doesn't format the output of shell commands correctly if the shell process exits with non-zero error code.

For example, with IPython kernel:

![Screenshot from 2020-11-22 20-38-54](https://user-images.githubusercontent.com/1526224/99902732-5dfdd480-2d03-11eb-9b13-efcb9ba507c0.png)

But with IHaskell kernel:

![Screenshot from 2020-11-22 20-41-19](https://user-images.githubusercontent.com/1526224/99902739-681fd300-2d03-11eb-8c61-6faf74bb75d4.png)

**Comment by vaibhavsagar** [comment]
Here's what I think the relevant snippet of code is:
https://github.com/gibiansky/IHaskell/blob/aa15573158f91d3dedde38c76debf1e0ba171731/src/IHaskell/Eval/Evaluate.hs#L708-L716

It seems like we're doing a reasonable thing. How do you think we should handle this instead?

**Comment by vaibhavsagar** [comment]
Maybe we shouldn't be trying to output an HTML version at all? I will try that and see if it's more consistent.

**Comment by vaibhavsagar** [comment]
I went ahead and did this because we were never producing HTML in the success case, which was causing the inconsistency.
