### ISSUE TITLE
I can't install because diagrams fails to build

### ISSUE THREAD

**Issue by saucetray** [gibiansky/IHaskell#1200]
```--  While building package diagrams-lib-1.4.3 using:
      /Users/saucetray/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.4 --builddir=.stack-work/dist/x86_64-osx/Cabal-3.0.1.0 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

I am running Big Sur and I can't seem to build this package. It seems like when I build it alone, it gives me that the cocoa framework can't be found but I have Xcode tools.

**Comment by jamesdbrock** [comment]
You're using these [Mac](https://github.com/gibiansky/IHaskell#mac) build instructions, I take it?

**Comment by saucetray** [comment]
Yes.. I think this is a GHC issue. Sorry.
