### ISSUE TITLE
Missing extension module "lib/index.js"

### ISSUE THREAD

**Issue by borgauf** [gibiansky/IHaskell#1203]
I just installed IHaskell following the Linux instructions (I'm on Ubuntu 21.04) and left out

`jupyter labextension install jupyterlab-ihaskell`

I got jupyter to open with

`stack exec jupyter -- notebook`

I killed it then tried the jupyterlab-ihaskell command again, but got

ValueError: "jupyterlab-ihaskell" is not a valid extension:
Missing extension module "lib/index.js"

What have I done wrong?

**Comment by jamesdbrock** [comment]
In September, *IHaskell* was changed so that you no longer need the *jupyterlab-ihaskell* extension to get syntax highlighting. https://github.com/gibiansky/IHaskell/pull/1191

See https://github.com/gibiansky/IHaskell/issues/1202#issuecomment-755118387
