### ISSUE TITLE
Is this install fighting with my previous Anaconda install?

### ISSUE THREAD

**Issue by borgauf** [gibiansky/IHaskell#1204]
I've installed IHaskell as instructed, but I do have a previous Anaconda environment on my Ubuntu 20.04. Are these installs fighting? For example, what is the difference between starting with

`jupyter notebook`

or

`stack exec jupyter -- notebook`

Either way, I can only see the home root directory, i.e., files are being created in my home directory. I tried to change the working directory, i.e.

`jupyter notebook --generate-config`

then changing in `~/.jupyter/jupyter_notebook_config.py`

...
c.NotebookApp.notebook_dir = '/home/lawrence/Notebooks/Haskell'

This has no effect. Are there any tutorials?

**Comment by vaibhavsagar** [comment]
I don't have enough information to say whether this install is clobbering your Anaconda install, but have you tried running `stack exec jupyter -- notebook` from the directory you want files to be created in, such as `/home/lawrence/Notebooks/Haskell`?

**Comment by borgauf** [comment]
I'm fairly certain now they are not in conflict, because it would seem a IHaskell is a completely separate, stand-alone world from Anaconda when cloned from here. My problem is none of the help for normal Jupyter Notebook seems to apply to this IHaskell version. For example, footnotes don't seem to work, and what about mono-spaced font for code? I can look up answers, but they don't seem to apply to IHaskell. Some tutorials would help on what's different and what's the same.

**Comment by vaibhavsagar** [comment]
We have https://github.com/gibiansky/IHaskell/blob/master/notebooks/IHaskell.ipynb, which is reasonably comprehensive.

**Comment by vaibhavsagar** [comment]
Closing because there doesn't really seem to be an issue to be resolved here.
