### ISSUE TITLE
ihaskell kernel crash with gloss and essence-of-live-coding

### ISSUE THREAD

**Issue by miguel-negrao** [gibiansky/IHaskell#1206]
When running the notebook [here](https://github.com/miguel-negrao/essence-of-live-coding-tutorial/blob/master/essence.ipynb) the kernel crashes:

```
[xcb] Unknown sequence number while processing reply
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
ihaskell: ../../src/xcb_io.c:643: _XReply: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```

It is possible to run this notebook by cloning the repo [here](https://github.com/miguel-negrao/essence-of-live-coding-tutorial) and doing `stack build`, then running `stack exec jupyter -- notebook` from that directory.

Linux debian 10. Ihaskell installed from source (git clone) with 

```
stack install --fast
ihaskell install --use-rtsopts="-N4" --stack
```

This works fine when running from ghci which I believe is also threaded by default.

**Comment by jamesdbrock** [comment]
Hm that's a tricky one. Have you tried `--use-rtsopts="-N1"` to force the runtime to be single-threaded? https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-concurrent.html#rts-options-for-smp-parallelism

**Comment by miguel-negrao** [comment]
Still crashes:

Using vscode notebooks: (which prints the exact ihaskell command)
```
~/.local/bin/ihaskell kernel /tmp/tmp-13727xMa0KpTLr5ie.json --ghclib ~/.stack/programs/x86_64-linux/ghc-tinfo6-8.8.4/lib/ghc-8.8.4 +RTS -N1 -RTS --stack
cwd: ~/Development/Haskell/checkouts/essence-of-live-coding-tutorial
```
Same behaviour with ```stack exec jupyter -- notebook```

**Comment by miguel-negrao** [comment]
It was not a problem with IHaskell, just that "load" and "save" from essence of live coding shouldn't be used with IHaskell.
