### ISSUE TITLE
Access local package when using Docker.

### ISSUE THREAD

**Issue by Lemmih** [gibiansky/IHaskell#1207]
Running `docker run --rm -p 8888:8888 -v "$PWD":/home/jovyan/work gibiansky/ihaskell` from the folder of a local package gives me an instance of Jupyter/IHaskell which doesn't have access to said local package. Do I need to do something special to get IHaskell to read my `stack.yaml` file? Isn't running `import LocalModule` enough?

**Comment by vaibhavsagar** [comment]
IHaskell doesn't include any package management logic internally, the extent of its integration with Stack is to use `stack exec -- env` to get the environment variables it needs. It won't pick up your host machine's package database, which I think would be required to get the behaviour that you are expecting here. However, I think this might be made to work with a few extra steps, e.g. running `:!stack build` from within the notebook, which would download and build all necessary dependencies in the container, and then restarting. I'm not sure though, I would need to try this and report back.

**Comment by vaibhavsagar** [comment]
I tried running `!stack build` in a notebook launched from the `work` directory, and then launching a new notebook gave me access to the compiled modules.
