### ISSUE TITLE
Publish versions on Docker Hub

### ISSUE THREAD

**Issue by ad-si** [gibiansky/IHaskell#1209]
Currently there is only `latest` available on Docker Hub:
https://hub.docker.com/r/gibiansky/ihaskell/tags

If a new broken version is pushed there is no way to use an older working version. This is a big red flag for anyone trying to productively use IHaskell.

Shouldn't be too hard to adapt the CI publishing workflow, right?

**Comment by vaibhavsagar** [comment]
We don't currently have any automated versioning/release process, I'm still uploading packages to e.g. Hackage manually. It would actually be a fair amount of work to adapt the current workflow. What other images would you want us to upload to Docker Hub?

**Comment by ad-si** [comment]
It would already be enough to simply push the image with another tag in addition to `ihaskell:latest`. E.g. something like `haskell:lts-16.23-5b7e03b`.
All it needs is a simple script to build the tag slug.

**Comment by vaibhavsagar** [comment]
Closed by https://github.com/gibiansky/IHaskell/commit/e07b198f07d7dc7a12863f8507439ae3834947e4.

**Comment by ad-si** [comment]
Awesome, thanks!
