### ISSUE TITLE
ihaskell-{display, basic}: too strict version bounds on hackage

### ISSUE THREAD

**Issue by sternenseemann** [gibiansky/IHaskell#1217]
base is restricted too much despite building fine with most recent base.

**Comment by vaibhavsagar** [comment]
Both these packages are no longer in use (and I don't think i even have Hackage maintainer permissions to do anything about this). A quick search for reverse dependencies (https://packdeps.haskellers.com/reverse/ihaskell-display and https://packdeps.haskellers.com/reverse/ihaskell-display) doesn't turn up anything. I'm closing this.

**Comment by sternenseemann** [comment]
Huh, `nixpkgs` includes them in the default package list for its `ihaskell-wrapper`. This thing is somewhat outdated, it'd be cool if you could take a look at it since I have no clue about IHaskell, so can't really judge what is required to implement it properly.

Current state: <https://github.com/NixOS/nixpkgs/blob/haskell-updates/pkgs/development/tools/haskell/ihaskell/wrapper.nix>

**Comment by vaibhavsagar** [comment]
Oh weird, thanks for letting me know! I would be happy to contribute a change to improve this.
