### ISSUE TITLE
Hiding / suppressing cell output

### ISSUE THREAD

**Issue by vreuter** [gibiansky/IHaskell#1219]
Hello, thanks for a fantastic development tool! I'm wondering if there's a way to suppress / hide output on a per-cell basis? For example, to avoid unused pragma warnings where the pragmas apply to cells later in the notebook, but I want to declare them in the first cell. Sorry if I missed this in the code or already-solved/-opened issues, but a quick search didn't turn up anything.

**Comment by vaibhavsagar** [comment]
Thanks for the kind words! Jupyter notebooks have a way of hiding output on a per-cell basis already, would that meet your requirements? 
![toggle-cell-output](https://user-images.githubusercontent.com/1525767/119775331-cd4cbf00-bf06-11eb-987a-c779f132641e.png)

**Comment by vreuter** [comment]
Thanks for your reply @vaibhavsagar ! I think the output will re-appear as I'm running a script to batch produce HTML from a few notebooks, so I was hoping for a programmatic solution, but it's no big deal if one's unavailable.

**Comment by vaibhavsagar** [comment]
I don't think a programmatic solution is available in IHaskell.

**Comment by vreuter** [comment]
No problem, thanks for the info & again, for making working in Haskell in a REPL so much nicer!
