### ISSUE TITLE
Enable profiling build

### ISSUE THREAD

**Issue by daviddavo** [gibiansky/IHaskell#1226]
It would be nice to enable profiling, as it enables some useful features for debugging

With nix, it should be as easy as adding a boolean parameter to the build and setting up the environment if it's set to true. With stack, you can do `stack build --profile`, but It fails as the dependencies are not properly configured.

1. See [Debugging](https://wiki.haskell.org/Debugging) In Haskell's wiki

**Comment by vaibhavsagar** [comment]
You need to set up the dependencies correctly, that is not something I have control over.
