### ISSUE TITLE
The command :hoogle no longer works

### ISSUE THREAD

**Issue by wstomv** [gibiansky/IHaskell#1232]
The command `:hoogle`used to work nicely (and conveniently). But now it no longer does so. The kernel just hangs when executing it. The command `:doc` still works.

I then upgraded my IHaskell installation to the latest version (`ihaskell --version` says `0.10.2.0`), which took some effort (e.g., I had to edit `~/.stack/global-project/stack.yaml` to change `resolver` to match the one mentioned in IHaskell's `stack.yaml`. But that made no difference.

Any idea what can be the matter? And how to fix it (or a workaround)?

I work on macOS 10.14.6 with GHC 8.6.3.

**Comment by vaibhavsagar** [comment]
This still works for me on the latest IHaskell (https://github.com/gibiansky/IHaskell/commit/a6d0a651f3116f03d8c8e212982d3d2423bba24b):
![working_hoogle](https://user-images.githubusercontent.com/1525767/124593230-bb652100-dea1-11eb-9e4e-e35e0a0975ec.png)

**Comment by wstomv** [comment]
I was quite surprised that when I tried `:hoogle mapMaybe` it did work.

Then I tried `:hoogle concat`, and that worked, but was very slow.

And then `:hoogle map` just hangs. And after restarting the dead kernel, it does work.

And `:hoogle fromMaybe` just hangs.

But `:hoogle a -> (a -> b) -> b` just hangs, always. (On https://hoogle.haskell.org these just all work instantaneously.)

There is one kind of Jupyter message that I see popping up in the cases where it hangs:
```
[I 15:45:41.493 NotebookApp] Replaying 4 buffered messages
ihaskell: src/IHaskell/Eval/Hoogle.hs:196:11-42: Non-exhaustive patterns in [name, args]
```

Seems like there is at least some kind of problem inside IHaskell.

**Comment by vaibhavsagar** [comment]
I just made https://github.com/gibiansky/IHaskell/pull/1233 to address this issue, which I think happened because of changes in the Haddocks that Hoogle pulls from (we haven't updated the relevant code for `:hoogle` in a couple of years). The slowness is because IHaskell is doing a bunch of computationally expensive formatting on `Strings` to get nice HTML output and I don't currently know how to fix that, so I can't help you there.

**Comment by vaibhavsagar** [comment]
I just published https://hackage.haskell.org/package/ihaskell-0.10.2.1 which includes this fix.

**Comment by wstomv** [comment]
A quick question about updating to get this fix. Will it suffice for me to pull the changes to my local `ihaskell` repo, and then run `ihaskell install --stack` again, and restart Jupyter. Or is there more to it?

**Comment by vaibhavsagar** [comment]
Yes, that should work.

**Comment by wstomv** [comment]
I fixed the instrudtions above to update IHaskell in a local repo (I forgot the `stack install --fast`).

And I can confirm that the fix works. Thanks a heap for such a fast response.
