### ISSUE TITLE
Add support for the command :kind! 

### ISSUE THREAD

**Issue by wstomv** [gibiansky/IHaskell#1234]
IHaskell supports some of the (more relevant) commands of GHCI.

I do miss `:kind[!] type`, which is like `:type expressions`, but then on the type level.

Is there any particular reason it is missing?

Would it be easy to add?

**Comment by vaibhavsagar** [comment]
This is already supported! I should update the output of `:help` to reflect this.
![ihaskell_kind](https://user-images.githubusercontent.com/1525767/124797152-4f63e500-df95-11eb-9357-dcf81878e7e0.png)

**Comment by wstomv** [comment]
I see. I tried `:kind! Monad`, and that didn't work.
![Screen Shot 2021-07-07 at 18 54 47](https://user-images.githubusercontent.com/5611123/124799489-e3fa2300-df54-11eb-9045-cb4fbc624c61.png)

**Comment by vaibhavsagar** [comment]
This has been implemented in https://github.com/gibiansky/IHaskell/commit/486fc9f4e39ace2ddf69f00dc7003f482411fff5. I won't be cutting a new release for this addition alone, but you can pull the changes in as before.
