### ISSUE TITLE
Default install instructions for Linux not working

### ISSUE THREAD

**Issue by ReddSpark1** [gibiansky/IHaskell#1236]
I tried to follow the default instructions for Ubuntu but it resulted in it saying iHaskell was not available. Think the stack install is failing before hand. Try the steps on a fresh Ubuntu install.

**Comment by vaibhavsagar** [comment]
We test every commit on a fresh Ubuntu install: https://github.com/gibiansky/IHaskell/actions/workflows/ci.yml. Can you be more specific about the errors you're getting?

**Comment by vaibhavsagar** [comment]
Closing as this isn't enough information to reproduce the issue or investigate further. Please reopen with more context if you want me to look into this again.
