### ISSUE TITLE
Syntax highlighting not working in JupyterLab

### ISSUE THREAD

**Issue by odcameron** [gibiansky/IHaskell#1238]
Syntax highlighting issue. The command described in this install-how-to (Linux) is broken:

`jupyter labextension install jupyterlab-ihaskell`

**Comment by vaibhavsagar** [comment]
Can you be more specific about the error message you are getting?

**Comment by tannerlegvold** [comment]
Syntax highlighting is not working for me. 
```
jupyter labextension install jupyterlab-ihaskell
```
is also not working for me. Though I don't know if they are related. When I call the above command I get
```
Building jupyterlab assets (production, minimized)
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-v2drmmkn.log
```
Heres the contents of the log file: https://pastebin.com/xXczWda2

OS: Ubuntu 20.04.2
`ihaskell --version` gives `0.10.1.2`
`jupyter --version` gives 
```
jupyter core     : 4.6.3
jupyter-notebook : 6.1.5
qtconsole        : 5.0.3
ipython          : 7.22.0
ipykernel        : 5.3.4
jupyter client   : 6.1.3
jupyter lab      : 3.0.16
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.1.3
traitlets        : 5.0.5
```

Let me know if you need any more info

**Comment by dnovick** [comment]
I am seeing the same behavior on Ubuntu 21.04 with

ihaskell --version = 0.10.2.1
jupyter --version 

jupyter core     : 4.6.3
jupyter-notebook : 6.1.5
qtconsole        : 5.1.1
ipython          : 7.26.0
ipykernel        : 6.0.3
jupyter client   : 6.1.3
jupyter lab      : 3.1.4
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.1.3
traitlets        : 5.0.5

**Comment by jamesdbrock** [comment]
I think that this error

```
ERROR in resolving fallback for shared module jupyterlab-ihaskell
Module not found: Error: Can't resolve 'jupyterlab-ihaskell' in 
resolve 'jupyterlab-ihaskell' in '/home/tanner/.anaconda3/share/jupyter/lab/staging/build'
```

means that `jupyterlab-ihaskell` is not in the conda repositories, which is true.

Try cloning the IHaskell repository and installing `jupyterlab-ihaskell` from source:

```bash
cd jupyterlab-ihaskell
npm install
npm run build
jupyter labextension link .
```

Does that work?

We should update those README instructions.

**Comment by dnovick** [comment]
I tried this and received an error (see details in attached build-error.txt during "npm run build". It's complaining now about a Namespace not having an exported member "FontFace". 

I have also attached the relevant log file.

[build-error.txt](https://github.com/gibiansky/IHaskell/files/6992008/build-error.txt)
[2021-08-16T11_29_28_121Z-debug.log](https://github.com/gibiansky/IHaskell/files/6992014/2021-08-16T11_29_28_121Z-debug.log)

**Comment by vaibhavsagar** [comment]
We now have a prebuilt extension available [here](https://github.com/gibiansky/IHaskell/tree/master/jupyterlab-ihaskell/labextension), you should be able to copy the contents of that directory to the `labextensions/jupyterlab-ihaskell` directory in your `jupyter --data-dir` (e.g. for me that's `~/.local/share/jupyter/labextensions/jupyterlab-ihaskell`). Does that work for you?

**Comment by vaibhavsagar** [comment]
Closing since I believe we've fixed this, please reopen if required.
