### ISSUE TITLE
Kernerl doesn't connect

### ISSUE THREAD

**Issue by supergary10** [gibiansky/IHaskell#1241]
Tried to reinstall, but it didn't help with the problem.
Jupyter lists Haskell as a kernel option, but all attempts to start the kernel fail.
Thanks in advance!

[I 00:16:23.801 LabApp] JupyterLab extension loaded from /home/supergary/anaconda3/lib/python3.8/site-packages/jupyterlab
[I 00:16:23.801 LabApp] JupyterLab application directory is /home/supergary/anaconda3/share/jupyter/lab
[I 00:16:23.804 LabApp] Serving notebooks from local directory: /home/supergary/Workplaces
[I 00:16:23.804 LabApp] Jupyter Notebook 6.1.5 is running at:
[I 00:16:23.805 LabApp] http://localhost:8888/?token=8d2d258c8f0f27f72cca584c576100d1ca07200cdb403148
[I 00:16:23.805 LabApp]  or http://127.0.0.1:8888/?token=8d2d258c8f0f27f72cca584c576100d1ca07200cdb403148
[I 00:16:23.805 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 00:16:24.220 LabApp]

    To access the notebook, open this file in a browser:
        file:///home/supergary/.local/share/jupyter/runtime/nbserver-26319-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=8d2d258c8f0f27f72cca584c576100d1ca07200cdb403148
     or http://127.0.0.1:8888/?token=8d2d258c8f0f27f72cca584c576100d1ca07200cdb403148
[I 00:16:26.767 LabApp] 301 GET /lab/workspaces/auto-c/?clone (::1) 6.82ms
[I 00:16:29.428 LabApp] Build is up to date
[I 00:16:29.598 LabApp] Kernel started: 7a0f9622-9ce3-4368-a684-92e9afa7549e, name: haskell
|ihaskell: /home/supergary/.stack/programs/x86_64-linux/ghc-tinfo6-8.0.2/lib/ghc-8.0.2/package.conf.d/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (Not a valid Unicode code point!)
[I 00:16:32.599 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
ihaskell: /home/supergary/.stack/programs/x86_64-linux/ghc-tinfo6-8.0.2/lib/ghc-8.0.2/package.conf.d/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (Not a valid Unicode code point!)
[I 00:16:35.604 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
ihaskell: /home/supergary/.stack/programs/x86_64-linux/ghc-tinfo6-8.0.2/lib/ghc-8.0.2/package.conf.d/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (Not a valid Unicode code point!)
[I 00:16:38.611 LabApp] KernelRestarter: restarting kernel (3/5), new random ports
ihaskell: /home/supergary/.stack/programs/x86_64-linux/ghc-tinfo6-8.0.2/lib/ghc-8.0.2/package.conf.d/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (Not a valid Unicode code point!)
[I 00:16:41.616 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
ihaskell: /home/supergary/.stack/programs/x86_64-linux/ghc-tinfo6-8.0.2/lib/ghc-8.0.2/package.conf.d/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (Not a valid Unicode code point!)
[W 00:16:44.624 LabApp] KernelRestarter: restart failed
[W 00:16:44.625 LabApp] Kernel 7a0f9622-9ce3-4368-a684-92e9afa7549e died, removing from map.

**Comment by vaibhavsagar** [comment]
This looks like https://github.com/gibiansky/IHaskell#the-kernel-keeps-dying-ihaskell--stack

**Comment by supergary10** [comment]
I've tried to create a new haskell notebook. Unfortunately, it didn't work.

**Comment by vaibhavsagar** [comment]
I'm not sure you read the correct section. What are the contents of `~/.stack/global-project/stack.yaml` for you?

**Comment by vaibhavsagar** [comment]
The error you're getting indicates that you are running IHaskell with GHC 8.0, which is a very old release compared to what we currently use (GHC 8.10). Assuming you followed the instructions, you installed an IHaskell that is too new for your `global-project`. You can fix this by either changing your `snapshot` field in your `~/.stack/global-project/stack.yaml` to be the same as the current `IHaskell` ([`lts-17`](https://github.com/gibiansky/IHaskell/blob/6f1b51bb18051271910c10ac4c38de021ed4e201/stack.yaml#L1)), or you could move `stack-8.0.yaml` to `stack.yaml` and try reinstalling again which would give you a GHC 8.0-compatible IHaskell.

**Comment by supergary10** [comment]
I meant that I created a new project which is suppose to use the default setting, but Idk if that is really the case. And I have changed the resolver to the one that is used in stack.yaml located in the IHaskell folder.

That is the content for that file.
packages: []
resolver: lts-16.23

**Comment by supergary10** [comment]
> The error you're getting indicates that you are running IHaskell with GHC 8.0, which is a very old release compared to what we currently use (GHC 8.10). Assuming you followed the instructions, you installed an IHaskell that is too new for your `global-project`. You can fix this by either changing your `snapshot` field in your `~/.stack/global-project/stack.yaml` to be the same as the current `IHaskell` ([`lts-17`](https://github.com/gibiansky/IHaskell/blob/6f1b51bb18051271910c10ac4c38de021ed4e201/stack.yaml#L1)), or you could move `stack-8.0.yaml` to `stack.yaml` and try reinstalling again which would give you a GHC 8.0-compatible IHaskell.

Thanks so much. I think I kind of know the reason why. I will try it now to see if it helps.

**Comment by supergary10** [comment]
Thank you so much, After changing my `~/.stack/global-project/stack.yaml`, it works now. But still, in that file there is nothing in the packages, wil this be an issue? And I think the issue can be closed now. Thanks again.

**Comment by vaibhavsagar** [comment]
No, that shouldn't be an issue.

**Comment by supergary10** [comment]
> No, that shouldn't be an issue.

Thanks so much for you quick help.
