### ISSUE TITLE
ihaskell-diagrams/Test.ipynb

### ISSUE THREAD

**Issue by jamesdbrock** [gibiansky/IHaskell#1245]
This is actually the Test notebook for Charts, not diagrams, and it always has been. Did this notebook ever exist? diagrams should have an example notebook.

https://github.com/gibiansky/IHaskell/blob/master/ihaskell-display/ihaskell-diagrams/Test.ipynb

**Comment by vaibhavsagar** [comment]
Fixed by https://github.com/gibiansky/IHaskell/pull/1249.
