### ISSUE TITLE
diagramData shouldn't write to disk when rendering

### ISSUE THREAD

**Issue by jamesdbrock** [gibiansky/IHaskell#1248]
I bet we could refactor the `diagramData` function so it uses `renderDia` instead of `renderCairo` and then it wouldn't need to write the the output to a temporary file and then read it back in again.

https://github.com/gibiansky/IHaskell/blob/65434e970e19b69c07b37969b3534643e819369a/ihaskell-display/ihaskell-diagrams/IHaskell/Display/Diagrams.hs#L29-L34

Reference: https://hackage.haskell.org/package/diagrams-cairo-1.4.1/docs/Diagrams-Backend-Cairo.html

**Comment by vaibhavsagar** [comment]
Looking at the haddocks is making me dizzy. Happy to review any PRs around this but I'm not planning to tackle this myself anytime soon.

**Comment by jamesdbrock** [comment]
I attempted to stop `diagramData` from writing the tmp file in this branch:

https://github.com/jamesdbrock/IHaskell/tree/diagramData

It turns out to actually be impossible?

The call to `renderCairo` figures out whether to write a PNG or SVG to
file by the extension of the filename.

When we instead call `renderDia` with `RenderOnly`, there is no way to
tell the `renderWith` function to write a PNG or SVG to the ByteString.
We can only write `FormatARGB32` to the ByteString.

This appears to be a limitation of the __cairo__ library.

https://hackage.haskell.org/package/cairo-0.13.5.0/docs/Graphics-Rendering-Cairo.html#v:withImageSurfaceFromPNG

**Comment by jamesdbrock** [comment]
__cairo__ only exports the `surface_write_to_png` FFI function.

https://github.com/gtk2hs/gtk2hs/blob/master/cairo/Graphics/Rendering/Cairo/Internal/Surfaces/PNG.chs

To solve this we would need to add a __cairo__ FFI export for the `surface_write_to_png_stream` function.

https://www.cairographics.org/manual/cairo-PNG-Support.html#cairo-surface-write-to-png-stream

**Comment by jamesdbrock** [comment]
I made an issue, but I don't anyone to pick it up any time soon: https://github.com/gtk2hs/gtk2hs/issues/307

**Comment by vaibhavsagar** [comment]
I'm going to close this even though it hasn't been fixed as it appears to be an upstream issue. Even if it is fixed, we will probably have to maintain the current suboptimal behaviour until we drop support for older GHCs.
