### ISSUE TITLE
Adding packages?

### ISSUE THREAD

**Issue by borgauf** [gibiansky/IHaskell#1250]
I'm specifically trying to add [matplotlib](https://hackage.haskell.org/package/matplotlib) with this in my ~/IHaskell/stack.yaml

```
resolver: lts-17.4
allow-newer: true

flags: {}
packages:
    - .
    - ./ipython-kernel
    - ./ghc-parser
    - ./ihaskell-display/ihaskell-aeson
    - ./ihaskell-display/ihaskell-blaze
    - ./ihaskell-display/ihaskell-charts
    - ./ihaskell-display/ihaskell-diagrams
    - ./ihaskell-display/ihaskell-gnuplot
    - ./ihaskell-display/ihaskell-hatex
    - ./ihaskell-display/ihaskell-juicypixels
    - ./ihaskell-display/ihaskell-magic
    - ./ihaskell-display/ihaskell-plot
    # - ./ihaskell-display/ihaskell-static-canvas
    - ./ihaskell-display/ihaskell-widgets
    # - matplotlib
    - location: https://github.com/abarbu/matplotlib-haskell/archive/refs/heads/master.zip
```
 This is my best guess at how to do it, but it's not working. Any advice?

**Comment by vaibhavsagar** [comment]
Try this: https://github.com/gibiansky/IHaskell/issues/792#issuecomment-349186483

**Comment by borgauf** [comment]
Where and what should I add to ihaskell.cabal, stack.yaml? After a few rounds of guess-and-test, I'm not getting anywhere.

**Comment by vaibhavsagar** [comment]
There are more details in the linked issue, but what I recommend is installing IHaskell globally, creating a new Stack project with your desired libraries, and launching IHaskell from your project directory so it will pick up the packages that you want.

**Comment by borgauf** [comment]
I ran `stack exec -- jupyter notebook` in `~/.stack/global-project/ `and it worked.
