### ISSUE TITLE
Docker image fails with "Bad interface file"

### ISSUE THREAD

**Issue by brandon-leapyear** [gibiansky/IHaskell#1251]
Repro:
* `docker run --rm -p 8888:8888 gibiansky/ihaskell`
* Open `localhost:8888`
* Create a new notebook in the top-level directory
* Type in `putStrLn "Hello world!"`, shift + Enter
* Get error:
```
ihaskell: Bad interface file: /home/jovyan/.stack/programs/x86_64-linux/ghc-8.8.4/lib/ghc-8.8.4/base-4.13.0.0/Prelude.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /home/jovyan/.stack/programs/x86_64-linux/ghc-8.8.4/lib/ghc-8.8.4/directory-1.3.6.0/System/Directory.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /home/jovyan/.stack/programs/x86_64-linux/ghc-8.8.4/lib/ghc-8.8.4/unix-2.7.2.2/System/Posix/IO.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /home/jovyan/.stack/programs/x86_64-linux/ghc-8.8.4/lib/ghc-8.8.4/base-4.13.0.0/System/IO.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
Bad interface file: /home/jovyan/.stack/programs/x86_64-linux/ghc-8.8.4/lib/ghc-8.8.4/template-haskell-2.15.0.0/Language/Haskell/TH.hi
    magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)
```

My system:
* Mac 10.15.7
* Docker version 20.10.7, build f0df350

**Comment by brandon-leapyear** [comment]
It works after manually ssh-ing into the Docker container and editing `~/.stack/global-project/stack.yaml` to use the same resolver as `/home/jovyan/ihaskell/stack.yaml`.

The instructions should probably include something like "make sure to create new notebooks within a directory containing a `stack.yaml` with the same resolver as the `stack.yaml` in `/home/jovyan/ihaskell/`". Right now, the instructions only talk about "check the resolver is the same" when mounting volumes

**Comment by brandon-leapyear** [comment]
My current workaround script: https://github.com/brandon-leapyear/config/blob/main/bin/ihaskell

It would be nice if the Docker image initialized `~/.stack/global-project/stack.yaml` with the same resolver as the one in the repo, to ensure that `ihaskell` is run with the same resolver. It would also be nice to get a better error message if the resolvers are different (or maybe it could be a bit more lax, just checking if GHC versions are different?)

**Comment by vaibhavsagar** [comment]
I'm trying to reproduce this now but I have a couple of suggestions:

1. Are you using the latest docker image? We haven't been on a resolver with GHC 8.8 for a while now.
2. Another workaround would have been to go to the IHaskell directory and create a new notebook from there, which uses IHaskell's own `stack.yaml` instead of the one in `~/.stack/global-project/`

**Comment by brandon-leapyear** [comment]
1. Yes. It seems like the Dockerfile hardcodes the resolver to store in the
global project, and is out of sync with the one in stack.yaml.
2. Yes, thats one solution, but that doesnt help when I want to mount a
volume and make new notebooks there. As a user, I shouldnt have to write a
stack.yaml file in the directory im writing in; ihaskell should Just Work.

**Comment by vaibhavsagar** [comment]
Okay, I'm seeing the same behaviour which means there is something very wrong with our Docker image.

**Comment by vaibhavsagar** [comment]
Ah, this is my fault for forgetting to update https://github.com/gibiansky/IHaskell/blob/6116de70da08ec2975c6afc76a16aeee8e1039eb/Dockerfile#L4, I'll fix this shortly.

**Comment by brandon-leapyear** [comment]
To prevent this from happening again, maybe get the resolver from the
stack.yaml file instead of having two sources of truth?

**Comment by vaibhavsagar** [comment]
I don't know of a good way to do that, do you have any suggestions?

**Comment by vaibhavsagar** [comment]
I fixed this in https://github.com/gibiansky/IHaskell/commit/6e69c210c5127d74870a8d3645fc492a7f064eba, and I confirmed that the newest Docker image no longer has this issue. If you know of a good Docker-compatible way of getting the resolver out of `stack.yaml` I'm open to suggestions (I'm not a Docker expert), but I've looked into this in the past myself and I didn't find anything.

**Comment by brandon-leapyear** [comment]
I'm familiar with Docker. I think I can make the Docker experience better. I'll put up a PR

**Comment by daviddavo** [comment]
There's also the `haskell` base image, that could be used in a new Dockerfile.
