### ISSUE TITLE
Error while installing IHaskell on MacOS Monterey 12.0.1 

### ISSUE THREAD

**Issue by f64u** [gibiansky/IHaskell#1288]
magic               > Configuring magic-1.1...                                         
magic               > Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7: Missing dependency on a foreign
magic               > library:                                                         
magic               > * Missing (or bad) C library: magic                              
magic               > This problem can usually be solved by installing the system package that
magic               > provides this library (you may need the "-dev" version). If the library is
magic               > already installed but in a non-standard location then you can use the flags
magic               > --extra-include-dirs= and --extra-lib-dirs= to specify where it is.If the
magic               > library file does exist, it may contain errors that are caught by the C
magic               > compiler at the preprocessing stage. In this case you can re-run configure
magic               > with the verbosity flag -v3 to see the error messages.     

with `libmagic` already installed using brew.

**Comment by k4rtik** [comment]
I was surprised to find this closed without any other info.

Here's the correct command if others come here looking for a fix on an arm64 Apple machine:
```
stack install --fast --extra-include-dirs=${HOMEBREW_PREFIX}/include --extra-lib-dirs=${HOMEBREW_PREFIX}/lib
```

The instructions at https://github.com/gibiansky/IHaskell/blob/master/README.md#mac are somewhat imprecise.

Ideally, the installation should be fixed to support these directories by default. Homebrew's decision to use `/opt/homebrew` for Apple Silicon is both permanent and the default. I would not call it a "custom location".

**Comment by vaibhavsagar** [comment]
> Ideally, the installation should be fixed to support these directories by default.

As far as I can tell, this is a `stack` issue and not something we are able to fix on our end. I've gone ahead and updated the instructions in https://github.com/gibiansky/IHaskell/commit/618a315bbd8b2def4928a72ef7024b7e5fbcbc39, but if you have suggestions for a more permanent solution I'm happy to take them on board.
