### ISSUE TITLE
Plugins don't work

### ISSUE THREAD

**Issue by abarbu** [gibiansky/IHaskell#1289]
Sadly, plugins don't work. But in a confusing way!

There's a notebook showing the problem here: https://gist.github.com/abarbu/664c35e5140033a45af588434c70d694

And an explanation below.

Start with a notebook that has the `ghc-typelits-knownnat` package available.

```
:set -XFlexibleContexts -XFlexibleInstances
:set -XPolyKinds -XRankNTypes -XScopedTypeVariables -XTypeApplications -XTypeFamilies
:set -XTypeFamilyDependencies -XTypeInType -XTypeOperators -XUndecidableInstances
import Data.Proxy
import GHC.TypeLits
let f :: forall n . (KnownNat n, KnownNat (n+2)) => Proxy n -> Integer; f _ = natVal (Proxy :: Proxy n) + natVal (Proxy :: Proxy (n+2))
```

Will work. Then add:

```
let f :: forall n . KnownNat n => Proxy n -> Integer; f _ = natVal (Proxy :: Proxy n) + natVal (Proxy :: Proxy (n+2))
```

This will fail with 
```
Could not deduce (KnownNat (n + 2)) arising from a use of ‘natVal’
```

Now enable the plugin with

```
:set -fplugin GHC.TypeLits.KnownNat.Solver
```

And again run

```
let f :: forall n . KnownNat n => Proxy n -> Integer; f _ = natVal (Proxy :: Proxy n) + natVal (Proxy :: Proxy (n+2))
```

In GHCi this works because of the plugin. But in iHaskell it doesn't and errors the same way as before the plugin.

The confusing part is that adding a plugin that doesn't exist with

```
:set -fplugin GHC.TypeLits.KnownNat.SolverX
```

produces errors about plugins that don't exist. So at some level plugins are being loaded. But they aren't being used.

**Comment by abarbu** [comment]
Looks like plugins are working after all with :set
In case anyone else finds this, plugin errors don't appear immediately like they do in GHCi.

**Comment by abarbu** [comment]
Sadly, plugins don't work. But in a confusing way!

Start with a notebook that has the `ghc-typelits-knownnat` package available.

```
:set -XFlexibleContexts -XFlexibleInstances
:set -XPolyKinds -XRankNTypes -XScopedTypeVariables -XTypeApplications -XTypeFamilies
:set -XTypeFamilyDependencies -XTypeInType -XTypeOperators -XUndecidableInstances
import Data.Proxy
import GHC.TypeLits
let f :: forall n . (KnownNat n, KnownNat (n+2)) => Proxy n -> Integer; f _ = natVal (Proxy :: Proxy n) + natVal (Proxy :: Proxy (n+2))
```

Will work. Then add:

```
let f :: forall n . KnownNat n => Proxy n -> Integer; f _ = natVal (Proxy :: Proxy n) + natVal (Proxy :: Proxy (n+2))
```

This will fail with 
```
Could not deduce (KnownNat (n + 2)) arising from a use of ‘natVal’
```

Now enable the plugin with

```
:set -fplugin GHC.TypeLits.KnownNat.Solver
```

And again run

```
let f :: forall n . KnownNat n => Proxy n -> Integer; f _ = natVal (Proxy :: Proxy n) + natVal (Proxy :: Proxy (n+2))
```

In GHCi this works because of the plugin. But in iHaskell it doesn't and errors the same way as before the plugin.

The confusing part is that adding a plugin that doesn't exist with

```
:set -fplugin GHC.TypeLits.KnownNat.SolverX
```

produces errors about plugins that don't exist. So at some level plugins are being loaded. But they aren't being used.

**Comment by vaibhavsagar** [comment]
There's [this work-in-progress commit](https://github.com/gibiansky/IHaskell/commit/1c78b092925cfb7eb988b2378de998d584e7e44c) that I think was intended to fix https://github.com/gibiansky/IHaskell/issues/443, but otherwise I don't believe this is currently supported.

**Comment by abarbu** [comment]
That makes sense for `OPTIONS_GHC`, but I wonder what's up with `:set`?

https://github.com/gibiansky/IHaskell/blob/master/src/IHaskell/Eval/Util.hs#L247 calls `setInteractiveDynFlags` which calls `initializePlugins` 

It looks like this should work?

**Comment by vaibhavsagar** [comment]
I think support needs to be implemented [like it is in `ghci`](https://gitlab.haskell.org/ghc/ghc/-/blob/7445bd714c1bea39207f9a2fa497c325b95ba2c7/ghc/GHCi/UI.hs#L2902-2933) for it to work.

**Comment by abarbu** [comment]
It looks correct as is as far as I can tell. Do you have an idea about what is missing?

Both call `setInteractiveDynFlags`. Then the plugins will end up in `DynFlags` at which point `execStmt` should do the right thing.

**Comment by vaibhavsagar** [comment]
The [`ghci` implementation of `newDynFlags` that `:set` uses](https://gitlab.haskell.org/ghc/ghc/-/blob/7445bd714c1bea39207f9a2fa497c325b95ba2c7/ghc/GHCi/UI.hs#L3083-3147) seems a lot more involved than what we do in IHaskell, I suspect that there is some subtlety there that we are missing.

**Comment by abarbu** [comment]
I was looking at newDynFlags, but I was blind. I submitted a PR. Thanks!
