### ISSUE TITLE
update argument parsing to use optparse-applicative

### ISSUE THREAD

**Issue by teto** [gibiansky/IHaskell#1303]
I ran ` ihaskell --debug install`  to test  something but ihaskell doesn't display where the file was installed (I found it via strace). I would expect to see where it is installed in a normal usage, but even more with --debug !

I peeked at the code but argument handling is home-made. All packages with home-made argument parsing end up with inconsistent help or argument parsing. 
For instance ` ihaskell --debug --env-file=bazel-bin/core/compile-package_env-core install`  works while it should trigger a warning that --env-file is not supported for that subcommand.
Would you accept a MR that reimplements argument parsing with optparse-applicative ?

**Comment by teto** [comment]
(also how can I get a better error than 
```
ihaskell: ihaskell: /home/teto/.local/share/jupyter/kernels/haskell/kernel.json: Failed to parse profile file
CallStack (from HasCallStack):
  error, called at main/Main.hs:122:20 in main:Main
```
what's the profile file ? 
 ```
$  cat /home/teto/.local/share/jupyter/kernels/haskell/kernel.json
{"display_name":"Haskell","argv":["/nix/store/nn7qhp8ng8d605pqmawm5nyhhlq9m9v8-ihaskell-0.10.2.1/bin/ihaskell","kernel","{connection_file}","--debug","--ghclib","/nix/store/673ic4dsw35wmqwq59z821l67fjfix8w-ghc-8.10.7/lib/ghc-8.10.7","+RTS","-M3g","-N2","-RTS"],"language":"haskell"
```
)

**Comment by vaibhavsagar** [comment]
It looks like your profile file is missing a closing bracket maybe?

**Comment by teto** [comment]
ha sry it was too late when I had a look yesterday and thought this was some homemade solution. I dont want to rewrite stuff for the sake of it and cmdargs looks like a valid solution, I will have a second look. Would it be possible for cmdargs to warn for unvalid arguments, e.g., as in `ihaskell --debug --env-file=bazel-bin/core/compile-package_env-core install` though ?

**Comment by vaibhavsagar** [comment]
I'm not 100% sure since I haven't really made many changes to the argument parsing after I became a maintainer, I would expect that `cmdargs` does provide this functionality somehow though. Are you completely sure that command is invalid? It looks very similar to what we currently do in the Dockerfile: https://github.com/gibiansky/IHaskell/blob/4e12b44d55dd322da1546408811976636b546660/Dockerfile#L92

**Comment by teto** [comment]
will close for now as it's not something I will work on in the short term
