### ISSUE TITLE
IHaskell Widget example notebooks fail to run 

### ISSUE THREAD

**Issue by chapmanbe** [gibiansky/IHaskell#1311]
I've pulled the latest image from Docker:

```bash
docker pull gibiansky/ihaskell
```

and started a container based on that image.

If I start a new notebook and copy the first line from one of the IPython widget examples (say, ihaskell-display/ihaskell-widgets/Examples/00 Introduction to Widgets.ipynb), it fails to find the module:

```Haskell
{-# LANGUAGE OverloadedStrings #-}
import IHaskell.Display.Widgets
```
```
<interactive>:1:1: error:
    Could not find module ‘IHaskell.Display.Widgets’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
```

Am I missing something here? It seems like I should be able to start up the Docker image and run any of the example notebooks in the github repository.

**Comment by vaibhavsagar** [comment]
Hey, it used to work like that but the resulting image was pretty large and most people didn't end up using `ihaskell-widgets` ( which contributes significantly to the image size) so when it was reworked in https://github.com/gibiansky/IHaskell/pull/1261 I thought I would leave it alone until someone brought it up. I think the broader question is what the purpose of the Docker image is: to be a fully-fledged IHaskell installation with all the bells and whistles, or to be a minimal base for other people to build off. I don't personally use the Docker image but I do have to maintain it and I don't want to keep changing it back and forth. If you want a Docker image that does include `ihaskell-widgets` I can suggest https://github.com/jamesdbrock/ihaskell-notebook.

**Comment by chapmanbe** [comment]
Thanks for the reply. No need to change the image on my account. I had found Brock's Docker image and am happy with his image or just knowing that the new image doesn't have the widgets. It has been a while since I've tried the other methods of running IHaskell, but in the past the Docker image is the only way I could get IHaskell running on my Mac.

**Comment by vaibhavsagar** [comment]
I'm not averse to changing it back, but I'd rather wait and see if there's interest from enough people first. Please create a new issue or reopen this one if you want further help with this.
