### ISSUE TITLE
repl (IHaskell console) is slow

### ISSUE THREAD

**Issue by anderspapitto** [gibiansky/IHaskell#143]
this interaction

```
In [1]: 1
1

In [2]:
```

takes almost a second - evaluating `1` with either ghci or IPython is instantaneous, so it seems that faster should be possible.
##

**Comment by kxxoling** [comment]
In my situation, it takes 1 second to export the result, and takes another 2 seconds to finish the whole process. This runs fast on ghci.

Anyone works on this now?

**Comment by gibiansky** [comment]
No, sadly no one is working on this at the moment. It's on the bucket list of things to address in the near future, but I haven't gotten around to it in a while. (That said, as always, I am more than happy to answer questions or help people dig in and figure this out, and will happily merge code produced as a result)

**Comment by vaibhavsagar** [comment]
Closing as too broad.
