### ISSUE TITLE
Allow inline TemplateHaskell

### ISSUE THREAD

**Issue by gibiansky** [gibiansky/IHaskell#236]
See previous discussion on https://github.com/gibiansky/IHaskell/issues/183.

Implement once GHC 7.8 is being used, as then we can use `pprint`? Or perhaps `zeroth`.

**Comment by cje** [comment]
Has anybody managed to get DecQ splices working under GHC 7.8.3 and IHaskell?   It seems like with that, acowley/Frames would work.

**Comment by gibiansky** [comment]
No, this hasn't been worked on at all. I've talked to @houshuang about some ideas for how to implement it so I think there is a pretty clear path towards the implementation, but no effort has been put into it yet. (If you're interested in taking a stab at it, let me know, and we can discuss implementation strategies. Otherwise, hopefully I'll get to it eventually.)

**Comment by gibiansky** [comment]
It's definitely something I'm very interested in getting working though – without it, you can't really use things like lenses or various special deriving things in IHaskell...
