### ISSUE TITLE
Option to save notebook as .hs file

### ISSUE THREAD

**Issue by d10genes** [gibiansky/IHaskell#253]
It would be nice to eventually have a way to directly save notebook files to `.hs` files. Currently you can go to `File > Download as > .py`, which comments the `In [ ]/Out [ ]` entries with hashes (#). It would be convenient to have a similar way to get `.hs` files, and perhaps have a flag to `IHaskell notebook` to automatically save a `.hs` copy periodically, like python's `--script` flag.

    $ ipython notebook --help
    ...
    --script
    Auto-save a .py script everytime the .ipynb notebook is saved
    ...

**Comment by gibiansky** [comment]
This currently can't be implemented in Jupyter, but once it can be it will happen.
