### ISSUE TITLE
Demo doesn't looks properly in nbviewer

### ISSUE THREAD

**Issue by cblp** [gibiansky/IHaskell#258]
> Unshowable:Graphics.Rendering.Chart.Renderable ()
> No instance for (Show (Graphics.Rendering.Chart.Renderable ())) arising from a use of `print'

--

> Unshowable:Html
> No instance for (Show Html) arising from a use of `print'

--

> ```haskell
import qualified Data.ByteString as B
B.readFile "code/IHaskell/images/ihaskell-notebook.png"
```
```
"\137PNG\r\n\SUB\n\NUL\NUL\NUL\rIHDR\NUL\NUL\SOH\248\NUL\NUL\STXQ...
```

--

> Not in scope: \`diagram'
> Perhaps you meant \`dimgray' (imported from Diagrams.Prelude)

--

http://nbviewer.ipython.org/github/gibiansky/IHaskell/blob/master/demo/IHaskell.ipynb
http://nbviewer.ipython.org/github/gibiansky/IHaskell/blob/v0.4.0.0/demo/IHaskell.ipynb

**Comment by gibiansky** [comment]
This is noted in #410.
