### ISSUE TITLE
Notebook: In popup completion list, down key moves edit cursor in text, not selection in comletion list

### ISSUE THREAD

**Issue by cblp** [gibiansky/IHaskell#269]
Up key moves selection in completion list, it's ok.

Spacebar selects next completion, but it's too unnatural to use space/up to select completion.

In IPython, everything is ok, I can select completion with up/down keys.

IHaskell 0.4.1.0
browsers: Yandex 14.5, Safari 7.0.5, Firefox 25.0.1

**Comment by gibiansky** [comment]
No longer happening in `master`
