### ISSUE TITLE
ihaskell-charts base dependency

### ISSUE THREAD

**Issue by cacplate** [gibiansky/IHaskell#282]
ihaskell-charts could not be installed because it requires base==4.6.*
here is the error message:
cabal: Could not resolve dependencies:
trying: ihaskell-charts-0.1.0.0 (user goal)
next goal: base (dependency of ihaskell-charts-0.1.0.0)
rejecting: base-4.7.0.1/installed-e4b... (conflict: ihaskell-charts =>
base==4.6.*)
rejecting: base-4.7.0.1, 4.7.0.0, 4.6.0.1, 4.6.0.0, 4.5.1.0, 4.5.0.0, 4.4.1.0,
4.4.0.0, 4.3.1.0, 4.3.0.0, 4.2.0.2, 4.2.0.1, 4.2.0.0, 4.1.0.0, 4.0.0.0,
3.0.3.2, 3.0.3.1 (global constraint requires installed instance)
Dependency tree exhaustively searched.

**Comment by gibiansky** [comment]
Things have been updated on Hackage.
