### ISSUE TITLE
IHaskell notebook fails to create a virtualenv with Python 3.4

### ISSUE THREAD

**Issue by srhb** [gibiansky/IHaskell#284]
The problem appears to be fixed by changing installation/virtualenv.sh to grab a newer version.

    VIRTUALENV=virtualenv-1.11.6

This is the error before:

    Creating a virtualenv.
    Failed to import the site module
    Traceback (most recent call last):
      File "/home/sarah/.ihaskell/ipython/lib/python3.4/site.py", line 67, in <module>
        import os
      File "/home/sarah/.ihaskell/ipython/lib/python3.4/os.py", line 614, in <module>
        from _collections_abc import MutableMapping
    ImportError: No module named '_collections_abc'
    Using base prefix '/usr'
    New python executable in /home/sarah/.ihaskell/ipython/bin/python
    ERROR: The executable /home/sarah/.ihaskell/ipython/bin/python is not functioning
    ERROR: It thinks sys.prefix is '/tmp/tmpThreadId425115/virtualenv-1.9.1' (should be '/home/sarah/.ihaskell/ipython')
    ERROR: virtualenv is not compatible with this system or executable
    IHaskell:
    Ran commands:
    mkdir -p /home/sarah/.ihaskell
    mkdir -p /home/sarah/.ihaskell/ipython
    withTmpDir
    rm -f /tmp/tmpThreadId425115
    mkdir /tmp/tmpThreadId425115
    cd /tmp/tmpThreadId425115
    bash /home/sarah/scratch/ihaskell/IHaskell/.cabal-sandbox/share/x86_64-linux-ghc-7.8.3/ihaskell-0.4.2.0/installation/virtualenv.sh /home/sarah/.ihaskell/ipython
    which bash
    rm -rf /tmp/tmpThreadId425115
    
    Exception: error running: bash /home/sarah/scratch/ihaskell/IHaskell/.cabal-sandbox/share/x86_64-linux-ghc-7.8.3/ihaskell-0.4.2.0/installation/virtualenv.sh /home/sarah/.ihaskell/ipython
    exit status: 1003.4 
    stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 1957k  100 1957k    0     0   697k      0  0:00:02  0:00:02 --:--:--  697k
    Failed to import the site module
    Traceback (most recent call last):
      File "/home/sarah/.ihaskell/ipython/lib/python3.4/site.py", line 67, in <module>
        import os
      File "/home/sarah/.ihaskell/ipython/lib/python3.4/os.py", line 614, in <module>
        from _collections_abc import MutableMapping
    ImportError: No module named '_collections_abc'

**Comment by gibiansky** [comment]
We no longer use virtualenv, so this is not an issue. Installation has been simplified in `master`.
