### ISSUE TITLE
Kernel immediately dies when I open a new notebook. Mismatched interface file ways

### ISSUE THREAD

**Issue by DonManley** [gibiansky/IHaskell#287]
[I 21:17:30.336 NotebookApp] KernelRestarter: restarting kernel (2/5)
    WARNING:root:kernel d7b49bb1-8e33-4610-bf5f-f18e6007ccfb restarted
    IHaskell: Bad interface file: /home/jon/.cabal/lib/x86_64-linux-ghc-7.8.3/ihaskell-0.4.2.0/IHaskell/Display.hi
    mismatched interface file ways (wanted "", got "dyn")
    Bad interface file: /home/jon/.cabal/lib/x86_64-linux-ghc-7.8.3/ihaskell-0.4.2.0/IHaskell/IPython/Stdin.hi
    mismatched interface file ways (wanted "", got "dyn")

I installed it using `./build all`

**Comment by gibiansky** [comment]
Dynamic flag has been removed; closing this.
