### ISSUE TITLE
/bin/bash doesn't exist on NixOS Linux

### ISSUE THREAD

**Issue by peti** [gibiansky/IHaskell#291]
Most BSD Unices don't have `/bin/bash` either. On those systems, this packages fails to compiles because that path is hard-coded in the build script. IMHO, it would be a good idea to

 1. use `/usr/bin/env bash` instead or
 2. make sure the script works with plain  bourne shell `/bin/sh`.

**Comment by gibiansky** [comment]
Switching it to use `/bin/sh` in https://github.com/gibiansky/IHaskell/commit/b6ae5f58623c018a6e9975bff63a03745886204c
