### ISSUE TITLE
doesn't seem possible to have IHaskell and chart-cairo at the same time

### ISSUE THREAD

**Issue by silky** [gibiansky/IHaskell#293]
if i install chart-cairo (forcing reinstalls) this breaks `IHaskell.Display` in that it can't be imported

if i install IHaskell using (my modified #292) `build.sh all` then i can no longer import `import Graphics.Rendering.Chart` in a IHaskell notebook

seems related to https://github.com/gibiansky/IHaskell/issues/287 insofaras if i have chart-cairo installed and then install IHaskell, i get the kernal constantly crashing. if i do it the other way round, IHaskell kills the Graphics.Rendering.Chart package, and the import fails.

has anyone else noticed this issue?

**Comment by gibiansky** [comment]
Updated everything on Hackage, everything builds on my box, this bug hasn't been updated in a while. Closing it. Reopen if you have more issues.
