### ISSUE TITLE
How to remove imported module?

### ISSUE THREAD

**Issue by qzchenwl** [gibiansky/IHaskell#298]
For example, I have imported Text.PrettyPrint, but I don't need it afterwards. I want to undo importing to avoid function conflicts.

In GHCi, I can:

    :m+ Text.PrettyPrint
    :m- Text.PrettyPrint

In IHaskell notebook:

    import Text.PrettyPrint
    -- what to do here?

**Comment by gibiansky** [comment]
Note that just like in GHCi, you cannot actually use `:m+` or `:m-`; you must have a space between `:m` and `+` or `-`.
