### ISSUE TITLE
load more than one module?

### ISSUE THREAD

**Issue by bfredl** [gibiansky/IHaskell#300]
`:load` seems not to work with more than one module,
```
:load a.hs
:load b.hs
```
gives on the second load the cryptic message:
```
Failed to load module B: attempting to use module ‘main:A’ (a.hs) which is not loaded
```
(a and b doesn't reference each other at all)
`:load a.hs b.hs` as one can do in `ghci` doesn't work either, it seems to interpret this as the single filename `"a.bs b.hs"`

**Comment by gibiansky** [comment]
This issue should be handled with #449.

**Comment by bfredl** [comment]
Nice, thanks!
