### ISSUE TITLE
Integrate with Stackage

### ISSUE THREAD

**Issue by houshuang** [gibiansky/IHaskell#302]
Would it be possible to submit IHaskell to Stackage? I have been using Stackage lately, and have found it incredibly much easier to install all the packages already supported - never any Cabal Hell, etc. 

Right now, it seems that cabal-install would be a problem, IHaskell requires >1.19.2, and Stackage only has <1.17.

**Comment by houshuang** [comment]
I would really like to push this forwards, since Cabal hell often roars its ugly head whenever I get inspired to get back into Haskell, and is a great motivation killer. I'd love for there to be a more durable solution in the future, some combination of Backpack and Nix or whatever, but for now, Stackage seems to work pretty well (perfectly installed Yesod without problems)... 

Just to get the ball rolling, I thought I'd see if there are any conflicts between the current Stackage nightly and the requirements for IHaskell (I didn't check all the IHaskell-display packages - there should be a script to do this automatically, and maybe there already is)... 

Most of the requirements are already in Stackage in the current version ranges, but there are two packages where the current Stackage nightly version does not match the IHaskell requirements, and two packages that are not part of Stackage nightly so far.

mono-traversable     >=0.6 && < 0.7,
Stackage: 0.8.0.1

ghc-parser not found

shelly ==1.5.*, 
Stackage: 1.6.0

system-argv0 not found

I think it would also be good to make the HSpec tests work before submitting a pull request. I'm not quite sure what the problem is there.

**Comment by gibiansky** [comment]
Does Stackage require that all packages `IHaskell` depends on also be in Stackage?

**Comment by houshuang** [comment]
Snoyman [says no](https://twitter.com/snoyberg/status/568497426497200128), they'll be pulled in automatically. At this point, I would suggest making a pull request and seeing what Jenkins says. https://github.com/fpco/stackage/wiki/Maintainers-Agreement

**Comment by gibiansky** [comment]
This is *finally* done!
