### ISSUE TITLE
Issues installing / running IHaskell on OSX Yosemite

### ISSUE THREAD

**Issue by razzius** [gibiansky/IHaskell#306]
I'm new to Haskell so I apologize if any of this doesn't make sense.

`cabal install ihaskell` failed at first because my system lacked `pkg-config` which was causing `zeromq4-haskell` to fail to install. I was able to `brew install pkg-config` and install IHaskell, but the executable `IHaskell` wasn't on my `$PATH`.

I found a `where_is_my_stuff.txt` in `~/.cabal` which pointed me to `$HOME/Library/Haskell/bin` where I found IHaskell. I added that directory to my `$PATH` and could execute IHaskell.

`IHaskell console`, however, failed to find the `IHaskell` executable midway through starting up. I put a breakpoint in IPython's source and found the problem:

```
> /Library/Python/2.7/site-packages/IPython/kernel/launcher.py(183)launch_kernel()
(Pdb) cmd
[u'/Users/razzi/.cabal/bin/IHaskell', u'kernel', u'/Users/razzi/.ipython/profile_haskell/security/kernel-52516.json']
```

Apparently it was looking for `IHaskell` in `~/.cabal/.bin`! Creating that directory and symlinking the executable again fixed that and I was able to start IHaskell.

Perhaps the IHaskell executable location could avoid being hardcoded, so the IHaskell already on my `$PATH` would be found?

As a side note, is it just a Mac quirk that `~/.cabal/bin` is not where executables live? I was very confused by the `where_is_my_stuff.txt` file (but glad it was there)!

**Comment by gibiansky** [comment]
It currently works on Yosemite. Also, installation procedures will be changing with next version of IPython. So reopen if there are further issues, closing for now.
