### ISSUE TITLE
codemirror runmode

### ISSUE THREAD

**Issue by Carreau** [gibiansky/IHaskell#318]
To highlight in output and get less codemirror element on the page, your might want to use [runmode](http://codemirror.net/demo/runmode.html), we use it in notebook.js ~line 98 in marked options. 

We could expose the function probably that would allow to get unifor highlighting between markdown cell in triple backticks, and output code.

**Comment by gibiansky** [comment]
I'm going to be migrating away from using CodeMirror in outputs, as that does not survive exporting to html or latex :(
