### ISSUE TITLE
intro notebook error ?

### ISSUE THREAD

**Issue by Carreau** [gibiansky/IHaskell#320]
```
First, in `ihaskell-basic`, we have very simple displays for data types from `Prelude`.
```
do you mean  `ihaskell-display` ? 

Not sure as I can't install it as cabal complain I have base-4.7, and not sure how to downgrade to 4.6

**Comment by gibiansky** [comment]
I do indeed mean `ihaskell-basic`. Sadly this was due to outdated packages on Hackage. They have just been updated so should now be fixed. Reopen if more issues.
