### ISSUE TITLE
Kernel need ctrl+C twice to restart.

### ISSUE THREAD

**Issue by Carreau** [gibiansky/IHaskell#322]
This break the UI on 3.0 to restart the kernel.

I need to investigate both  on IHaskell and IPython side on how to separate restart/interrupt cleanly.

**Comment by gibiansky** [comment]
I think this is functioning as expected. Off of `master` right now, if I control C once, I get the "do you want to exit" prompt, where I can type yes or no. If I ctrl c twice it kills the notebook, as expected. If that's not what is supposed to happen, let me know / reopen.
