### ISSUE TITLE
mention ./build.sh display in readme

### ISSUE THREAD

**Issue by Carreau** [gibiansky/IHaskell#323]
Shoudl be pretty simple, but it also feel weird that `./build.sh all`  does not actually build all. 

I would switch build.sh noarg to show help, and "build all"  to build display subpackages also.

So up to you, I can submit PRs depending on your choice.

**Comment by gibiansky** [comment]
Consolidating into https://github.com/gibiansky/IHaskell/issues/410 and https://github.com/gibiansky/IHaskell/issues/412
