### ISSUE TITLE
Mention How To Share Directories With Docker In README?

### ISSUE THREAD

**Issue by xcthulhu** [gibiansky/IHaskell#324]
When I use IHaskell in a docker container, I typically share my current working directory as follows:

```bash
docker run -p 8778:8778 -v $(pwd):/home/haskell/.ihaskell/notebooks gregweber/ihaskell
```

Now, I have my notes about this, but if others think so, maybe it's worth mentioning this trick in the README?

**Comment by gibiansky** [comment]
I think that's probably a good idea. However, I actually very rarely use the docker installation and didn't write it, so don't really know what needs to be added to the README. I'm happy to accept PRs for that though, or integrate any chunks you suggest.
