### ISSUE TITLE
kronos: cant install sqlite-simple via gui

### ISSUE THREAD

**Issue by cartazio** [gibiansky/IHaskell#329]
Resolving dependencies...
Downloading blaze-textual-0.2.0.9...
Downloading direct-sqlite-2.3.14...
Configuring blaze-textual-0.2.0.9...
Failed to install blaze-textual-0.2.0.9
Build log ( /Applications/Kronos-Haskell.app/Contents/Resources/ghc-7.8.3/Contents/cabal/dot-cabal/logs/blaze-textual-0.2.0.9.log ):
Configuring direct-sqlite-2.3.14...
Failed to install direct-sqlite-2.3.14
Build log ( /Applications/Kronos-Haskell.app/Contents/Resources/ghc-7.8.3/Contents/cabal/dot-cabal/logs/direct-sqlite-2.3.14.log ):
cabal: Error: some packages failed to install:
blaze-textual-0.2.0.9 failed during the configure step. The exception was:
user error
('/Applications/Kronos-Haskell.app/Contents/Resources/ghc-7.8.3/Contents/cabal/../bin/ghc'
exited with an error:
<command line>: cannot satisfy -package-id
Cabal-1.22.0.0-ca8c3db7c6c7170aca45126b5b04810b:
Cabal-1.22.0.0-ca8c3db7c6c7170aca45126b5b04810b is unusable due to missing or
recursive dependencies:
base-4.7.0.1-a286b0e00ce442b41516eb1139baa2fb
directory-1.2.1.0-3ba5f45f22d8b88e28f9a9e30c97cde8
unix-2.7.0.1-bba06d6b881c852914a8f208836a1951
(use -v for more information)
)
direct-sqlite-2.3.14 failed during the configure step. The exception was:
user error
('/Applications/Kronos-Haskell.app/Contents/Resources/ghc-7.8.3/Contents/cabal/../bin/ghc'
exited with an error:
<command line>: cannot satisfy -package-id
Cabal-1.22.0.0-ca8c3db7c6c7170aca45126b5b04810b:
Cabal-1.22.0.0-ca8c3db7c6c7170aca45126b5b04810b is unusable due to missing or
recursive dependencies:
base-4.7.0.1-a286b0e00ce442b41516eb1139baa2fb
directory-1.2.1.0-3ba5f45f22d8b88e28f9a9e30c97cde8
unix-2.7.0.1-bba06d6b881c852914a8f208836a1951
(use -v for more information)
)
sqlite-simple-0.4.8.0 depends on direct-sqlite-2.3.14 which failed to install.

Done.

**Comment by gibiansky** [comment]
Interesting. Thanks for the report.  It seems to be an issue with the isolation, somehow, since it works on my setup.

What version of cabal do you have natively? Is it 1.22? Seems strange what's going on.

**Comment by cartazio** [comment]
yeah, a slightly pre RC 1.22

**Comment by gibiansky** [comment]
Try the following from a shell which has stuff set up as if you were running an application:

```
export DYLD_LIBRARY_PATH=/Applications/Kronos-Haskell.app/Contents/Resources/ghc-7.8.3/dylibs; export N=/Applications/Kronos-Haskell.app/Contents/Resources/ghc-7.8.3/Contents; export PATH=$N/bin:$PATH; $N/bin/cabal --config-file=$N/cabal/config install sqlite-simple -j --enable-relocatable -v3
```

this is effectively the command being run by the application, so if you could run that and dump the log here to investigate that'd be super helpful.

**Comment by gibiansky** [comment]
Kronos is unmaintained/deprecated now.
