### ISSUE TITLE
Kernel crash on soem completions

### ISSUE THREAD

**Issue by Carreau** [gibiansky/IHaskell#331]
Got a kernel crash with `\.<tab>`

```
[I 14:55:55.516 NotebookApp] Saving file at /Untitled.ipynb
IHaskell: src/IHaskell/IPython/Message/Parser.hs:(125,3)-(129,59): Irrefutable pattern failed for pattern Data.Aeson.Types.Internal.Success parsed
```

You can easily reproduce programatically with `IPython.notebook.kernel.complete('\.',2, function(data){console.log(data)})`

I also saw it on a few other occasion, but did not found the sequence triggering it.

**Comment by gibiansky** [comment]
Addressed in #441
