### ISSUE TITLE
Kronos: issues with Yosemite and :hoogle

### ISSUE THREAD

**Issue by ArthurClune** [gibiansky/IHaskell#333]
In Kronos, running 

:hoogle :: a -> a

on 10.10.1 produces
```
No response available: security: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

This may be the same problem as mentioned in http://www.chrisjr.org/posts/2014/12/22/nix-osx-haskell/ 

*One tricky OS X-specific problem I encountered was a failure in the http-client-tls library (required by many apps that use secure HTTP connections). Its single test was constantly failing, with an error message of security: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory).*

*Turns out there’s a security executable that is used to manage certificates in OS X, to which the hermetically sealed Nix package builder does not allow access.*

**Comment by gibiansky** [comment]
Interesting. Somehow, I cannot reproduce this. It seems to work fine for me, also on 10.10.1. 

Do you have any idea how I might reproduce this, so I can figure out how to fix it? 

(One idea – could you try this with different settings for "Allow apps downloaded from" in "Settings -> Security/Privacy -> General"? Maaaybe that has an effect, although it doesn't seem to for me... I just have no other clues about how I might figure out this bug.)

**Comment by ArthurClune** [comment]
The Settings -> Security -> General has no affect, but it is a permissions problem. If I run

    sudo open /Applications/Kronos.app

hoogle works. This Mac has been updated through many versions, and the config moved across hardware via restores from TimeMachine so it's probably some old settings somewhere

**Comment by ArthurClune** [comment]
I don't understand why this happens as I don't understand enough about Mac packages, but adding this symlink fixes it for me:

    cd /Applications/Kronos-Haskell.app/Contents/Resources/ghc-7.8.3/Contents/bin
    ln -s /usr/bin/security .

**Comment by ArthurClune** [comment]
In Kronos.app
```
import System.Environment
p <- getEnv "PATH"
print p
   
 
"/Applications/Kronos-Haskell.app/Contents/Resources/ghc-7.8.3/Contents/bin:/Applications/Kronos-Haskell.app/Contents/Resources/ghc-7.8.3/Contents/bin:/Applications/Kronos-Haskell.app/Contents/Resources/ghc-7.8.3/Contents/cabal/dot-cabal/bin::/Applications/Kronos-Haskell.app/Contents/Resources/py/bin"
```

System.Certificate.X509 calls `security` without an absolute path (https://hackage.haskell.org/package/certificate-1.2.7/docs/src/System-Certificate-X509-MacOS.html) and this is called from `Hoogle.hs` L62 in Kronos via tlsManagerSettings -> Network.Connection. initConnectionContext -> System.X509.getSystemCertificates

**Comment by gibiansky** [comment]
That was some solid sluething there... thanks for the help. I know what is wrong and will release an updated version soon, after which I'll update this issue. (It is the same issue as #334 actually)

**Comment by gibiansky** [comment]
@ArthurClune Do you mind trying [the updated app](https://s3-us-west-1.amazonaws.com/europanotebook/Kronos-Haskell-dev.zip)? This *should* I think be fixed in it.

**Comment by ArthurClune** [comment]
That fixes it for me. Thanks
