### ISSUE TITLE
HTML export not working

### ISSUE THREAD

**Issue by pjward** [gibiansky/IHaskell#334]
I have a vanilla install of Kronos Haskell Notebook (the Mac App) under Yosemite on a MacBook Pro. It is lovely but the HTML export is empty. Is there something I should do to enable this feature?

**Comment by gibiansky** [comment]
No, it should "Just Work", so it's probably a bug. I have to run right now but in the next day or two I'll give you a test command to run which may spit out errors that will be helpful for us to determine what is going wrong :)

**Comment by gibiansky** [comment]
@pjward 

As a first step, could you try running this application from the command-line and seeing if that yields any useful output? Specifically, you can run it like this from a command-line:

```bash
cd /Applications/Kronos-Haskell.app
./Contents/MacOS/Kronos\ Notebook
```
Then go ahead and try to export something and see what happens. I get an output somewhat like this:

```
Compiled as IHaskell.
2015-01-10 15:59:27.273 Kronos Notebook[79871:2648063] CFURLResourceIsReachable failed because it was passed this URL which has no scheme: /var/folders/0l/vg6g5pdd32l6ggh_xdngnkwh0000gn/T/Untitled.ipynb
2015-01-10 15:59:27.502 Kronos Notebook[79871:2648063] Sparkle: ===== Kronos-Haskell =====
Augmented path: ...
Attempting to find an open port.
Completed port finding.
Found port Optional(9511)
Running IPython notebook.
Optional(2015-01-10 15:59:29.824 [NotebookApp] Using existing profile dir: u'/Applications/Kronos-Haskell.app/Contents/Resources/py/ipython/profiles/profile_haskell'
2015-01-10 15:59:29.837 [NotebookApp] Serving local MathJax from /Applications/Kronos-Haskell.app/Contents/Resources/py/ipython/profiles/nbextensions/mathjax/MathJax.js at /nbextensions/mathjax/MathJax.js
2015-01-10 15:59:29.861 [NotebookApp] Serving notebooks from local directory: /var/folders/0l/vg6g5pdd32l6ggh_xdngnkwh0000gn/T
2015-01-10 15:59:29.862 [NotebookApp] 0 active kernels
2015-)
IPython notebook launched.
[NbConvertApp] Using existing profile dir: u'/Applications/Kronos-Haskell.app/Contents/Resources/py/ipython/profiles/profile_default'
[NbConvertApp] Converting notebook /var/folders/0l/vg6g5pdd32l6ggh_xdngnkwh0000gn/T/Untitled.ipynb to html
[NbConvertApp] Support files will be in Untitled_files/
[NbConvertApp] Loaded template full.tpl
/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-packages/IPython/nbconvert/filters/markdown.py:78: UserWarning: Node.js 0.9.12 or later wasn't found.
Nbconvert will try to use Pandoc instead.
  "Nbconvert will try to use Pandoc instead.")
```

This is if I open and them immediately export as HTML. What output does that give you?

**Comment by pjward** [comment]
Missing pandoc, I guess:

[NbConvertApp] Using existing profile dir:
u'/Applications/Kronos-Haskell.app/Contents/Resources/py/ipython/profiles/pr
ofile_default'

[NbConvertApp] Converting notebook
/var/folders/j0/k6pt6kx17dj8xk24k9868cch0000gp/T/Untitled.ipynb to html

[NbConvertApp] Support files will be in Untitled_files/

[NbConvertApp] Loaded template full.tpl

/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-pa
ckages/IPython/nbconvert/filters/markdown.py:78: UserWarning: Node.js 0.9.12
or later wasn't found.

Nbconvert will try to use Pandoc instead.

  "Nbconvert will try to use Pandoc instead.")

[NbConvertApp] ERROR | Error while converting
'/var/folders/j0/k6pt6kx17dj8xk24k9868cch0000gp/T/Untitled.ipynb'

Traceback (most recent call last):

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/nbconvertapp.py", line 301, in convert_notebooks

    output, resources = exporter.from_filename(notebook_filename,
resources=resources)

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/exporter.py", line 151, in from_filename

    return self.from_notebook_node(nbformat.read(f, 'json'),
resources=resources, **kw)

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/templateexporter.py", line 215, in
from_notebook_node

    output = self.template.render(nb=nb_copy, resources=resources)

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/jinja2/environment.py", line 969, in render

    return self.environment.handle_exception(exc_info, True)

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/jinja2/environment.py", line 742, in handle_exception

    reraise(exc_type, exc_value, tb)

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/../templates/html/full.tpl", line 2, in
top-level template code

    {% from 'mathjax.tpl' import mathjax %}

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/../templates/html/basic.tpl", line 1, in
top-level template code

    {%- extends 'display_priority.tpl' -%}

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/../templates/skeleton/display_priority.t
pl", line 1, in top-level template code

    {%- extends 'null.tpl' -%}

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/../templates/skeleton/null.tpl", line
26, in top-level template code

    {%- block body -%}

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/../templates/html/full.tpl", line 63, in
block "body"

    {{ super() }}

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/../templates/skeleton/null.tpl", line
29, in block "body"

    {%- block any_cell scoped -%}

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/../templates/skeleton/null.tpl", line
73, in block "any_cell"

    {%- block markdowncell scoped-%}

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/../templates/html/basic.tpl", line 68,
in block "markdowncell"

    {{ cell.source  | markdown2html | strip_files_prefix }}

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/filters/markdown.py", line 83, in markdown2html

    return markdown2html_pandoc(source)

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/filters/markdown.py", line 87, in
markdown2html_pandoc

    return pandoc(source, 'markdown', 'html', extra_args=['--mathjax'])

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/utils/pandoc.py", line 63, in pandoc

    check_pandoc_version()

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/utils/pandoc.py", line 104, in
check_pandoc_version

    v = get_pandoc_version()

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/utils/pandoc.py", line 88, in get_pandoc_version

    raise PandocMissing()

PandocMissing: Pandoc wasn't found.

Please check that pandoc is installed:

http://johnmacfarlane.net/pandoc/installing.html

**Comment by gibiansky** [comment]
Could you include the entire output (starting with 'Compiled as ...'), not just that last bit? That may help – it may be a path issue. 

Also, that's very strange – check whether you have pandoc here:
```
ls -l /Applications/Kronos-Haskell.app/Contents/Resources/py/bin/pandoc
du -h /Applications/Kronos-Haskell.app/Contents/Resources/py/bin/pandoc
```

Pandoc *should* be included there...

**Comment by pjward** [comment]
Yes, sorry. I have added the pandoc check at the end.

Last login: Sun Jan 11 08:29:13 on ttys001

pete:~ peter$ cd /Applications/Kronos-Haskell.app

pete:Kronos-Haskell.app peter$ ./Contents/MacOS/Kronos\ Notebook

Compiled as IHaskell.

2015-01-12 10:21:35.746 Kronos Notebook[16582:916605]
CFURLResourceIsReachable failed because it was passed this URL which has no
scheme: /var/folders/j0/k6pt6kx17dj8xk24k9868cch0000gp/T/Untitled.ipynb

/bin/bash: brew: command not found

Traceback (most recent call last):

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/bin/compute_path.py"
, line 23, in <module>

    brew_prefix = subprocess.check_output([shell, "-c", prefix_cmd]).strip()

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/subpro
cess.py", line 573, in check_output

    raise CalledProcessError(retcode, cmd, output=output)

subprocess.CalledProcessError: Command '['/bin/bash', '-c', 'brew
--prefix']' returned non-zero exit status 127

Augmented path: 
/Applications/Kronos-Haskell.app/Contents/Resources/ghc-7.8.3/Contents/bin:/
Applications/Kronos-Haskell.app/Contents/Resources/ghc-7.8.3/Contents/cabal/
dot-cabal/bin::/Applications/Kronos-Haskell.app/Contents/Resources/py/bin

2015-01-12 10:21:35.994 Kronos Notebook[16582:916605] Sparkle: =====
Kronos-Haskell =====

Attempting to find an open port.

Failed port 9511

Completed port finding.

Found port Optional(9512)

Running IPython notebook.

Optional(sh: grep: command not found

sh: sysctl: command not found

sh: sw_vers: command not found

sh: grep: command not found

2015-01-12 10:21:37.457 [NotebookApp] Using existing profile dir:
u'/Applications/Kronos-Haskell.app/Contents/Resources/py/ipython/profiles/pr
ofile_haskell'

2015-01-12 10:21:37.473 [NotebookApp] Serving local MathJax from
/Applications/Kronos-Haskell.app/Contents/Resources/py/ipython/profiles/nbex
tensions/mathjax/MathJax.js at /nbextensions/mathjax/MathJax.js

2015-01-12 10:21:37.501 [NotebookApp] Serving notebooks from local dire)

IPython notebook launched.

[NbConvertApp] Using existing profile dir:
u'/Applications/Kronos-Haskell.app/Contents/Resources/py/ipython/profiles/pr
ofile_default'

[NbConvertApp] Converting notebook
/var/folders/j0/k6pt6kx17dj8xk24k9868cch0000gp/T/Untitled.ipynb to html

[NbConvertApp] Support files will be in Untitled_files/

[NbConvertApp] Loaded template full.tpl

/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-pa
ckages/IPython/nbconvert/filters/markdown.py:78: UserWarning: Node.js 0.9.12
or later wasn't found.

Nbconvert will try to use Pandoc instead.

  "Nbconvert will try to use Pandoc instead.")

[NbConvertApp] ERROR | Error while converting
'/var/folders/j0/k6pt6kx17dj8xk24k9868cch0000gp/T/Untitled.ipynb'

Traceback (most recent call last):

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/nbconvertapp.py", line 301, in convert_notebooks

    output, resources = exporter.from_filename(notebook_filename,
resources=resources)

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/exporter.py", line 151, in from_filename

    return self.from_notebook_node(nbformat.read(f, 'json'),
resources=resources, **kw)

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/templateexporter.py", line 215, in
from_notebook_node

    output = self.template.render(nb=nb_copy, resources=resources)

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/jinja2/environment.py", line 969, in render

    return self.environment.handle_exception(exc_info, True)

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/jinja2/environment.py", line 742, in handle_exception

    reraise(exc_type, exc_value, tb)

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/../templates/html/full.tpl", line 2, in
top-level template code

    {% from 'mathjax.tpl' import mathjax %}

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/../templates/html/basic.tpl", line 1, in
top-level template code

    {%- extends 'display_priority.tpl' -%}

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/../templates/skeleton/display_priority.t
pl", line 1, in top-level template code

    {%- extends 'null.tpl' -%}

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/../templates/skeleton/null.tpl", line
26, in top-level template code

    {%- block body -%}

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/../templates/html/full.tpl", line 63, in
block "body"

    {{ super() }}

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/../templates/skeleton/null.tpl", line
29, in block "body"

    {%- block any_cell scoped -%}

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/../templates/skeleton/null.tpl", line
73, in block "any_cell"

    {%- block markdowncell scoped-%}

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/exporters/../templates/html/basic.tpl", line 68,
in block "markdowncell"

    {{ cell.source  | markdown2html | strip_files_prefix }}

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/filters/markdown.py", line 83, in markdown2html

    return markdown2html_pandoc(source)

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/filters/markdown.py", line 87, in
markdown2html_pandoc

    return pandoc(source, 'markdown', 'html', extra_args=['--mathjax'])

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/utils/pandoc.py", line 63, in pandoc

    check_pandoc_version()

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/utils/pandoc.py", line 104, in
check_pandoc_version

    v = get_pandoc_version()

  File 
"/Applications/Kronos-Haskell.app/Contents/Resources/py/lib/python2.7/site-p
ackages/IPython/nbconvert/utils/pandoc.py", line 88, in get_pandoc_version

    raise PandocMissing()

PandocMissing: Pandoc wasn't found.

Please check that pandoc is installed:

http://johnmacfarlane.net/pandoc/installing.html



pete:Kronos-Haskell.app peter$

pete:Kronos-Haskell.app peter$ ls -l
/Applications/Kronos-Haskell.app/Contents/Resources/py/bin/pandoc

-rwxr-xr-x@ 1 peter  staff  85878288  3 Jan 01:10
/Applications/Kronos-Haskell.app/Contents/Resources/py/bin/pandoc

pete:Kronos-Haskell.app peter$ du -h
/Applications/Kronos-Haskell.app/Contents/Resources/py/bin/pandoc

 82M /Applications/Kronos-Haskell.app/Contents/Resources/py/bin/pandoc

pete:Kronos-Haskell.app peter$



From:  Andrew Gibiansky <notifications@github.com>
Reply-To:  gibiansky/IHaskell
<reply+001733a326983d6076241e1c9b5e272e1e7c9349efba4da692cf0000000110ca5aee9
2a169ce03325a0b@reply.github.com>
Date:  Sunday, 11 January 2015 15:38
To:  gibiansky/IHaskell <IHaskell@noreply.github.com>
Cc:  Peter Ward <peter-ward@bcs.org.uk>
Subject:  Re: [IHaskell] HTML export not working (#334)

du -h /Applications/Kronos-Haskell.app/Contents/Resources/py/bin/pandoc

**Comment by gibiansky** [comment]
Great! Thank you for that. I understand what's going on now and know how to fix it. I'll post an updated version soon and then let you know.

**Comment by gibiansky** [comment]
@pjward  Do you mind trying [the updated app](https://s3-us-west-1.amazonaws.com/europanotebook/Kronos-Haskell-dev.zip)?

**Comment by pjward** [comment]
Cool! Yes, it's great. The diagrams come out in the HTML too ­ it "just
works".
Splendid turn-around. Many thanks.

Peter

From:  Andrew Gibiansky <notifications@github.com>
Reply-To:  gibiansky/IHaskell
<reply+001733a3499a09fd3bcf22df283fd10752167b6afbb239cd92cf0000000110cbc7069
2a169ce03325a0b@reply.github.com>
Date:  Monday, 12 January 2015 17:31
To:  gibiansky/IHaskell <IHaskell@noreply.github.com>
Cc:  Peter Ward <peter-ward@bcs.org.uk>
Subject:  Re: [IHaskell] HTML export not working (#334)


@pjward <https://github.com/pjward>   Do you mind trying the updated app
<https://s3-us-west-1.amazonaws.com/europanotebook/Kronos-Haskell-dev.zip> ?

‹
Reply to this email directly or view it on GitHub
<https://github.com/gibiansky/IHaskell/issues/334#issuecomment-69609295> .
