### ISSUE TITLE
nix-env -i ihaskell on NixOs does not produce a working installation

### ISSUE THREAD

**Issue by rrottier** [gibiansky/IHaskell#336]
I am trying to set up ihaskell on EC2.  I start with the NixOs EC2 instance (from http://nixos.org/nixos/download.html) and then basically install the ihaskell package using nix-env -i ihaskell.  The installation runs fine but when I try to start the notebook with ihaskell notebook i get the following:

    Updating IPython profile.
    Loading profile from /nix/store/hlkvkavkgm3hj08ffdlziq30r7zyr060-haskell-ihaskell-ghc7.8.3-0.4.3.0-   shared/share/x86_64-linux-ghc-7.8.3/ihaskell-0.4.3.0/profile/profile.tar
    IHaskell:
    Ran commands:
    mkdir -p /root/.ihaskell
    mkdir -p /root/.ihaskell/notebooks
    mkdir -p /root/.ihaskell
    /nix/store/hnmgn0jrpzlp5d91m5xawpr2iqsjxh7j-ipython-2.3.1/bin/ipython locate profile haskell
    which /nix/store/hnmgn0jrpzlp5d91m5xawpr2iqsjxh7j-ipython-2.3.1/bin/ipython
    /nix/store/hnmgn0jrpzlp5d91m5xawpr2iqsjxh7j-ipython-2.3.1/bin/ipython locate profile haskell
  which /nix/store/hnmgn0jrpzlp5d91m5xawpr2iqsjxh7j-ipython-2.3.1/bin/python

    Exception: /root/.ipython/profile_haskell/ipython_config.py: openFile: does not exist (No such file or   directory)

Manually creating a config file with:

    c = get_config()
    c.KernelManager.kernel_cmd = [exe, 'kernel', '{connection_file}']
    c.Session.key = b''
    c.Session.keyfile = b''

    # Syntax highlight properly in Haskell notebooks.
    c.NbConvertBase.default_language = "haskell"

    # Where to look for templates.
    template_path = "/".join(__file__.split("/")[:-1] + ["templates"])
    c.TemplateExporter.template_path = [template_path]

Allow me to run haskell console which add the line:

    exe = '/nix/store/hlkvkavkgm3hj08ffdlziq30r7zyr060-haskell-ihaskell-ghc7.8.3-0.4.3.0-shared/bin/IHaskell'.replace(' ', '\\ ')

to the config file (every time I run it).  

But the kernel dies with the error:

    IPython profile: haskell
    IHaskell: Failed to load interface for ‘IHaskell.Display’
    Use -v to see a list of the files searched for.
    Failed to load interface for ‘IHaskell.Display’
    Use -v to see a list of the files searched for.
    Failed to load interface for ‘IHaskell.IPython.Stdin’
    Use -v to see a list of the files searched for.

**Comment by aavogt** [comment]
Does `ghc-pkg list ihaskell` list it? My experience is that you need to be using `https://nixos.org/wiki/Haskell#Customized_GHC_environment`, which would be the case if `ghc-pkg list` puts everything in one package.conf.d database like:

```
/nix/store/5pv6wpd4ygicpkjxd1qvl3zajc4fdl3i-haskell-env-ghc-7.8.3/lib/ghc-7.8.3/package.conf.d
   Adaptive-0.23
   Boolean-0.2.1
   BoundedChan-1.0.3.0
   CTRex-0.5
   Cabal-1.18.1.3
   Chart-1.2.4
   Chart-cairo-1.2.4
...
   ihaskell-0.4.2.0
   ihaskell-aeson-0.1.0.0
   ihaskell-basic-0.1.0.0
   ihaskell-blaze-0.1.0.0
   ihaskell-charts-0.1.0.0
   ihaskell-diagrams-0.1.0.0
   ihaskell-hatex-0.1.0.0
   ihaskell-juicypixels-0.1.0.0
   ihaskell-magic-0.1.0.0
   ihaskell-parsec-0.1.0.0
   ihaskell-rlangqq-0.1.0.0
   ihaskell-widgets-0.1.0.0
...
```

**Comment by rrottier** [comment]
ghc-pkg list ihaskell returns empty, just:
    /nix/store/4yn5j14b3650lsdka16x30z1inmbpnyl-ghc-7.8.3/lib/ghc-7.8.3/package.conf.d

So I tried to install it using the instructions you referenced, since this AWS machine is supposed to only serve ihaskell I decided to make it system wide adding:

    # other configuration options
  environment.systemPackages = [
      # other system packages
      (pkgs.haskellPackages.ghcWithPackages (self : [
        self.ihaskell
        # add more Haskell packages here
      ]))
    ];

to my /etc/nixos/configuration.nix

Running that with `nixos-rebuild switch` results in an error:

    building Nix...
    building the system configuration...
    these derivations will be built:
    /nix/store/xzhbr48h6dsiflq5bsbpfw3imb9lmshq-haskell-env-ghc-7.8.3.drv
    /nix/store/0hi2xydixmnf32zvgraqfmhkm2rf3csm-system-path.drv
    /nix/store/dk7w909lw9ddrzpv6ks0hk0vp0csbrx5-system-crontab.drv
    /nix/store/hrmgz7787i9lzhbq3c3hwp12rfcv8j06-unit-script.drv
    /nix/store/5l65y7ckqs710b2axdrfxhryzi8ssfq4-unit-cron.service.drv
    /nix/store/r37fkdaxwvcq9m4liw1vlyqc8f76jzav-unit-polkit.service.drv
    /nix/store/2cdfzwsskm5bx9xzrcpkbn70wj6bz33p-system-units.drv
    /nix/store/xf89zd4ikzrkmq8wykp9w69xb5xz6dam-dbus-conf.drv
    /nix/store/rfvaggfrpzd1asprjqvw6m9y2f27phd2-etc.drv
    /nix/store/a86pfrcxzghwlrsb8azdhg4z05vvx7sf-nixos-14.12.298.0667587.drv
    building path(s) ‘/nix/store/jyllhizs428c6s6zv7zw30lgn990q7fl-haskell-env-ghc-7.8.3’
    building /nix/store/jyllhizs428c6s6zv7zw30lgn990q7fl-haskell-env-ghc-7.8.3
    collision between `/nix/store/4yn5j14b3650lsdka16x30z1inmbpnyl-ghc-7.8.3/lib/ghc-7.8.3/terminfo-0.4.0.0/System/Console/Terminfo.dyn_hi' and `/nix/store/w1p44mp0fk1zb0szd86xqh3i8zgl379z-haskell-terminfo-ghc7.8.3-0.4.0.0-shared/lib/ghc-7.8.3/terminfo-0.4.0.0/System/Console/Terminfo.dyn_hi' at /nix/store/9z6d76pz8rr7gci2n3igh5dqi7ac5xqj-builder.pl line 72.
    builder for ‘/nix/store/xzhbr48h6dsiflq5bsbpfw3imb9lmshq-haskell-env-ghc-7.8.3.drv’ failed with exit code 25
    cannot build derivation ‘/nix/store/0hi2xydixmnf32zvgraqfmhkm2rf3csm-system-path.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/nix/store/a86pfrcxzghwlrsb8azdhg4z05vvx7sf-nixos-14.12.298.0667587.drv’: 1 dependencies couldn't be built
    error: build of ‘/nix/store/a86pfrcxzghwlrsb8azdhg4z05vvx7sf-nixos-14.12.298.0667587.drv’ failed  

Am I doing the environment wrong?  Or is this some other error?

**Comment by gibiansky** [comment]
@rrottier @aavogt I'm afraid I've never used nix or NixOS, so can't be of much help here, but just wanted to say that if you track this down to an issue that can be reproduced without nix or find an issue that should be patched in IHaskell itself, I'm happy to help / merge PRs. Sorry to be somewhat useless otherwise, as I'm not sure how I would debug this without familiarizing myself with nix and the like...

**Comment by rrottier** [comment]
I finally managed to get the environment working by using:

    (pkgs.haskellPackages.ghcWithPackagesOld (self : [
            self.ihaskell
          ]))

`ghc-pkg list ihaskell`

now returns

    /nix/store/g66rcfxcr22psb4xz8wdphhpbl2d8b2d-haskell-env-ghc-7.8.4/lib/ghc-7.8.4/package.conf.d
       ihaskell-0.4.3.0

But still the same problem:
    # IHaskell console
    Updating IPython profile.
    Loading profile from /nix/store/zw2a8a60pigxlcspx9f0g4cwdx83i1gk-haskell-ihaskell-ghc7.8.4-0.4.3.0-  shared/share/x86_64-linux-ghc-7.8.4/ihaskell-0.4.3.0/profile/profile.tar
    WARNING: IPython History requires SQLite, your history will not be saved
    WARNING: Readline services not available or not loaded.
    WARNING: The auto-indent feature requires the readline library
    Python 2.7.9 (default, Jan 01 1970, 00:00:01)
    Type "copyright", "credits" or "license" for more information.

    IPython 2.3.1 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.

    IPython profile: haskell
    IHaskell: Failed to load interface for ‘IHaskell.Display’
    Use -v to see a list of the files searched for.
    Failed to load interface for ‘IHaskell.Display’
    Use -v to see a list of the files searched for.
    Failed to load interface for ‘IHaskell.IPython.Stdin’
    Use -v to see a list of the files searched for.

    ERROR: Kernel did not respond

My config file is:

    exe = '/run/current-system/sw/bin/IHaskell'.replace(' ', '\\ ')
    # Available Variables:
    # exe:    Path to IHaskell kernel.
    c = get_config()
    c.KernelManager.kernel_cmd = [exe, 'kernel', '{connection_file}']
    c.Session.key = b''
    c.Session.keyfile = b''

    # Syntax highlight properly in Haskell notebooks.
    c.NbConvertBase.default_language = "haskell"

    # Where to look for templates.
    template_path = "/".join(__file__.split("/")[:-1] + ["templates"])
    c.TemplateExporter.template_path = [template_path]

Any thoughts?

**Comment by edwtjo** [comment]
This issue can be closed as it has been resolved in the nixpkgs repo, https://github.com/NixOS/nixpkgs/commit/2594999cede5b0ceb2991d74c42a5dde2514dfbb

**Comment by gibiansky** [comment]
Great, closing it. If it's still an issue, feel free to reopen.
