### ISSUE TITLE
Diagrams not working with vanilla install of Mac application

### ISSUE THREAD

**Issue by pjward** [gibiansky/IHaskell#337]
Hi.
:extension NoMonomorphismRestriction
import Diagrams.Prelude
diagram $ circle 1
... gives me...
: can't load .so/.DLL for: libcairo.dylib (dlopen(libcairo.dylib, 9): Library not loaded: /opt/X11/lib/libxcb-shm.0.dylib
  Referenced from: /Applications/Kronos-Haskell.app/Contents/Resources/ghc-7.8.3/dylibs/libcairo.dylib
  Reason: image not found)

Do I need to manually cabal install Diagrams? If so, please offer guidance as to where. I have used GHC from the CLI before but I am no expert with Haskell or OS X.

**Comment by gibiansky** [comment]
This is a bug! Thank you for reporting it.

I think you may be able to work around it by installing X11 for Mac. 

I will fix this in the next release.

**Comment by pjward** [comment]
I'll try that. Thanks.

**Comment by gibiansky** [comment]
@pjward It seems that some users have successfully worked around this by installing Xquartz.

**Comment by pjward** [comment]
Yes, that works. Thank you. (Still no HTML export though.)

**Comment by gibiansky** [comment]
I've noted the X11 dependency on the website and also upon startup (if X11 isn't installed). It doesn't seem like it's possible to truly fix this without a lot of effort, though (including the X11 dylibs in the application bundle is non-trivial)
