### ISSUE TITLE
Add to nbviewer featured languages

### ISSUE THREAD

**Issue by FranklinChen** [gibiansky/IHaskell#342]
It might be useful to show off Haskell by contributing to the `nbviewer` front page http://nbviewer.ipython.org

They suggest submitting a pull request:
http://nbviewer.ipython.org/faq#how-do-you-choose-the-featured-notebooks
##

**Comment by gibiansky** [comment]
Oh, cool. I have pinged them about this but didn't know you could make a PR for it. Good idea.

**Comment by vaibhavsagar** [comment]
It seems like the current method is to submit via a Google Form. I've done this.
