### ISSUE TITLE
IHaskellDisplay in example notebook

### ISSUE THREAD

**Issue by gitfoxi** [gibiansky/IHaskell#343]
This seems to work:

```
import IHaskell.Display

instance IHaskellDisplay Color where
  display color = display [html code]
    where
      code = concat ["<div style='font-weight: bold; color:"
                    , css color
                    , "'>Look!</div>"]
      css Red   = "red"
      css Blue  = "blue"
      css Green = "green"
```

The diff is `display` instead of `return`

**Comment by gibiansky** [comment]
Does the original not work?

**Comment by gitfoxi** [comment]
No. It complains of wanting `Display` type I'm giving it `[DisplayContainer]`. I forget. I just borked my docker. Maybe I'll try Kronos next ...

**Comment by gitfoxi** [comment]
Okay, the original gives this error in my just-installed Kronos:

```
Couldn't match expected type ‘Display’ with actual type ‘[DisplayData]’
In the first argument of ‘return’, namely ‘[html code]’
In the expression: return [html code]
In an equation for ‘display’:
    display color
      = return [html code]
      where
          code = concat ["
Look!
"]
          css interactive:IHaskell210.Red = "red"
          css interactive:IHaskell210.Blue = "blue"
          css interactive:IHaskell210.Green = "green"
```

**Comment by gibiansky** [comment]
Oh, I understand now. Oops. Yes, this is some bitrot. `display` would work, also `return $ Display [...]` would probably be the "correct" fix. Will fix this. Thanks for the issue notifications!

**Comment by FranklinChen** [comment]
I just bumped into this myself, while going over the tutorial in preparation for a demo to present for the next meeting of Pittsburgh Haskell. The HTML of the notebook should also be regenerated.

**Comment by gibiansky** [comment]
The current demo notebook works, but the html versions are outdated. Including in the general documentation issue #410, so closing as "duplicate".
