### ISSUE TITLE
What about uploadin the IHaskell.Display packages on hackage?

### ISSUE THREAD

**Issue by meditans** [gibiansky/IHaskell#354]
Hi, could you upload the display packages on hackage? This could enable, eg, the nixos users to have them in their package manager, and benefit from build cache and not be forced to configure the package from source.

**Comment by gibiansky** [comment]
`ihaskell`, `ghc-parser`, `ipython-kernel`, as well as all of the display packages except `ihaskell-widgets` (which is not a real package, just experimental) have been updated on Hackage.

Sadly I have not been keeping track of changes (or API changes) and so bumped the versions of all the packages. Also not respecting PVP. Sorry about that, will try to be better about that in the future.

**Comment by gibiansky** [comment]
If there are any issues, open a new issue and let me know. I have gotten all of them to build on my box with the current version constraints.

**Comment by meditans** [comment]
Thanks, great work. They builded fine from this github repo last time I build it. I'll keep you posted, thanks again :)
