### ISSUE TITLE
ihaskell-parsec-0.2.0.0 does not compile

### ISSUE THREAD

**Issue by peti** [gibiansky/IHaskell#355]
Citing from http://hydra.cryp.to/build/543078/log/raw:

    IHaskell/Display/Parsec.hs:21:13:
        Exception when trying to run compile-time code:
          widget.html: openFile: does not exist (No such file or directory)
        Code: template-haskell:Language.Haskell.TH.Quote.quoteExp
                hereFile "widget.html"

**Comment by gibiansky** [comment]
Thanks! My mistake – forgot to put an `extra-source-files` field in the `.cabal` file. Should be fixed now, just uploaded a `ihaskell-parsec-0.2.1` that seems to be working on my end. Reopen if issue continues.
