### ISSUE TITLE
Showing :i and other output inline (by choice?)

### ISSUE THREAD

**Issue by houshuang** [gibiansky/IHaskell#363]
I think an important use case for IHaskell is to create demos/demonstrations, and for that, it is sometimes useful to include the output of :i, :k etc inline. Currently that's only shown in a popup, which is not part of the generated report. (An example is trying to create a demo of Frames, where showing the autogenerated types is really key). 

I made a quick change to the rendering of :i, and actually quite like it inline. 
![screen shot 2015-02-19 at 12 37 26](https://cloud.githubusercontent.com/assets/61575/6272252/50bd7dce-b834-11e4-909a-8fc7153afffd.png)

I was first thinking we could have a separate command :infoinline or something, however we could also have some kind of a switch :set IHaskell-inline, which would affect all commands. I'm happy to hack on something like this, but would like some direction about how you'd like it implemented, and if you think it's desirable.

**Comment by gibiansky** [comment]
Try out 
```
:option no-pager
```
followed by
```
:i Num
```

Is this what you were looking for?

...for some reason that option is not in `:help`. Oops. That's an error.

**Comment by houshuang** [comment]
Indeed, exactly what I was looking for!

Maybe include this in the demo notebook as well, right now the text "The
same goes for the :info command. However, unlike GHCi, which simply prints
info, the IHaskell notebook brings up a separate pane.", and the pasted
image, makes it seem like this is the only way. (See separate pull request)

On Thu, Feb 19, 2015 at 12:48 PM, Andrew Gibiansky <notifications@github.com
> wrote:

> Try out
>
> :option no-pager
>
> followed by
>
> :i Num
>
> Is this what you were looking for?
>
> ...for some reason that option is not in :help. Oops. That's an error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gibiansky/IHaskell/issues/363#issuecomment-75100211>.
>



-- 
http://reganmian.net/blog -- Random Stuff that Matters

**Comment by gibiansky** [comment]
I will regenerate the HTML and add info to the help text as well, at some point.
