### ISSUE TITLE
Enabling command plugins for IH

### ISSUE THREAD

**Issue by houshuang** [gibiansky/IHaskell#364]
I'm wondering if it would be possible to enable other packages to supply commands for IHaskell. An example is that I would love to integrate haskell-names, so that I could query where a certain function comes from. However, this would require several new dependencies, that might not be useful for most people. It would be great if I could create an ihaskell-names package, and still supply the :names command. (Not sure how that would actually be integrated, how would IH-core know that IH-names supplies a certain command?

**Comment by gibiansky** [comment]
I like this idea. Could we implement it somehow by providing some sort of
```
:define <name> <expression>
```
command?

For example, we might define `name` as something like
```
:define name lookupName
```
where `lookupName :: String -> Display`. 

That leaves the question – how does IHaskell know to `:define` this? We could go the same route as `ihaskell-display` packages, which look for a `IHaskell.Display.PkgName` module, and perhaps IHaskell would also look for a `IHaskell.Command.PkgName` module; this module would have some identifier, like `commands :: [(String, String -> String)], that would contain all the necessary bindings. Or something like that. Thoughts?

**Comment by aavogt** [comment]
At this point it looks like `lookupName "foo"` could do the job just as well as the proposed `:name foo`. `lookupName` probably needs to know things like which modules are imported. That might be doable by adding another constructor to `data Display = ... | DisplayWithImportedModules ([String] -> Display)`.

I can see tab completion being different for `:name`, but it seems like that feature could be done for either syntax.

**Comment by sumitsahrawat** [comment]
A `:def` command has an advantage that it won't overlap with someone's function names. It also provides a good logical separation between what is provided by `IHaskell` and what comes from third party libraries. Ultimately, integrating packages such as `present` and `haskell-numbers` will become much more pleasant afterwards.

Also, I'm leaning towards avoiding text-replacement based macros, but the name `:def` sounds good as it gets syntax highlighted inside `IHaskell` already.

**Discussion from gmail**

*Me*

Initially, I thought that we could make a GHCi ':def' equivalent. But it causes strange behaviors, it's a C-style text-replacement based macro stuffed into a type-safe static world.
I did not complete the definition. I'm at a stage where I can get something like this <attached> (where :testing is a special directive meant for testing different behaviors).

![status](https://cloud.githubusercontent.com/assets/5645741/6859372/29c73568-d43e-11e4-8379-f698f75d90ca.png)

I wanted to send a PR but there is not enough code yet. I've pushed it to GitHub though: https://github.com/sumitsahrawat/IHaskell/commit/6d97290a6013b53f1faeffbe6ee6bd37b94d650f

If such a feature existed, it would be possible to define a directive (:pretty) which does the pretty-printing. And then a flag could be provided which turns off pretty printing by default.
Giving the user more flexible control of what to pretty-print and what to print normally.

I'm still reading code. I want to track where the new definitions are stored. I have experience with only building a small calculator-ish REPL, which used dictionaries of functions and variables as state.
One I understand the flow of information, I'm considering having some pre-defined functions, for example:

```
:def <name> <macro defn>   -- A ghci style macro
:printer <name> <func>     -- func :: String -> String
:vacuum <structure>        -- Print some structure using GHC.Vacuum.Graphviz
```

Any other custom visualizers like these can then be built easily.
The main inspiration is the possible future use case for (:present), and preventing more dependencies for adding commands as highlighted in #364.

@gibiansky 

Hmm, interesting. My main question is this – what is the advantage of having a `def`'d macro over just a function call?

For example, if you create a command `:pretty` that pretty-prints a structure, you then have to invoke it as

:pretty myValue

However, you could also just write a function called "pretty" that pretty-prints your value, with something like this:

data PrettyData = ...
instance IHaskellDisplay PrettyData where ...
pretty :: a -> PrettyData

And then you invoke it with

pretty myValue

Which is the same thing as ":pretty myValue", except shorter, and doesn't require any special mechanism within IHaskell!

That said, I don't have anything against the idea of having :def – I'd just like to have a motivation for it that can't be easily replaced by a function call. Also, note that even if this code that you're writing doesn't go into master eventually, it's still great for learning, and I would say could still be mentioned on the proposal.

Also, let's continue these discussions via the issue tracker – that way other people can also chime in. Feel free to start new issues just for the sake of discussion.

**Comment by gibiansky** [comment]
This was never really fully hashed out – we can restart this discussion at some point but I am closing this for the time being until we know what we want.
