### ISSUE TITLE
Out of date documentation at http://gibiansky.github.io/IHaskell/

### ISSUE THREAD

**Issue by FranklinChen** [gibiansky/IHaskell#377]
http://gibiansky.github.io/IHaskell/ seems out of date in comparison with the README. For example, it mentions Mac Homebrew installation of Haskell platform even though Homebrew removed that several months ago.

**Comment by gibiansky** [comment]
Thanks for the note. I'll work on updating that – the README is updated much more regularly than the Github.io page.

**Comment by gibiansky** [comment]
Consolidated into https://github.com/gibiansky/IHaskell/issues/410
