### ISSUE TITLE
Switch to using Text.Show.Pretty

### ISSUE THREAD

**Issue by houshuang** [gibiansky/IHaskell#382]
I know this will pull in some dependencies (pretty-show and haskell-lexer), but the improvement is amazing. 

![screen shot 2015-02-25 at 23 28 25](https://cloud.githubusercontent.com/assets/61575/6386425/2ae03a3a-bd46-11e4-993f-3a7421d5f22b.png)

![screen shot 2015-02-25 at 23 27 54](https://cloud.githubusercontent.com/assets/61575/6386428/327f6df6-bd46-11e4-9821-54bd6d79a4b1.png)

If it was included, we could also add a function to the module to output HTML (not sure what we'd change though). 

As an alternative, if you don't want to add the dependencies, enable :set show-function ppShow, to allow people to define their own show functions. (Is there already a .ihaskell file that is executed automatically before each GHC session in IHaskell?)

**Comment by gibiansky** [comment]
I'm a little bit confused. What's the actual proposed change? Instead of `show-function`, could you just write an `ihaskell-display` package that uses these? What data types are showable like this?

**Comment by houshuang** [comment]
The idea is that it's a drop-in replacement for show, just more nicely structured. Example 

![screen shot 2015-02-25 at 23 45 35](https://cloud.githubusercontent.com/assets/61575/6386551/7ab6d0a8-bd48-11e4-8b09-899e5f9cb197.png)

**Comment by gibiansky** [comment]
Ah, I see... so you'd have to have something like `Show a => IHaskellDisplay a` which is not an option because that would apply to all `a`. Hrmph.

I wonder if there are any places where this yields a worse result.

**Comment by houshuang** [comment]
It actually already has an HTML-output mode built-in as well, I was looking at the Haddocks for an older version. I haven't played with HTML options at all, to make it look nicer. It's also quite slow for very large data structures, but still kind of neat. 

![screen shot 2015-02-25 at 23 48 12](https://cloud.githubusercontent.com/assets/61575/6386573/e516dff6-bd48-11e4-94ae-40b85386a41d.png)

![screen shot 2015-02-25 at 23 50 41](https://cloud.githubusercontent.com/assets/61575/6386587/3028da94-bd49-11e4-8483-65cd6c2d9dd0.png)

**Comment by houshuang** [comment]
This is actually possible from stock ghci, following the instructions [here](http://www.reddit.com/r/haskell/comments/144biy/pretty_output_in_ghci_howto_in_comments)

![screen shot 2015-02-26 at 00 06 39](https://cloud.githubusercontent.com/assets/61575/6386694/7a261bfa-bd4b-11e4-96c5-3a53dadc84d1.png)

So just need to implement 
```
:set -interactive-print=myPrint
```

**Comment by houshuang** [comment]
See my pull request. We can also augment this with hscolour, examples: 

![screen shot 2015-02-26 at 11 33 31](https://cloud.githubusercontent.com/assets/61575/6396265/6b30bd52-bdab-11e4-9646-4cb5e8eaf920.png)
---
![screen shot 2015-02-26 at 11 33 37](https://cloud.githubusercontent.com/assets/61575/6396266/6b315898-bdab-11e4-8984-6158a8b25235.png)

**Comment by houshuang** [comment]
(This later would have to implemented as an IHaskell display I think, not just hooking into ghci, because you want the HTML to be sent as HTML, not as plain text)

**Comment by houshuang** [comment]
Regarding the last, it seems to me that IHaskell does not differentiate between an expression like 

```haskell
a
```

and 

```haskell
putStrLn "Hi " ++ name
```

The fact that the first one causes GHCi to run `show a`, or use whatever function is in `-interactive-print`, and the other one is the direct output of a statement is transparent to IHaskell. This means that any attempt to color-code the former, would also color-code the latter. The only way around this as I can see is either to catch the statement before it gets sent to GHCi (is this a bound name which is not a function?), or to insert an `-interactive-printer` which provides some special formatting, which can then be picked up on the return to separate `show` output from other output, and then color coding would happen within IHaskell...

...if we want it at all, that is. Simple pretty-formatting without color-coding works perfectly as per my pull request, because it can just lean on GHCi's machinery.

(A final option is to somehow recognize html tags in the output from GHCi and automatically display this as HTML, rather than as plain text "<html><p>" etc...)

**Comment by houshuang** [comment]
Any thoughts on this?

**Comment by gibiansky** [comment]
I like the idea of providing colored output.

I am leaning towards `:opt interactive-print myFun` where `myFun :: Show a => a -> Display`. 

Then create an `ihaskell-show` package which exports `prettyShow` and `prettyShowHtml`; the user could then edit `~/.ihaskell/rc.hs` and add `:opt interactive-print prettyShow` (or `prettyShowColor` or `prettyShowHtml`).

Since there a few choices I am hesitant to choose one and make it canonical by building it into IHaskell core.

**Comment by houshuang** [comment]
This makes sense. On the one hand, I think providing sane and really helpful defaults is important - right now there is a lot you can do with GHCi for example, I've found complicated .ghci files on Reddit enabling built-in hoogle, colorization etc..., but most people just use the out-of-box experience (as opposed to for Clojure, where there is a whole ecosystem of actual plugins to enhance the REPL). But I also understand the concern about dependencies, choosing one solution, etc.

I'll see if I can get a pull request together based on your ideas above.
