### ISSUE TITLE
Add support for Criterion/benchmarking

### ISSUE THREAD

**Issue by houshuang** [gibiansky/IHaskell#385]
I love how you can do 

```python
%timeit test()
100000 loops, best of 3: 3.91 us per loop
```

in IHaskell. I wonder if we could bake in support for Criterion to enable something similar. I know things are a bit different with Haskell, and it might not work for all functions etc. But even being able to quickly compare say a function using String and Text, without setting up the source file in a special way, etc, and getting nice graphs inline in IH, would be amazing.

(Would love to have some kind of memory profiling too).

**Comment by gibiansky** [comment]
I like the idea of making this simple. However, why does this need to be baked into IHaskell?

Specifically, why use the [`timeit`](https://hackage.haskell.org/package/timeit-1.0.0.0/docs/System-TimeIt.html) package or add a few features to it?

Alternatively, create a `quickbench` package with the following signatures (or something similar):
```haskell
type Repeats = Int
type MillisPerRepeat = Double

-- Benchmark a computation by running it many times and reporting the average runtime
benchEval :: NFData a => a -> Repeats -> IO MillisPerRepeat
benchIO :: IO a -> Repeats -> IO MillisPerRepeat

-- Benchmark a computation with a parameter
data ParamBench b = ParamBench (Map b MillisPerRepeat)
benchEvalDep :: NFData a => (b -> a) -> [b] -> Repeats -> IO (ParamBench b)
benchIODep ::  (b -> IO a) -> [b] -> Repeats -> IO (ParamBench b)
```
Then define an `ihaskell-quickbench` package to display `ParamBench a` as a graph, dependent on `ihaskell-chart` or something like that.


This would be a great library and display instance to have, but I wonder whether IHaskell really needs any sort of builtin support for it?

**Comment by houshuang** [comment]
Probably doesn't need to be part of core - the only thing would be to
create a display instance for it. Which technically would be a separate
package, but I just thought this would be a space for all kinds of
discussions about features we'd like to see in IH, whether as part of core,
or not. If you want to restrict this to discussions about the core package,
where should those larger discussions go?

On Fri, Feb 27, 2015 at 4:36 PM, Andrew Gibiansky <notifications@github.com>
wrote:

> I like the idea of making this simple. However, why does this need to be
> baked into IHaskell?
>
> Specifically, why use the timeit
> <https://hackage.haskell.org/package/timeit-1.0.0.0/docs/System-TimeIt.html>
> package or add a few features to it?
>
> Alternatively, create a quickbench package with the following signatures
> (or something similar):
>
> type Repeats = Inttype MillisPerRepeat = Double
> -- Benchmark a computation by running it many times and reporting the average runtimebenchEval :: NFData a => a -> Repeats -> IO MillisPerRepeatbenchIO :: IO a -> Repeats -> IO MillisPerRepeat
> -- Benchmark a computation with a parameterdata ParamBench b = ParamBench (Map b MillisPerRepeat)benchEvalDep :: NFData a => (b -> a) -> [b] -> Repeats -> IO (ParamBench b)benchIODep ::  (b -> IO a) -> [b] -> Repeats -> IO (ParamBench b)
>
> Then define an ihaskell-quickbench package to display ParamBench a as a
> graph, dependent on ihaskell-chart or something like that.
>
> This would be a great library and display instance to have, but I wonder
> whether IHaskell really needs any sort of builtin support for it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gibiansky/IHaskell/issues/385#issuecomment-76476319>.
>



-- 
http://reganmian.net/blog -- Random Stuff that Matters

**Comment by gibiansky** [comment]
Nope, no reason to restrict it to discussions of just core. I misunderstood :)

Probably just try to explicitly mention display packages or widgets in the issue title / content, that's all.

**Comment by aavogt** [comment]
The built-in support might be a more convenient way to say "the code for this function should be compiled with -O2/-O1" than to define that function a module cell (seems to be done in #39 but I haven't tried it out yet). But I think it would be pretty difficult to define a `compiledWithFlags :: String -> a -> a` because that `a` might include things only in-scope in the interpreter. So a session like:

```
n <- randomRIO (0,1.0)
let f x = x**n --or whatever
let g = compiledWithFlags "-O2" f
```
generates a module
```
module F where
fOpt n x = x**n
```

and `compiledWithFlags "-O2" f` is replaced with `fOpt n`. Or if `n` has a Show (or Binary) instance, that generated module could be
```
module F where
n = 0.23412
fOpt x = x**n
```
and then `compiledWithFlags "-O2" f` is replaced by `fOpt`

Name shadowing complicates things for the first approach:
```
n <- randomRIO (0,1.0)
let f x = x**n --or whatever
let g x = compiledWithFlags "-O2" f x
n <- randomRIO (0,1.0)
-- hopefully g uses the old n and not the new n here
```

**Comment by zyv** [comment]
I'm sorry for hijacking this thread, but could someone please help me with a working example of using Criterion from within IHaskell? My understanding was that this should be possible now, right? I did run

    stack install criterion

from inside the container, and it worked. I was able to run

    stack exec -- ghci

and type there `defaultMain [ bench "exp" $ whnf exp (2 :: Double) ]`, which directly run the appropriate benchmark. Unfortunately, when I paste the following in the notebook cell:

    import Criterion.Main
    defaultMain [ bench "exp" $ whnf exp (2 :: Double) ]

all I get is "ExitFailure 1". Any hints?

**Comment by zyv** [comment]
Also, I've noticed that when I run the cell, here is what I get in the console:
```
Usage: ihaskell ([-I|--ci CI] [-G|--no-gc] [-L|--time-limit SECS]
                [--resamples COUNT] [--regress RESP:PRED..] [--raw FILE]
                [-o|--output FILE] [--csv FILE] [--junit FILE]
                [-v|--verbosity LEVEL] [-t|--template FILE] [-m|--match MATCH]
                [NAME...] | [-n|--only-run ITERS] [-m|--match MATCH] [NAME...] |
                [-l|--list] | [--version])
```
