### ISSUE TITLE
Upgrade to support IPython 3

### ISSUE THREAD

**Issue by gibiansky** [gibiansky/IHaskell#387]
As current IHaskell may not work anymore for new ipython installations.

**Comment by zackp30** [comment]
:+1:

**Comment by gibiansky** [comment]
Development is happening on the `jupyter` branch. It is currently not in a working state, but once it is, I will be very glad if people stress test it. Will post updates.

**Comment by zackp30** [comment]
I would be happy to. Thanks!

**Comment by gibiansky** [comment]
@zackp30 It should now work with IPython3 if you pull from the `jupyter` branch. The only known bug is that the pager commands `:info`, `:doc`, etc, yield raw HTML instead of the desired output. If you try stuff out and have difficulty or encounter other bugs, please let me know. This should be getting ready for a small release in the next several days, I hope.

**Comment by gibiansky** [comment]
Pager should also work now.

**Comment by FranklinChen** [comment]
I'm scheduled to give a presentation on IHaskell on Monday, think I'll advise `pip install -U 'ipython[notebook]==2.4.1'` and test out Jupyter later :-).

**Comment by gibiansky** [comment]
@FranklinChen You may also want to suggest `cabal install ihaskell==0.5.*`, because I expect that by Monday I will have released `ihaskell-0.6` with support for Jupyter. That said it will be relatively untested support.

**Comment by gibiansky** [comment]
@FranklinChen @zackp30 @houshuang @Carreau 

`jupyter` has been merged into `master`, so IHaskell now supports IPython 3. A Hackage release won't be for a little while -- there are still a bunch of features and cleaning up to do. Note that `master` **no longer supports IPython versions earlier than 3.0**.

**Comment by Carreau** [comment]
Great ! 

Feel free to  announce on Jupyter google groups (and/or IPython dev)

**Comment by houshuang** [comment]
Do we have a list of features and breaking bugs before the Hackage release?

On Friday, March 6, 2015, Matthias Bussonnier <notifications@github.com>
wrote:

> Great !
>
> Feel free to announce on Jupyter google groups (and/or IPython dev)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gibiansky/IHaskell/issues/387#issuecomment-77647160>.
>


-- 
http://reganmian.net/blog -- Random Stuff that Matters

**Comment by gibiansky** [comment]
@houshuang 

I'd like to get through the [IHaskell 0.6 milestone issue list](https://github.com/gibiansky/IHaskell/milestones/IHaskell%200.6) before the Hackage release. I estimate that this should happen within a week (maybe two, hopefully less).
