### ISSUE TITLE
The demo notebook is broken on nbviewer.ipython.org

### ISSUE THREAD

**Issue by mineo** [gibiansky/IHaskell#388]
http://nbviewer.ipython.org/github/gibiansky/IHaskell/blob/master/demo/IHaskell.ipynb has several issues:

- [ ] Input 10: 

> If you're looking at this notebook after it's been exported to HTML, you won't be able to see this interactive pane. However, it looks approximately like this:

There's just whitespace after that.

- [ ] Inputs 15, 17, 19 & 20 complain about unshowable types.

- [ ] Input 18 complains about `diagram` not being in scope.

- [ ] Input 21 is supposed to show an image, but shows the raw bytestring instead.

**Comment by FranklinChen** [comment]
I mentioned the brokenness of the demo notebook here: https://github.com/gibiansky/IHaskell/issues/343

I should probably help out and just fix it and submit a pull request.

**Comment by gibiansky** [comment]
Adding this as a bullet point of #410 for consolidation of minor documentation-related issues.

**Comment by mineo** [comment]
The new demo notebook in `notebooks/` fixes the above bugs, but the one in `demo/` still has them. Is the latter one deprecated? If so, could it simply be removed?

**Comment by gibiansky** [comment]
Good call. I've removed it. Thanks.
