### ISSUE TITLE
Integrate HIndent for automatic reformatting of cells?

### ISSUE THREAD

**Issue by gibiansky** [gibiansky/IHaskell#391]
I am not sure this is possible without frontend support, but it may be worth looking in to.

**Comment by sumitsahrawat** [comment]
On [this link](http://ipython.org/ipython-doc/dev/development/messaging.html#introspection), the documentation for the messaging specification says that:

> Changed in version 5.0: Reply is changed from structured data to a mime bundle, allowing formatting decisions to be made by the kernel.

This might be easy to do now, I'll give it a shot.

**Comment by gibiansky** [comment]
I'm not sure I understand what you intend to do here. The link you gave me pertains specifically to info requests, not to reformatting cells. 

I suspect that the approach here would be to add some javascript to handle some sort of key event – you can add key events to the IPython frontend fairly easily. Then use a comm to reformat the code. (To do so, you'll have to do some tricks to turn the code into a HSE (haskell-src-exts) module, then feed it to `hindent`). Then on the frontend replace the code with the formatted version returned by the comm.

I suspect that all of this is fairly straightforward, but quite a bit of work – probably just as much as #347.

**Comment by sumitsahrawat** [comment]
I'm sorry, I didn't read the whole section completely. The reply provides tooltips, not code reformatting. Putting that aside, my idea is still applicable using custom comms.

The idea is to send a formatting request as soon as a code execution request is sent. The request will contain all the code inside a cell. (It might be possible to make use of the code sent over during execution request)

The kernel will work with these requests in a similar way to `ihaskell-diagrams`, i.e write the code to a file, format it using hindent, and read it back.

**Comment by gibiansky** [comment]
That sounds good. Three questions / concerns:

1. Why should this happen during code execution? It seems like this should happen whenever the user asks for it to happen, for example, on key press for a particular key combination.
2. Writing it out to a file is actually a bit tricky, because the contents of the cells are not valid Haskell. Take a look at the `HLint.hs` file to see what we have to do (roughly) to get that to work: we have to add a bunch of things that turn a cell into valid code, run hlint, then remove all the things we added.
3. Is it preferable to write a file and call `hindent`, or just to invoke `hindent`'s API? At first, I thought it would be better to do the latter: why shell out and write a file when we can do it all in-process? On the other hand, if done with an executable, then we don't have to add `hindent` to the dependencies, and can just return an error if the user doesn't have `hindent` installed.

The core idea sounds sound though.

**Comment by sumitsahrawat** [comment]
1. Execution is a good point for code re-formatting, as it kinda goes with the notebook philosophy. You write a set of code-output examples and it can be displayed in a cross platform way. Key-combinations will be essential, all editors provide similar functionality and users will expect them here too.

2. That means that it is a good time to separate out a `ihaskell` to `haskell` (and the reverse) transformation. They might be used in the future to allow exporting to `.hs` or `.lhs` files which can actually compile.

3. Yeah, I just looked through the source for hindent and saw that it also provides a library. That will be much better.

I'm glad you liked it. :+1:

**Comment by gibiansky** [comment]
1. Reformatting is somewhat subjective, though. And `hindent` doesn't always give you what you want. So the right way to view reformatting is as a user requesting IHaskell to reformat the code – the way that you might reindent code automatically in Eclipse or something. It's not something that you want to happen automatically – it should definitely just happen upon user request.

2. Hmm, that's an interesting thought. I might steer away from that for now. There's a lot of ways to convert an IHaskell notebook to a haskell file; the way I'd ultimately like to have is that all decls get transformed into decls, and all expressions get transformed into decls as well. However, for the purposes of `hindent`, we can instead just pass it a `Module` object (from `haskell-src-exts`).

Actually, now that I think about it, this is quite a complex issue. There's a lot of small finicky details that I think you'll run into. For example, if you have a code cell like this:

```haskell
print x

y <- expr
print y
let x = y
```
reformatting it will require first changing it into

```haskell
do
  print x

  y <- expr
  print y
  let x = y
  return () -- necessary b/c otherwise you'll get errors about let being last in do block
```
Then stripping the `do`, the extra `return`, and the indentation to get back the proper formatting. On the other hand, if you have something like
```haskell
x :: Int
x = 3
```
sticking it in a `do` block won't work. 

So unless this issue *particularly* interests you I might warn you away from it – it is likely to end up harder than it seems at first glance, and I think could easily take 3-5 weeks of on-and-off work.

Do you think you plan on tackling this issue, or #347? (at least first)

**Comment by sumitsahrawat** [comment]
This does interest me, I'll attempt it afterwards.
I don't have any experience with haskell-src-exts and the ghc api, but they interest me a lot.
Thanks for the warning.
