### ISSUE TITLE
deriving (a, b) only derives a

### ISSUE THREAD

**Issue by houshuang** [gibiansky/IHaskell#392]
Somehow when auto-deriving, only the first item is picked up. Ie. if derive(Show, Eq), it can show, but not compare. If derive (Eq, Show), it's the opposite. I'm not quite sure where in the process this error happens, but it does check the items, because derive (Eq, Stian) tells me that it cannot derive Stian, so it doesn't just discard the items past the first...

![](https://cloud.githubusercontent.com/assets/61575/6277721/1bff8322-b85f-11e4-90f3-34548c34c64e.png)

![](https://cloud.githubusercontent.com/assets/61575/6277744/6c170cf4-b85f-11e4-9131-414879f25d1f.png)

**Comment by gibiansky** [comment]
Bizarre. For the time being you can work around this probably with `-XStandaloneDeriving`, but this is a bizarre and serious bug.

As an aside, is the first output from `cabal test`? Did you get it to work?

**Comment by houshuang** [comment]
I found this when working on the tests, see latest comment on #358. Decided
to make it a stand-alone issue.

On Tue, Mar 3, 2015 at 2:11 PM, Andrew Gibiansky <notifications@github.com>
wrote:

> Bizarre. For the time being you can work around this probably with
> -XStandaloneDeriving, but this is a bizarre and serious bug.
>
> As an aside, is the first output from cabal test? Did you get it to work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gibiansky/IHaskell/issues/392#issuecomment-77012764>.
>



-- 
http://reganmian.net/blog -- Random Stuff that Matters

**Comment by gibiansky** [comment]
Fixed in https://github.com/gibiansky/IHaskell/commit/9f157b36a0aef05e1cde4eee15e6224a2400988d

This is a good reminder not to ignore test suites; this is a very silly issue that would've been caught by the test suite. I'm adding it to travis and going to pay more attention to it in the future.
