### ISSUE TITLE
curses headers could not be found

### ISSUE THREAD

**Issue by SuperHex** [gibiansky/IHaskell#396]
Hi, guys.
After clone the source and typing `./build.sh all` I got this:
```
Failed to install terminfo-0.4.0.0
Build log ( /home/clinix/.cabal/logs/terminfo-0.4.0.0.log ):
Configuring terminfo-0.4.0.0...
configure: WARNING: unrecognized options: --with-compiler, --with-gcc
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking ncurses.h usability... no
checking ncurses.h presence... no
checking for ncurses.h... no
checking curses.h usability... no
checking curses.h presence... no
checking for curses.h... no
configure: error: in `/tmp/terminfo-0.4.0.0-17854/terminfo-0.4.0.0':
configure: error: curses headers could not be found, so this package cannot be built
See `config.log' for more details
```
It seems that `libncurses5-dev` is also required but not mentioned in the README file.
Is this problem due to my carelessness? My operating system is Linux Mint Debian.
Thanks.

**Comment by gibiansky** [comment]
I have not encountered this but likely all of my computers already had that. So it is quite possible that it is needed. If so it should be added to the readme.

As an aside please be aware that right now it works with IPython 2.* only; if you want it to work with ipython 3, use the `jupyter` branch (but documentation does not yet reflect many of the changes).

**Comment by SuperHex** [comment]
Got it,Thanks for your kindly reply. 
Besides, is it possible for me to make any contribution to this project? (also for applying this year's Google Summer of Code project). I have intermediate level of skills of Haskell and like to learn anything unfamiliar for me.

**Comment by gibiansky** [comment]
Yes, there is much room for contributing. I suggest starting by sending me an email describing your level of background and starting with some small contribution which we can discuss via email (probably something on the issues list).

**Comment by SuperHex** [comment]
OK, thanks a lot.

**Comment by jackieleng** [comment]
I'm encountering the same problem while trying to build the Docker image. If I add ``libncurses5-dev`` to the apt-get line in the Dockerfile it builds correctly.

**Comment by jhrcek** [comment]
Hello, just in case anyone had the this problem on Fedora (I had it with Fedora 25) and I solved it by running

```
sudo dnf install ncurses-devel
```
