### ISSUE TITLE
Set up Travis CI?

### ISSUE THREAD

**Issue by gibiansky** [gibiansky/IHaskell#398]
And make it test for last 3 GHC versions (7.6, 7.8, and 7.10, though 7.10 isn't actually out yet...).

**Comment by FranklinChen** [comment]
Base it on `build.sh` and https://github.com/hvr/multi-ghc-travis ?

**Comment by gibiansky** [comment]
Based on my cursory glance [here](http://docs.travis-ci.com/user/languages/haskell/), it seems like it supports several versions at once, but I'm not sure.

**Comment by FranklinChen** [comment]
Here is a `.travis.yml` that I use for the Ebnf package I maintain and test for three versions of GHC: https://github.com/FranklinChen/Ebnf2ps/blob/master/.travis.yml

**Comment by FranklinChen** [comment]
Embarrassingly, my `.travis.yml` is actually out of date and fails on 7.8.4 :-). I'm in the middle of fixing it.

**Comment by FranklinChen** [comment]
I got my project's `.travis.yml` working for 7.8.x and lower, but not yet for 7.10.x because of the big Prelude change it seems (since I don't use 7.10.x yet). But the updated template seems to work well otherwise.
