### ISSUE TITLE
Get GHC 7.10 working on Travis

### ISSUE THREAD

**Issue by gibiansky** [gibiansky/IHaskell#400]
@bgamari 

I'm having some trouble getting the IHaskell with your PR to build on Travis using GHC 7.10.

Here is the [build log](https://travis-ci.org/gibiansky/IHaskell/jobs/53154980).

The current issue is that `arithmoi`, which I believe is needed for `diagrams`, does not play nicely with GHC 7.10, as it requires `integer-gmp==0.*`, whereas in GHC 7.10 it seems like it is `1.*`. 

Could you check what version of `arithmoi` you had installed with GHC 7.10 where you got all the notebooks working?

**Comment by bgamari** [comment]
Currently there are a number of packages for which patches have been merged upstream but no release is available on Hackage. These include `../statestack/ ../diagrams-core/ ../diagrams-lib ../diagrams-svg ../diagrams-contrib/ ../dual-tree/ ../monoid-extras/ lucid-svg `

**Comment by gibiansky** [comment]
`arithmoi` is pulled in by [`diagrams-contrib`](https://hackage.haskell.org/package/diagrams-contrib-1.1.2.3), I believe. I'm disabling checking the `ihaskell-display` package on 7.10 for the time being, we'll see what breaks on 7.10 next.

**Comment by bgamari** [comment]
@gibiansky I believe the dependency may have been [dropped](https://github.com/diagrams/diagrams-contrib/commit/d3fb199ba3ae93ff26f321057d6ee99e31ab5d8c) upstream. Hopefully this will be fixed in the next Hackage release.

**Comment by gibiansky** [comment]
Looks like there's a ton of packages that haven't been pushed to Hackage yet; I'm probably just going to hold off on getting Travis working with 7.10 until it's released. Right now it would require a lot of custom logic to pull packages from Github and such.
