### ISSUE TITLE
A pressed Tab will cause kernel died

### ISSUE THREAD

**Issue by SuperHex** [gibiansky/IHaskell#406]
Hi guys,
In the `jupyter` branch a pressed `Tab` key will lead the kernel died immediately.
This problem can be reproduced by following steps:
1. `IHaskell console` to enter console mode.
2. whenever in the console mode just press the `Tab` key and the kernel will die. More than one press will cause the kernel restart many times.

I have tried  in `IPython console` it works fine. So it seems that problem is caused by the completion request, while the parser don't know how to deal with it. I will try to fix it. Any suggestion will be appreciated.

**Comment by gibiansky** [comment]
Sounds good. Look at `Parser.hs` in the `ipython-kernel` package/directory; the message it is sending should be detailed in [the messaging spec](http://ipython.org/ipython-doc/dev/development/messaging.html). You can use the `Debug.Trace` module and the `traceShow` function in order to print out intermediate results to see what messages are actually being received (before the exception happens).

**Comment by SuperHex** [comment]
@gibiansky 
I find the problem is located in Parser.hs line 121 where the ` parse parser decoded` evaluated `Error String` rather than `Success parsed`. This lead to a `Irrefutable pattern failed`. But I have totally no idea how to deal with the `parse` function to avoid it. Maybe we should try `parseMaybe` instead?
Here is the debugging output:
```
In [5]: 
Content:"{\"code\":\"\",\"cursor_pos\":0}"                       -- content to be decoded
Decoded:fromList [("code",String ""),("cursor_pos",Number 0.0)]  -- It is not `Nothing` !
Error!                                                           -- `Error e` pattern
```
By the way, is there even a function handling command completion request? I don't really know about that.

**Comment by gibiansky** [comment]
@SuperHex I've realized that this might not be a great way to learn the IHaskell codebase; I'm going to go ahead and fix this as it's fairly serious and is somewhat blocking merging the `jupyter` branch. 

If you would like to learn about the messaging protocol, I suggest trying your hand at #389. There were new messages introduced in 3.0 for dealing with history, which have yet to be implemented; search in `Main.hs` for `TODO`, as well as `Types.hs` in the `ipython-kernel` package. Alternatively you may want to start with a bit of an easier challenge, like https://github.com/gibiansky/IHaskell/issues/371. Feel free to ping me by email if you'd like to discuss further.

Also, I'm not getting this error; this doesn't seem like it should be happening. What version of `ipython` are you running?
```
ipython --version
```

**Comment by SuperHex** [comment]
It is exactly `3.0.0`. while in browser interface it works fine. I will take a look at them. Thanks a lot.
