### ISSUE TITLE
Fix the sample notebooks

### ISSUE THREAD

**Issue by FranklinChen** [gibiansky/IHaskell#420]
All the sample notebooks except for `IHaskell.ipynb` in https://github.com/gibiansky/IHaskell/tree/master/notebooks complain on load that

```console
I couldn't find a kernel matching (No name).
```

**Comment by gibiansky** [comment]
That's strange. I've updated all the notebooks to v4, and they seem to be aware that they are using the Haskell kernels, so this should be gone. Also verified that they all say that their kernel is "haskell" in the metadata, so should be good now.
