### ISSUE TITLE
IHaskell on iPython 3

### ISSUE THREAD

**Issue by sindhus** [gibiansky/IHaskell#423]
hi! I installed IHaskell successfully through cabal (from instructions in README).
I am unable to see Haskell under the "new" menu of iPython 3

![home - http___localhost_8778_tree](https://cloud.githubusercontent.com/assets/4291156/6550550/7cd7d38a-c650-11e4-8f0f-064e03dba152.png)

Am I supposed to start Haskell under Clusters? If so, I did but I still don't see Haskell under the "new" menu.

Also when I run `ipython console`, I get:
```
Using system-wide dev version of IPython.
/usr/local/lib/python2.7/site-packages/IPython/kernel/manager.py:95: UserWarning: Setting kernel_cmd is deprecated, use kernel_spec to start different kernels.
  warnings.warn("Setting kernel_cmd is deprecated, use kernel_spec to "
Unknown flag: --profile
```

I am unable to get any sort of console, the message appears and things seem to have hung.

**Comment by gibiansky** [comment]
`ihaskell-0.5` on Hackage does not support IPython 3; I am planning on making a release soon, though. 

If you want IPython 3 support, build from Github, and run `ihaskell install` to install the kernel. 

Apologies for the confusion -- I am working on getting IPython 3 fully supported, with documentation and Hackage release, but it is quite a bit of work and so may take another week or so until it's really in a good shape.

Reopen if installing from Github and running `IHaskell install` does not fix things.

**Comment by sindhus** [comment]
Awesome! I can now use haskell notebooks by running `IHaskell notebook`. Thank you @gibiansky :+1:
