### ISSUE TITLE
check for `sudo` for installing python on mac osx

### ISSUE THREAD

**Issue by gibiansky** [gibiansky/IHaskell#429]
This causes macos-install.sh to fail to install IPython.

@FranklinChen

**Comment by FranklinChen** [comment]
Do you mean the `brew install python` part? By default the Homebrew installation from `http://brew.sh/` does not require `sudo` for anything, nor does `pip`.

Or do you mean, if someone is using some other version of Python, such as Apple's?

**Comment by gibiansky** [comment]
Ahhh I see. Okay. The computer I tested it on had some weird pip configurations, a mix of Apple's and brew's install... makes sense now.
