### ISSUE TITLE
ihaskell: Unexpected argument: console

### ISSUE THREAD

**Issue by slon1024** [gibiansky/IHaskell#437]
After updated and installed i can't run ihaskell (i used `./build.sh all`). 
I pulled the newest version: `[900b092] Andrew Gibiansky 4 days ago: Dont screw up kernelspec when no conf file is present`
```
➜  ihaskell notebook
ihaskell: Unexpected argument: console

➜  ihaskell
ihaskell: Unexpected argument: console
```
@gibiansky any ideas why it's happened :bowtie: ?

**Comment by gibiansky** [comment]
This is a documentation issue -- apologies, still working through the IPython 3 upgrade, and documentation hasn't yet been updated (that's issue #410 though).

IHaskell commands that just wrap the underlying IPython are no longer supported, so you must invoke IHaskell through one of the following:
```bash
ipython console --kernel haskell # Open the console
ipython notebook # Open Jupyter notebook 
```

**Comment by gibiansky** [comment]
Note that you must run `ihaskell install` first, before those `ipython` commands.

Let me know if you have issues getting it to work.

**Comment by slon1024** [comment]
So, it looks like not too deterministic.
```
➜  ./build.sh all
➜  ipython console --kernel haskell
[ZMQTerminalIPythonApp] CRITICAL | Could not find kernel haskell
```

But after this magic step it works :smile:
```
➜ git reset b96f6af --hard
HEAD is now at b96f6af Merge pull request #427 from juselius/master
➜ cabal build
➜ ipython console --kernel haskell
[ZMQTerminalIPythonApp] CRITICAL | Could not find kernel haskell
➜ dist/build/IHaskell/IHaskell
Welcome to IHaskell! Run `IHaskell --help` for more information.
Enter `:help` to learn more about IHaskell built-ins.

In [1]:

➜ ipython console --kernel haskell
IPython Console 3.0.0

In [1]:
```

**Comment by gibiansky** [comment]
Don't forget to `ihaskell install`! Somehow IHaskell has to tell `ipython` that it exists, and that's what `ihaskell install` does. Once you run `ihaskell install` it should work in the way you originally expected.

**Comment by slon1024** [comment]
I see, thansk @gibiansky :+1: 
I prepared this PR: https://github.com/gibiansky/IHaskell/pull/438 where it's running `ihaskell install` in the end of the script.
