### ISSUE TITLE
ihaskell-parsec, no output in some cases

### ISSUE THREAD

**Issue by sumitsahrawat** [gibiansky/IHaskell#447]
The ihaskell-parsec widget doesn't provide output in some cases.

![screenshot from 2015-03-21 14 03 52](https://cloud.githubusercontent.com/assets/5645741/6764349/21eebc36-cfd3-11e4-8e89-5ce565a4d9d7.png)

Whereas the following works in ghci.

```haskell
ghci> parse (read <$> many digit :: Parser Int) "<interactive>" "123x"
Right 123
```

EDIT: Browser info

![screenshot from 2015-03-21 14 14 20](https://cloud.githubusercontent.com/assets/5645741/6764417/9eb70fec-cfd4-11e4-89ab-f5d7f0bc238e.png)

**Comment by gibiansky** [comment]
IHaskell parsec is now deprecated and gone. Instead we can use backbone widgets!
