### ISSUE TITLE
Kernel not responding

### ISSUE THREAD

**Issue by houshuang** [gibiansky/IHaskell#454]
Trying to get IH working with Jupyter, however it complains that the kernel is not responding. I've tried all the reinstall clean, build.sh, macos-install.sh etc. If I try to run ipython console --kernel haskell, I see in ps that an IH kernel is spun up, however it just sits there, until it exits with Kernel did not respond. Same with notebook. I'm sure this is due to something left over from the previous installation, but how to fix it/diagnose further?

**Comment by gibiansky** [comment]
Install the kernel with `ihaskell install --debug`. This will cause it to print debug messages.
