### ISSUE TITLE
Update Dockerfile

### ISSUE THREAD

**Issue by gibiansky** [gibiansky/IHaskell#455]
@gregwebs 

I've temporarily removed the `Dockerfile` as it is out of date, since IHaskell now uses IPython 3 and needs to be invoked and installed somewhat differently. I don't use `docker`, and so can't test it very well, so although the changes are minor I probably can't get around to them for a while.

I expect the changes would need to be:
- Install IPython and any dependencies it has manually.
- Run `ihaskell install` after IHaskell is installed
- Expose `ipython notebook` or `ipython console --kernel haskell` as well, as that is how you now run IPython (no more wrapper commands)

**Comment by pikeas** [comment]
I'm banging together a new Dockerfile, but I'm in the opposite position - I'm very new to Haskell. To keep things lean, I'm not installing the full Haskell Platform, only the subset of packages which are actually necessary.

Which brings me to my question - which parts of the Platform are needed to run IHaskell?

**Comment by gibiansky** [comment]
I suggest just installing GHC and Cabal, and then using `cabal install`. It's hard to say exactly what IHaskell requires since the set of transitive dependencies is quite large.

**Comment by pikeas** [comment]
I'm stepping through it and seeing what breaks. What's the GHC 7.10 status?

**Comment by gibiansky** [comment]
GHC 7.10 is supported for IHaskell base but hasn't been verified or debugged for the ihaskell-display packages, which have a lot of dependencies for things like diagrams and charts and so on.

**Comment by FranklinChen** [comment]
I've periodically looked to see where `ihaskell-display` stands. Right now, `Rlang-QQ` is the main holdup for `ihaskell-rlangqq`, and I emailed the maintainer who is working on getting it working. `ihaskell-diagrams` might need to be updated to `diagrams` 1.3 and `active` 0.2 but I haven't tested that.

**Comment by pikeas** [comment]
The old Dockerfile installed everything via cabal. This is also the documented process under the ReadMe's "install manually" section. However, `build.sh` installs everything from subdirs in the project.

Which method is preferred/better?

**Comment by gibiansky** [comment]
Installing IHaskell components from subdirectories and their dependencies from Hackage is the preferred way to go. (That is what build.sh does)

**Comment by FranklinChen** [comment]
I've just been informed that a new `Rlang-QQ` is out: "ok I've made Rlang-QQ 0.3. I rearranged how files are written in Rtmp/ which probably breaks ihaskell-rlangqq however"

**Comment by FranklinChen** [comment]
Got the displays building: https://github.com/gibiansky/IHaskell/pull/488

But not fully tested yet.

**Comment by gibiansky** [comment]
Added a new and improved Dockerfile in 45ad25a9bb82cbec09aab55a2a6

Also uploaded to `gibiansky/ihaskell:latest` on Docker Hub
