### ISSUE TITLE
linux-install.sh breaks gentoo systems and only works on ubuntu

### ISSUE THREAD

**Issue by triclops200** [gibiansky/IHaskell#458]
Not all linux systems use apt-get. Also, easy-install is buggy on some linuxes, and using it on Gentoo is enough to effectively destroy users' systems. Please find a cross-platform way to fix this.

**Comment by gibiansky** [comment]
Fair enough; sounds like we should rename it to `ubuntu-install.sh`. I'm fairly explicit about that [here in the README](https://github.com/gibiansky/IHaskell#ubuntu).

@FranklinChen Do you mind renaming it?

**Comment by gibiansky** [comment]
This has been clarified in the naming and the README. I don't have a Gentoo system so can't provide an install script that will work, so closing this issue (and the recommended installation path is via the other routes). That said I am happy to accept PRs for more install scripts.
