### ISSUE TITLE
Add IHaskell to Beaker

### ISSUE THREAD

**Issue by FranklinChen** [gibiansky/IHaskell#462]
It would nice to add IHaskell to Beaker http://beakernotebook.com/

Some notes on how to do this here:

https://github.com/twosigma/beaker-notebook/wiki/How-to-Add-a-Language-to-Beaker

Contributor license agreement apparently needed: http://beakernotebook.com/community

Pages mentioning various languages that would be updated if we got Haskell in:
- http://beakernotebook.com/
- http://beakernotebook.com/features
- http://beakernotebook.com/getting-started
- http://beakernotebook.com/examples
- https://github.com/twosigma/beaker-notebook

**Comment by pbronez** [comment]
Looks like there is a [roadmap](https://github.com/twosigma/beaker-notebook/wiki/Importing-Plugins-from-IPython) for importing iPython kernels to Beaker Notebook.

**Comment by FranklinChen** [comment]
@pbronez Cool. I'm too busy to work on this in the next two weeks, but if nobody's done it by then, I'll tackle it. (Meanwhile, still hoping https://github.com/bmillwood/haskell-src-meta/issues/42 gets resolved soon so that IHaskell will build on GHC 7.10.1.)

**Comment by gibiansky** [comment]
I do not have time to implement this and do not use Beaker myself, so am closing this for the time being. I'm happy to support getting this done so if anyone volunteers I'm happy to re-open this.
