### ISSUE TITLE
Install fails on Ubuntu 14, GHC 7.6.3 (Haskell Platform)

### ISSUE THREAD

**Issue by sbrother** [gibiansky/IHaskell#466]
I just tried to install IHaskell on both my work and personal computers, and each failed on the `cabal install ihaskell --reorder-goals` step with the message

    cabal: The following packages are likely to be broken by the reinstalls:
    HTTP-4000.2.18

I'm running Ubuntu 14.04, cabal 1.21.1.0, and ghc 7.6.3 on both machines.

**Comment by gibiansky** [comment]
Could you include the full build log from `cabal`?

You could also pass it `--force-reinstalls` and let it break HTTP.

Also, you can install `IHaskell` in a cabal sandbox:
```bash
mkdir ihaskell-sandbox
cd ihaskell-sandbox
cabal sandbox init
cabal install ihaskell --reorder-goals
```

This doesn't look like a bug / error in IHaskell, just difficulty installing it with the packages you happen to have installed globally :( It can be solved by reinstalling some of the packages you have (that's the `--force-installs` option) or by using a sandbox.

**Comment by sbrother** [comment]
Thanks for the quick reply! I did get it working with --force-reinstalls, but I figured it was worth posting a bug just because this will affect anyone who tries to install IHaskell using the most recent version of Ubuntu and the Haskell Platform.

**Comment by gibiansky** [comment]
Great; good to know.

Once 7.10 is out and IHaskell works with 7.10, I'll try to make sure it installs cleanly with the Haskell platform.
