### ISSUE TITLE
ghci 7.10.1 compilation patch

### ISSUE THREAD

**Issue by blippy** [gibiansky/IHaskell#469]
IHaskell has a few problems compiling with 7.10.1. I have created a patch which fixes the compile, which is available at http://pastebin.com/KjYekARB

Edit: I confirm that the patch works (at least for me)

**Comment by gibiansky** [comment]
Thanks. I've started a PR to test on Travis GHC 7.10 [here](https://github.com/gibiansky/IHaskell/pull/470) and will start working on adding GHC 7.10 support. Will incorporate your patch soon.

**Comment by gibiansky** [comment]
Patch has been incorporated. Thanks! Will merge it once I get verification from Travis that IHaskell builds on 7.10.
