### ISSUE TITLE
There is only 7.6 support in hackage

### ISSUE THREAD

**Issue by ztq56** [gibiansky/IHaskell#476]
In https://hackage.haskell.org/package/ghc-parser the package depends on `ghc` (>=7.6 && <7.11) but only `src-7.6` folder in the cabal source package.
I install failed on my arch linux ghc 7.10.1, cabal 1.22.2.0, and It shows:

> Resolving dependencies...
Downloading ghc-parser-0.1.6.0...
Configuring ghc-parser-0.1.6.0...
Building ghc-parser-0.1.6.0...
Failed to install ghc-parser-0.1.6.0
Build log ( ~/.cabal/logs/ghc-parser-0.1.6.0.log ):
[1 of 1] Compiling Main             ( /tmp/ghc-parser-0.1.6.0-6508/ghc-parser-0.1.6.0/dist/setup/setup.hs, /tmp/ghc-parser-0.1.6.0-6508/ghc-parser-0.1.6.0/dist/setup/Main.o )
Linking /tmp/ghc-parser-0.1.6.0-6508/ghc-parser-0.1.6.0/dist/setup/setup ...
unused rules: 20
shift/reduce conflicts:  42
reduce/reduce conflicts: 1
unused rules: 18
shift/reduce conflicts:  46
reduce/reduce conflicts: 1
unused rules: 18
shift/reduce conflicts:  46
reduce/reduce conflicts: 1
Configuring ghc-parser-0.1.6.0...
Warning: 'hs-source-dirs: src-7.10' directory does not exist.
Building ghc-parser-0.1.6.0...
Preprocessing library ghc-parser-0.1.6.0...
setup: can't find source for Language/Haskell/GHC/HappyParser in generic-src,
src-7.10, dist/build/autogen
cabal: Error: some packages failed to install:
ghc-parser-0.1.6.0 failed during the building phase. The exception was:
ExitFailure 1

**Comment by aueelis** [comment]
I noticed this, too.
Although the folders `ghc-7.6`, `ghc-7.8.2`, `ghc-7.8.3` and `ghc-7.10` appear in the repository, only the first one is included in the hackage package.

**Comment by gibiansky** [comment]
Thanks for the note. Looks like `cabal sdist` isn't including `src-7.10` for some reason (see #478). Will fix soon (https://github.com/gibiansky/IHaskell/pull/480)

**Comment by gibiansky** [comment]
This is fixed and will be included in the upcoming Hackage release.
