### ISSUE TITLE
Automatic quotation mark closing not working correctly.

### ISSUE THREAD

**Issue by bsmith89** [gibiansky/IHaskell#481]
When typing in a Jupyter notebook running an IHaskell kernel, typing the double quote character (`"`) behaves unintuitively.

For example:

In a blank cell (although approximately the same thing happens regardless of the surrounding text), typing the first double quote results in
```
"|
```
(where the pipe character is the cursor position)

Typing a second double quote
```
""|"
```
(That's three double quote characters.  Syntax highlighting makes the first two dark red and the third green.)

Typing a third double quote
```
"""|
```

Moving the cursor to after the first character
```
"|""
```
(not unexpected)

And then hitting backspace
```
|"
```

If I type a new line after the first quote, typing a quote on the second line behaves the same way (that is, as though it were the only line).

I built IHaskell without the display libraries (`./build.sh ihaskell`) from deb92f1.
And then installed it as a kernel with `ihaskell install --debug`.  No interesting debug information was printed while going through the actions above.

IHaskell appears to be otherwise working.  Notebooks with a python kernel are not affected.

```
>ipython --version
3.1.0
>ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.1
```

```
Python 3.4.3 (default, Feb 25 2015, 21:28:45) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]
```

**Comment by bsmith89** [comment]
Turns out the same stuff happens for single quotes (`'`).

**Comment by gibiansky** [comment]
Thanks for pointing this out. I think it's not something I've thought of. Something strange on the client-side... Will look into it.

**Comment by bsmith89** [comment]
Any progress on this?  Does it have something to do with CodeMirror?

**Comment by bsmith89** [comment]
I can reproduce this bug in IHaskell notebook running on [try.jupyter.org](http://try.jupyter.org) using Chrome, Safari, and Firefox.

**Comment by gibiansky** [comment]
Fixed in newest on Hackage, I think.
