### ISSUE TITLE
Could not find module ‘IHaskell.IPython.Stdin’

### ISSUE THREAD

**Issue by rrottier** [gibiansky/IHaskell#485]
I am trying to install ihaskell from source using the sandbox instructions provided in the Readme.  When I run the cabal install step I get the following error.
```
src/Main.hs:36:18:
    Could not find module ‘IHaskell.IPython.Stdin’
    Perhaps you meant
      IHaskell.IPython.Types (from ipython-kernel-0.6.0.0)
      IHaskell.IPython.Kernel (from ipython-kernel-0.6.0.0)
      IHaskell.IPython.ZeroMQ (from ipython-kernel-0.6.0.0)
    Use -v to see a list of the files searched for.
```

**Comment by gibiansky** [comment]
Make sure to install `IHaskell` from source and not from Hackage; Hackage is outdated again. (Sorry, should fix this.) Install via `cabal install` instead of `cabal install IHaskell`.

**Comment by rrottier** [comment]
Thanks - that seems to work for ihaskell but I am still struggling with installing the display components.

So I am assuming the instructions should read:
```
cd IHaskell
cabal sandbox init
cabal sandbox add-source ihaskell-display/* ghc-parser ipython-kernel
cabal install
cabal install $(basename ihaskell-display/*)
```
but the last line does not seem to successfully install the display packages, instead it gives me:
`basename: extra operand ‘ihaskell-display/ihaskell-blaze’`

**Comment by gibiansky** [comment]
Try installing  them via 
```
cabal install ihaskell-display/*
```

**Comment by rrottier** [comment]
For some reason that seems to get me back to the original issue.  It tries to re-install ihaskell because:
`ihaskell-0.6.0.0 (reinstall) changes: utf8-string-1 -> 0.3.8`
and then fails with the error:
`Could not find module ‘IHaskell.IPython.Stdin’`

BTW. I also get an error:
```
Failed to install magic-1.1
Build log ( /Users/rrottier/Haskell/IHaskell/.cabal-sandbox/logs/magic-1.1.log ):
Configuring magic-1.1...
Building magic-1.1...
Preprocessing library magic-1.1...
Data.hsc:19:10: fatal error: 'magic.h' file not found
#include "magic.h"
         ^
1 error generated.
```

I have installed libmagic using homebrew as per the .sh file.

**Comment by gibiansky** [comment]
Try to install both of them at once:
```bash
cabal install . ihaskell-display/*
```

Yeah, the sandbox instructions aren't well updated :( I usually install everything with `./build.sh`.

You may need to use `--extra-lib-dirs` and `--extra-include-dirs` for `cabal`; something like this:
```
cabal install . ihaskell-display/* --extra-lib-dirs=`brew --prefix libmagic`/lib --extra-include-dirs=`brew --prefix libmagic`/include
```

**Comment by rrottier** [comment]
Works perfectly.  Thanks for the help.   Maybe worth updating the readme.
:-)

**Comment by gibiansky** [comment]
readme updated. Thanks.
