### ISSUE TITLE
libHShslogger-1.2.8.so: cannot open shared object file

### ISSUE THREAD

**Issue by blippy** [gibiansky/IHaskell#487]
I have downloaded IHaskell:
commit 44ebe75c0c6c69c6a48bf73094c349c0fe1a0d88
Author: Andrew Gibiansky <andrew.gibiansky@gmail.com>
Date:   Thu Apr 23 16:51:44 2015 -0700

I type 
    ./build.sh quick

and it gives me:
... bunch of output ...
Loading package hslogger-1.2.8 ... <command line>: can't load .so/.DLL for: libHShslogger-1.2.8.so (libHShslogger-1.2.8.so: cannot open shared object file: No such file or directory)
cabal: Error: some packages failed to install:
ihaskell-0.6.0.0 failed during the building phase. The exception was:
ExitFailure 1

However, when I type
    cabal install hslogger
Resolving dependencies...
All the requested packages are already installed:
hslogger-1.2.8

I don't know how to proceed.

**Comment by gibiansky** [comment]
This seems like some strange, strange GHC/cabal bug. Perhaps [this](https://ghc.haskell.org/trac/ghc/ticket/8618)? Do you have `shared: False` in your `~/.cabal/config` by any chance?

I don't know how to deal with this but I would probably try to deal with it by removing `hslogger` and then installing `IHaskell` again. Perhaps in a sandbox (using a sandbox with IHaskell is described [here](https://github.com/gibiansky/IHaskell#build-ihaskell)).

**Comment by blippy** [comment]
I removed hslogger as suggested, and used the sandbox approach. That seemed to help a lot. However, when I type
    ./build.sh quick
I get
...
The command "ihaskell install" failed. Please check your 'ipython --version'. 3.0 or up is required but it is 3.1.0!

Hmm. 
$ ipython --version
3.1.0

**Comment by gibiansky** [comment]
Add the bin directory of the sandbox (./cabal-sandbox/bin or some such) to
your PATH.

**Comment by blippy** [comment]
Thanks. Haskell kernel now works in Jupyter, and this issue can be closed.
