### ISSUE TITLE
src/IHaskell/Eval/Evaluate.hs:404:16:

### ISSUE THREAD

**Issue by marmalodak** [gibiansky/IHaskell#491]
(ihaskell-venv) [root@qa-notebook zeromq-4.0.5]# PKG_CONFIG_PATH=/e2e/lib/zeromq4/lib/pkgconfig:/e2e/lib/zeromq4/lib/pkgconfig:/usr/share/licenses/pkgconfig:/usr/share/pkgconfig:/usr/share/doc/pkgconfig cabal install ihaskell --extra-lib-dirs=/e2e/lib/zeromq4/lib --extra-include-dirs=/e2e/lib/zeromq4/include

...

Loading package MissingH-1.3.0.1 ... linking ... done.
[16 of 18] Compiling IHaskell.Eval.Evaluate ( src/IHaskell/Eval/Evaluate.hs, dist/build/IHaskell/Eval/Evaluate.o )

src/IHaskell/Eval/Evaluate.hs:404:16:
    Couldn't match type `FilePath' with `[Char]'
    Expected type: GHC.IO.FilePath
      Actual type: FilePath
    In the first argument of `writeFile', namely
      `(fpFromString $ directory ++ filename)'
    In a stmt of a 'do' block:
      writeFile (fpFromString $ directory ++ filename) contents
    In the second argument of `($)', namely
      `do { createDirectoryIfMissing True directory;
            writeFile (fpFromString $ directory ++ filename) contents }'

src/IHaskell/Eval/Evaluate.hs:566:40:
    Couldn't match type `FilePath' with `[Char]'
    Expected type: GHC.IO.FilePath
      Actual type: FilePath
    In the return type of a call of `fpFromString'
    In the second argument of `($)', namely `fpFromString filename'
    In a stmt of a 'do' block:
      contents <- readFile $ fpFromString filename
Failed to install ihaskell-0.6.0.0
cabal: Error: some packages failed to install:
ihaskell-0.6.0.0 failed during the building phase. The exception was:
ExitFailure 1

**Comment by sumitsahrawat** [comment]
It seems like this issue arises because of some package upgrade. It installed fine for me, but cabal told me that I should run `cabal update`. Afterwards, reinstalling in a fresh sandbox gives the same error.

**Comment by gibiansky** [comment]
It arises due to an update of `classy-prelude` which removed `system-filepath`. Since IHaskell doesn't build using current Hackage I'm going to delay the release somewhat to fix this. I'll try to get to it ASAP because it's somewhat blocking but I'm getting my degree tomorrow and so today and tomorrow are incredibly busy, so it might end up happening next week. It should be a fairly simple fix involving just changing some types around but we'll see.

**Comment by sumitsahrawat** [comment]
@gibiansky Congratulations :tada:.

I'll try to fix this issue if possible by tomorrow.

**Comment by sumitsahrawat** [comment]
@marmalodak This has been solved. Can you try building it once again (this time from the repo) using the `build.sh` script?

**Comment by marmalodak** [comment]
Linking dist/build/happy/happy ...
Installing executable(s) in /root/.cabal/bin
Installed happy-1.19.5
+(./qa-ihaskell-build.bash:50): main(): export
PKG_CONFIG_PATH=/e2e/lib/zeromq4/lib/pkgconfig:/e2e/lib/zeromq4/lib/pkgconfig:/usr/share/licenses/pkgconfig:/usr/share/pkgconfig:/usr/share/doc/pkgconfig
+(./qa-ihaskell-build.bash:50): main():
PKG_CONFIG_PATH=/e2e/lib/zeromq4/lib/pkgconfig:/e2e/lib/zeromq4/lib/pkgconfig:/usr/share/licenses/pkgconfig:/usr/share/pkgconfig:/usr/share/doc/pkgconfig
+(./qa-ihaskell-build.bash:51): main(): cabal install ihaskell
--reorder-goals --extra-lib-dirs=/e2e/lib/zeromq4/lib
--extra-include-dirs=/e2e/lib/zeromq4/include
Resolving dependencies...
Configuring ihaskell-0.6.0.0...
Building ihaskell-0.6.0.0...
Preprocessing library ihaskell-0.6.0.0...
[ 1 of 18] Compiling Paths_ihaskell   (
dist/build/autogen/Paths_ihaskell.hs, dist/build/Paths_ihaskell.o )
[ 2 of 18] Compiling IHaskell.BrokenPackages (
src/IHaskell/BrokenPackages.hs, dist/build/IHaskell/BrokenPackages.o )
[ 3 of 18] Compiling IHaskell.Eval.Util ( src/IHaskell/Eval/Util.hs,
dist/build/IHaskell/Eval/Util.o )

src/IHaskell/Eval/Util.hs:116:59: Warning:
    In the use of `elem'
    (imported from ClassyPrelude, but defined in Data.Sequences):
    Deprecated: "use oelem"
[ 4 of 18] Compiling IHaskell.Eval.Parser ( src/IHaskell/Eval/Parser.hs,
dist/build/IHaskell/Eval/Parser.o )

src/IHaskell/Eval/Parser.hs:263:22: Warning:
    In the use of `elem'
    (imported from ClassyPrelude, but defined in Data.Sequences):
    Deprecated: "use oelem"
[ 5 of 18] Compiling IHaskell.Eval.ParseShell (
src/IHaskell/Eval/ParseShell.hs, dist/build/IHaskell/Eval/ParseShell.o )
[ 6 of 18] Compiling IHaskell.Types   ( src/IHaskell/Types.hs,
dist/build/IHaskell/Types.o )
[ 7 of 18] Compiling IHaskell.Flags   ( src/IHaskell/Flags.hs,
dist/build/IHaskell/Flags.o )

src/IHaskell/Flags.hs:61:30: Warning:
    In the use of `elem'
    (imported from ClassyPrelude, but defined in Data.Sequences):
    Deprecated: "use oelem"

src/IHaskell/Flags.hs:65:19: Warning:
    In the use of `elem'
    (imported from ClassyPrelude, but defined in Data.Sequences):
    Deprecated: "use oelem"
[ 8 of 18] Compiling IHaskell.Convert.Args ( src/IHaskell/Convert/Args.hs,
dist/build/IHaskell/Convert/Args.o )
[ 9 of 18] Compiling IHaskell.Convert.IpynbToLhs (
src/IHaskell/Convert/IpynbToLhs.hs,
dist/build/IHaskell/Convert/IpynbToLhs.o )
[10 of 18] Compiling IHaskell.Convert.LhsToIpynb (
src/IHaskell/Convert/LhsToIpynb.hs,
dist/build/IHaskell/Convert/LhsToIpynb.o )
[11 of 18] Compiling IHaskell.Convert ( src/IHaskell/Convert.hs,
dist/build/IHaskell/Convert.o )
[12 of 18] Compiling IHaskell.IPython ( src/IHaskell/IPython.hs,
dist/build/IHaskell/IPython.o )

src/IHaskell/IPython.hs:191:23: Warning:
    In the use of `elem'
    (imported from ClassyPrelude, but defined in Data.Sequences):
    Deprecated: "use oelem"
[13 of 18] Compiling IHaskell.Eval.Hoogle ( src/IHaskell/Eval/Hoogle.hs,
dist/build/IHaskell/Eval/Hoogle.o )
[14 of 18] Compiling IHaskell.Display ( src/IHaskell/Display.hs,
dist/build/IHaskell/Display.o )
[15 of 18] Compiling IHaskell.Eval.Lint ( src/IHaskell/Eval/Lint.hs,
dist/build/IHaskell/Eval/Lint.o )
Loading package ghc-prim ... linking ... done.

.... < lots more > ...


Loading package MissingH-1.3.0.1 ... linking ... done.
[16 of 18] Compiling IHaskell.Eval.Evaluate (
src/IHaskell/Eval/Evaluate.hs, dist/build/IHaskell/Eval/Evaluate.o )

src/IHaskell/Eval/Evaluate.hs:404:16:
    Couldn't match type `FilePath' with `[Char]'
    Expected type: GHC.IO.FilePath
      Actual type: FilePath
    In the first argument of `writeFile', namely
      `(fpFromString $ directory ++ filename)'
    In a stmt of a 'do' block:
      writeFile (fpFromString $ directory ++ filename) contents
    In the second argument of `($)', namely
      `do { createDirectoryIfMissing True directory;
            writeFile (fpFromString $ directory ++ filename) contents }'

src/IHaskell/Eval/Evaluate.hs:566:40:
    Couldn't match type `FilePath' with `[Char]'
    Expected type: GHC.IO.FilePath
      Actual type: FilePath
    In the return type of a call of `fpFromString'
    In the second argument of `($)', namely `fpFromString filename'
    In a stmt of a 'do' block:
      contents <- readFile $ fpFromString filename
Failed to install ihaskell-0.6.0.0
cabal: Error: some packages failed to install:
ihaskell-0.6.0.0 failed during the building phase. The exception was:
ExitFailure 1

**Comment by sumitsahrawat** [comment]
That's strange. The version has been updated to `0.6.3.0`. Did you do a `git pull` first?
Also, if there is a pre-existing sandbox, you should remove it.

I do something like this for building in a sandbox:

```bash
cabal update ; cabal sandbox delete ; cabal sandbox init ; cabal install happy alex ; cabal install gtk2hs-buildtools ; cabal install cpphs ; ./build.sh ihaskell
```

**Comment by marmalodak** [comment]
Thanks for getting back to me.  This is where I am now.


+(bin/qa-ihaskell-build.bash:39): main(): git clone
http://www.github.com/gibiansky/IHaskell
Cloning into 'IHaskell'...
remote: Counting objects: 5055, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 5055 (delta 21), reused 0 (delta 0), pack-reused 4998
Receiving objects: 100% (5055/5055), 4.00 MiB | 3.19 MiB/s, done.
Resolving deltas: 100% (3033/3033), done.
Checking connectivity... done.
+(bin/qa-ihaskell-build.bash:40): main(): cd IHaskell
+(bin/qa-ihaskell-build.bash:41): main(): ./build.sh ihaskell
[1 of 1] Compiling Main             ( Setup.hs, dist/setup/Main.o )

Setup.hs:2:1: Warning:
    Module `System.Cmd' is deprecated: Use "System.Process" instead
Linking ./dist/setup/setup ...
cleaning...
cleaning...
cleaning...
CMD: cabal install --constraint arithmoi -llvm -j ./ghc-parser
./ipython-kernel ./. --force-reinstalls --max-backjumps=-1 --reorder-goals
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: ghc-parser-0.1.7.0
trying: base-4.6.0.1/installed-8aa...
trying: ihaskell-0.6.3.0
rejecting: classy-prelude-0.10.4/installed-721..., 0.12.0, 0.11.1.1, 0.11.1,
0.11.0 (conflict: ihaskell => classy-prelude>=0.10.5 && <0.11)
trying: classy-prelude-0.10.5
rejecting: mutable-containers-0.3.0 (conflict: classy-prelude =>
mutable-containers>=0.2 && <0.3)
rejecting: mutable-containers-0.2.1.2, 0.2.1.1, 0.2.1, 0.2.0.1, 0.2.0
(conflict: base==4.6.0.1/installed-8aa..., mutable-containers => base>=4.7
&&
<5)
rejecting: mutable-containers-0.1.2.0, 0.1.1.0, 0.1.0.0 (conflict:
classy-prelude => mutable-containers>=0.2 && <0.3)

**Comment by marmalodak** [comment]
To reduce uncertainty, I'm going to write a script to build this for me.
Here's what it looks like right now:

#!/bin/bash

set -e
set -x
set -u
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'


# yum groupinstall "Development Tools"
# yum install libquadmath-devel gcc-gfortran blas-devel lapack-dvel
# yum -y install libcurl-devel libmemcached libmemcached-devel

VENV=/e2e/ihaskell-venv
pyvenv-3.4 $VENV
set +u
source $VENV/bin/activate
set -u


(
    if [[ ! -r /e2e/lib/zeromq4/lib/libzmq.so.4.0.0 ]] ; then
        if [[ ! -r /e2e/Downloads/zeromq-4.0.5.tar.gz ]]; then
            mkdir -p /e2e/Downloads/zeromq4
            cd /e2e/Downloads/zeromq4
            wget http://download.zeromq.org/zeromq-4.0.5.tar.gz
        fi
        cd /e2e/Downloads/zeromq4
        tar xvzf zeromq-4.0.5.tar.gz
        cd zeromq-4.0.5/
        ./configure --prefix=/e2e/lib/zeromq4
        make && make install
    fi
)
cabal install happy cpphs
export
PKG_CONFIG_PATH=/e2e/lib/zeromq4/lib/pkgconfig:/e2e/lib/zeromq4/lib/pkgconfig:/usr/share/licenses/pkgconfig:/usr/share/pkgconfig:/usr/share/doc/pkgconfig
(
    cd /e2e/Downloads
    rm -rf /e2e/Downloads/IHaskell
    git clone http://www.github.com/gibiansky/IHaskell
    cd IHaskell
    ./build.sh ihaskell
)

pip -V
pip install numpy
pip install scipy

pip install -r /e2e/etc/qa-ihaskell-requirements.text

#cabal install ihaskell --reorder-goals
--extra-lib-dirs=/e2e/lib/zeromq4/lib
--extra-include-dirs=/e2e/lib/zeromq4/include
#cabal install ihaskell --reorder-goals

**Comment by marmalodak** [comment]
Oh, I had only 'build.sh' instead of './build.sh ihaskell', I changed it
based on your recommendation.

**Comment by sumitsahrawat** [comment]
> rejecting: classy-prelude-0.10.4/installed-721..., 0.12.0, 0.11.1.1, 0.11.1,
> 0.11.0 (conflict: ihaskell => classy-prelude>=0.10.5 && <0.11)
> trying: classy-prelude-0.10.5
> rejecting: mutable-containers-0.3.0 (conflict: classy-prelude =>
> mutable-containers>=0.2 && <0.3)
> rejecting: mutable-containers-0.2.1.2, 0.2.1.1, 0.2.1, 0.2.0.1, 0.2.0
> (conflict: base==4.6.0.1/installed-8aa..., mutable-containers => base>=4.7
> &&
> <5)
> rejecting: mutable-containers-0.1.2.0, 0.1.1.0, 0.1.0.0 (conflict:
> classy-prelude => mutable-containers>=0.2 && <0.3)

It seems like you have a pre-installed `classy-prelude`. As pointed in #495, IHaskell uses an old version, which is conflicting with the one you have installed (cabal hell?).

You should probably start with an empty sandbox, install the executable requirements (`alex`, `happy`, `gtk2hs-buildtools`), and then execute `./build.sh ihaskell` or `./build.sh all` according to your requirements.

**PS:** If you're able to create a working script for fedora, I'm sure @gibiansky will add be willing to add it to the repository.

**Comment by gibiansky** [comment]
Ugh. This is incredibly frustrating. @sumitsahrawat is right, both on the count of classy-prelude and the fedora script. 

I might try to upgrade to classy-prelude 0.12, but honestly I think it's probably time to migrate away from `classy-prelude`. I liked the idea of it but it's caused me so much grief and maintenance burden that I'm not sure it's worthwhile.

**Comment by marmalodak** [comment]
Which version of classy-prelude could I use?

This is the list of packages that yum installs when I issue just `yum install ghc cabal-install`:
    Installing : ghc-base-4.6.0.1-26.3.fc21.x86_64
    Installing : ghc-array-0.4.0.1-26.3.fc21.x86_64
    Installing : ghc-compiler-7.6.3-26.3.fc21.x86_64
    Installing : ghc-base-devel-4.6.0.1-26.3.fc21.x86_64
    Installing : ghc-deepseq-1.3.0.1-26.3.fc21.x86_64
    Installing : ghc-bytestring-0.10.0.2-26.3.fc21.x86_64
    Installing : ghc-old-locale-1.0.0.5-26.3.fc21.x86_64
    Installing : ghc-time-1.4.0.1-26.3.fc21.x86_64
    Installing : ghc-unix-2.6.0.1-26.3.fc21.x86_64
    Installing : ghc-containers-0.5.0.0-26.3.fc21.x86_64
    Installing : ghc-array-devel-0.4.0.1-26.3.fc21.x86_64
    Installing : ghc-filepath-1.3.0.1-26.3.fc21.x86_64
    Installing : ghc-directory-1.2.0.1-26.3.fc21.x86_64
    Installing : ghc-old-time-1.1.0.1-26.3.fc21.x86_64
    Installing : ghc-process-1.1.0.2-26.3.fc21.x86_64
    Installing : ghc-filepath-devel-1.3.0.1-26.3.fc21.x86_64
    Installing : ghc-deepseq-devel-1.3.0.1-26.3.fc21.x86_64
    Installing : ghc-containers-devel-0.5.0.0-26.3.fc21.x86_64
    Installing : ghc-pretty-1.1.1.0-26.3.fc21.x86_64
    Installing : ghc-transformers-0.3.0.0-35.fc21.x86_64
    Installing : ghc-mtl-2.1.2-29.fc21.x86_64
    Installing : ghc-bytestring-devel-0.10.0.2-26.3.fc21.x86_64
    Installing : ghc-old-locale-devel-1.0.0.5-26.3.fc21.x86_64
    Installing : ghc-time-devel-1.4.0.1-26.3.fc21.x86_64
    Installing : ghc-unix-devel-2.6.0.1-26.3.fc21.x86_64
    Installing : ghc-directory-devel-1.2.0.1-26.3.fc21.x86_64
    Installing : ghc-process-devel-1.1.0.2-26.3.fc21.x86_64
    Installing : ghc-text-0.11.3.1-4.fc21.x86_64
    Installing : ghc-parsec-3.1.3-32.fc21.x86_64
    Installing : ghc-old-time-devel-1.1.0.1-26.3.fc21.x86_64
    Installing : ghc-Cabal-1.16.0-26.3.fc21.x86_64
    Installing : ghc-pretty-devel-1.1.1.0-26.3.fc21.x86_64
    Installing : ghc-Cabal-devel-1.16.0-26.3.fc21.x86_64
    Installing : ghc-network-2.4.1.2-33.fc21.x86_64
    Installing : ghc-template-haskell-2.8.0.0-26.3.fc21.x86_64
    Installing : ghc-template-haskell-devel-2.8.0.0-26.3.fc21.x86_64
    Installing : ghc-hpc-0.6.0.0-26.3.fc21.x86_64
    Installing : ghc-hpc-devel-0.6.0.0-26.3.fc21.x86_64
    Installing : ghc-binary-0.5.1.1-26.3.fc21.x86_64
    Installing : ghc-binary-devel-0.5.1.1-26.3.fc21.x86_64
    Installing : ghc-hoopl-3.9.0.0-26.3.fc21.x86_64
    Installing : ghc-hoopl-devel-3.9.0.0-26.3.fc21.x86_64
    Installing : ghc-ghc-7.6.3-26.3.fc21.x86_64                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    Installing : ghc-ghc-devel-7.6.3-26.3.fc21.x86_64
    Installing : ghc-HTTP-4000.2.8-34.fc21.x86_64
    Installing : ghc-haskell98-2.0.0.2-26.3.fc21.x86_64
    Installing : ghc-haskell98-devel-2.0.0.2-26.3.fc21.x86_64
    Installing : ghc-random-1.0.1.1-28.fc21.x86_64
    Installing : ghc-zlib-0.5.4.1-29.fc21.x86_64
    Installing : ghc-doc-index-7.6.3-26.3.fc21.x86_64
    Installing : ghc-haskell2010-1.1.1.0-26.3.fc21.x86_64
    Installing : ghc-haskell2010-devel-1.1.1.0-26.3.fc21.x86_64
    Installing : ghc-libraries-7.6.3-26.3.fc21.x86_64
    Installing : ghc-7.6.3-26.3.fc21.x86_64
    Installing : cabal-install-1.16.0.2-36.fc21.x86_64

**Comment by sumitsahrawat** [comment]
You should give `ihaskell-0.6.2.0` a try. It's very likely that the issue is with your installation of ghc.
IHaskell builds with `ghc-7.6.3` but it's not supported officially. Most things don't work as you'd expect with that version.

For installing new versions of `ghc` on fedora, take a look at [this guide](https://github.com/bitemyapp/learnhaskell/blob/master/install.md#fedora-21). The instructions are for `ghc-7.8.3`, and they can be modified to work for `ghc-7.10.1` too. Both are supported by IHaskell.

**Comment by madjestic** [comment]
I have the same issue:
(ghc-7.8.4)
...
src/IHaskell/Eval/Evaluate.hs:406:16:
    Couldn't match expected type ‘FilePath’ with actual type ‘[Char]’
...

http://lpaste.net/133148

**Comment by sumitsahrawat** [comment]
@gibiansky It seems like this was introduced here https://github.com/gibiansky/IHaskell/commit/accbec475f3c854033aaf4b1fe64fc8146a3e165.

`classy-prelude-0.10.5` requires the conversions, whereas the higher versions (`>=0.11`) don't.

What would be preferable now? A temporary fix could be made by adding those conversions back, or we could go on and completely remove `classy-prelude`.

**Comment by sumitsahrawat** [comment]
@marmalodak @madjestic It should work now. Also, it won't even compile under `ghc-7.6.3` now.

**Comment by madjestic** [comment]
Thanks guys,

The fixes worked.

**Comment by gibiansky** [comment]
Thanks @sumitsahrawat!

**Comment by sumitsahrawat** [comment]
You're welcome. I'm glad it worked :+1:

**Comment by marmalodak** [comment]
What should the value of `PKG_CONFIG_PATH` be?  This is what I'm using:

    PKG_CONFIG_PATH=/e2e/lib/zeromq4/lib/pkgconfig:/e2e/lib/zeromq4/lib/pkgconfig:/usr/share/licenses/pkgconfig:/usr/share/pkgconfig:/usr/share/doc/pkgconfig

and I'm getting this:

    Loading package semigroups-0.16.2.2 ... linking ... done.
    Loading package zeromq4-haskell-0.6.3 ... <command line>: can't load .so/.DLL for:     /root/.cabal/lib/x86_64-linux-ghc-7.8.4/zeromq4-haskell-0.6.3/libHSzeromq4-haskell-0.6.3-ghc7.8.4.so     (libzmq.so.4: cannot open shared object file: No such file or directory)
    Failed to install ihaskell-0.6.3.0
    cabal: Error: some packages failed to install:
    ihaskell-0.6.3.0 failed during the building phase. The exception was:
    ExitFailure 1


Should this be a separate issue?

**Comment by sumitsahrawat** [comment]
It depends on where the `libzmq.so.4` file is. According to this [SO](http://stackoverflow.com/questions/1766380/determining-the-path-that-a-yum-package-installed-to) thread, you can use `rpm -ql <package-name>` to find where a package installs files.

**Comment by marmalodak** [comment]
Below is my install script in its current form.  It seems that I have to build libzmq myself.  I think that's why my installation is not working.  

    #!/bin/bash

    set -e
    set -x
    set -u
    export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'


    (
        ghc="$(rpm -q ghc 2>&1 | cut -c1-9)"
        if [[ ${ghc} != "ghc-7.8.4" ]] ; then
            yum-config-manager --add-repo https://copr.fedoraproject.org/coprs/petersen/ghc-7.8.4/repo/fedora-21/petersen-ghc-7.8.4-fedora-21.repo
            yum -y remove \*ghc\* cabal-install
            yum -y install ghc cabal-install
        fi
        ghc="$(rpm -q ghc 2>&1 | cut -c1-9)"
        if [[ ${ghc} != "ghc-7.8.4" ]] ; then
            echo "Uniinstall anything before ghc-7.8.4"
            echo "Install ghc-7.8.4 or later"
            exit 1
        fi
    )

    (
        set +x
        rpms='ghc cabal-install libquadmath-devel gcc-gfortran blas-devel lapack-devel libcurl-devel libmemcached libmemcached-devel'
        error=0
        for i in $rpms; do
            set +e
            rpm -q $i
            status=$?
            set -e
            if [[ $status -ne 0 ]]; then
                error=1
            fi
            if [[ $error -ne 0 ]]; then
                echo "$i is not installed"
                echo 'gcc et al must be installed, i.e. yum groupinstall "Development Tools"'
                exit 1
            fi
        done
        set -x
    )

    VENV=/e2e/ihaskell-venv
    set +u
    rm -rf $VENV
    set -u
    pyvenv-3.4 $VENV
    set +u
    source $VENV/bin/activate
    set -u


    (
        set +u
        rm -rf ~/.ghc ~/.cabal
        set +u
        cabal update
        cabal install happy cpphs
        #cabal install happy cpphs --constraint='classy-prelude < 0.12'
    )
    (
        if [[ ! -r /e2e/lib/zeromq4/lib/libzmq.so.4.0.0 ]] ; then
            if [[ ! -r /e2e/Downloads/zeromq-4.0.5.tar.gz ]]; then
                mkdir -p /e2e/Downloads/zeromq4
                cd /e2e/Downloads/zeromq4
                wget http://download.zeromq.org/zeromq-4.0.5.tar.gz
            fi
            cd /e2e/Downloads/zeromq4
            tar xvzf zeromq-4.0.5.tar.gz
            cd zeromq-4.0.5/
            ./configure --prefix=/e2e/lib/zeromq4
            make && make install
        fi
    )
    export PKG_CONFIG_PATH=/e2e/lib/zeromq4/lib/pkgconfig:/e2e/lib/zeromq4/lib/pkgconfig:/usr/share/licenses/pkgconfig:/usr/share/pkgconfig:/usr/share/doc/pkgconfig
    (
        export PKG_CONFIG_PATH=/e2e/lib/zeromq4/lib/pkgconfig:/e2e/lib/zeromq4/lib/pkgconfig:/usr/share/licenses/pkgconfig:/usr/share/pkgconfig:/usr/share/doc/pkgconfig
        cd /e2e/Downloads
        rm -rf /e2e/Downloads/IHaskell
        git clone http://www.github.com/gibiansky/IHaskell
        cd IHaskell
        ./build.sh ihaskell
    )

    pip -V
    #pip install numpy
    #pip install scipy

    pip install -r /e2e/etc/qa-ihaskell-requirements.text
