### ISSUE TITLE
is ihaskell-widgets functional ?

### ISSUE THREAD

**Issue by miguel-negrao** [gibiansky/IHaskell#493]
Specifically, does the slider widget work ? Is there code example of usage somewhere ?

**Comment by gibiansky** [comment]
`ihaskell-widgets` was a playground for experimentation with widgets; there is no functional widgets functionality at the moment. It should probably be removed from the repository so as not to be confusing.

@sumitsahrawat is working with me for Google Summer of Code this summer to implement full support for IPython's widgets, so hopefully this will be rectified soon!

**Comment by miguel-negrao** [comment]
Great, I look forward to it.
