### ISSUE TITLE
Please update ihaskell to recent versions its dependencies

### ISSUE THREAD

**Issue by peti** [gibiansky/IHaskell#495]
http://packdeps.haskellers.com/feed?needle=exact%3Aihaskell

We are interested in support for `classy-prelude-0.12.0` in particular, because that dependency is preventing us from building `ihaskell` in NixOS at the moment.

**Comment by gibiansky** [comment]
Does NixOS build from Hackage? Now that IHaskell no longer depends on classy-prelude, do I need to make a new release to make ihaskell nisox-compatible?

**Comment by peti** [comment]
Yes, we build from Hackage. A new release would be very much appreciated.

**Comment by gibiansky** [comment]
Finally done. See [`ihaskell-0.6.4.0`](https://hackage.haskell.org/package/ihaskell).
