### ISSUE TITLE
ihaskell-0.6.2.0 broken with ghc-7.10.1

### ISSUE THREAD

**Issue by sumitsahrawat** [gibiansky/IHaskell#496]
`ihaskell-0.6.2.0` doesn't build using `ghc-7.10.1`, with `ghc-parser-0.1.6.0`. The dependencies should be changed to `ghc-parser >=0.1.7.0`.

**Comment by gibiansky** [comment]
Fixed I believe in 0.6.3 and up.

**Comment by sumitsahrawat** [comment]
You just have to go to the hackage page for ihaskell, and change the package metadata for version `0.6.2.0`.
This will make a version which may or may not work with `ghc-7.10`, to work surely.

**Comment by gibiansky** [comment]
Fair enough. Updated to remove support for ghc 7.10 in 0.6.2, just in case.
