### ISSUE TITLE
ipython-kernel-0.6.1.0 depends on zeromq4-haskell-0.6.3 which failed to install.

### ISSUE THREAD

**Issue by marmalodak** [gibiansky/IHaskell#500]
I upgraded to Fedora 22.  zeromq4 is available but the package is simply called `zeromq`.  The older versions are called `zeromq3` and `zeromq2`.  

    Preprocessing library classy-prelude-0.10.5...
    [1 of 1] Compiling ClassyPrelude    ( ClassyPrelude.hs, dist/build/ClassyPrelude.o )

    ClassyPrelude.hs:35:7: Warning:
        ‘PrimMonad’ is exported by ‘PrimMonad’ and ‘module Data.Mutable’

    ClassyPrelude.hs:36:7: Warning:
        ‘PrimState’ is exported by ‘PrimState’ and ‘module Data.Mutable’

    ClassyPrelude.hs:41:7: Warning:
        ‘Prim’ is exported by ‘Prim’ and ‘module Data.Mutable’

    ClassyPrelude.hs:220:1: Warning:
        The import of ‘PrimState, PrimMonad’
        from module ‘Control.Monad.Primitive’ is redundant

    ClassyPrelude.hs:222:1: Warning:
        The import of ‘Data.Primitive.Types’ is redundant
          except perhaps to import instances from ‘Data.Primitive.Types’
        To import instances alone, use: import Data.Primitive.Types()
    In-place registering classy-prelude-0.10.5...
    Installing library in
    /root/.cabal/lib/x86_64-linux-ghc-7.8.4/classy-prelude-0.10.5
    Registering classy-prelude-0.10.5...
    Installed classy-prelude-0.10.5
    cabal: Error: some packages failed to install:
    ihaskell-0.6.3.0 depends on zeromq4-haskell-0.6.3 which failed to install.
    ipython-kernel-0.6.1.0 depends on zeromq4-haskell-0.6.3 which failed to
    install.
    zeromq4-haskell-0.6.3 failed during the configure step. The exception was:
    ExitFailure 1
    (ihaskell-venv) [root@qa-notebook ~]# rpm -q zeromq
    zeromq-4.0.5-1.fc22.x86_64
    (ihaskell-venv) [root@qa-notebook ~]# rpm -q ghc cabal-install
    ghc-7.8.4-44.fc22.x86_64
    cabal-install-1.18.0.8-1.fc22.x86_64

**Comment by marmalodak** [comment]
I've revised my install script to just this.


    #!/bin/bash

    set -e
    set -x
    set -u
    export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'


    if [[ \"$(cat /etc/redhat-release)\" != "Fedora release 22 (Twenty Two)" ]]; then
        echo "This will not work on Fedora 21 because zeromq is old and because ghc >= 7.8.4 is required"
    fi

    (
        set +x
        rpms='ghc-7.8.4 zeromq cabal-install libquadmath-devel gcc-gfortran blas-devel lapack-devel libcurl-devel libmemcached libmemcached-devel'
        error=0
        for i in $rpms; do
            set +e
            rpm -q $i
            status=$?
            set -e
            if [[ $status -ne 0 ]]; then
                error=1
            fi
            if [[ $error -ne 0 ]]; then
                echo "$i is not installed"
                echo 'gcc et al must be installed, i.e. yum groupinstall "Development Tools"'
                exit 1
            fi
        done
        set -x
    )

    VENV=/e2e/ihaskell-venv
    set +u
    rm -rf $VENV
    set -u
    pyvenv-3.4 $VENV
    set +u
    source $VENV/bin/activate
    set -u


    (
        set +u
        rm -rf ~/.ghc ~/.cabal
        set +u
        cabal update
        cabal install happy cpphs
    )

    if [[ 0 ]]; then
    (
        if [[ ! -r /e2e/lib/zeromq4/lib/libzmq.so.4.0.0 ]] ; then
            if [[ ! -r /e2e/Downloads/zeromq-4.0.5.tar.gz ]]; then
                mkdir -p /e2e/Downloads/zeromq4
                cd /e2e/Downloads/zeromq4
                wget http://download.zeromq.org/zeromq-4.0.5.tar.gz
            fi
            cd /e2e/Downloads/zeromq4
            tar xvzf zeromq-4.0.5.tar.gz
            cd zeromq-4.0.5/
            ./configure --prefix=/e2e/lib/zeromq4
            make && make install
        fi
    )
    fi

    (
        cd /e2e/Downloads
        rm -rf /e2e/Downloads/IHaskell
        git clone http://www.github.com/gibiansky/IHaskell
        cd IHaskell
        ./build.sh ihaskell
    )

    pip -V
    pip install -r /e2e/etc/qa-ihaskell-requirements.text

**Comment by gibiansky** [comment]
You may need to use the `--extra-include-dirs` and `--extra-lib-dirs` arguments to `cabal` to tell it where to find zeromq include files and libraries. To do so `cabal install zeromq4-haskell` separately, before the `build.sh` invocation.

**Comment by marmalodak** [comment]
My fault.  I had neglected to install zeromq-devel.
