### ISSUE TITLE
`build.sh ihaskell` succeeds but `build.sh all` fails on fedora 22

### ISSUE THREAD

**Issue by marmalodak** [gibiansky/IHaskell#501]
In-place registering ihaskell-parsec-0.2.1.0...
    Installing library in
    /root/.cabal/lib/x86_64-linux-ghc-7.8.4/ihaskell-parsec-0.2.1.0
    Registering ihaskell-parsec-0.2.1.0...
    Installed ihaskell-parsec-0.2.1.0
    Configuring ihaskell-static-canvas-0.1.0.0...
    Building ihaskell-static-canvas-0.1.0.0...
    Preprocessing library ihaskell-static-canvas-0.1.0.0...
    [1 of 1] Compiling IHaskell.Display.StaticCanvas ( src/IHaskell/Display/StaticCanvas.hs, dist/build/IHaskell/Display/StaticCanvas.o )
    In-place registering ihaskell-static-canvas-0.1.0.0...
    Installing library in
    /root/.cabal/lib/x86_64-linux-ghc-7.8.4/ihaskell-static-canvas-0.1.0.0
    Registering ihaskell-static-canvas-0.1.0.0...
    Installed ihaskell-static-canvas-0.1.0.0
    Configuring ihaskell-widgets-0.1.0.0...
    Building ihaskell-widgets-0.1.0.0...
    Preprocessing library ihaskell-widgets-0.1.0.0...
    [1 of 2] Compiling IHaskell.Widgets ( IHaskell/Widgets.hs, dist/build/IHaskell/Widgets.o )
    [2 of 2] Compiling IHaskell.Display.Widgets ( IHaskell/Display/Widgets.hs, dist/build/IHaskell/Display/Widgets.o )
    In-place registering ihaskell-widgets-0.1.0.0...
    Installing library in
    /root/.cabal/lib/x86_64-linux-ghc-7.8.4/ihaskell-widgets-0.1.0.0
    Registering ihaskell-widgets-0.1.0.0...
    Installed ihaskell-widgets-0.1.0.0
    Configuring ihaskell-rlangqq-0.2.2.0...
    Building ihaskell-rlangqq-0.2.2.0...
    Preprocessing library ihaskell-rlangqq-0.2.2.0...
    [1 of 1] Compiling IHaskell.Display.Rlangqq ( IHaskell/Display/Rlangqq.hs, dist/build/IHaskell/Display/Rlangqq.o )
    In-place registering ihaskell-rlangqq-0.2.2.0...
    Installing library in
    /root/.cabal/lib/x86_64-linux-ghc-7.8.4/ihaskell-rlangqq-0.2.2.0
    Registering ihaskell-rlangqq-0.2.2.0...
    Installed ihaskell-rlangqq-0.2.2.0
    cabal: Error: some packages failed to install:
    Chart-cairo-1.4 depends on cairo-0.13.1.0 which failed to install.
    cairo-0.13.1.0 failed during the configure step. The exception was:
    ExitFailure 1
    diagrams-cairo-1.3.0.1 depends on glib-0.13.1.0 which failed to install.
    glib-0.13.1.0 failed during the configure step. The exception was:
    ExitFailure 1
    ihaskell-charts-0.2.1.0 depends on cairo-0.13.1.0 which failed to install.
    ihaskell-diagrams-0.2.2.0 depends on glib-0.13.1.0 which failed to install.
    ihaskell-magic-0.2.0.0 depends on magic-1.1 which failed to install.
    ihaskell-plot-0.2.0.0 depends on glib-0.13.1.0 which failed to install.
    magic-1.1 failed during the configure step. The exception was:
    ExitFailure 1
    pango-0.13.1.0 depends on glib-0.13.1.0 which failed to install.
    plot-0.2.3.4 depends on glib-0.13.1.0 which failed to install.

**Comment by sumitsahrawat** [comment]
That's issues with `cairo` and `glib`. Try `cabal install gtk2hs-buildtools && ./build.sh all`.

**Comment by marmalodak** [comment]
What is `alex`?

        SPECIALISE pragma on INLINE function probably won't fire: ‘mapM_’
    In-place registering hashtables-1.2.0.2...
    Installing library in
    /root/.cabal/lib/x86_64-linux-ghc-7.8.4/hashtables-1.2.0.2
    Registering hashtables-1.2.0.2...
    Installed hashtables-1.2.0.2
    Downloading gtk2hs-buildtools-0.13.0.3...
    Configuring gtk2hs-buildtools-0.13.0.3...
    cabal: The program alex version >=3.0.1 is required but it could not be found.
    Failed to install gtk2hs-buildtools-0.13.0.3
    cabal: Error: some packages failed to install:
    gtk2hs-buildtools-0.13.0.3 failed during the configure step. The exception
    was:
    ExitFailure 1

**Comment by gibiansky** [comment]
Alex is a lexer generator (and Happy is a parser generator); Haskell equivalents of lex and bison. Used for parsing programming languages.
