### ISSUE TITLE
Show debug messages in Notebook

### ISSUE THREAD

**Issue by aueelis** [gibiansky/IHaskell#511]
While using the Debug module, I noticed that my trace messages don't show up in the Notebook, but in the system log (Jupyter is running as a service). So, this is more or less a feature request to reach the debug messages faster and to not clutter the log.

Example:

```
import Debug.Trace
trace "test" 5
```

This produces the output "5" in the notebook and the message "test" in my system log.
##

**Comment by gibiansky** [comment]
Yes, `stderr` messages don't show up. This is a bug that should be relatively easy to fix – `capturedStatement` in `Evaluate.hs` needs to be generalized to capture `stderr` as well as `stdout`. Good thing to fix.

**Comment by orome** [comment]
It would be great to have this. Another item that falls (along with, e.g., #559, #362, and #585)  into the category of things helpful for the common IHaskell use case: learning and experimenting with Haskell.

**Comment by rattrayalex** [comment]
+1

**Comment by vaibhavsagar** [comment]
Closed by #1060.
