### ISSUE TITLE
Newlines not printed as newlines

### ISSUE THREAD

**Issue by arnetheduck** [gibiansky/IHaskell#512]
If I try to print a newline character, it'll be printed as `\n`, making it hard to format output.
Compare the following, which shows IPython and IHaskell:
```
(foo) [~/src/foo]$ ipython console --kernel=Haskell
IPython Console 3.1.0

In [1]: print "hello\nthere"
"hello\nthere"


In [2]: 
Do you really want to exit ([y]/n)? y
(foo) [~/src/foo]$ ipython console
IPython Console 3.1.0

In [1]: print("hello\nthere")
hello
there

In [2]: 
```

**Comment by arnetheduck** [comment]
Ah, there's a workaround:
```
In [1]: putStr "hello\nthere"
hello
there
```
not sure what the right thing is then - keeping similar to IPython or keeping current behaviour which might make more sense (?) for haskell..

**Comment by sumitsahrawat** [comment]
```haskell
print :: Show a => a -> IO ()
print = putStrLn . show
```

It is supposed to work that way.

`print` prints the string representation of anything, whereas `putStrLn`/`putStr` actually print strings to the screen.
