### ISSUE TITLE
Running under ipython kernel

### ISSUE THREAD

**Issue by rrottier** [gibiansky/IHaskell#522]
I am trying to run ipython in the headless mode with ihaskell.  From what I could figure out from the documentation to do this I need to run:

`ipython kernel --IPKernelApp.kernel_class=<class name of IHaskell kernel>`

For ipython the kernel is:
` 'IPython.kernel.zmq.ipkernel.Kernel' `

What is the equivalent for IHaskell?

**Comment by gibiansky** [comment]
If you have a `profile.json` with things like port and so on, you can use `ihaskell kernel <profile.json>`. There's no Python class that corresponds to the IHaskell kernel as far as I know... but there might be a generic `Kernel` class that's parameterized on the kernel executable. 

This is probably a question for the IPython team, actually. @Carreau might be able to answer it, or perhaps just the IPython mailing list would be a better bet. (Sorry!)

**Comment by Carreau** [comment]
What do you mean in "headless mode" ? 

`ipython kernel <something>` is actually used to launch the **python** kernel, it is not what is used to launch other languages. 

nbconvert is capable of executing the notebook in a headless manner, see how this is done [here](https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/execute.py#L67-L88)  

the km (kernel manager) and kc (kernel Channel manager IIRC) are the things that communicate with teh kernel and that you probably want to poke around to do custom "headless" execution. 

Does that make sens ? (you can of course also ask on jupyter or IPython ML to get more people to respond help you)

**Comment by rrottier** [comment]
I am trying to replicate what Greg Sexton has done with this org-mode plugin for ipython (https://github.com/gregsexton/ob-ipython) with ihaskell.  Greg uses

`ipython kernel —IPKernelApp.connection_file=<session-name.json>`

To start a new kernel and generate a file making it easy to have track multiple kernels inside a single org mode document.  Each code segment is identified with a session parameter and he then uses a python driver file to communicate with the various kernels using the <session-name.json> to uniquely identify them.  While there could be other approaches, like that used by EIN (https://github.com/tkf/emacs-ipython-notebook) what I like about Greg’s approach is that emacs does the process management by using the command above to start the kernels and tracking the various running sessions.

I was hoping to re-use as much as possible of his code since both my python and elisp is rather weak.  However to do that I need be able to replicate what the ipython kernel command is doing.  Using

`ihaskell kernel <session-name.json>` 

works, but it requires an existing session.  Which limits me either using a library of pre-creates session or using the ipython command to start the session, then terminating it and re-using the file.

Using the python method in nbconvert works as well but I think that to use it with multiple session would mean re-implementing the process management in a python driver file which at the moment is beyond my meagre skills.

Not sure if this triggers any other ideas that I could try.  If not could you suggest which jupyter or ipython list I could try?  Just the github issues or is the an active google group or chatroom?

-- 
Riaan Rottier

On 4 July 2015 at 1:37:28 am, Matthias Bussonnier (notifications@github.com) wrote:

What do you mean in "headless mode" ?

ipython kernel <something> is actually used to launch the python kernel, it is not what is used to launch other languages.

nbconvert is capable of executing the notebook in a headless manner, see how this is done here

the km (kernel manager) and kc (kernel Channel manager IIRC) are the things that communicate with teh kernel and that you probably want to poke around to do custom "headless" execution.

Does that make sens ? (you can of course also ask on jupyter or IPython ML to get more people to respond help you)
