### ISSUE TITLE
Is it possible to build/install IHaskell on a mac without xquartz, etc?

### ISSUE THREAD

**Issue by radix** [gibiansky/IHaskell#530]
I would like to install IHaskell to use with the Atom editor and its Hydrogen package which allows in-editor evaluation of expressions via Jupyter. However, installing IHaskell and all of its dependencies is really difficult on a mac, and I don't really want or need XQuartz and the image processing and font systems. I'd like to be able to just get basic code-evaluation support. Is there a way to build or install IHaskell without all of these dependencies?

I see that `build.sh` takes some parameters that determine which dependencies to use, but the `macos-install.sh` script doesn't.

**Comment by gibiansky** [comment]
You can install just IHaskell without any of the components with `./build.sh ihaskell`.
