### ISSUE TITLE
Could IHaskell installation scripts use a sandbox instead of installing cabal packages globally?

### ISSUE THREAD

**Issue by radix** [gibiansky/IHaskell#531]
Installing cabal packages globally (even if "globally" means "for a user") is pretty dangerous and can lead to problems with "Cabal Hell". It'd be nice if the installation scripts created and used a sandbox for installing cabal packages into.

**Comment by sumitsahrawat** [comment]
Generally, it is understood that cabal invocations, such as `cabal install` use a sandbox if present and install into the global environment otherwise.

The scripts work similarly. I personally have a sandbox in the IHaskell repo, and it's also already present in the `.gitignore` file.

**Comment by radix** [comment]
yeah, I'm just suggesting that the scripts set one up if not already there, since they are meant to be end-user facing and the documentation just says "run the script to install IHaskell", so it'd be nice if they avoided "infecting" the user's system.

I also notice that `stack.yaml` was recently added to the repository... If the scripts were updated to use stack to build stuff then I guess this point would be moot.

**Comment by radix** [comment]
Oh, hold the phone, I just noticed the mention of sandboxes in the README. Somehow I missed them before. Anyway, I guess this ticket could be closed, *or* it could be a request for the shell scripts to set up a sandbox by default instead of making the user run some commands manually :)

**Comment by gibiansky** [comment]
Hmm, good points. I personally also use sandboxes – my main worry with switching the main install scripts to them is that afterwards you cannot delete the `ihaskell` directory, which the user may want to do. Switching to `stack` is definitely an idea for the longer term – I haven't used it yet myself but intend to soon.
