### ISSUE TITLE
Irrefutable pattern Message/Parser.hs line 58

### ISSUE THREAD

**Issue by radix** [gibiansky/IHaskell#532]
Trying to run IHaskell with Atom / Hydrogen. Running it through `ipython console --kernel haskell` seems to work, but when I try to evaluate a simple assignment in Atom/Hydrogen, I notice this error in the console:

```
kernel process received on stderr: ihaskell: src/IHaskell/IPython/Message/Parser.hs:(58,5)-(63,51): Irrefutable pattern failed for pattern Success (messageType,
                                                               username,
                                                               messageUUID,
                                                               sessionUUID)
```

I don't know if this is helpful, but I see this log message from Hydrogen right before that:

```
["<IDS|MSG>", "", "{"msg_id":"execute_3d19345d-5276-43da-8b45-4134979…":0,"msg_type":"execute_request","version":"5.0"}", "{}", "{}", "{"code":"x = 2","silent":false,"store_history":true,"user_expressions":{},"allow_stdin":false}"]
```

This may also be useful: the way that Hydrogen is launching IHaskell:

```
launching kernel: /Users/radix/Projects/IHaskell/.cabal-sandbox/bin/ihaskell ["kernel", "/Users/radix/.atom/packages/Hydrogen/kernel-configs/kernel-1e0bd2f9-92d3-4a16-a65c-09100d5cba03.json", "--ghclib", "/usr/local/Cellar/ghc/7.10.1/lib/ghc-7.10.1"]
```

**Comment by gibiansky** [comment]
Try running `ihaskell install --debug` first – this should tell IHaskell to print a lot of debug info to the console. 

If you do that, do you get any more debug dump info?

**Comment by radix** [comment]
Ok @gibiansky I did  that. I'm not totally sure if this is new output but after doing this I also saw this in the console. Doesn't look like it has anything interesting but I don't know:

```
kernel process received on stdout: Header: {"msg_id":"execute_58905133-a261-4f52-ad29-9e2f84517895","username":"","session":0,"msg_type":"execute_request","version":"5.0"}
Content: {"code":"x = 2","silent":false,"store_history":true,"user_expressions":{},"allow_stdin":false}
```

Followed by the same irrefutable pattern on stderr.

**Comment by gibiansky** [comment]
I think it's because Atom doesn't provide a `username` or `session` field.

**Comment by radix** [comment]
Is that a bug I should file against Hydrogen? or should handling lack of username/session be handled by Haskell?

**Comment by gibiansky** [comment]
Wait, perhaps not. They seem to exist on the kernel process received on stdout, but not in the original log message from Hydrogen. So perhaps hydrogen inserts them afterwards.

**Comment by gibiansky** [comment]
Ah, I think I see what's going on. The message and session IDs need to be valid UUIDs. IPython doesn't enforce this, but IHaskell requires them to at least be *strings*. This is a bug in Hydrogen, as they don't follow the message spec detailed [here](https://ipython.org/ipython-doc/dev/development/messaging.html#the-wire-protocol).

That said it's easy to accommodate this in IHaskell. I would accept a PR that allows numbers for UUIDs I guess; see `UUID.hs`.

**Comment by radix** [comment]
So, to be clear, it seems that Hydrogen is sending `msg_id` as a string, but not a UUID. And worse, it's sending `session` as a number (0) instead of a string (containing a UUID), right? I just want to make sure so I can file a bug with them.

**Comment by gibiansky** [comment]
Both of these are technically not allowed and should be valid UUIDs. `msg_id` is _almost_ a valid UUID, I think, except the `execute_` prefix, perhaps. `sessions` is sent as a number.

IHaskell allows any string to be used as a UUID, which is actually slightly more general than the messaging spec says it should be.

**Comment by gibiansky** [comment]
So for the purposes of getting this fixed: `session` needs to be a String, not a number.

That said this is just my guess at the solution based on rereading the parsing code and looking at that request. No 100% guarantees that that's the *only* issue, though.

**Comment by radix** [comment]
@gibiansky turns out you're right: I've fixed it in Hydrogen and filed a PR with them. Thanks for helping me debug this :) I can at least run "x = 1" and evaluate "x" to get back 1 now :)

**Comment by gibiansky** [comment]
Great!
