### ISSUE TITLE
Using stack with IHaskell

### ISSUE THREAD

**Issue by codygman** [gibiansky/IHaskell#533]
Is it currently supported? Perhaps I could simply change cabal invocations to stack invocations? I'm guessing it's a bit more involved than that?

**Comment by gibiansky** [comment]
I got a PR for it a few days ago, check out stack.yaml and the README. It should work but I haven't tried it.

**Comment by codygman** [comment]
Checking it out now... can't believe I missed that. I searched the open/closed issues and looked through the readme... but didn't read the most recent commit message :S

**Comment by codygman** [comment]
I didn't get to finish checking if it worked, I hope to be able to get to it tomorrow lest I forget about it :S

**Comment by hans25041** [comment]
I just successfully installed with stack, but I had to add `- hfsevents-0.1.5` to the `extra-deps` in `stack.yaml`.

**Comment by shaydon** [comment]
You need to run it via stack (in your build directory) so that it can find its libraries:
```bash
stack exec ipython -- console --kernel haskell
```
(Mentioned in the README.)

**Comment by hans25041** [comment]
Right. Sorry about that. I opened a [PR](https://github.com/gibiansky/IHaskell/pull/537) for the missing hfsevents-0.1.5.

**Comment by gibiansky** [comment]
Stack is now definitely supported (I have switched over to using it). I'm not sure whether `hfsevents` was necessary, I did not need it. Perhaps it got added to Stackage recently...
