### ISSUE TITLE
resource vanished (Broken Pipe)

### ISSUE THREAD

**Issue by rocurley** [gibiansky/IHaskell#538]
Whenever I run certain commands in IHaskell, I reliably get some error about broken pipes. Two reliable examples:

```
In [1]:
import Test.QuickCheck

In [2]:
quickCheck (1==1)
: hFlush: resource vanished (Broken pipe)
```

```
In [1]:
:ext RankNTypes
type A a= Functor f => f a
: hPutChar: resource vanished (Broken pipe)
```

Possibly relevant: I'm using ghc 7.10.

If you're having trouble reproducing this, I've got a [vagrant configuration](https://github.com/rocurley/hs-vagrant) that should get IHaskell running exactly as I have it on port 8888 just by running:

```
git clone https://github.com/rocurley/hs-vagrant.git
vagrant up
```

(And then waiting about an hour).
##

**Comment by sumitsahrawat** [comment]
@rocurley Is this still relevant with the latest version?

**Comment by vaibhavsagar** [comment]
I'm not seeing this with the latest IHaskell, please reopen if required.
