### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by sw1sh** [gibiansky/IHaskell#546]
Would love to see UTF-8 support in ihaskell output cells. It just requires some pretty printer wrapper like described in this [answer](http://stackoverflow.com/a/13113906/1694636) for the same problem with ghci. I've already tried to fix it myself, by changing every `show` in IHaskell.Display.Basic instance. But it didn't fix the issue. I'm guessing some other instance is responsible for the output. Just point me at it and I will pull request myself :)

**Comment by sumitsahrawat** [comment]
It seems like [this](https://github.com/gibiansky/IHaskell/blob/master/src/IHaskell/Types.hs#L56-L64) is what you're looking for.

**Comment by sw1sh** [comment]
But for what type I should write an instance for? I already tried to change `instance Show a => IHaskellDisplay (Maybe a) where` from `IHaskell/ihaskell-display/ihaskell-basic/IHaskell/Display/Basic.hs`, and it didn't work.

**Comment by gibiansky** [comment]
I don't think this is a display instance issue... I think this is just an issue with encodings as data goes from kernel to ipython. Is this an issue with e.g. Putstrln? Because that is just stdout to kernel directly, so is an issue with iHaskell internals. (Sry phone)

**Comment by sw1sh** [comment]
Normal output contains characters escaped `"\1092\1099\1074\1072"` and `putStrLn` prints gibberish. So I think it is both, a problem with IHaskell.Display and encodings.

**Comment by gibiansky** [comment]
Putstrln output doesn't go through the display mechanism. Stuff output to stdout is captured and sent separately

**Comment by gibiansky** [comment]
Check out capturedStmt in util.hs or evaluate.hs for the start point

**Comment by gibiansky** [comment]
This is done now.

**Comment by gasparka** [comment]
Standard cell output can't print unicode, while `putStrLn` can:
![Screenshot_2019-04-04_13-46-33](https://user-images.githubusercontent.com/16946258/55549639-01d5df00-56df-11e9-8930-958faf2431b2.png)

I think this issue should be reopened.
