### ISSUE TITLE
ihaskell-0.6.4.1: Module ‘IHaskell.IPython.Types’ does not export ‘showMessageType’

### ISSUE THREAD

**Issue by juhp** [gibiansky/IHaskell#548]
ihaskell-0.6.4.1 fails to build in Stackage Nightly:

```
[14 of 24] Compiling IHaskell.Eval.Hoogle ( src/IHaskell/Eval/Hoogle.hs, dist/build/IHaskell/Eval/Hoogle.o )

src/IHaskell/Eval/Hoogle.hs:59:59: Warning:
    In the use of ‘withManager’
    (imported from Network.HTTP.Client, but defined in http-client-0.4.19:Network.HTTP.Client.Manager):
    Deprecated: "Use newManager instead"
:
[19 of 24] Compiling IHaskell.Eval.Widgets ( src/IHaskell/Eval/Widgets.hs, dist/build/IHaskell/Eval/Widgets.o )

src/IHaskell/Eval/Widgets.hs:26:42:
    Module ‘IHaskell.IPython.Types’ does not export ‘showMessageType’
```

**Comment by gibiansky** [comment]
Damn. I'll fix this in about six hours. Sorry. I know what's going on, I didn't upload new versions of all the packages, and it builds with master but not hackage.

**Comment by juhp** [comment]
Thanks, I temporarily disabled ihaskell again for the nightly stackage build (also inadvertently the new packages you added).

**Comment by gibiansky** [comment]
I pushed a new version of `ipython-kernel` -- could you rerun the build to find out if IHaskell builds now? It should...

**Comment by juhp** [comment]
It did thanks however there testcase failures - I will open a separate ticket for those now.

**Comment by juhp** [comment]
However there was a haddock error for ipython-kernel-0.6.1.1:

```
src/IHaskell/IPython/ZeroMQ.hs:146:23:
    parse error on input ‘-- ^ HMAC encryption key’
```

**Comment by gibiansky** [comment]
This is fixed in the newest version of ipython-kernel, 0.6.1.2.

**Comment by juhp** [comment]
Nice
