### ISSUE TITLE
Error installing zeromq4

### ISSUE THREAD

**Issue by wyager** [gibiansky/IHaskell#554]
$ cabal install ihaskell --reorder-goals
    blah blah blah...
    cabal: Error: some packages failed to install:
    ihaskell-0.6.4.1 depends on zeromq4-haskell-0.6.3 which failed to install.
    ipython-kernel-0.6.1.2 depends on zeromq4-haskell-0.6.3 which failed to
    install.
    zeromq4-haskell-0.6.3 failed during the configure step. The exception was:
    ExitFailure 1

Let's try it manually...

    $ cabal install zeromq4-haskell-0.6.3
    Resolving dependencies...
    Configuring zeromq4-haskell-0.6.3...
    Failed to install zeromq4-haskell-0.6.3
    Build log ( /Users/williamyager/.cabal/logs/zeromq4-haskell-0.6.3.log ):
    Configuring zeromq4-haskell-0.6.3...
    setup-Simple-Cabal-1.22.4.0-x86_64-osx-ghc-7.10.2: The program 'pkg-config'
    version >=0.9.0 is required but it could not be found.
    cabal: Error: some packages failed to install:
    zeromq4-haskell-0.6.3 failed during the configure step. The exception was:
    ExitFailure 1

**Comment by gibiansky** [comment]
This isn't an IHaskell issue, but it's one that comes up fairly frequently -- perhaps the answer should be in the FAQ or something...

If you're using Homebrew, install `pkg-config` via `brew install pkg-config` and then verify that it exists with `which pkg-config` (which should give you a path). Once you do that, does the install work?

**Comment by wyager** [comment]
That fixed it! Yes, it would be great if that was in the ``Installing Manually`` section. Thanks for the help.
