### ISSUE TITLE
bin-package-db-0.0.0.0 not found when building with stack?

### ISSUE THREAD

**Issue by erantapaa** [gibiansky/IHaskell#555]
I'm trying to build IHaskell using `stack` and I'm getting this error:

~~~
$ stack install
NOTE: the install command is functionally equivalent to 'build --copy-bins'
Didn't see bin-package-db-0.0.0.0 in your package indices. Updating and trying again.
Fetched package index.
Populated index cache.
The following package identifiers were not found in your indices: bin-package-db-0.0.0.0
~~~

Some more info:

~~~
$ stack --version
Version 0.1.3.1

$ stack exec ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 7.10.2

$ git log | head -4
commit 35e469d115c2e94f3effbbd033f094aca76c98fa
Author: Andrew Gibiansky <andrew.gibiansky@gmail.com>
Date:   Mon Aug 17 01:25:33 2015 -0700

~~~

**Comment by gibiansky** [comment]
Are you using the `stack.yaml` from `IHaskell`? With
```
resolver: nightly-2015-08-15
```

What OS are you using?

`bin-package-db` is a weird package that should be included with GHC, so this might be something strange to do with `stack`...

**Comment by erantapaa** [comment]
Yes - I'm using the supplied stack.yaml file.

I'm on OS X. I've got the Haskell Platform-7.10.2a installed.

I think I found the problem... I had another version of `ghc-pkg` in my PATH.

(I wish stack would always use it's own tools for building stuff.)

Currently building IHaskell - if it succeeds I'll close this ticket.

**Comment by erantapaa** [comment]
Removing the other ghc-pkg from my PATH seems to have fixed this problem. Closing issue.
