### ISSUE TITLE
[Question] adding a graphics package

### ISSUE THREAD

**Issue by ocramz** [gibiansky/IHaskell#558]
What is required for adding a graphics backend and the IHaskell hooks?

E.g. I am considering to work on a Bokeh plugin.
A Bokeh page, ready for browser display, is HTML + a .js file containing 
   *) all the numerical tables, label data and plotting directives in a single JSON object (along with JS hexadecimal id's)
   *) javascript incantations for loading various extras

**Comment by gibiansky** [comment]
Take a look at the [demo notebook](http://nbviewer.ipython.org/github/gibiansky/IHaskell/blob/master/notebooks/IHaskell.ipynb), especially the parts from cell 14 to 18. It outlines how to make such a package.

1. Make a package called `ihaskell-bokeh`.
2. Give it a module called `IHaskell.Display.Bokeh`
3. Implement the `IHaskellDisplay` typeclass for whatever your data type that you want rendered in graphics is.

The output of the `display` function in the `IHaskellDisplay` typeclass is a `Display`, which ultimately boils down to a list of `DisplayData` values; each `DisplayData` value is something to publish with whatever representations it may have. For example, if something can be rendered as text or as a PNG, it will have one display data for each, and the frontend will choose how to render it appropriately. 

Take a look at the documentation [here](http://haddock.stackage.org/nightly-2015-08-21/ihaskell-0.6.4.1/IHaskell-Display.html) as well.

For Javascript, you can dump it to the frontend either by passing HTML with a script tag or, better yet, by using the `Javascript` `MimeType` for a `DisplayData`.

Let me know if you have any other questions or need help or want me to review anything. Happy to help out.

**Comment by gibiansky** [comment]
I'm closing this for the time being, but please re-open if you have any questions. You can email me directly at ANDREW dot gibiansky at google's email service.

**Comment by ocramz** [comment]
Hi Andrew, thanks; 
for the time being I'm trying to understand how to represent the Bokeh AST, and how to render its output in a minimal way (i.e. not requiring passing through any additional host language). 

The output to be displayed in a notebook is html with included javascript tags, because the Bokeh plots are usually interactive (zooming, panning etc). Moreover, the actual Bokeh js and css is pulled from their CDN.
