### ISSUE TITLE
New code cells are not formatted

### ISSUE THREAD

**Issue by orome** [gibiansky/IHaskell#560]
New cells added to a notebook (0.6.5.0) are not formatted as code (with code coloring and styles applied). Saving and reloading a notebook formats all cells, but new cells added after opening are not formatted until saving, closing, and reopening the notebook again.

This problem occurs only in Haskell notebooks (Python notebooks format as expected).

**Comment by gibiansky** [comment]
Is this with IPython 4.0?

**Comment by orome** [comment]
@gibiansky 4.0.0

**Comment by gibiansky** [comment]
Confirmed this on my own machine.

**Comment by gibiansky** [comment]
Should be fixed in `master`.

**Comment by gibiansky** [comment]
And uploaded to Hackage.
