### ISSUE TITLE
Frustrating parentheses matching behavior in notebooks

### ISSUE THREAD

**Issue by orome** [gibiansky/IHaskell#562]
For example, if I type

    "frustrating

and then try to close the quote by typing a `"` I get

     "frustrating""

and simply backspacing to delete the first closing quote results in deletion of both

    "frustrating

so that to get from

    "frustrating

to 

     "frustrating"

I need to 

   1. type a quote
   2. arrow right
   3. backspace

when (1) alone should do the trick.

I get similar behavior with parentheses.

I'm not sure, but I think this just appeared in 4.0. It is not an issue in Python notebooks.

**Comment by gibiansky** [comment]
It should be fixed in newest version on Hackage. Quotes are not completed, brackets and parens should work.

**Comment by orome** [comment]
I still have this issue in 0.7.0.3.

**Comment by gibiansky** [comment]
Have you rerun `ihaskell install`?

**Comment by orome** [comment]
Now I have. (Duh! Sorry!)

**Comment by gibiansky** [comment]
Did that fix it?

**Comment by orome** [comment]
Yes!

**Comment by orome** [comment]
Sorry for the false alarm!
