### ISSUE TITLE
Unable to compile under OSX: undefined symbol "_iconv"

### ISSUE THREAD

**Issue by carrutstick** [gibiansky/IHaskell#563]
Attempting to install under Mac OSX (10.10.4), I receive the linker error:

```
    [2 of 2] Compiling Main             ( doc/examples/TicTacToe.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/operational-TicTacToe/operational-TicTacToe-tmp/Main.o )
    Linking .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/operational-TicTacToe/operational-TicTacToe ...
    Undefined symbols for architecture x86_64:
      "_iconv", referenced from:
          _hs_iconv in libHSbase-4.8.1.0-GDytRqRVSUX7zckgKqJjgw.a(iconv.o)
         (maybe you meant: _hs_iconv, ... )
      "_iconv_close", referenced from:
          _hs_iconv_close in libHSbase-4.8.1.0-GDytRqRVSUX7zckgKqJjgw.a(iconv.o)
         (maybe you meant: _hs_iconv_close)
      "_iconv_open", referenced from:
          _hs_iconv_open in libHSbase-4.8.1.0-GDytRqRVSUX7zckgKqJjgw.a(iconv.o)
         (maybe you meant: _hs_iconv_open)
      "_locale_charset", referenced from:
          _localeEncoding in libHSbase-4.8.1.0-GDytRqRVSUX7zckgKqJjgw.a(PrelIOUtils.o)
    ld: symbol(s) not found for architecture x86_64
```

I get this error whether I attempt to build with `stack install ihaskell --resolver lts-3.1`, or with `stack build --extra-lib-dirs=/opt/local/lib/ --extra-include-dirs=/opt/local/include/` using the latest from github (`069a2638fd8` as of writing).

I have `libiconv` installed under `/opt/local`.

**Comment by gibiansky** [comment]
I've run into this a few times before but don't really know what causes it. Sometimes it's because not all modules are listed under `exposed-modules` or `other-modules`. 

What is `doc/examples/TicTacToe.hs` and `operational-TicTacToe`? Are those from the IHaskell project?

**Comment by carrutstick** [comment]
It seems that `operational-TicTacToe` is an executable built by the [`operational` package](https://github.com/HeinrichApfelmus/operational). I suppose I should take this issue up over there, but it does not look actively developed.

Do you know how to tell why `operational` is being pulled in as a dependency? It is not directly used by IHaskell.

**Comment by gibiansky** [comment]
No idea. Sounds like this is a build failure for `operational`? Try installing `operational` separately first and then `ihaskell`?

**Comment by carrutstick** [comment]
So `stack build operational` succeeds under resolvers `lts-3.0` and `lts-3.1`, but fails under `nightly-2015-08-15`. However, trying to build `ihaskell` under `lts-3.1` also fails with errors about `iconv`, but this time those errors come from IHaskell itself:

```
[2 of 2] Compiling Main             ( main/Main.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ihaskell/ihaskell-tmp/Main.o )
    Linking .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ihaskell/ihaskell ...
    Undefined symbols for architecture x86_64:
      "_iconv", referenced from:
          _hs_iconv in libHSbase-4.8.1.0-GDytRqRVSUX7zckgKqJjgw.a(iconv.o)
         (maybe you meant: _hs_iconv, ...)
      "_iconv_close", referenced from:
          _hs_iconv_close in libHSbase-4.8.1.0-GDytRqRVSUX7zckgKqJjgw.a(iconv.o)
         (maybe you meant: _hs_iconv_close)
      "_iconv_open", referenced from:
          _hs_iconv_open in libHSbase-4.8.1.0-GDytRqRVSUX7zckgKqJjgw.a(iconv.o)
         (maybe you meant: _hs_iconv_open)
      "_locale_charset", referenced from:
          _localeEncoding in libHSbase-4.8.1.0-GDytRqRVSUX7zckgKqJjgw.a(PrelIOUtils.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by carrutstick** [comment]
Ah, this seems to be similar to [this problem](https://github.com/haskell/haskell-platform/issues/74), and I suppose I'll just have to find a way to deal with the duplicate libraries on my own system. Thanks for the help!
