### ISSUE TITLE
Add info to README about Package for Archlinux

### ISSUE THREAD

**Issue by Jiehong** [gibiansky/IHaskell#564]
Hello,

Curious to use Ihaskell, I've created a package in AUR for Archlinux:

https://aur.archlinux.org/packages/ihaskell-git/

I use stack instead of cabal, because it's a little bit easier to manage afterwards, and it only installs the ihaskell binary for the user (well, without counting all the packages stack installs).
 
Hope it can be useful for some people!

Cheers,

Jiehong

**Comment by gibiansky** [comment]
That's great!

This should be added to the README.

**Comment by gibiansky** [comment]
Added to README. Thanks!
