### ISSUE TITLE
IHaskell unable to print unicode

### ISSUE THREAD

**Issue by orome** [gibiansky/IHaskell#568]
IHaskell seems unable to produce Unicode output. In GHCi can

    putStrLn "δγβ"

and get
    
    δγβ

but in IHaskell, I get

    Î´Î³Î²

This may be related to #338.

[OS X: 10.10.5;  Clang: 6.1; Homebrew Python (2.7.10_2); IHaskell 0.7.0.3; IPython 4.0.0]

**Comment by gibiansky** [comment]
This is a [known issue](https://github.com/gibiansky/IHaskell/issues/546) so I'm closing this as a duplicate. It would be great to get this fixed. I agree that #338 is also the same issue.

**Comment by orome** [comment]
Sorry, I see that something similar is also discussed in #546; but I don't see a solution.

**Comment by gibiansky** [comment]
No solution as of yet; it's a bug.
