### ISSUE TITLE
Illegal byte sequence when using ihaskell-diagrams

### ISSUE THREAD

**Issue by thomasjm** [gibiansky/IHaskell#571]
I'm trying to get `ihaskell-diagrams` to work in a notebook. I have the following code:

```
import Diagrams.Prelude
import IHaskell.Display
import IHaskell.Display.Diagrams

display $ diagram $ circle 0.1 # fc red
```

and I get the following error: 

```
.ihaskell-diagram.png: hGetContents: invalid argument (invalid byte sequence)
```

I think this may be related to doing `Char.readFile` on a png file in `Diagrams.hs`? Not sure

**Comment by sumitsahrawat** [comment]
I also think that you're right. This should have been fixed in #517 and #524. Would you be willing to experiment and send a PR?

**Comment by thomasjm** [comment]
You know, I think I might have just had an older version of `ihaskell-diagrams` installed. It seems to work now. Closing this issue...

**Comment by thomasjm** [comment]
Oh, I think this actually works on current master branch but not on the version of `ihaskell-diagrams` currently not on stackage. Which is weird because they both seem to be 0.3.0.0. I guess we just need to update the version on stackage?

**Comment by gibiansky** [comment]
`ihaskell-diagrams-0.3.1.0` uploaded to Hackage

**Comment by xavier83** [comment]
can't find ihaskell-diagrams-0.3.1.0 on stackage yet.
