### ISSUE TITLE
Fails to build with newly released singletons 2.0.0.x

### ISSUE THREAD

**Issue by parente** [gibiansky/IHaskell#578]
Spotted regression in jupyter/docker-demo-images#71 rebuild:

```
Downloading singletons-2.0.0.1...
Configuring singletons-2.0.0.1...
Building singletons-2.0.0.1...
Failed to install singletons-2.0.0.1
Build log ( /home/jovyan/.cabal/logs/singletons-2.0.0.1.log ):
Configuring singletons-2.0.0.1...
Building singletons-2.0.0.1...
Preprocessing library singletons-2.0.0.1...

src/Data/Singletons/Decide.hs:28:8:
    Could not find module `Data.Void'
    It is a member of the hidden package `void-0.7.1'.
    Perhaps you need to add `void' to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

singletons package was released recently (Sept. 16 for 2.0) and ihaskell-widgets is not compatible with the latest version. Maybe pin the dependency to a specific known-to-work major version?

**Comment by gibiansky** [comment]
@sumitsahrawat Can we use `stack` and `Stackage` in `docker-demo-images`?

**Comment by sumitsahrawat** [comment]
@gibiansky Yup, that should make life easier.

**Comment by sumitsahrawat** [comment]
I modified the build process to use the same nightly snapshot that's being used in the current `stack.yaml` (https://github.com/parente/docker-demo-images/pull/1).

**Comment by gibiansky** [comment]
Is this the same as this issue https://github.com/gibiansky/IHaskell/issues/589 ?

**Comment by sumitsahrawat** [comment]
In #589, @artuuge said that the upper bound `<2.0.0.0` for singletons was being ignored, and that changing it to `<2.0` fixed it for him.

Looking at the singletons repo, it seems like it has started passing builds. I'll check if ihaskell-widgets really breaks with the new versions, and update it if required.

**Comment by sumitsahrawat** [comment]
I just found out that the new singletons versions require `ghc>=7.10.2`.

**Comment by artuuge** [comment]
I was able to build IHaskell with widgets starting from the commit 8177b77543552b4370d1c06526bbb7e1b405c081 using singletons-2.0.0.2 and ghc 7.10.2. 

It suffices [after adjusting the upper bound for singletons in ihaskell-widgets.cabal]
to modify the file ihaskell-display/ihaskell-widgets/src/IHaskell/Display/Widgets/Singletons.hs: 

{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE InstanceSigs #-}
import Data.Singletons.Prelude.Ord

Cabal defines apparently 2.0 < 2.0.0.0, therefore:
... < 1.1.2.1 < 2.0 < 2.0.0.0 < ...

There is no version 2.0.0.0 for singletons, but only 2.0, 2.0.0.1, and 2.0.0.2.
The restriction "< 2.0.0.0" leads to an installation of 2.0, and "< 2.0"
leads to 1.1.2.1 [the last version in the 1.* series].

**Comment by gibiansky** [comment]
I think this was resolved, and that IHaskell builds with current `stack.yaml`. Re-open if that is incorrect? @sumitsahrawat
