### ISSUE TITLE
Pattern match failure on missing binary

### ISSUE THREAD

**Issue by Profpatsch** [gibiansky/IHaskell#579]
Yeah, this is not nice:

    Just ipython <- SH.which "ipython"

because it produces this error:

    Sep 28 11:52:30 katara bash[28716]: Exception: user error (Pattern match failure in do expression at src/IHaskell/IPython.hs:204:5-16)

Instead of a

    binary for ipython not found

or something similar.

Came up in https://github.com/NixOS/nixpkgs/issues/10074#issuecomment-143644326

**Comment by sumitsahrawat** [comment]
@Profpatsch Done, thanks for the report :+1:

**Comment by Profpatsch** [comment]
:+1:
