### ISSUE TITLE
Implement :sprint from GHCi

### ISSUE THREAD

**Issue by orome** [gibiansky/IHaskell#585]
Adding to the list (e.g. #559 and #362) of things that would be useful to adopt from GHCi (a lot of these hit right at the use case for IHaskell: learning and experimenting with the language).
##

**Comment by gibiansky** [comment]
Agreed, I want this. Happy to help anyone who may want to take a shot at
it!

**Comment by orome** [comment]
@gibiansky — Still a beginner, but maybe eventually!

**Comment by vaibhavsagar** [comment]
Closed by #1139.
