### ISSUE TITLE
Problem with Diagrams when running the notebook (mac OS X)

### ISSUE THREAD

**Issue by guillaumecherel** [gibiansky/IHaskell#588]
I'm running into problems when using Diagram within the IHaskell notebook. I tried drawing a simple circle. I made a cell containing:
```
:extension NoMonomorphismRestriction

import Diagrams.Prelude

diagram $ circle 1
```

Executing it gives me the following error:
```
: can't load .so/.DLL for: /opt/local/lib/libpangocairo-1.0.dylib (dlopen(/opt/local/lib/libpangocairo-1.0.dylib, 5): Symbol not found: _g_object_unref
  Referenced from: /opt/local/lib/libpango-1.0.0.dylib
  Expected in: flat namespace
 in /opt/local/lib/libpango-1.0.0.dylib)
```

I first thought it was yet another conflict with macports or that I hadn't specified my macports libraries directory correctly when building IHaskell (with `stack install`). But the following seems to be saying that the libraries are installed correctly.

I put the content of the cell (adapted for making a standalone executable) in a file tmp/test.hs in the IHaskell directory
```
{-# LANGUAGE NoMonomorphismRestriction #-}

import Diagrams.Prelude
import Diagrams.Backend.SVG.CmdLine
-- also works with: import Diagrams.Backend.Cairo.CmdLine

main = mainWith (circle 1 :: Diagram B)
```
Then ran `stack ghc -- --make Diag.hs` and `./Diag -o circle.svg -w 400` and everything worked fine. Since I'm using stack, I believe that I'm using the same environment here than when I launch ipython with `stack exec ipython -- notebook`. Any idea why it doesn't work in the notebook?

(I installed IHaskell by cloning the repository and running stack install in it)

**Comment by gibiansky** [comment]
Sorry that I was not able to reply in a timely fashion. Since I'm guessing this issue is no longer relevant to you, I am closing it, but please re-open it if you are interested in help. That said, I haven't seen this error before and have no idea how to diagnose what is going on with it.
