### ISSUE TITLE
ihaskell-widgets and singletons come into conflict during an installation into a cabal sandbox

### ISSUE THREAD

**Issue by artuuge** [gibiansky/IHaskell#589]
*Problem:* The installation process into a cabal sanbox fails and gives a long sequence of errors while compiling ihaskell-widgets (ghc 7.10.2, cabal 1.22.6.0, commit 8104d98f7b733df6f993c4bb6138def874e2f79e ). 

*Solution:* Fix a typo in the build-depends section in ihaskell-display/ihaskell-widgets/ihaskell-widgets.cabal replacing ", singletons >= 0.9.0 && <2.0.0.0" with ", singletons >= 0.9.0 && <2.0".

There is a conflict betwen ihaskell-widgets and the 2.* version of the singletons library. Cabal ignores "<2.0.0.0" and proceeds with an installation of the most recent version of singletons. If the restriction is "<2.0", then the result is singletons-1.1.2.1.

**Comment by sumitsahrawat** [comment]
Thanks for the patch :+1:.

**Comment by gibiansky** [comment]
@artuuge Thanks!
