### ISSUE TITLE
Github shows only three first paragraphs of README.md in mobile version

### ISSUE THREAD

**Issue by gracjan** [gibiansky/IHaskell#592]
Github shows only three first paragraphs of README.md in mobile version:

<img width="454" alt="gibianski-ihaskell-readme" src="https://cloud.githubusercontent.com/assets/917978/10426777/b4710242-70e3-11e5-9e76-a6f9440f2eef.png">

Many people are browsing idly on phones and would be good if they found useful information without clicking 'View all of README.md'.

**Comment by gibiansky** [comment]
Done.
