### ISSUE TITLE
macos - qtconsole support 

### ISSUE THREAD

**Issue by kfiz** [gibiansky/IHaskell#597]
Hi,
at present there seems to be no qtconsole support for ihaskell on my macbook pro, running el capitan and ghc 7.10.2. I can launch the qtconsole with:
`jupyter qtconsole --kernel=haskell`
but after that, every message passed to the REPL leads to a dying kernel.
Is there an easy fix for this?

Best

Doro

**Comment by sumitsahrawat** [comment]
Which version of IHaskell are you using?

**Comment by sumitsahrawat** [comment]
I can confirm this. Will look and see if I can do something about it.

**Comment by kfiz** [comment]
I'm using
`ihaskell-0.8.2.0`.
Installed from hackage.
