### ISSUE TITLE
IHaskell not aware of Stack/Cabal project packages

### ISSUE THREAD

**Issue by alandao** [gibiansky/IHaskell#598]
I'm having trouble getting IHaskell to recognize my packages I included in my stack project.

Here's what I did:
1. Installed IHaskell with Stack in my home dir
2. Installed IHaskell into Juypter by inputting "ihaskell install --stack". 
3. Made a new notebook in my Stack project(where stack.yaml exists)
4. Inputted "import Control.Lens"

When I did this, IHaskell prints out "Failed to load interface for 'Control.Lens'. My .cabal has 'lens' in build-depends. Is there anyway for IHaskell to "see" this?

**Comment by gibiansky** [comment]
Are you running `ipython` in the directory with the `stack.yaml`?

**Comment by alandao** [comment]
Yes. I'm typing in "ipython notebook" in my project directory where I have stack.yaml. Here is how my notebook looks.

http://i.imgur.com/rNN9DKM.jpg

**Comment by gibiansky** [comment]
You installed IHaskell from Github?

**Comment by alandao** [comment]
Yup. I git cloned it to my desktop, went inside, and typed "stack install".

**Comment by sid-kap** [comment]
@alandao Did you resolve this? If so, how? I am having a similar issue?

**Comment by alandao** [comment]
@sid-kap Sorry, I gave up trying to get this to work.. If you find a solution, it'd be great if you shared it to us.

**Comment by sid-kap** [comment]
`ihaskell install --stack` and then `stack exec ipython -- notebook` worked for me.
