### ISSUE TITLE
Installation of kernel locally to home

### ISSUE THREAD

**Issue by kotrfa** [gibiansky/IHaskell#602]
Hello,

I'd like to know if it is possible to somehow install IHaskell kernel locally to my home folder, since I don't enjoy installing packages system wide. Even though it is quite easy since I am on Arch Linux, I would appreciate a way to install this locally to e.g. my home folder. 

Thank you

**Comment by gibiansky** [comment]
Yup, the standard `stack`-based installation described on the [README](https://github.com/gibiansky/IHaskell) installs locally.

**Comment by kotrfa** [comment]
Thank you. Maybe it would be nice to mention explicitly, but never mind. 

Great work!
