### ISSUE TITLE
Haskell kernel keeps dying

### ISSUE THREAD

**Issue by mistguy** [gibiansky/IHaskell#603]
I installed ihaskell with `stack`, but in my jupyter notebook, haskell kernel keeps dying. In terminal:
```
[wangc@wangc-work ~]$ ipython console --kernel haskell
ihaskell: Failed to load interface for ‘IHaskell.Display’
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display’
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.IPython.Stdin’
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Eval.Widgets’
Use -v to see a list of the files searched for.

Jupyter Console 4.0.2

[ZMQTerminalIPythonApp] Loading IPython extension: storemagic
```
Then it stops.

**Comment by sumitsahrawat** [comment]
How did you install IHaskell using stack? From the GitHub master branch, or from stackage?

**Comment by mistguy** [comment]
More information
```
[wangc@wangc-work ~]$ ihaskell kernel --debug
No kernel profile JSON specified.
This may be a bug!
Args (Kernel Nothing) [KernelDebug]
```

**Comment by sumitsahrawat** [comment]
Can you try running `ihaskell install --stack`, and see how it goes?

**Comment by mistguy** [comment]
I installed stack from stackage, and then `stack install ihaskell`.

```
[wangc@wangc-work bin]$ ihaskell install --stack
Unknown flag: --stack
```

**Comment by sumitsahrawat** [comment]
Yup, seems like it's an old version which doesn't support stack as well. You can proceed by cloning the repository and running `stack install` inside it, followed by `ihaskell install --stack`.

**Comment by mistguy** [comment]
Problem solved! Maybe the old version provided stack LTS does not support jupyter.
