### ISSUE TITLE
IHaskell installer fails to install libmagic on Mac OS X + Homebrew

### ISSUE THREAD

**Issue by bollu** [gibiansky/IHaskell#607]
`libmagic` was installed, but turns out that homebrew installs `libmagic` headers onto `/usr/local/include` and libraries into `/usr/lib/include` that was causing the installer to fail at 

```
cabal: Error: some packages failed to install:
ihaskell-magic-0.3.0.0 depends on magic-1.1 which failed to install.
magic-1.1 failed during the building phase. The exception was:
ExitFailure 1
```

However, the fix was really simple. Just point cabal to the right folders:

```
cabal install magic-1.1  --extra-lib /usr/local/lib --extra-include /usr/local/include
Resolving dependencies...
Configuring magic-1.1...
Building magic-1.1...
Installed magic-1.1
```

I can send a pull request if that's cool :) Thanks!

**Comment by sumitsahrawat** [comment]
> I can send a pull request if that's cool

That's always cool :smile:
