### ISSUE TITLE
Using html for errors and warnings causes issues

### ISSUE THREAD

**Issue by sumitsahrawat** [gibiansky/IHaskell#611]
Input Cell:

``` haskell
let x = x + 1

x
```

Output:

``` haskell
<>
```

Reason:

The actual output was `<<loop>>`, but `<loop>` was interpreted as HTML and hidden. Might be different with different browsers too.
##

**Comment by gibiansky** [comment]
Good catch. We should escape that HTML.

**Comment by GregorySchwartz** [comment]
This is also an issue in org-mode as it just spits out html instead of plain text (as it's not in the browser).

**Comment by vaibhavsagar** [comment]
This seems like it would be fixed by #1008.

**Comment by vaibhavsagar** [comment]
This should be fixed now, please reopen if required.
