### ISSUE TITLE
Installation on Ubuntu

### ISSUE THREAD

**Issue by aragnon** [gibiansky/IHaskell#618]
You should query cabal for the bin path and add that to PATH during installation, because otherwise one of the gtk*hs packages doesn't build and the installation fails.  

Additionally, running  `./ubuntu-install.sh` returns: 
```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: ghc-parser-0.1.8.0
trying: base-4.6.0.1/installed-8aa...
rejecting: ihaskell-static-canvas-0.1.0.0 (conflict:
base==4.6.0.1/installed-8aa..., ihaskell-static-canvas => base>=4.7 && <4.9)
```

**Comment by sumitsahrawat** [comment]
> You should query cabal for the bin path and add that to PATH during installation, because otherwise one of the gtk*hs packages doesn't build and the installation fails.

Great suggestion. Would you be willing to send a PR?

Also, we just got a PR for the macos installation script (#614), if you want you can do something similar for ubuntu as well.

---

> Additionally, running ./ubuntu-install.sh returns:

IHaskell requires atleast `ghc-7.6.3`. It seems like you have an older version. Can you confirm this?

**Comment by aragnon** [comment]
@sumitsahrawat I have exactly 7.6.3.

**Comment by sumitsahrawat** [comment]
I double checked, and the travis build for ghc-7.6.3 doesn't build any of the display packages. I remember @gibiansky saying that even though IHaskell compiles on ghc-7.6.3, it is not officially supported. Did you try lowering the constraints for that specific package?

**Comment by aragnon** [comment]
@sumitsahrawat No, but an installation script should just check the environment. 
```
ghc_version=$(ghc --version | egrep -o '[0-9.]+') # getting the version is easy, see?

```

**Comment by aragnon** [comment]
@sumitsahrawat Alternatively, just give up on Linux distro specific scripts and just use Nix (and join the 21st century of packaging). Then you can also get rid of the MacOSX specific scripts and OS specific installation instructions.

**Comment by sumitsahrawat** [comment]
I don't have any experience with Nix. I would personally prefer `cabal` for the installation scripts, as it is a standard tool in the haskell toolchain, and ships with the haskell-platform.

> No, but an installation script should just check the environment.

That is a valid suggestion, although it would require that the installation scripts be kept in sync with the code.

**Comment by gibiansky** [comment]
@aragnon Until GHC 8.0 is out I'd like to continue supporting 7.6.3 to some degree at least.

As for Nix, I personally know almost nothing about it – for my own work, `brew` and `stack` work very smoothly – but I believe there is some support for IHaskell.  [This](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/ihaskell.nix), perhaps?

If that Nix package / recipe doesn't work, I suggest sending them a PR :)
