### ISSUE TITLE
Cabal file needs here package added to build-deps for ihaskell.

### ISSUE THREAD

**Issue by capn-freako** [gibiansky/IHaskell#621]
I had to make this change, to get IHaskell to re-build, after upgrading to Haskell Platform 7.10.3:

diff --git a/ihaskell.cabal b/ihaskell.cabal
index fb53441..9562240 100644
--- a/ihaskell.cabal
+++ b/ihaskell.cabal
@@ -147,7 +147,8 @@ executable ihaskell
                        strict               >=0.3,
                        unix                 >= 2.6,
                        directory            -any,
-                       ipython-kernel       >=0.7
+                       ipython-kernel       >=0.7,
+                       here                 -any
 
   if flag(binPkgDb)
     build-depends:       bin-package-db

**Comment by sumitsahrawat** [comment]
You found a fix, why not send a PR :smile:

**Comment by gibiansky** [comment]
What version of ihaskell were you working with? "Here" was recently removed from the codebase, so it should not be needed. What errors did you encounter?

**Comment by capn-freako** [comment]
Just cloned, yesterday.

Here's the error I got:

[24 of 25] Compiling IHaskell.Eval.Info ( src/IHaskell/Eval/Info.hs, dist/build/IHaskell/Eval/Info.o )
[25 of 25] Compiling IHaskell.Publish ( src/IHaskell/Publish.hs, dist/build/IHaskell/Publish.o )
In-place registering ihaskell-0.8.3.0...
Preprocessing executable 'ihaskell' for ihaskell-0.8.3.0...

main/Main.hs:29:18:
    Could not find module ‘Data.String.Here’
    It is a member of the hidden package ‘here-1.2.7@here_63mTmLx8Sz20TyEJBVCnnC’.
    Perhaps you need to add ‘here’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
Updating documentation index
/Users/dbanas/Library/Haskell/share/doc/x86_64-osx-ghc-7.10.3/index.html
cabal: Error: some packages failed to install:
ihaskell-0.8.3.0 failed during the building phase. The exception was:
ExitFailure 1

**Comment by gibiansky** [comment]
I think you are likely installing an old version of IHaskell. Line 29 of Main.hs does not contain a reference to `Data.String.Here`.

**Comment by gibiansky** [comment]
Nevermind, my mistake. I've now pushed a fix to `master`.

Thanks for letting me know!
