### ISSUE TITLE
Hide imports from IHaskellPrelude or import alternate prelude instead?

### ISSUE THREAD

**Issue by dmcclean** [gibiansky/IHaskell#625]
(This may already be a feature, but I'm having trouble finding any documentation or examples that show how to do it.)

Is it possible to hide some imports from the `IHaskellPrelude` module, or to suppress the import of that module and pick a different one? `:set -XNoImplicitPrelude` doesn't seem to work.

**Comment by gibiansky** [comment]
What is this for?

Is this for within the notebook? Within the notebook the normal prelude is imported, not the `IHaskellPrelude`. That's just the Prelude used for the IHaskell codebase.

`IHaskellPrelude` is imported qualified, so it shouldn't matter. 

Here is what I am seeing when using `:set -XNoImplicitPrelude`:

![image](https://cloud.githubusercontent.com/assets/1865411/12255317/3b136186-b8a7-11e5-8b5c-5c5b3e15f4fc.png)


Is that not what you would want?

**Comment by dmcclean** [comment]
I'm sorry. I think I may have just needed to restart the kernel and do the -XNoImplicitPrelude before I did the imports. I think the first time I did the import, ran it, got an ambiguous resolution message, realized I needed -XNoImplicitPrelude, and added it. That doesn't work, even in GHCi you need to do the `:m -Prelude` trick. But doing it in the right order does in fact work.
