### ISSUE TITLE
-bash: ihaskell: command not found

### ISSUE THREAD

**Issue by evanbiederstedt** [gibiansky/IHaskell#627]
I am slightly confused by the installation guidelines. 

Using Mac OS X, I cloned the git repo and installed from there with `cabal`. It appears that everything has been installed. 

    Installed ihaskell-widgets-0.2.2.1
    Reminder: run 'ihaskell install' to install the IHaskell kernel to Jupyter.

    $ ihaskell notebook

This returns 

    -bash: ihaskell: command not found

How can I remedy this? 

Also, I believe there's a spelling error with "With MacPorts installed, run `ports install zmq`". This should be `sudo port install zmq`.

**Comment by sumitsahrawat** [comment]
This means that the `ihaskell` binary is not in your `$PATH`. If you installed IHaskell in a sandbox, then it will be found in `.cabal-sandbox/bin`, if you installed normally, then it will be found in `~/.cabal/bin` I think.

**Comment by evanbiederstedt** [comment]
Thanks. 

`ihaskell` is in `~/.cabal/bin`. I edited ` ~/.bash_profile` to contain the following:

    export PATH=~/.cabal/bin:$PATH

I still run into `-bash: ihaskell: command not found`. How can I set the path correctly?

**Comment by sumitsahrawat** [comment]
Try using `$HOME` instead of `~`, putting this in your `.bash_profile`:

```bash
export PATH=$HOME/.cabal/bin:$PATH
```

**Comment by evanbiederstedt** [comment]
Thank you, this works. 

The kernel runs without many issues using `sudo ipython notebook` in the command line. However, the kernel immediately shutdowns and doesn't restart using `ipython notebook`, apparently due to lack of permissions. Is there a quick fix to this? Perhaps this deserves a separate issue:

```
[I 08:30:11.254 NotebookApp] Kernel started: 70bc3f3b-4783-4ac6-9008-6ead9ac2f45f
[W 08:30:12.017 NotebookApp] 404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js?v=20160118083002 (::1) 192.58ms referer=http://localhost:8888/notebooks/Untitled86.ipynb?kernel_name=haskell
ihaskell: /Users/USERNAME/.ihaskell/.kernel-profile: openFile: permission denied (Permission denied)
[I 08:30:14.257 NotebookApp] KernelRestarter: restarting kernel (1/5)
ihaskell: /Users/USERNAME/.ihaskell/.kernel-profile: openFile: permission denied (Permission denied)
[I 08:30:17.266 NotebookApp] KernelRestarter: restarting kernel (2/5)
ihaskell: /Users/USERNAME/.ihaskell/.kernel-profile: openFile: permission denied (Permission denied)
[I 08:30:20.276 NotebookApp] KernelRestarter: restarting kernel (3/5)
ihaskell: /Users/USERNAME.ihaskell/.kernel-profile: openFile: permission denied (Permission denied)
[W 08:30:21.390 NotebookApp] Timeout waiting for kernel_info reply from 70bc3f3b-4783-4ac6-9008-6ead9ac2f45f
[I 08:30:23.285 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 70bc3f3b-4783-4ac6-9008-6ead9ac2f45f restarted
ihaskell: /Users/USERNAME/.ihaskell/.kernel-profile: openFile: permission denied (Permission denied)
[W 08:30:26.295 NotebookApp] KernelRestarter: restart failed
[W 08:30:26.296 NotebookApp] Kernel 70bc3f3b-4783-4ac6-9008-6ead9ac2f45f died, removing from map.
ERROR:root:kernel 70bc3f3b-4783-4ac6-9008-6ead9ac2f45f restarted failed!
[W 08:30:26.313 NotebookApp] Kernel deleted before session
[W 08:30:26.314 NotebookApp] 410 DELETE /api/sessions/d4e8c5b7-bf37-4576-a835-192b15e6327d (::1) 2.01ms referer=http://localhost:8888/notebooks/Untitled86.ipynb?kernel_name=haskell
```

**Comment by evanbiederstedt** [comment]
Issue resolved. 

One must use `sudo chown USERNAME` for each "permission denied" subdirectory

`sudo chown USERNAME /Users/USERNAME/.ihaskell/`
`sudo chown USERNAME /Users/USERNAME/.ihaskell/.kernel-profile`
`sudo chown USERNAME /Users/USERNAME/.ihaskell/.last-req-header`

Feel free to close Issue. Thank you

**Comment by sumitsahrawat** [comment]
Two points to consider:

1. All directories in your `$HOME` should be owned by you, so there should not be any reason to have to explicitly `chown` them.
2. You can use `-R` with `chown`, which makes it recursive.

It seems like you installed IHaskell as the root user, using `sudo` maybe?.

**Comment by evanbiederstedt** [comment]
"It seems like you installed IHaskell as the root user, using sudo maybe?"

I suspect you're correct. Yes, the recursive flag should be used here.
