### ISSUE TITLE
Error during ./ubuntu-install.sh

### ISSUE THREAD

**Issue by acardona** [gibiansky/IHaskell#628]
$ ./ubuntu-install.sh
[...]
cleaning...
cleaning...
cleaning...
cleaning...
CMD: cabal install --constraint arithmoi -llvm -j ./ghc-parser ./ipython-kernel ./. ./ihaskell-display/ihaskell-aeson ./ihaskell-display/ihaskell-basic ./ihaskell-display/ihaskell-blaze ./ihaskell-display/ihaskell-charts ./ihaskell-display/ihaskell-diagrams ./ihaskell-display/ihaskell-hatex ./ihaskell-display/ihaskell-juicypixels ./ihaskell-display/ihaskell-magic ./ihaskell-display/ihaskell-plot ./ihaskell-display/ihaskell-rlangqq ./ihaskell-display/ihaskell-static-canvas --force-reinstalls --max-backjumps=-1 --reorder-goals
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: ghc-parser-0.1.8.0 (user goal)
trying: base-4.6.0.1/installed-8aa... (dependency of ghc-parser-0.1.8.0)
next goal: ihaskell-static-canvas (user goal)
rejecting: ihaskell-static-canvas-0.1.0.0 (conflict:
base==4.6.0.1/installed-8aa..., ihaskell-static-canvas => base>=4.7 && <4.9)
Dependency tree exhaustively searched.

Then the installation stops. Thanks in advance for any help.

**Comment by acardona** [comment]
I've tried with a new, empty cabal sandbox, and resulted in the same issue:

$ ./ubuntu-install.sh
[...]
cleaning...
cleaning...
cleaning...
cleaning...
CMD: cabal install --constraint arithmoi -llvm -j ./ghc-parser ./ipython-kernel ./. ./ihaskell-display/ihaskell-aeson ./ihaskell-display/ihaskell-basic ./ihaskell-display/ihaskell-blaze ./ihaskell-display/ihaskell-charts ./ihaskell-display/ihaskell-diagrams ./ihaskell-display/ihaskell-hatex ./ihaskell-display/ihaskell-juicypixels ./ihaskell-display/ihaskell-magic ./ihaskell-display/ihaskell-plot ./ihaskell-display/ihaskell-rlangqq ./ihaskell-display/ihaskell-static-canvas --force-reinstalls --max-backjumps=-1 --reorder-goals
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: ghc-parser-0.1.8.0 (user goal)
trying: base-4.6.0.1/installed-8aa... (dependency of ghc-parser-0.1.8.0)
next goal: ihaskell-static-canvas (user goal)
rejecting: ihaskell-static-canvas-0.1.0.0 (conflict:
base==4.6.0.1/installed-8aa..., ihaskell-static-canvas => base>=4.7 && <4.9)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.

**Comment by sumitsahrawat** [comment]
You're using an old version of ghc. Many of the display packages require newer versions of ghc.

**Comment by acardona** [comment]
@sumitsahrawat I am using ghc 7.6, which the docs here state it is OK, and it is also the default in Ubuntu 14.04 LTS, which is the latest LTS.

But I get it: should install new GHC.
