### ISSUE TITLE
Determine the current version of ihaskell from the command line

### ISSUE THREAD

**Issue by seagreen** [gibiansky/IHaskell#632]
I'd like to learn what version of ihaskell I have installed, but I'm having trouble.

### Details

(On nixpkgs checkout `421989f` and with `ihaskell` installed)

`ihaskell --version` doesn't print anything.

`ihaskell --help` doesn't show the version.

By opening a notebook and going to Help > About I can view this screen:

![screenshot](https://cloud.githubusercontent.com/assets/1310143/12595846/90feb73a-c44b-11e5-92f4-0a0cad6f0c0b.png)

I'm not sure, but I think "4.1.0" refers to the Jupyter version, not the ihaskell kernel version.

### Question

I think I may be on a much earlier version of ihaskell. Has a `--version` flag been added to later versions of ihaskell, and if not would that be a good thing to have?

**Comment by nicluo** [comment]
+1. I fixed some issues on my installation of iHaskell by doing <code>git clone</code> and <code>./build.sh ihaskell</code>, but I had no way to find out which version I was using previously.

**Comment by nicluo** [comment]
I found out that Jupyter Notebook populates the current kernel information box with the <code>banner</code> value in kernel info.

Adding one row to KernelInfoReply gave notebook the required information.

    -- Writer.hs (rows 24 - 33)
    -- Convert message bodies into JSON.
    instance ToJSON Message where
      toJSON rep@KernelInfoReply{} =
        object
          [ "protocol_version" .= string "5.0"  -- current protocol version, major and minor
          , "implementation" .= implementation rep
          , "implementation_version" .= implementationVersion rep
          , "language_info" .= languageInfo rep
          , "banner" .= string ("IHaskell " ++ (implementationVersion rep) ++ " GHC " ++ (languageVersion (languageInfo rep)))
          ]

Here's the relevant debug row when running <code>jupyter notebook --debug</code>

    [D 18:21:55.023 NotebookApp] Received kernel info: {u'language_info': {u'file_extension': u'.hs', u'version': u'7.10.2', u'name': u'haskell', u'codemirror_mode': u'ihaskell'}, u'protocol_version': u'5.0', u'banner': u'IHaskell 0.8.3.0 GHC 7.10.2', u'implementation_version': u'0.8.3.0', u'implementation': u'IHaskell'}

Here's the output in the About screen:

<img width="688" alt="screen shot 2016-02-09 at 6 28 21 pm" src="https://cloud.githubusercontent.com/assets/3689208/12913662/0bdcf6a0-cf5b-11e5-81be-c6280efdb61d.png">

This was as far as I could go. I'm still learning Haskell,  I hope the information helps.

**Comment by sumitsahrawat** [comment]
Thanks for digging in @nicluo. If you want, you can send a PR and I'll happily merge it.

Sorry for not being late to the party. I'll try and see if I can add a `--version` flag sometime soon. In case you also want to make an attempt at it, you should take a look at `main/Main.hs`.

**Comment by nicluo** [comment]
@sumitsahrawat I've bundled the change into a PR.

I would not mind attempting <code>--version</code> support. Still grokking at the moment.

**Comment by sumitsahrawat** [comment]
> @sumitsahrawat I've bundled the change into a PR.

Thanks for taking the time :+1: 

> I would not mind attempting --version support. Still grokking at the moment.

Great, happy hacking :wink:
