### ISSUE TITLE
Jupyter message specification v5 support in ipython-kernel

### ISSUE THREAD

**Issue by joehendrix** [gibiansky/IHaskell#633]
Jupyter now has a [5.0 version specification](http://jupyter-client.readthedocs.org/en/latest/messaging.html#general-message-format) of their message format.

Are there plans to support those changes?

I made a few of the changes needed in a fork repo [here](https://github.com/joehendrix/IHaskell), and could expand that, but I'm not sure if support for older versions is needed.

**Comment by sumitsahrawat** [comment]
Thanks for the work :+1: 

I remember @gibiansky saying that we aim to support the latest ipython/jupyter, and the last three versions of ghc. Only he can decide what to do here.

**Comment by gibiansky** [comment]
Yes, we'd like to support 5.0, though preferably without breaking support for 3.0-4.0. Happy to take PRs with support (esp if they include explanation of what changed in the protocol).

**Comment by vaibhavsagar** [comment]
AFAIK IHaskell now supports this.
