### ISSUE TITLE
Multiline Quasiquotes from Persistent example

### ISSUE THREAD

**Issue by herbertjones** [gibiansky/IHaskell#638]
Examples from the [Persistent documentation](http://www.yesodweb.com/book/persistent) fail for me.

```
:extension EmptyDataDecls
:extension FlexibleContexts
:extension GADTs
:extension GeneralizedNewtypeDeriving
:extension MultiParamTypeClasses
:extension OverloadedStrings
:extension QuasiQuotes
:extension TemplateHaskell
:extension TypeFamilies
import Database.Persist
import Database.Persist.TH
import Database.Persist.Sqlite
import Control.Monad.IO.Class (liftIO)

mkPersist sqlSettings [persistLowerCase|
Person
    name String
    age Int
    deriving Show
|]
```

The error:

```
Parse error (line 15, column 41): unterminated quasiquotation at end of input
Parse error (line 19, column 5): parse error on input `deriving'
Parse error (line 20, column 1): parse error on input `|]'
```

I ensured persistent is installed in the recommended docker container via `docker exec ihaskell stack install persistent-sqlite && docker commit ihaskell gibiansky/ihaskell:latest`.  Looks like the only error is that quasiquotation doesn't work across newlines.  It looks as if this should work, according to #236 and #183.  Is this a bug or is it unsupported?

**Comment by gibiansky** [comment]
Confirmed via another example:

![image](https://cloud.githubusercontent.com/assets/1865411/15979702/91f5ef02-2f1a-11e6-8443-14850b0a253d.png)

This is a bug in the IHaskell parser.

**Comment by gibiansky** [comment]
This should be fixed in the latest commit.

There are still some unhandled quasiquote cases but they should be quite rare.
