### ISSUE TITLE
Create new notebook - kernel busy

### ISSUE THREAD

**Issue by domogled** [gibiansky/IHaskell#644]
I did start jupyter notebook

I did created new notebook for haskell from jupyter dashboard on http://localhost:8888/tree#

If have new notebook on http://localhost:8888/notebooks/Untitled1.ipynb?kernel_name=haskell

But haskell kernel is continuously busy (grey icon). If I write any code and try it, this not be run.

shell console

[I 03:39:54.217 NotebookApp] Creating new notebook in 
[I 03:39:56.567 NotebookApp] Kernel started: c09375e0-b755-47d7-92eb-3bf2e63b4d7c
[W 03:39:57.770 NotebookApp] 404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js?v=20160301033940 (127.0.0.1) 56.53ms referer=http://localhost:8888/notebooks/Untitled1.ipynb?kernel_name=haskell
ihaskell: main/Main.hs:(240,13)-(250,15): Missing field in record construction protocolVersion

[W 03:40:06.756 NotebookApp] Timeout waiting for kernel_info reply from c09375e0-b755-47d7-92eb-3bf2e63b4d7c

**Comment by domogled** [comment]
$ ps -ax | jupyter

8725 pts/2    Sl+    0:02 /usr/bin/python3 /usr/local/bin/jupyter-notebook
 8847 pts/2    Sl     0:06 /home/domogled/.cabal/bin/ihaskell kernel /run/user/1000/jupyter/kernel-6d2600da-0ad0-45e8-bb9d-9c4684aefefe.json --ghclib /usr/local/haskell/ghc-7.10.3-x86_64/lib/ghc-7.10.3

**Comment by domogled** [comment]
RESOLVED

I did uninstall haskell-platform (I did used generic package from https://www.haskell.org/platform/
and
I did install haskell-platform from linux-mint repository (ghc 7.6)

It works!!!

**Comment by sumitsahrawat** [comment]
While IHaskell builds fine with ghc 7.6, it is not fully supported. I suggest you atleast have ghc 7.8.4 installed.

**Comment by domogled** [comment]
Yes, of course. However, the simplest recomended way to install haskell on Linux Mint (Ubuntu also) on https://www.haskell.org/platform/ is from ubuntu package repository.

I dont understand, why is in repository so the old version.

I did install first from generic source, unfortunelly it did not work with jupyter ihaskell.

Im considering now, that I will use old version, or I will detect problem reported with message

_ihaskell: main/Main.hs:(240,13)-(250,15): Missing field in record construction protocolVersion_

**Comment by sumitsahrawat** [comment]
Mint and Ubuntu provide old ghc in the official repositories. For knowing the recommended way to get up-to-date ghc, take a look at the [learnhaskell guilde](https://github.com/bitemyapp/learnhaskell).

**Comment by domogled** [comment]
O great, with stack working all excellent. 

ghc 7.10.3, iHaskell with Jupiter work

very Thanks

**Comment by sumitsahrawat** [comment]
Glad I could help :smile:
