### ISSUE TITLE
ghc-7.10.3 kernel

### ISSUE THREAD

**Issue by madjestic** [gibiansky/IHaskell#645]
Is there a reason why iHaskell kernell would not allow 7.10.3 and is limited to 7.8.4?

ipython is looking for /usr/lib64/ghc-7.8.4/settings, which, obviously, does not exist if 7.10.3 is installed.  Creating a symlink `ln -s /usr/lib64/ghc-7.8.4 /usr/lib64/ghc-7.10.3` seems to be fixing the issue, the ipython notebook seems to run ok with haskell kernel.

Cheers

**Comment by sumitsahrawat** [comment]
> Is there a reason why iHaskell kernell would not allow 7.10.3 and is limited to 7.8.4?

7.10.3 is _not_ disallowed. The version of ghc being used is determined during `ihaskell install`. How did you install IHaskell?

**Comment by madjestic** [comment]
I installed it through portage.  Perhaps something is wrong with one of the ebuilds...

**Comment by Jiehong** [comment]
I kinda had the same issue on Arch recently when installing with stack, but it was because I ended up putting ihaskell at the wrong place for stack…

So it may be something to do with the ebuilds indeed.

**Comment by gibiansky** [comment]
7.8.4 through 7.10.3 are all currently supported; 7.6.3 probably also works but is no longer *officially* supported, 8.0.0 support is coming soon most likely.

Sadly i cannot help much with Arch packaging but I am happy to include more info on documentation if there is something that could be added.
