### ISSUE TITLE
fmap Just [1, 2, 3] prints multi-line result 

### ISSUE THREAD

**Issue by andrevdm** [gibiansky/IHaskell#648]
`[1, 2, 3]` prints `[1, 2, 3]` 
`fmap id [1, 2, 3]` prints `[1, 2, 3]` 

but `fmap Just [1, 2, 3]` prints
```
  Just 1
  Just 2
  Just 3
```

Which does not match ghci's `[Just 1, Just 2, Just 3]`

Thanks for a great tool BTW

**Comment by andrevdm** [comment]
Interestingly `print (fmap Just [1, 2, 3])` does print `[Just 1, Just 2, Just 3]`

**Comment by gibiansky** [comment]
This was due to the `ihaskell-basic` display package most likely which has now been removed:

![image](https://cloud.githubusercontent.com/assets/1865411/15979541/6f29ce9a-2f19-11e6-9bc5-01b3cd47a178.png)

**Comment by andrevdm** [comment]
Great thanks!

Looking forward to seeing this in the latest docker image :)
