### ISSUE TITLE
unsafePerformIO hangs

### ISSUE THREAD

**Issue by imh** [gibiansky/IHaskell#649]
This works fine:
```
import System.IO.Unsafe
let x = unsafePerformIO $ return 1
```

But this hangs:
```
import System.IO.Unsafe
x = unsafePerformIO $ return 1
```

This also hangs:
```
x <- (return 1 :: IO Int)
```

In iPython notebooks, a common pandas workflow is to read a DataFrame from disk, then use it repeatedly in other cells. In order to not re-read it from disk in every cell in iHaskell, the data must be pulled out of IO, so this is an important use case.

**Comment by gibiansky** [comment]
This was an error due to `hlint` misbehaving. It should be fixed now:

![image](https://cloud.githubusercontent.com/assets/1865411/15979513/39964646-2f19-11e6-995c-cd3c16e5eec1.png)
