### ISSUE TITLE
Some cells won't run

### ISSUE THREAD

**Issue by Threynaud** [gibiansky/IHaskell#650]
I just started using IHaskell and it is wonderful, but I have some trouble running very simple cells.
For instance, using an apostrophe in the middle of the name of a function is a problem:

-  `helloAll= "Hi"` works perfectly and print `Hi`as expected, same with `helloAll' = "Hi"`, but `hello'all = "Hi"` doesn't run and display the `[*]`symbol. 

-  Same with boolean operation: `True && True`won't run to print `True`.

Otherwise everything I tried seems working for now, so I don't understand what could be the problem..

I am working with Mac OS X and built IHaskell manually.

Thank you

**Comment by leftaroundabout** [comment]
I had this problem with IHaskell-0.8.3, but it seems to be fixed in 0.8.4. Apparently, the old version would hang on precisely those inputs for which the new version gives stilistic warnings:

![ihaskell-warnings](https://cloud.githubusercontent.com/assets/1528675/14232270/c9f3b02a-f9a4-11e5-9178-61b712af589b.png)

**Comment by leftaroundabout** [comment]
The issue was in fact [already discussed earlier](https://github.com/gibiansky/IHaskell/issues/622).

**Comment by hackrole** [comment]
how to check the version of the ihaskell. and how to update the version?? I am new to haskell and ihaskell.

**Comment by gibiansky** [comment]
This was due to `hlint` integration malfunctioning and should be fixed now.

To update to new IHaskell, you can clone the Github repository, `cd` into that directory, and then run `stack install` to install IHaskell.
