### ISSUE TITLE
what's the workflow for wanting to use ihaskell with your own set of libraries?

### ISSUE THREAD

**Issue by silky** [gibiansky/IHaskell#653]
my approach at the moment is to edit the `stack.yaml` for ihaskell itself, add in my library under `packages`, and proceed that way.

this seems pretty "heavy" in some sense, because it means practically that i need to have different forks of ihaskell for any such different configuration

am i doing this a totally crazy way? (probably). is there a better way? (probably).

any advice appreciated!

**Comment by sumitsahrawat** [comment]
Yes, and yes :)

Install IHaskell using `ihaskell install --stack`, and it should be able to see any package installed using stack.

**Comment by silky** [comment]
so i don't even have `--stack` as an available command line option to `ihaskell`

what version is that in?

also, does it take directories as an input, or only package names? suppose my package i want to include isn't up on stackage

**Comment by silky** [comment]
so i'm confused

if i have a package in `ext/foo` how i can install this?

i can't ask `stack` to install this package directly, right? it needs to be specified as part of a yaml file?

**Comment by sumitsahrawat** [comment]
Change to the directory and then run `stack install`. That should install the package.

Try the latest version. The flag makes ihaskell interface with stack, just the way it does for cabal packages. 

The yaml files are a way of adding additional dependencies, and dependencies that are available from stackage are usually added to the cabal file without any version constraints. You should take a look at the stack tutorial for more.

Hope this helps.

**Comment by silky** [comment]
indeed.

jumping into the directory of my project and doing `stack install` doesn't work; it installs the library into the `.stack-work` dir of the project itself.

**Comment by sumitsahrawat** [comment]
`stack install /path/to/package` should install in the global context. Did you try that?

I got a VM up and running, so that I could confirm if it works. Stack refuses to install `ghc-7.10.3`, so I'm kinda stuck. If the above doesn't work, let me know and I'll take a look.

**Comment by silky** [comment]
i actually realised last night a way i could do this - just set the `STACK_WORK` directory during a stack install. i'll give this a try later on; but if it works i'd say this is the best way.

**Comment by gibiansky** [comment]
In addition to the things mentioned in the other comments, you can install IHaskell into the environment of the package that you're working on. That is likely the most reliable method.
