### ISSUE TITLE
caskroom capitalization 

### ISSUE THREAD

**Issue by aaronmck** [gibiansky/IHaskell#656]
This is very minor, but when running the macos-install.sh script on my Mac, I had to change

brew tap caskroom/cask

to 

brew tap Caskroom/cask

in the XQuartz section to get the install to work.  I'm not sure if this is a recent brew change.

**Comment by sumitsahrawat** [comment]
Thanks for the report. Would you be willing to send a quick patch?

**Comment by aaronmck** [comment]
Sure, though I'm not sure if this affects other people.  It would be good if some other mac user could try a clean install and see if this is a unique problem.

**Comment by Hodapp87** [comment]
What version of OS X are you on? I ran into issues installing on my Mac but I can't recall exactly what they were.

**Comment by aaronmck** [comment]
10.11.  Again not sure if this affects others, though I found mention of a similar problem in other projects.

**Comment by gibiansky** [comment]
Patched has been merged.
