### ISSUE TITLE
A bunch of issues in example notebook IHaskell.ipynb

### ISSUE THREAD

**Issue by shitikanth** [gibiansky/IHaskell#658]
Steps to reproduce-
1. Clone IHaskell
2. Install using stack (`stack setup; stack build; stack install`)
3. Cd to directory notebooks
4. Run `stack jupyter -- notebook` and open the IHaskell.ipynb on Safari v9.1
5. Run the cells one by one

Issues

1. After `:opt no-pager`, the output of `:info Integral` appears within `<pre>` tags, and therefore not formatted correctly.
<img width="1118" alt="screen shot 2016-04-16 at 1 12 29 am" src="https://cloud.githubusercontent.com/assets/544054/14579259/5eac42ca-0370-11e6-8e55-aef36067676b.png">

  This issue also affects other examples – hoogle integration example, for instance.
 
2. The JSON examples doesn't get work as expected (formatting is okay, but no colors).
<img width="1118" alt="screen shot 2016-04-16 at 1 14 35 am" src="https://cloud.githubusercontent.com/assets/544054/14579282/0a748310-0371-11e6-8ade-75787a20476e.png">

3. The ihaskell-blaze example also throws up an error.
<pre>Ambiguous occurrence ‘width’
It could refer to either ‘Text.Blaze.Html4.Strict.Attributes.width’, imported from ‘Text.Blaze.Html4.Strict.Attributes’
                      or ‘IHaskell.Display.StaticCanvas.width’, imported from ‘IHaskell.Display.StaticCanvas’</pre>

4. The ihaskell-diagrams example fails with
<pre>Non type-variable argument in the constraint: R1 (V a)
(Use FlexibleContexts to permit this)
When checking that ‘IHaskell3.sierpinski’ has the inferred type
  interactive:IHaskell3.sierpinski :: forall a a1. (Eq a, Num a, Semigroup a1, Juxtaposable a1, HasOrigin a1, TrailLike a1, R1 (V a1), Alignable a1, V a1 ~ V2) => a -> a1</pre>

I am not familiar enough with ihaskell to determine if these are issues with the code or just the case that the example is lagging behind the development, so I am assuming it's the latter and submitting it as one issue.

**Comment by gibiansky** [comment]
Thank you!

Issues have now been fixed and a test has been added to Travis to ensure that the notebook continues to build without issues.
