### ISSUE TITLE
Easy pretty-printing of simple structured Haskell data

### ISSUE THREAD

**Issue by leftaroundabout** [gibiansky/IHaskell#661]
As nice and powerful as the `Display` class is (allowing complex graphical types to be shown) it's currently rather dissapointing for most standard Haskell data &ndash; basically just the same as GHCi's standard behaviour.

Of course, defaulting to plaintext `Show` has its merits, but in particular for displaying nested lists with floating-point numbers (in full precision, as Haskell always does), this quickly becomes very hard to read.

IPython handles this specific case in a somewhat Matlab-ish way: NumPy matrices are displayed structured and reasonably compact. For sure, the equivalent can be achieved with [hmatrix](http://hackage.haskell.org/package/hmatrix) and its pretty-printing `Show` instance, but hey... this is Haskell, right? Surely we can do better than hammer every data structure as a matrix nail!

I started [an experimental project](https://github.com/leftaroundabout/IHaskell-tables) that displays such simple Haskell data (at the moment, basically lists of tuples of numbers, but the type class should compose quite well to more complex stuff) as html tables, including sensible rounding precision (depending on context). I think it [looks quite promising](http://nbviewer.jupyter.org/github/leftaroundabout/IHaskell-tables/blob/master/README.ipynb), about like this:

<table class="List-Double-Double">
        <thead>
            <tr class="Double-Double">
                <td class="List-Char">
                    n
                </td>
                <td class="List-Char">
                    ln (sin n)
                </td>
            </tr>
        </thead>
        <tbody>
            <tr class="Double-Double">
                <td class="Double">
                    <div class="approxWithTooltip">
                        -0.5
                    </div>
                </td>
                <td class="Double">
                    <div class="approxWithTooltip">
                         NaN
                    </div>
                </td>
            </tr>
            <tr class="Double-Double">
                <td class="Double">
                    <div class="approxWithTooltip">
                         0
                    </div>
                </td>
                <td class="Double">
                    <div class="approxWithTooltip">
                        -Infinity
                    </div>
                </td>
            </tr>
            <tr class="Double-Double">
                <td class="Double">
                    <div class="approxWithTooltip">
                         0.5
                    </div>
                </td>
                <td class="Double">
                    <div class="approxWithTooltip">
                        -0.73<span style="opacity:0.42">5</span><span style="opacity:0.12">2</span>
                    </div>
                </td>
            </tr>
            <tr class="Double-Double">
                <td class="Double">
                    <div class="approxWithTooltip">
                         1
                    </div>
                </td>
                <td class="Double">
                    <div class="approxWithTooltip">
                        -0.17<span style="opacity:0.42">2</span><span style="opacity:0.12">6</span>
                    </div>
                </td>
            </tr>
            <tr class="Double-Double">
                <td class="Double">
                    <div class="approxWithTooltip">
                         1.5
                    </div>
                </td>
                <td class="Double">
                    <div class="approxWithTooltip">
                         -2.5<span style="opacity:0.42">0</span><span style="opacity:0.12">8</span>·<sub>10</sub><sup>-3</sup>
                    </div>
                </td>
            </tr>
            <tr class="Double-Double">
                <td class="Double">
                    <div class="approxWithTooltip">
                         2.0
                    </div>
                </td>
                <td class="Double">
                    <div class="approxWithTooltip">
                         -9.5<span style="opacity:0.42">0</span><span style="opacity:0.12">8</span>·<sub>10</sub><sup>-2</sup>
                    </div>
                </td>
            </tr>
            <tr class="Double-Double">
                <td class="Double">
                    <div class="approxWithTooltip">
                         2.5
                    </div>
                </td>
                <td class="Double">
                    <div class="approxWithTooltip">
                        -0.51<span style="opacity:0.42">3</span><span style="opacity:0.12">4</span>
                    </div>
                </td>
            </tr>
            <tr class="Double-Double">
                <td class="Double">
                    <div class="approxWithTooltip">
                         3
                    </div>
                </td>
                <td class="Double">
                    <div class="approxWithTooltip">
                        -1.9<span style="opacity:0.42">5</span><span style="opacity:0.12">8</span>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>

Now, I would make this project an independent hackage package, but perhaps the approach would actually be useful enough to include it in the main project? The dependencies aren't very heavy &ndash; mainly blaze-html, but I suppose that's kind of a recommended import anyway.

Any opinions?

**Comment by gibiansky** [comment]
In general, for displayable bits we aim to keep them separate from the core of IHaskell, and rather make them installable. You can make an `ihaskell-tables` package with a `Table` newtype, for example, and that way you can have a `tabularize` function (as you do) that customizes the display. 

That said, I am open to accepting these small display packages into the IHaskell _repo_ under the `display/` namespace, where most of the other `ihaskell-*` packages are contained!

**Comment by leftaroundabout** [comment]
Ok. Indeed, the project itself isn't _that_ small (~500 LOC for sure eventually) . Even if it's going to be an own cabal package &ndash; there are two options for integration:

- I could `pull -s subtree` the project into `IHaskell` entirely.
- Or split it into a more generic tables part that knows nothing about IHaskell (comparable to diagrams or HaTeX) and only put a single patch with the `Display` instance in the `IHaskell` repo.

The latter would probably be better in principle, but it would only make really sense if I developed these tables with a stable data interface (different backends etc.) and make them useful for other targets but IHaskell, and frankly I can't see myself putting a lot of time into the maintenance of such a project.

I propose this: I'll flesh out the concept a bit more, yet purely in IHaskell, then submit a pull request. If you then decide it's too big or too niche, I'll split it up into a generic part with different backends plus a tiny `Display` integration.

**Comment by gibiansky** [comment]
Sounds good to me. Up to you which of those you prefer. That said for a larger project (even if it's an `ihaskell-*` project) I prefer to keep it out of the repo, mostly because it's unlikely that I'll have the time to maintain it as GHC and the Haskell community evolve if it's more than a hundred lines or so. So, my suggestion is to develop it as an `ihaskell-tables` package and put it on Hackage. You may also want to check out the [Frames](https://github.com/acowley/Frames) library – does it have any overlap? I think it has IHaskell displays for its tables that get printed as HTML tables
