### ISSUE TITLE
boolean operation will block the forever which make the notebook not work any more.

### ISSUE THREAD

**Issue by hackrole** [gibiansky/IHaskell#662]
I face this error on notebook. after I type `True && False`. all the input after this get no output any more.
so I try it on the console. It seems the `True && False` will block forever which seems be bugs.
![2016-05-24-11 55 45-screenshot](https://cloud.githubusercontent.com/assets/2100811/15491798/e203b3d4-21a6-11e6-9226-003320ac6475.png)
![2016-05-24-11 55 58-screenshot](https://cloud.githubusercontent.com/assets/2100811/15491806/fb1676c2-21a6-11e6-9466-d2a9d23df342.png)

**Comment by gibiansky** [comment]
This was caused due to an issue with `hlint` that should now be fixed.
