### ISSUE TITLE
 404 : Not Found  You are requesting a page that does not exist!

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [gibiansky/IHaskell#664]
I've done the docker installation, because the guide says it's the easiest option. However, when I run:

`docker run -it --volume $(pwd):/notebooks --publish 8888:8888 gibiansky/ihaskell:latest`

The notebook starts up, but doesn't find a browser. Ok, no problem, I simple go to the URL myself, but then there I only see a Jupyter page saying: `404 : Not Found  You are requesting a page that does not exist!`.

On the command line I see:

    Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
    [W 12:25:14.572 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
    [W 12:25:14.572 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
    [I 12:25:14.577 NotebookApp] Serving notebooks from local directory: /notebooks
    [I 12:25:14.578 NotebookApp] 0 active kernels 
    [I 12:25:14.578 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/
    [I 12:25:14.578 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
    [W 12:25:14.579 NotebookApp] No web browser found: could not locate runnable browser.

And when I reload `localhost:8888`, I also see:

    [I 12:30:43.815 NotebookApp] Refusing to serve hidden directory, via 404 Error
    [W 12:30:43.839 NotebookApp] 404 GET /tree (172.17.42.1) 24.57ms referer=None
    [I 12:30:45.997 NotebookApp] 302 GET / (172.17.42.1) 0.35ms
    [I 12:30:46.018 NotebookApp] Refusing to serve hidden directory, via 404 Error
    [W 12:30:46.019 NotebookApp] 404 GET /tree (172.17.42.1) 1.85ms referer=None

So I guess it's an access rights issue.

I don't know how to solve it and according to the guide it should have worked out of the box. What can I do to fix this? (And can you please update the guide?)

**Comment by gibiansky** [comment]
What URL are you going to? I just tried exactly that command, followed by going to `localhost:8888`, and got a working notebook. 

It seems like maybe your `pwd` is hidden? What OS is this on?

**Comment by gibiansky** [comment]
Closing for the time being as I cannot confirm it but happy to help you resolve it if you are still having this issue.

**Comment by ZelphirKaltstahl** [comment]
This would be a fedora docker image on fedora 22. It was a few weeks ago, but I think I tried all sorts of URLs, mostly the localhost:8888 and the URL for browsing the files to open notebooks.

**Comment by juhp** [comment]
I hit this too: are any particular permissions needed on `$PWD` for this to work?

```
[I 07:30:41.225 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 07:30:41.368 NotebookApp] 404 GET /tree (172.17.0.1) 144.13ms referer=None
```

**Comment by ebigelow** [comment]
I'm getting the same first error, and I get a 404 when I navigate to `localhost:8888` :

    [W 12:25:14.579 NotebookApp] No web browser found: could not locate runnable browser.

But without the directory permission issues (this error doesn't show):

    [I 12:30:43.815 NotebookApp] Refusing to serve hidden directory, via 404 Error

I'm running mac os 10.11.4

**Comment by MattEttus** [comment]
I get this exact same problem with Fedora 22 and Fedora 25.  Seems like it's a real issue.

**Comment by altear** [comment]
Same on raspi 2017

**Comment by jalako** [comment]
Same on debian 8 with virtualenv

**Comment by oaroldan** [comment]
For me this error message appeared because my file was is in a folder with name "folder name". Note the white space. So by renaming to "folder-name" it solved the problem.
