### ISSUE TITLE
In ipython-kernel, EasyKernel.replyTo creates incomplete KernelInfoReply

### ISSUE THREAD

**Issue by WolframKahl** [gibiansky/IHaskell#665]
My first attempt at a custom kernel crashes with the following message:
```
[W 14:48:28.660 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20160528144808 (::1) 1.56ms referer=http://localhost:8888/notebooks/PropLogic1.ipynb
KernelInfoRequest {header = MessageHeader {identifiers = ["\NUL\244\176\220Q"], parentHeader = Nothing, metadata = fromList [], messageId = UUID {uuidToString = "bb214027-fa68-4dbb-80ed-e0948a7b8156"}, sessionId = UUID {uuidToString = "76434A610DBA44D38763C4952471163C"}, username = "kahl", msgType = KernelInfoRequestMessage}}
ICalcCheck: src/IHaskell/IPython/EasyKernel.hs:(160,5)-(165,7): Missing field in record construction protocolVersion
````

Trying to hunt this down, I find that the definition of ```IHaskell.IPython.EasyKernel.replyTo``` contains:
```
replyTo config _ _ KernelInfoRequest{} replyHeader =
  return
    KernelInfoReply
      { header = replyHeader
      , languageInfo = kernelLanguageInfo config
      , implementation = "ipython-kernel.EasyKernel"
      , implementationVersion = "0.0"
      }
```
But in ```IHaskell.IPython.Types```, the relevant part of ```data Message``` is:
```
             -- | A response to a KernelInfoRequest.
               KernelInfoReply
                 { header :: MessageHeader
                 , protocolVersion :: String -- ^ current protocol version, major and minor
                 , banner :: String -- ^ Kernel information description e.g. (IHaskell 0.8.3.0 GHC 7.10.2)
                 , implementation :: String -- ^ e.g. IHaskell
                 , implementationVersion :: String -- ^ The version of the implementation
                 , languageInfo :: LanguageInfo
                 }
```
Now ```banner``` looks like something that should probably be populated from the ```KernelConfig``` or ```LanguageInfo```, but, being new to IPython/Jupyter, I have no idea what ```protocolVersion``` should be.

**Comment by sumitsahrawat** [comment]
`protocolVersion` specifies the version of the messaging specification being used by the kernel. I think IHaskell uses the value `"5.0"` for it,

`banner` is a string shown as a one line description of the kernel in some places.

**Comment by WolframKahl** [comment]
On Sat, May 28, 2016 at 06:45:51PM -0700, Sumit Sahrawat wrote:
> `protocolVersion` specifies the version of the messaging specification being used by the kernel. I think IHaskell uses the value `"5.0"` for it,
> 
> `banner` is a string shown as a one line description of the kernel in some places.

In my opinion, EasyKernel should either produce these, or provide an interface for supplying them.

**Comment by WolframKahl** [comment]
The commit 4ea7977460d9cb22eaaea6576734cecf4868c7ed looks mostly right (the previous one not).
Thank you!

The documentation of ```kernelProtocolVersion```,
```
         -- | The version of the messaging specification used by the kernel
```
presumably is a specification from the Jupyter/IPython side? Could there perhaps be a link that helps an EasyKernel user find out which version to use?

Does it really make sense to have
```
       , implementation = "ipython-kernel.EasyKernel"
       , implementationVersion = "0.0"
```
constant? There could be vastly different kernels generated from EasyKernel, and I would consider these the implementations...

If yes: Is there any relation between the ```"0.0"``` here, and the ipython-kernel version number 0.8.4.0?

I would have taken ```implementationVersion``` to be the version of my implementation, which is what
```
 , implementationVersion :: String -- ^ The version of the implementation
```
in the documentation of ```KernelInfoReply``` in ```IHaskell/IPython/Types.hs``` appears to suggest.


While you are at it: I found the documentation of ```languageCodeMirrorMode``` not only unsatisfactory (what is this meant to be?), but also confusing, since it mentions ```null```, linked to ```Data.Foldable```, instead of the string ```"null"```.

What is ```languageFileExtension``` used for? In the case of IHaskell, I don't think it can be saying that an IHaskell notebook is a ```.hs``` file, so this also deserves more documentation.

(The ```languageVersion``` documentation is missing an “e.g.,”.)

Seen in 72ccad9b08c028911c96e153cca100d0bcb5a71b: The documentation of ```banner```, now split over two lines, looks even more cryptic than before. Are the parentheses intended to be part of the “e.g.” example? Or is the content of the parentheses intended to be two examples? Since the type of banner is ```String```, having strings as examples would be more precise.

**Comment by sumitsahrawat** [comment]
> If yes: Is there any relation between the "0.0" here, and the ipython-kernel version number 0.8.4.0?

No, nope.

I'm not sure about the questions you've raised. Only @gibiansky can say more about that.

Those changes are meant to satisfy the formatting specification (enforced by `hindent`). I agree that it could be made clearer by using quotes to specify a `String`.

**Comment by gibiansky** [comment]
@WolframKahl To answer some of the questions:

- `kernelProtocolVersion`: The Jupyter project versions their protocols, but newer frontends can talk to older kernels. So if our kernel serves protocol 4.0, the Jupyter frontend can potentially automatically convert it to version 5.0 on its side; however, it needs to know what protocol the kernel expects. That is what this `kernelProtocolVersion` is. I believe we support 4.0 and most of 5.0 (they overlap greatly so I'm actually not 100% sure).
- `implementation` and `implementationVersion` could definitely be made configurable.
- `languageFileExtension` is the file extension that will be appended when you 'Save As'. It makes less sense in Haskell, because an IHaskell notebook not necessarily a valid `.hs` file; in Python though any notebook can be converted to a script. 
- `languageCodeMirrorMode` is the mode that will be set for the [CodeMirror editor](https://codemirror.net/) in the notebook view. You are right that `null` should not link to `Data.Foldable`.

Let me know if you have any more questions – and let's keep this issue open so that we can fix all these confusing points. 

I have been away from IHaskell for a while but soon should have time to return and do some cleanup and maintenance.

**Comment by gibiansky** [comment]
(Sorry, didn't mean to close it.)
