### ISSUE TITLE
What and where is “character concealing”?

### ISSUE THREAD

**Issue by WolframKahl** [gibiansky/IHaskell#667]
The IHaskell wiki homepage https://github.com/gibiansky/IHaskell/wiki mentions “automatic character concealing (typing -> yields an arrow)”: How do I get that effect in IHaskell notebooks? (I currently see nothing in that direction.)

And if it exists, where is its source code? (Searching for “conceal” in all files of the project finds nothing.)

**Comment by sumitsahrawat** [comment]
I think this feature has been removed.

**Comment by WolframKahl** [comment]
Thank you, @sumitsahrawat , for your prompt replies!

**Comment by gibiansky** [comment]
Indeed this feature has been removed because it quite often caused problems with layout (since IHaskell relies on whitespace, features that change the spacing of characters (such as -> to an arrow) can cause semantic problems and parsing issues that seem nonsensical)
