### ISSUE TITLE
In ipython-kernel, in EasyKernel, the KernelConfig parameter type output is unreachable?

### ISSUE THREAD

**Issue by WolframKahl** [gibiansky/IHaskell#668]
In `IHaskell.IPython.EasyKernel`, the type parameter `output` to `KernelConfig` seems to be unused: `run` gets a function of type `output -> IO ()` as argument, but nothing in `KernelConfig` can create `output`. Is this intended for a future extension, or is it outdated?

**Comment by vaibhavsagar** [comment]
It's [used in ICryptol](https://github.com/GaloisInc/ICryptol/blob/323c40969d3fceacfe652d164ea85ec27921bb64/src/Main_notebook.hs#L52), which is why this work was originally contributed.
