### ISSUE TITLE
Allow ihaskell convert to take input from stdin and output to stdout

### ISSUE THREAD

**Issue by rehno-lindeque** [gibiansky/IHaskell#672]
The `ihaskell convert` command implemented in #180 is great (I was surprised to see how well it works). I'd quite like to use it in a similar way to https://github.com/kynan/nbstripout, by configuring a git hook as follows:

```
git config filter.lhsconvert.clean 'ihaskell convert'
git config filter.lhsconvert.smudge cat
git config filter.lhsconvert.required true
```

```
*.ipynb filter=nbstripout
```

Unfortunately git filters need to pipe using stdin / stdout. Would it be possible to adapt `ihaskell convert` to allow for this use?

**Comment by gibiansky** [comment]
Can you use `/dev/stdin` and `/dev/stdout` as inputs to IHaskell `convert`? As in, `ihaskell convert --input=/dev/stdin --output=/dev/stdout`?

**Comment by rehno-lindeque** [comment]
I think I tried something like this before with process substitution before; suspect there may be a bug that prevents this from working:

```
$ cat notebooks/test.ipynb | ihaskell convert --input=/dev/stdin --output=/dev/stdout
ihaskell: Error: direction for conversion unknown
$ cat notebooks/package-associations.ipynb | ihaskell convert --input=/dev/stdin --output=/dev/stdout --from=ipynb --to=lhs
ihaskell: IHaskell.Convert.mergeArg: impossible argument: ConvertFromFormat IpynbFile
```

**Comment by vaibhavsagar** [comment]
This works after #1062:

```bash
cat notebooks/IHaskell.ipynb | ihaskell convert --input=/dev/stdin --output=/dev/stdout --force --to=lhs
```

**Comment by rehno-lindeque** [comment]
Thank you for this fix, much appreciated.
