### ISSUE TITLE
Kernel keeps running out of memory

### ISSUE THREAD

**Issue by 2426021684** [gibiansky/IHaskell#679]
Kernel runs out of memory
```
WARNING:root:kernel <x> restarted
ihaskell: out of memory (requested 2097152 bytes)
```
This is with the docker image

**Comment by gibiansky** [comment]
What are you doing in order to trigger this?

**Comment by 2426021684** [comment]
Not sure happened randomly. I stopped using docker once I got the native install working. I was just running simple haskell programs. I ran them again after restarting and they worked.

**Comment by gibiansky** [comment]
Got it. I can't currently reproduce this so I am closing this but if I encounter it (or anyone can help me reproduce it) please re-open.

I'll be adding a benchmark which might help diagnose memory issues as well.
