### ISSUE TITLE
Best way to use Jupyter + IHaskell + Python 3?

### ISSUE THREAD

**Issue by piquan** [gibiansky/IHaskell#681]
I've been enjoying using Jupyter + IHaskell, but I'd like to have a Jupyter instance with both Python 3 + SciPy and IHaskell kernels.  The IHaskell docs strongly recommend using the Docker container, but it seems that the container only provides a Python 2 kernel.

Can you give me a push in the right direction to set this up?  Thanks!

**Comment by sumitsahrawat** [comment]
You could set up a separate docker image with the required components, and then use docker compose to merge them into one. This would allow you to add and remove additional components as required.

The second way would be to modify the current image to accept an environmental variable as an argument, and use it to decide which version of python to use. This is less flexible.

**Comment by rehno-lindeque** [comment]
I have a little sample nix environment that includes python 3.4 if you would like to try an alternative method: https://github.com/rehno-lindeque/nix-jupyter-env

It's pretty simple to use if you have nix, just git clone it and run `nix-shell` in the root directory (and then pray it works on your platform...).

Disclaimer: For my own use at the moment, I don't make an effort to maintain it

**Comment by gibiansky** [comment]
If you would like to use the same installation of Jupyter for Haskell and Python 3, you will have to install IHaskell from source. However, there's no reason to do so most of the time -- you can fire up the Docker container when you want to use Haskell, and use your other installation when you want to use Python 3.
