### ISSUE TITLE
Debug try.jupyter.org

### ISSUE THREAD

**Issue by gibiansky** [gibiansky/IHaskell#683]
It's broken in IHaskell.

**Comment by agocorona** [comment]
I returned to https://try.jupyter.org/ after some months and it stay broken. What happens?

**Comment by gibiansky** [comment]
It's still broken.

Sadly I have not yet gotten a chance to fix it.

(If anyone wants to jump in and figure out why, they are welcome to do so! You can find the Dockerfile in the tmpnb repository and play with it.)

**Comment by agocorona** [comment]
Thanks I will take a look at it

**Comment by agocorona** [comment]
How I can add the IHaskell kernel to it?

**Comment by gibiansky** [comment]
The Dockerfile used for tmpnb is here: https://github.com/jupyter/docker-demo-images/blob/master/Dockerfile

If you were to fix the Dockerfile it would work

IHaskell is [here](https://github.com/jupyter/docker-demo-images/blob/master/Dockerfile#L101)

It's an old version that uses `cabal` instead of Stack for installation, but I'm not sure why it doesn't work. a first step would be to at least get this Dockerfile set up and fix the installation in the Dockerfile to a recent IHaskell using `stack` to install it

**Comment by sumitsahrawat** [comment]
I'll try and see if I can fix this.

**Comment by vaibhavsagar** [comment]
I fixed it (for now)! https://github.com/jupyter/docker-demo-images/pull/105
