### ISSUE TITLE
Image resolution

### ISSUE THREAD

**Issue by acowley** [gibiansky/IHaskell#684]
Something I do fairly regularly is vendor `ihaskell-diagrams` so that I can change [this line](https://github.com/gibiansky/IHaskell/blob/master/ihaskell-display/ihaskell-diagrams/IHaskell/Display/Diagrams.hs#L27) to increase the output image resolution. Is there some way that could be a runtime parameter?

**Comment by vaibhavsagar** [comment]
Maybe it could be an `IORef` that's set to `300` and exported from the library so it can be changed as required? What do you think?

**Comment by acowley** [comment]
It’s not the Haskelliest thing in the world, but it looks like it’ll be effective. Thanks for following up on this!

**Comment by vaibhavsagar** [comment]
My pleasure, sorry it took so long!
