### ISSUE TITLE
Option to ignore `module` declarations

### ISSUE THREAD

**Issue by acowley** [gibiansky/IHaskell#685]
I typically use IHaskell with source files that I also use with other Haskell build tools. Something I'd like to improve is that I'd like to be able to treat my notebook files as modules other than `Main`, which requires giving them a `module` declaration. As I understand what happens, `IHaskell` interprets a block of code that _can_ be parsed as a full Haskell module _as_ a full Haskell module. This breaks things for me, as it means subsequent blocks of code sent to IHaskell intended to be part of that module are treated independently.

I can work around this problem by ensuring that the `module` line is in its own source block that gets passed to IHaskell. This requires some care in document creation, but, as it happens, it also confuses emacs's notion of the current working directory which I then have to reset after the `module` block using a `:!cd` IHaskell command. All in all, not pretty.

Please tell me if there is an existing way of dealing with this. If not, my plan is to add an `ignoreModuleDeclarations` field to `KernelState` so I can set that IHaskell option and have it simply ignore the entire `module Foo (..) where` part of any input string. Does that sound reasonable?

**Comment by gibiansky** [comment]
Honestly the module support is somewhat half-baked anyways, and requires awkwardly writing temporary files into the current directory... It might make sense just to get rid of entirely...

**Comment by acowley** [comment]
What was the intention behind the existing thing, btw? When figuring out my own problem, I looked at what was happening and I couldn't come up with how I'd use it given that the module's contents have to be supplied in a single shot.

**Comment by gibiansky** [comment]
It compiles the module to object code not bytecode, so it's much faster. Allows obtaining GHC speeds in an interactive context.

**Comment by acowley** [comment]
Oh, that is appealing! I apologize for not looking this up myself, but if a module is imported via a typical `import` statement, is it not also loaded as object code? I do break some of my notebook work into separate modules, but I just import them the usual way.

**Comment by gibiansky** [comment]
If a module is imported via `import`, it should be loaded as object code; what IHaskell does allows the notebook to be the *entire* document, rather than having to be augmented with a file.

**Comment by acowley** [comment]
Yes, I really like the flexibility it provides in how one defines a top-level. So should I think about adding another `KernelState` field, or would you prefer I polish my work around until it's less irritating?
