### ISSUE TITLE
Kernel dies when opening new notebook if widgetsnbextension enabled

### ISSUE THREAD

**Issue by jmbromley** [gibiansky/IHaskell#688]
Steps to reproduce:
- Install latest stable jupyter suite using: `pip install jupyter`, [this will also pull in version 5.2.2 of ipywidgets and 1.2.6 of widgetsnbextension]
- Install IHaskell
- Run `jupyter notebook`.  IHaskell notebooks should run fine.
- Shutdown the notebook server.
- Run `jupyter nbextension enable --py widgetsnbextension` to enable the widgets extension.
- Run `jupyter notebook` again.
- Upon starting an IHaskell notebook the kernel will die quite quickly (without the user even having to evaluate any cells).  After automatically restarting the kernel then _seems_ to behave fine, although I have not tested it exhaustively.  Opening a new IHaskell notebook causes the same thing to occur again.

**Comment by vaibhavsagar** [comment]
Are you still experiencing this? IIRC the widgets extension doesn't need to be enabled explicitly now.

**Comment by vaibhavsagar** [comment]
Closing, please reopen if you are still seeing this.
