### ISSUE TITLE
Kernel not working and unable to restart (Dead kernel)

### ISSUE THREAD

**Issue by dario-castano** [gibiansky/IHaskell#689]
Tested in Xubuntu 16.04 and openSUSE tumbleweed. Both OS shows the same behaviour.

Steps to replicate
1. Install ghc, cabal and dependencies using apt (xubuntu) or zypper (opensuse)
2. cabal install ihaskell
3. ihaskell install
4. Open a jupyter-notebook and create a new haskell notebook

[I 23:58:15.764 NotebookApp] Serving notebooks from local directory: /home/dario/Documents
[I 23:58:15.765 NotebookApp] 0 active kernels 
[I 23:58:15.765 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 23:58:15.765 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Created new window in existing browser session.
[I 23:58:25.190 NotebookApp] Creating new notebook in 
[W 23:58:26.216 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20160831235815 (127.0.0.1) 13.51ms referer=http://localhost:8888/notebooks/Untitled1.ipynb?kernel_name=haskell
[I 23:58:26.342 NotebookApp] Kernel started: 474096e6-921f-420b-af03-53e14e2180f6
[W 23:58:26.427 NotebookApp] 404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js?v=20160831235815 (127.0.0.1) 1.90ms referer=http://localhost:8888/notebooks/Untitled1.ipynb?kernel_name=haskell
ihaskell: /home/dario/.cabal/lib/x86_64-linux-ghc-7.10.3/cryptonite-0.19-9fTgDVqlngxExANMsHUBS7/libHScryptonite-0.19-9fTgDVqlngxExANMsHUBS7.a: unhandled ELF relocation(RelA) type 42

ihaskell: ihaskell: unable to load package `cryptonite-0.19'

**Comment by vaibhavsagar** [comment]
Is this still an issue?

**Comment by vaibhavsagar** [comment]
Closing.
