### ISSUE TITLE
Support using IHaskell with GHC 8

### ISSUE THREAD

**Issue by vaibhavsagar** [gibiansky/IHaskell#690]
Now that LTS-7.0 is out, I'd like to use IHaskell with GHC 8. It looks like this will require changes to at least `ghc-parser`. Is this something you're planning to support soon?

**Comment by gibiansky** [comment]
This is perhaps a somewhat unsatisfactory answer, but I am currently working on a largely refactored and cleaned up IHaskell (`1.0`) that will support 7.10 and 8.0 (but not anything before 7.10). `ghc-parser` will no longer exist at that point, as it currently exists solely for the sake of maintaining support for pre-7.10 GHC versions. It is unlikely that IHaskell 1.0 will be out in the next few weeks, but probably within the next 2 months.

**Comment by vaibhavsagar** [comment]
This is really exciting and not unsatisfactory at all, thanks for getting back to me! Feel free to close.

**Comment by dabro** [comment]
I agree, great news.  For a stack and haskell newbie, how to run IHaskell in the meantime?  In a way that can be run in Jupyter from any directory?

**Comment by vaibhavsagar** [comment]
Hi @dabro, you should be able to

1. `stack install ihaskell --resolver lts-6.17`
2. `ihaskell install --stack`
3. `stack exec jupyter notebook`

to get an IHaskell notebook from any directory.

**Comment by dabro** [comment]
Thanks.  First line:
```
$ stack install ihaskell --resolver lts-6.17
Run from outside a project, using implicit global project config
Using resolver: lts-6.17 specified on command line
Downloaded lts-6.17 build plan.
No compiler found, expected minor version match with ghc-7.10.3 (x86_64) (based on resolver setting in /Users/browneej/.stack/global-project/stack.yaml).
Try running "stack setup" to install the correct GHC into /Users/browneej/.stack/programs/x86_64-osx/
```
I realize I'm missing a really simple stack concept--what is it?

**Comment by dabro** [comment]
Follow-up on the above.

When I start jupyter notebook with `stack exec jupyter notebook --resolver lts-6.17`, I am able to run ihaskell notebooks within my IHaskell directory with no issues.

However, if I move them out to another data/project folder (same jupyter instance still running), the kernel crashes on launch:
```
[I 10:42:31.016 NotebookApp] Kernel started: f5049300-4408-4a51-bb2a-a1cdedc1a85f
Run from outside a project, using implicit global project config
ihaskell: /Users/browneej/.stack/programs/x86_64-osx/ghc-8.0.1/lib/ghc-8.0.1/package.conf.d/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (not enough bytes)
[I 10:42:34.018 NotebookApp] KernelRestarter: restarting kernel (1/5)
Run from outside a project, using implicit global project config
ihaskell: /Users/browneej/.stack/programs/x86_64-osx/ghc-8.0.1/lib/ghc-8.0.1/package.conf.d/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (not enough bytes)
```

so ihaskell seems to be trying to use ghc 8.  The project folder doesn't have a `stack.yaml` file in it, unlike the ihaskell folder, but I provided the resolver with stack exec at beginning.  Should that affect it?

**Comment by vaibhavsagar** [comment]
Hey @dabro, it sounds like your global project has a resolver of `lts-7.0` or above and you've installed ihaskell with the `--stack` option which gets it to inherit the `stack` environment. I get the same thing when I try to use `ihaskell` outside a project with a `lts-6.x` resolver because I have the same setup.

**Comment by dabro** [comment]
@vaibhavsagar , guess I don't understand stack very well.  I'd think passing the `--resolver lts-6.17` command line argument would removed need to have that setting in a `stack.yaml` file in the appropriate .ipynb folder...

**Comment by vaibhavsagar** [comment]
Hey @dabro, I'm not an expert either but I think this might be due to [the way IHaskell works with `stack`](https://github.com/gibiansky/IHaskell/blob/master/main/Main.hs#L148-L154)

**Comment by vaibhavsagar** [comment]
Alternatively, you could change your resolver in `~/.stack/global-project/stack.yaml` to `lts-6.25` and that might fix it.

**Comment by dabro** [comment]
Sadly, the only thing that seems to work is having a `stack.yaml` file in the folder containing the `*.ipynb` file.

**Comment by benzrf** [comment]
Hey, is 1.0 still something being worked on?

**Comment by gibiansky** [comment]
@benzrf Sadly, not actively.

For the past few months I have not had much time (or sadly motivation) to work on IHaskell maintenance and upgrades. I hope that I will get back to it soon. I am happy to accept more external contributions and maintenance help, though.

**Comment by vaibhavsagar** [comment]
Is there anything in particular we can help with?

**Comment by vaibhavsagar** [comment]
I just discovered @abarbu's fork and so far it's working well with GHC 8: https://github.com/abarbu/IHaskell. Hopefully we can integrate these changes back into IHaskell soon :smile:

**Comment by vaibhavsagar** [comment]
Changes have been integrated into IHaskell!
