### ISSUE TITLE
Is it possible to use IHaskell Jupyer notebook/console just like `stack ghci` works?

### ISSUE THREAD

**Issue by Wizek** [gibiansky/IHaskell#692]
I've tried the following things.

Within the project folder, run:

```
stack exec --test -- jupyter-notebook
```

then try to

```
import MainSpec
```

Which gives me: `Failed to load interface for ‘MainSpec’`

I also tried

```
:set -package hs-di
```

Which gave me: `Warning: -package not supported yet`

Am I missing something? Or is it perhaps not (yet) possible to use Jupyter & IHaskell just like `stack ghci` woks -- that is to be able to import modules and run code within the context of a package?

**Comment by mgsloan** [comment]
The way intero gets run is like this - `stack ghci --test --with-ghc intero`.  So if you have an executable that can pretend to be `ghci` and process the same CLI flags, it should work fine.

**Comment by Wizek** [comment]
Thanks for the reply, I'm glad to hear that it should work in theory! Although I am quite new to IHaskell and Jupyter both, so not really sure how to execute your response. Would you be willing to say what I could write on the CLI to make sure the notebook uses `stack ghci --test --with-ghc intero`? 

<hr>

Without high hopes I tried to run that as a command itself (since `intero` is not even an executable on my path) and sure enough stack complained: `Executable named intero not found on path: ...`

I've also tried to look in `jupyter-notebook --help` to see if I can find any way to influence what the kernel executes when starting up -- without luck.

I've also tried to look in `ihaskell --help` for relevant flags, and `ihaskell install --stack` did seem promising, especially when it completed successfully in a few seconds, but I didn't observe any changes in the available packages within my notebook afterwards.

**Comment by mgsloan** [comment]
Yeah, you need to "stack build intero" for that to be available. The emacs integration for intero does that automatically

Not sure how to do it with ihaskell. I haven't used it much but i watch this repo because it's a cool project.

**Comment by vaibhavsagar** [comment]
Closing, as it is unlikely we will ever have first-class integration with Stack.
