### ISSUE TITLE
Lines with code output overflow in Latex output

### ISSUE THREAD

**Issue by dzackgarza** [gibiansky/IHaskell#693]
I'm not quite sure if this is more of a Latex issue than an iHaskell one, but since I wasn't able to find much info I figured I'd post here!

if I run a notebook, then choose File -> Download As -> PDF via Latex, some longer lines whose output is just wrapped (according to the width of the window) end up overflowing the margins in the PDF output.

For example, here's what one output looks like in the notebook:
![image](https://cloud.githubusercontent.com/assets/1149853/18901825/122b733e-8503-11e6-8e2c-738ade30d5fb.png)

And here's what the corresponding output in the PDF looks like:
![image](https://cloud.githubusercontent.com/assets/1149853/18901841/2fe26db0-8503-11e6-802c-424e8ddc7b3d.png)

The same sort of thing happens with long lines within code cells too:
![image](https://cloud.githubusercontent.com/assets/1149853/18901864/637f9670-8503-11e6-8e9a-dff88300debe.png)

Is it possible to alter the style file that iHaskell uses perhaps?

**Comment by leftaroundabout** [comment]
I reckon the conversion from monospace-code cells to LaTeX is handled by Jupyter, there's not much we could sensibly do about that. (LaTeX's `verbatim` environments never do line-breaking.)

The way to avoid this is to not have long lines in the first place. For code cells, you can easily enough control that; for output cells, you can use a pretty-printer, e.g. [`pretty-show`](http://hackage.haskell.org/package/pretty-show-1.6.13/docs/Text-Show-Pretty.html), or define your own [`IHaskellDisplay`](https://www.stackage.org/haddock/lts-6.35/ihaskell-0.8.4.0/IHaskell-Display.html) instance.

**Comment by vaibhavsagar** [comment]
It looks like the current conversion does correctly wrap long lines, so I'm closing this. Please reopen if necessary.
