### ISSUE TITLE
How to exit console?

### ISSUE THREAD

**Issue by jluttine** [gibiansky/IHaskell#695]
Thanks for the great IHaskell package! I'm just learning both Haskell and IHaskell. However, when starting with `jupyter console --kernel haskell`, I don't know how to exit the console. `:quit` doesn't work. So how can I exit?

**Comment by razzius** [comment]
Send an EOF with Control-D

```
$ jupyter console --kernel haskell
Jupyter console 5.1.0

IHaskell 0.8.4.0 GHC 7.10.3


In [1]: ^D
Do you really want to exit ([y]/n)? ^D
Shutting down kernel
```

**Comment by vaibhavsagar** [comment]
Closing.
