### ISSUE TITLE
IHaskell not finding packages (when using stack)

### ISSUE THREAD

**Issue by jluttine** [gibiansky/IHaskell#698]
(This might be duplicate of another issue https://github.com/gibiansky/IHaskell/issues/581#issuecomment-250975698 where I already gave this exact same comment.)

Hi! I'm experiencing an issue that packages are not found in IHaskell.

Here are steps to reproduce from scratch (moved my current `~/.stack` elsewhere) and outside any project directories:

Set up:

```
stack setup --resolver=lts-6.15
```

Change resolver to lts-6.15:

```
vim ~/.stack/global-project/stack.yaml
```

Install IHaskell (make sure `~/.local/bin` is in `PATH`):

```
stack install ihaskell
stack exec ihaskell -- install --stack
```

Install some other package:

```
stack install hmatrix
```

Start Jupyter console:

```
stack exec jupyter -- console --kernel haskell
```

Try to import hmatrix:

```
In [1]: import Numeric.LinearAlgebra
      :     
Failed to load interface for ‘Numeric.LinearAlgebra’
Use -v to see a list of the files searched for.
```

Try GHCi for comparison:

```
stack exec ghci
```

Importing hmatrix works:

```
Prelude> import Numeric.LinearAlgebra
Prelude Numeric.LinearAlgebra> 
```

Any ideas what I'm missing?

**Comment by benjamintanweihao** [comment]
I'm having similar problems with installing `random-1.1`. Any ideas?

**Comment by benjamintanweihao** [comment]
Minutes after writing this, I think I have a solution:

1. Add the dependencies in the `stack.yaml` file.
2. Run `stack build`.
3. Run `ihaskell install --stack` (This is the key step)

Somehow after this I could do `import System.Random`. 💃

**Comment by vaibhavsagar** [comment]
@jluttine have you tried `ihaskell install --stack`?

**Comment by jluttine** [comment]
I only tried those steps I listed above. I haven't been doing stuff related to this recently, but I'll keep that in mind when I'll try next time. Thanks!

**Comment by vaibhavsagar** [comment]
Great, I will close this.
