### ISSUE TITLE
getLine support under Jupyter notebook

### ISSUE THREAD

**Issue by kprav33n** [gibiansky/IHaskell#701]
I installed IHaskell on Mac using `stack install ihaskell`. Then, I ran `ihaskell install` to install the kernel to be used with Jupyter. Later, when I started Jupyter Haskell notebook, I'm not able to get the following example to work.

``` haskell
getLine >>= putStrLn
```

I get the following (error) message: `: hGetLine: end of file`. Is this a real issue, or am I using it in a nonsensical way?

**Comment by EvanZ** [comment]
Wondering if anyone has an answer to this now?

**Comment by leftaroundabout** [comment]
I don't think you can access STDIN in IHaskell, but I also really don't see why you'd want to. Anything you could enter there can be better written directly in code cells.

**Comment by gibiansky** [comment]
@leftaroundabout You actually can, but the functionality might be broken; it seems likely it was broken in the GHC 7 -> 8 transition. Support for stdin is [here](https://github.com/gibiansky/IHaskell/blob/master/src/IHaskell/IPython/Stdin.hs).

**Comment by vaibhavsagar** [comment]
This works fine for me on Linux. Is this still an issue for you?

**Comment by gasparka** [comment]
I am using IHaskell to follow examples from the "Get programming with Haskell" book - all good, until i made it to the IO section:

```haskell
main :: IO ()
main = do
    putStrLn "Your name?"
    name <- getLine
    putStrLn name
    
main
```

```
<stdin>: hGetLine: end of file
```

**Comment by leftaroundabout** [comment]
@gasparka as I already commented above: _it doesn't make sense_ to fetch from STDIN in IHaskell. Maybe it would be nice for the sake of completeness if this would be supported anyways, but there's really no good reason to ever use that feature.

If you want to learn IO in Haskell, either write small executables and run them outside of IHaskell, or use file IO instead of STDIO. For example,

```haskell
fName = "request.txt"

createFile :: IO ()
createFile = do
    writeFile fName "Dummy text"
    putStrLn $ "File "++fName++" has been created."
    
createFile
```
...Execute that cell, then open the file with an external editor, optionally edit&save it...
```haskell
retrieveFile :: IO ()
retrieveFile = do
    contents <- readFile fName
    putStrLn $ "File "++fName++" contains the following text:"
    putStrLn contents    

retrieveFile
```

**Comment by gasparka** [comment]
@leftaroundabout 
I understand your argument and you are probably right .. but it is still worth fixing because already 3 people have ran into this. Maybe i can tackle this issue after i finish the book :)

I will be using your workaround for now, thanks!

**Comment by vaibhavsagar** [comment]
Can you try this outside a Docker container? It seems to work for me with my Nix setup, which makes me suspect it might work with Stack too.

**Comment by gasparka** [comment]
Yes! Works outside of Docker.

**Comment by gasparka** [comment]
I regularly update my system using Pacman. Apparently one of such update broke the 'getLine' functionality (Stack install). No Luck with reinstalling IHaskell.
Price for the bleeding-edge system, i guess.

**Comment by daviddavo** [comment]
Not working for me either

**Comment by daiba** [comment]
Not working for me either. My environments as follows:
```
$ ihaskell --version
0.10.1.1

$ stack ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 8.8.3

$ stack --version
Version 2.3.1, Git revision de2a7b694f07de7e6cf17f8c92338c16286b2878 (8103 commits) x86_64 hpack-0.33.0

$ ps aux | grep ihaskell | grep -v grep | sed 's/[ ]\+/ /g' | cut -d ' ' -f 11-
/home/me/.local/bin/ihaskell kernel /home/me/.local/share/jupyter/runtime/kernel-ad930601-b76c-447f-812d-076c0e415a06.json --ghclib /home/me/.stack/programs/x86_64-linux/ghc-8.8.3/lib/ghc-8.8.3 +RTS -M3g -N2 -RTS --stack

stack$ cat ~/.local/share/jupyter/runtime/kernel-ad930601-b76c-447f-812d-076c0e415a06.json 
{
  "shell_port": 52949,
  "iopub_port": 46521,
  "stdin_port": 35053,
  "control_port": 57339,
  "hb_port": 33481,
  "ip": "127.0.0.1",
  "key": "62b90b83-8ac9347a45a19e2001bbb0ed",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": "haskell"

$ cat .ihaskell/.kernel-profile 
Profile {ip = "127.0.0.1", transport = TCP, stdinPort = 35053, controlPort = 57339, hbPort = 33481, shellPort = 52949, iopubPort = 46521, signatureKey = "62b90b83-8ac9347a45a19e2001bbb0ed"}

$ lsof -i -P -n | grep ihaskell
ihaskell  692  me    22u  IPv4  32557      0t0  TCP 127.0.0.1:33481 (LISTEN)
ihaskell  692  me    24u  IPv4  32559      0t0  TCP 127.0.0.1:57339 (LISTEN)
ihaskell  692  me    26u  IPv4  32561      0t0  TCP 127.0.0.1:52949 (LISTEN)
ihaskell  692  me    27u  IPv4  32563      0t0  TCP 127.0.0.1:46521 (LISTEN)
ihaskell  692  me    28u  IPv4  32573      0t0  TCP 127.0.0.1:57339->127.0.0.1:55888 (ESTABLISHED)
ihaskell  692  me    29u  IPv4  32577      0t0  TCP 127.0.0.1:46521->127.0.0.1:52170 (ESTABLISHED)
ihaskell  692  me    30u  IPv4  32601      0t0  TCP 127.0.0.1:52949->127.0.0.1:56960 (ESTABLISHED)
ihaskell  692  me    31u  IPv4  32602      0t0  TCP 127.0.0.1:57339->127.0.0.1:55912 (ESTABLISHED)
ihaskell  692  me    32u  IPv4  32603      0t0  TCP 127.0.0.1:46521->127.0.0.1:52190 (ESTABLISHED)

$ jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.4
ipython          : 7.14.0
ipykernel        : 5.3.0
jupyter client   : 6.1.3
jupyter lab      : not installed
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.6
traitlets        : 4.3.3
```
stdin port not found. Are there any check points ?

**Comment by vaibhavsagar** [comment]
Can you share a small code sample that doesn't work for you?

**Comment by daiba** [comment]
The code is
```
getLine
```
and I get an message "\<stdin\>: hGetLine: end of file".

According from debug log:
request is:
```
Content: {"code":"getLine","silent":false,"store_history":true,"user_expressions":{},"allow_stdin":true,"stop_on_error":true}
```

and reply:
```
Message: ExecuteError {header = MessageHeader {mhIdentifiers = ["dad30fea3eef4400bc2dd2dda3855756"], mhParentHeader = Just (MessageHeader {mhIdentifiers = ["dad30fea3eef4400bc2dd2dda3855756"], mhParentHeader = Nothing, mhMetadata = Metadata (fromList []), mhMessageId = UUID {uuidToString = "c2217fc568494c7f8c3aee34007209f4"}, mhSessionId = UUID {uuidToString = "dad30fea3eef4400bc2dd2dda3855756"}, mhUsername = "username", mhMsgType = ExecuteRequestMessage, mhBuffers = []}), mhMetadata = Metadata (fromList []), mhMessageId = UUID {uuidToString = "1c989d69-0fb7-41c9-bbc9-f5d48214f488"}, mhSessionId = UUID {uuidToString = "dad30fea3eef4400bc2dd2dda3855756"}, mhUsername = "username", mhMsgType = ExecuteErrorMessage, mhBuffers = []}, traceback = ["<stdin>: hGetLine: end of file"], ename = "", evalue = ""}
```

**Comment by daiba** [comment]
I think I got it. For my case, it because IHaskell.IPython.Stdin not included in global project. I installed ihaskell with:
```
curl -sSL https://get.haskellstack.org/ | sh
git clone https://github.com/gibiansky/IHaskell
cd IHaskell
pip3 install -r requirements.txt
stack install --fast
ihaskell install --stack
```
When I followed this steps, I installed ihaskell, but not installed IHaskell.* . So, ihaskell can run, but can't read IHaskell.IPython.Stdin then I can't use getLine, I think. 

What I do is reinstall ihaskell by:
```
stack install ihaskell
```
with
```
extra-deps:
- ghc-parser-0.2.2.0
```
It's not work getLine either, but when I add ihaskell to the extra-deps:
```
extra-deps:
- ghc-parser-0.2.2.0
- ihaskell-0.10.1.1
```
I can use getLine in ihaskell.

**Comment by jamesdbrock** [comment]
I had this problem when I was adapting *Learn You a Haskell for Great Good* to JupyterLab and my workaround was to make a `withStdin` function which supplies a string to standard input so that `getLine` has something to read: https://github.com/jamesdbrock/learn-you-a-haskell-notebook/blob/master/notebook/09-input-and-output.ipynb
