### ISSUE TITLE
Able to `:set args` like ghci?

### ISSUE THREAD

**Issue by dabro** [gibiansky/IHaskell#702]
In ghci once can artificially set command line options to support those functions that access them with `getArgs`.  This is quite useful in testing, or in using previously written code.

Any chance of adding this option to iHaskell?

Truly awesome project...This is the way of the future; I think the CLI is irreplaceable but needs to move from a 1970's terminal focus to 2000's html page basis.

**Comment by vaibhavsagar** [comment]
Can you use [`withArgs`](http://hackage.haskell.org/package/base-4.12.0.0/docs/System-Environment.html#v:withArgs)?

**Comment by vaibhavsagar** [comment]
Closing this, please reopen if necessary.
