### ISSUE TITLE
try.jupiter.org IHaskell not work?

### ISSUE THREAD

**Issue by dabro** [gibiansky/IHaskell#703]
Don't know if this is just me, but I've tried running IHaskell at [try.jupyter.org](try.jupyter.org) multiple times in the last two weeks, and have never gotten a reply back from wherever the kernel is running.  Input just stays '*' until the page reports a lost connection.

**Comment by typedeph** [comment]
Wanted to second this. I try to execute any of the cells and nothing returns.

**Comment by tbenst** [comment]
Confirmed. Times out on any cell

> A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration.

**Comment by Kludgy** [comment]
Same here. Is this maintained anymore? Can I debug/contribute in any way?

**Comment by sumitsahrawat** [comment]
Duplicate of #683.
