### ISSUE TITLE
Add ihaskell-display module

### ISSUE THREAD

**Issue by praalhans** [gibiansky/IHaskell#706]
More of a semi pull request than a bug report. I created

https://github.com/praalhans/ihaskell-test

to let any `Test` in [`Test.HUnit.Base`](https://hackage.haskell.org/package/HUnit-1.5.0.0/docs/Test-HUnit-Base.html) automatically executed and reported upon. This promotes the use of tests within a Notebook. Indeed, this ensures that a Notebook is the combination of documentation, implementation and tests, which I found useful in my developments.

If the test fails (at least one error or one failure), the result is marked red and the information is shown in pre-formatted text. Otherwise, the result is marked green and the test summary is shown.

Thank you for IHaskell, I really enjoy using it.

**Comment by vaibhavsagar** [comment]
Please submit a PR if you would still like to have this included in IHaskell.
