### ISSUE TITLE
No Web Browser Found

### ISSUE THREAD

**Issue by typedeph** [gibiansky/IHaskell#709]
On Ubuntu 16.04 I get the following:
![No web browser found: could not locate runnable browser.](https://cloud.githubusercontent.com/assets/6923930/22767923/97b11808-ee4c-11e6-95fa-975013f21e6f.png)

**Comment by louwers** [comment]
You can ignore that. Just open a webbrowser and go to http://localhost:8888

**Comment by typedeph** [comment]
@louwers Awesome, thanks didn't realize it would work regardless.
