### ISSUE TITLE
Switch to python3, or freeze to IPython-5?

### ISSUE THREAD

**Issue by leftaroundabout** [gibiansky/IHaskell#718]
[Once again, Python breaks the Travis build](https://travis-ci.org/gibiansky/IHaskell/jobs/237582487). The reason being that [IPython-6.0, which was released in april](http://ipython.readthedocs.io/en/stable/whatsnew/version6.html#python-3-only-codebase), doesn't support python2 anymore.

I think IHaskell should go with the stream and use python3 in the install. As far as Travis is concerned, this should be accomplished with
```diff
diff --git a/.travis.yml b/.travis.yml
index 28a4ebe..0a0af8f 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -50,7 +50,7 @@ before_install:
     fi
 
     # Install nbconvert for testing the notebook
-  - pip install jupyter notebook nbconvert
+  - pip3 install jupyter notebook nbconvert
 
 # This step takes the longest, and is what generates the Stack cache. 
 install:
```
But the alternative `pip install 'jupyter<6'` is also worth considering.

Opinions?

**Comment by vaibhavsagar** [comment]
I personally think we should use Python 3. It's worked without any issues that I'm aware of for as long as I've used IHaskell.

**Comment by vaibhavsagar** [comment]
See #719
