### ISSUE TITLE
Please push a release to Hackage

### ISSUE THREAD

**Issue by vaibhavsagar** [gibiansky/IHaskell#720]
Amongst other things, this will allow me to undo https://github.com/NixOS/nixpkgs/pull/22268 which I have been itching to do for months.

**Comment by Anrock** [comment]
@gibiansky please?

**Comment by gibiansky** [comment]
@Anrock Thank you for the bump. Will do this week.

**Comment by gibiansky** [comment]
@Anrock @vaibhavsagar Version 0.9.0.0 has [been uploaded](https://hackage.haskell.org/package/ihaskell). I also pushed a commit updating the version number in the cabal file. This may affect other packages; if it does so, let me know. I also only uploaded `ihaskell`, not versions of `ipython-kernel` or other packages.

**Comment by vaibhavsagar** [comment]
Hey @gibiansky, can you push a new `ghc-parser` (and preferably `ipython-kernel`) release as well? I can't use `ihaskell` as a dependency because it depends on updates and changed version bounds in `ghc-parser` that are not on Hackage.

**Comment by gibiansky** [comment]
Alright, how about now?

**Comment by vaibhavsagar** [comment]
Waiting for the new `ipython-kernel` to propagate to the mirror I'm using, give me a few more minutes :smile:.

**Comment by vaibhavsagar** [comment]
Okay, it works for me if I set the `binPkgDb` flag to `False` in my `stack.yaml`. Would you consider merging my PR and cutting a new `ihaskell` release, maybe `0.9.0.1`?

**Comment by gibiansky** [comment]
Done.

**Comment by vaibhavsagar** [comment]
Wonderful, thanks so much!
