### ISSUE TITLE
Make IHaskell available on CoCalc

### ISSUE THREAD

**Issue by slel** [gibiansky/IHaskell#731]
Making IHaskell available on CoCalc would let anyone try it!
See https://github.com/sagemathinc/cocalc/issues/125

**Comment by vaibhavsagar** [comment]
As you can see, I attempted to get it working earlier :smile:. I got preoccupied with other things but I'd still love to see IHaskell on CoCalc so let me know what is the best way to help.

**Comment by dougie-** [comment]
i have also tried to install into jupyterhub instance with no success.

**Comment by vaibhavsagar** [comment]
Hi @dougie-, that sounds like a separate issue.

**Comment by vaibhavsagar** [comment]
https://twitter.com/cocalc_com/status/982668255495180289
