### ISSUE TITLE
macOS install requires files in `IHaskell/.stack-work`?

### ISSUE THREAD

**Issue by defjaf** [gibiansky/IHaskell#733]
Hi,

I'm very happy to see that the latest versions seems to work more-or-less perfectly on macOS again! Thanks for that.

I have installed things slightly differently from the description in the readme, using the `homebrew` `brew install haskell-stack` recipe rather than the shell script install -- so it's possible this is related to the issue that I am about  to explain:

At present, the `iHaskell` kernel seems to rely on files in the `.stack-work` directory under the cloned git repo; if I delete or move that directory, the kernel fails to start.

This was at first only true on my laptop, but with an attempt to upgrade to the latest git version it now appears to occur on both of my machines.

This isn't a show-stopper, of course, but it seems brittle.

See below for the error message from `jupyter` if I delete the `.stack-work` dir; I think the relevant part is the first section, explicitly referencing `.stack-work` , with the rest just showing the "upstream" repercussions.

```
[E 12:03:46.811 NotebookApp] Failed to run command:
    [u'/Users/jaffe/home/python/IHaskell/.stack-work/install/x86_64-osx/lts-9.0/8.0.2/bin/ihaskell', u'kernel', u'/Users/jaffe/Library/Jupyter/runtime/kernel-29b8c13f-b8ab-40a5-a7d2-924f3542e5e6.json', u'--ghclib', u'/Users/jaffe/.stack/programs/x86_64-osx/ghc-8.0.2/lib/ghc-8.0.2', u'--stack']
        PATH='/Library/Frameworks/Python.framework/Versions/2.7/bin:/Users/jaffe/.stack/global-project/.stack-work/install/x86_64-osx/lts-8.23/8.0.2/bin:/Users/jaffe/.stack/snapshots/x86_64-osx/lts-8.23/8.0.2/bin:/Users/jaffe/.stack/programs/x86_64-osx/ghc-8.0.2/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/jaffe/home/local/Healpix_3.31/src/cxx/osx/bin:/Users/jaffe/home/local/Healpix_3.31/bin_gfortran-7:/usr/local/sbin:/Users/jaffe/home/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/Users/jaffe/home/local/root/bin:/Users/jaffe/.local/bin'
        with kwargs:
    {'cwd': u'/Users/jaffe', 'stdin': -1, 'preexec_fn': <function <lambda> at 0x107c836e0>, 'stderr': None, 'stdout': None}

[E 12:03:46.823 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/notebook/base/handlers.py", line 516, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
   
     ... many lines removed ...

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
[E 12:03:46.825 NotebookApp] {
      "Origin": "http://localhost:8888",
      "Content-Length": "92",
      "Accept-Language": "en-gb",
      "Accept-Encoding": "gzip, deflate",
      "X-Xsrftoken": "2|0f5bd8ca|e408b44cdc323be838ac4fa146cea019|1501076514",
      "Host": "localhost:8888",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8",
      "Connection": "keep-alive",
      "X-Requested-With": "XMLHttpRequest",
      "Referer": "http://localhost:8888/notebooks/Untitled6.ipynb?kernel_name=haskell",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1501153424|23:username-localhost-8888|44:YjY0ZjQxM2YwNDgzNGE5Mjk0N2NlMWMzNjdkMzQ5ZjI=|c180f16f22a6991d1023f114e7c4f0c5e0bedddc9e973e1a6bbc0b93c59ddb99\"; username-localhost-8889=\"2|1:0|10:1501143571|23:username-localhost-8889|44:NTM2MTYyZGE0NDVjNDE4NWJiNmEyYzliNjBiMmNlMmU=|15f073d774d30ff2712ca8860b92b013746f4f6ab3f1a99731437f534359dcc3\"; _xsrf=2|0f5bd8ca|e408b44cdc323be838ac4fa146cea019|1501076514",
      "Content-Type": "application/json"
    }
[E 12:03:46.825 NotebookApp] 500 POST /api/sessions (::1) 47.83ms referer=http://localhost:8888/notebooks/Untitled6.ipynb?kernel_name=haskell
[W 12:03:46.870 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170727120343 (::1) 7.05ms referer=http://localhost:8888/notebooks/Untitled6.ipynb?kernel_name=haskell
[W 12:03:46.875 NotebookApp] 404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js?v=20170727120343 (::1) 1.37ms referer=http://localhost:8888/notebooks/Untitled6.ipynb?kernel_name=haskell

```

**Comment by vaibhavsagar** [comment]
This is interesting. Did you by any chance skip the `stack install --fast ihaskell` step? It looks like that might explain what you are experiencing, although it is possible that there are other dependencies on files in `.stack-work`.

**Comment by defjaf** [comment]
Nope, I've done that.

To be specific, `~/.local/bin/ihaskell` exists, as does `~/Library/Jupyter/kernels/haskell/`

Note that in my first attempt at installation, it did work on one machine but not the other. I then did a `git pull` and got an updated version, re-ran `stack install gtk2hs-buildtools`, `stack install --fast` and `stack exec ihaskell -- install --stack` and then saw this.

**Comment by vaibhavsagar** [comment]
I was misremembering the instructions, you have it right without `ihaskell` at the end of your `stack install` command.

What are the contents of `~/Library/Jupyter/kernels/haskell/kernel.json`?

**Comment by defjaf** [comment]
Yep, that clearly shows where the problem comes from:

```json
{
  "display_name":"Haskell",
  "argv":
      ["/Users/jaffe/home/python/IHaskell/.stack-work/install/x86_64-osx/lts-9.0/8.0.2/bin/ihaskell",
        "kernel",
        "{connection_file}",
        "--ghclib","/Users/jaffe/.stack/programs/x86_64-osx/ghc-8.0.2/lib/ghc-8.0.2",
        "--stack"],
  "language":"haskell"
}
```

I assume editing it so that the first line points to `.local/bin/ihaskell` will fix the problem? (But it's not clear how it got to that state...)

**Comment by vaibhavsagar** [comment]
Yeah, that might be it. What is the output of `which ihaskell`?

**Comment by defjaf** [comment]
`which ihaskell` still only finds the version in `~/.local/bin`, but `stack exec which ihaskell` gives the one in `.stack-work`... so that seems to be the issue somehow. But now my installation is in such a brittle state (e.g., I've modified my `.bashrc`) that even that depends on which terminal window I'm in -- I can even find some in which I pick up the `lts-8.*` install from the previous version...

**Comment by vaibhavsagar** [comment]
What I think happened:

1. You ran `stack install --fast` from the project directory. `ihaskell` was copied into `~/.local/bin/`
1. You then ran `stack exec -- ihaskell install --stack` as the instructions indicated. The `ihaskell` under `.stack-work/` took precedence over the `ihaskell` under `~/.local/bin` because `stack exec` changes the `$PATH` (to see this in action, try `stack exec env` inside and outside the project directory)
1. Although `~/.local/bin/ihaskell` is present, you end up with a `.stack-work` dependent path in your `kernel.json`

This is a bug in our install instructions and I'm not sure what the best way is to address it.

**Comment by defjaf** [comment]
So, just to be clear: `stack exec ihaskell -- install --stack` should *not* be run from the project dir?

**Comment by vaibhavsagar** [comment]
Alternatively, what happens if you try just `ihaskell install --stack`?

**Comment by defjaf** [comment]
Yep, either changing dirs and using `stack exec` or staying in the project dir without it both seem to give the correct `kernel.json`

**Comment by vaibhavsagar** [comment]
Great, I'll update the instructions accordingly. Thanks for bearing with me :smile:

**Comment by defjaf** [comment]
No problem -- glad to help (and thanks for all the work on your end)!

**Comment by vaibhavsagar** [comment]
My pleasure :smile:. Closing this.
