### ISSUE TITLE
Bogus type uncertainty error.

### ISSUE THREAD

**Issue by capn-freako** [gibiansky/IHaskell#736]
Hi,

Thanks for bringing in GHC 8!

The attached notebook generates a bogus error, re: type uncertainty, which I don't get if I compile the code at the command line (after uncommenting the "module Main where" line, of course):

```
Davids-MacBook-Air-2:PhantomTypes dbanas$ stack ghc test.hs 
Run from outside a project, using implicit global project config
Using resolver: lts-8.23 from implicit global project's config file: /Users/dbanas/.stack/global/stack.yaml
Run from outside a project, using implicit global project config
Using resolver: lts-8.23 from implicit global project's config file: /Users/dbanas/.stack/global/stack.yaml
[1 of 1] Compiling Main             ( test.hs, test.o )
Linking test ...
Davids-MacBook-Air-2:PhantomTypes dbanas$ 
```
Do you know why?

The code in question is in **Exercise 4**.

Thanks!
-db

[Archive.zip](https://github.com/gibiansky/IHaskell/files/1191010/Archive.zip)

**Comment by vaibhavsagar** [comment]
I'm able to reproduce this but don't know enough about the internals of IHaskell to explain why it's behaving differently to GHC(i) here. Hopefully someone who knows more can enlighten us both.

**Comment by vaibhavsagar** [comment]
This doesn't seem to happen with GHC 8.2 onwards, so I'm assuming this has been fixed upstream. May I close this?

**Comment by capn-freako** [comment]
Yes. Thanks!
