### ISSUE TITLE
Creating an "isolated" version of IHaskell

### ISSUE THREAD

**Issue by habemus-papadum** [gibiansky/IHaskell#760]
Hi, I'd appreciate any advise about how to achieve the following: 

I'd like to use IHaskell without having to rely on the system jupyter, cairo, pango etc.  My basic plan is to try something like:

* git clone IHaskell ; cd IHaskell
* use miniconda to install an isolated version python3 + jupyter + pango + cairo into a local subdirectory 
* add local miniconda bin to the path
* `stack build` to build ihaskell; but do not install
* run `stack exec ihaskell -- -install -stack` to install a kernel spec to 
the local jupyter which refers to the ihaskell in the build dir
* run `stack exec jupyter -- notebook` etc

While I imagine the above is largely possible, given the large number of packages in the IHaskell dependency tree, I imagine there will be an assortment of build and runtime issues probably related to not finding the correct shared libraries and or headers. 

If anyone has tried something similar and has advise or scripts they could share, that would be greatly appreciated.  

(context: I'd like to a create script that reliably and repeatable creates various IHaskell instances (with different sets of packages) on heterogenous infrastructure (including macOS and linux))

thanks, nehal

**Comment by vaibhavsagar** [comment]
Hey, this is exactly the aim of the Nix package manager: https://nixos.org/nix/! Fortunately I recently added Nix support for IHaskell, which means you can install it, clone the IHaskell repo, and run

```bash
$(nix-build release.nix)/bin/ihaskell-notebook
```

to get a self-contained IHaskell environment! Adding Haskell packages and system packages is also possible, as per [this section](https://github.com/gibiansky/IHaskell#nix) of the README.

**Comment by habemus-papadum** [comment]
Hi - Thanks for mentioning that. I had considered going the nix route, but found it problematic due to requiring access to `/nix` which I would like to avoid, whereas I find miniconda does a good job at providing both python and common, precompiled, binaries (e.q cairo, zeromq) for multiple platforms in a way that can be kept in an isolated, user writable location.  Now from what I read about nix, I imagine it would be possible to install it in an isolated, user writable location, but from what I can tell that would trigger having to build gcc, libc, ghc, etc prior to building IHaskell (which is already a little slow).

**Comment by vaibhavsagar** [comment]
Nix uses caching quite heavily, which means that you might be able to download compiled versions of some of your dependencies instead of building them from source (although I'm not sure how well that works with a custom store location). AFAIK there's no performance penalty for using Nix, so perhaps you could use it inside a Docker container to get the binary caching as well as the self-contained environment?

I also don't know anything about your use case and it seems like you have a few unusual requirements. Can you tell me more?

**Comment by habemus-papadum** [comment]
actually, I've reconsidered my stance on nix and feel like I should explore it further.

 (without getting into the weeds of my particular details, I think in the abstract both nix and miniconda can be used to provide binaries to haskell, julia, python, etc; the way nix does it seems very iron clad (e.g. requiring /nix for caching, ensuring /nix is not a symlink etc), conda on the other hand  is much more flexible in where it needs to live, and has many ways that it could fail, but in practice I have found that it has worked fine for reliably providing a small set of isolated binaries on a per project basis)

will something like: 
`nix-build release.nix --arg packages "haskellPackages: [ haskellPackages.lens, /path/to/localpackage, github_url ]"`  
work?
e.g. can I add packages that are not on hackage/lts to my nix provisioned ihaskell, and, if I make changes to my local package, how do I get ihaskell to see those changes?

Thanks for your help.

**Comment by vaibhavsagar** [comment]
I'm completely fine with getting into the weeds of your particular details if you want :smile:.

> conda on the other hand is much more flexible in where it needs to live, and has many ways that it could fail, but in practice I have found that it has worked fine for reliably providing a small set of isolated binaries on a per project basis

I don't think anyone has put effort into packaging GHC or `ihaskell` for conda, and I'd be very surprised if you could get it to work without a lot of yak shaving. Definitely report back if you try this.

>will something like: 
`nix-build release.nix --arg packages "haskellPackages: [ haskellPackages.lens, /path/to/localpackage, github_url ]"`  
work?

You can certainly add packages not on Hackage/Stackage to your Nix-provisioned IHaskell, but not like that. For an example see my `git-from-scratch` notebook's [`default.nix`](https://github.com/vaibhavsagar/notebooks/blob/cc920b908d3fd137383b06102e2a1a6b492779c6/git-from-scratch/default.nix#L30-L31) where I include the current package in the list of provided packages. IHaskell also supports inline module definitions if that would help (see cell [27] of [the example notebook](https://github.com/gibiansky/IHaskell/blob/4e2d4ccc8b88519886171b2301219c1a31edc322/notebooks/IHaskell.ipynb)).

Most of the issues you'll encounter can be solved if/when you get more familiar with Nix, but the downside to all this is that Nix is a gigantic and poorly-documented rabbit hole (and I don't mean that as a challenge). I don't want to provide Nix support via the IHaskell issue tracker, but if you have more questions you can ask on the `#nixos` IRC channel or get in touch with me via email or [Twitter](https://twitter.com/vbhvsgr).

**Comment by habemus-papadum** [comment]
>  I don't think anyone has put effort into packaging GHC or ihaskell for conda

Definitely -- I was thinking that stack would provide/build these, but that conda would provide only jupyter, cairo, pango, etc.  

I agree that this train of questions has run it course, but thanks very much for your thoughts!
