### ISSUE TITLE
Why is it suggested to stack install gtk2hs-buildtools before building everything else?

### ISSUE THREAD

**Issue by habemus-papadum** [gibiansky/IHaskell#763]
Why do the install instructions state:
`stack install gtk2hs-buildtools`  before building everything else -- I can't seem to find where this is needed.  
thanks, nehal

**Comment by vaibhavsagar** [comment]
It's needed to avoid errors you might otherwise get while trying to install some of the `ihaskell-display` modules, e.g. `ihaskell-chart`, `ihaskell-diagrams`, `ihaskell-plot` which depend on Pango and Cairo.

**Comment by habemus-papadum** [comment]
I thought so, but so I'm clear, if Pango, Cairo, etc are available, skipping this step will cause no problems?  This is mostly so new users don't have  a fail several minutes into the build with an unfriendly error message about missing libraries?  For instance, would the advise of `stack build gtk2hs-buildtools` have been sufficient?

**Comment by habemus-papadum** [comment]
For instance, I  nuked `~/.stack`, and did only a `stack build` in IHaskell and had no problems -- does this make sense?

**Comment by vaibhavsagar** [comment]
Yup, that sounds about right to me. If you want to make absolutely sure you might be able to rig up a CI build to test it both ways and see if anything breaks. If it turns out that step is unnecessary I'm happy to remove it!

**Comment by habemus-papadum** [comment]
Thanks -- I have a fork running on travis to test this out.  The results will be available here [![Build Status](https://travis-ci.org/habemus-papadum/IHaskell.svg?branch=master)](https://travis-ci.org/habemus-papadum/IHaskell).

Regardless, in the mean time, consider suggestioning `build gtk2hs-buildtools` vs `install`,  as some (like me) might find that less confusing at first glance. 

I should close this out in a day or so.  thanks!

**Comment by vaibhavsagar** [comment]
Closing this.
