### ISSUE TITLE
Wouldn't it be much easier to not provide diagrams-cairo by default?

### ISSUE THREAD

**Issue by habemus-papadum** [gibiansky/IHaskell#766]
As the diagrams-cairo [docs](https://hackage.haskell.org/package/diagrams-cairo) point out, there are pure haskell backend alternatives for many rendering needs making this unnecessary, but particularly in the case of IHaskell, generating SVG and letting the browser do the heavy lifting is surely the best default, no?  Slimming all shared library dependencies (save zeromq) should be the goal!   

Charts backend could be switched to Charts-diagram, Plot would have to go..., but using plotlyhs i probably the best...

**Comment by habemus-papadum** [comment]
Charts could be changed to use Charts-diagram rather than the current Charts-cairo

**Comment by leftaroundabout** [comment]
Cairo is hardly an exotic library, so I don't quite see your concern.

But you're probably right, we could do without it, at least for diagrams this couldn't be much problem. There was a thing with svg that it makes resizing troublesome, but I always found that funny anyway.

**Comment by vaibhavsagar** [comment]
> Wouldn't it be much easier to not provide diagrams-cairo by default?

Easier for whom? And by how much?

> Slimming all shared library dependencies (save zeromq) should be the goal!
>
> Charts backend could be switched to Charts-diagram, Plot would have to go..., but using plotlyhs i probably the best...

You're welcome to rewrite `ihaskell-charts`, `ihaskell-diagrams`, and `ihaskell-plot` to remove the `cairo` dependency, but I personally have no desire to do it.

**Comment by vaibhavsagar** [comment]
Closing as not actionable.
