### ISSUE TITLE
404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js

### ISSUE THREAD

**Issue by tyler274** [gibiansky/IHaskell#774]
Same as #521 but its still happening two years later

**Comment by vaibhavsagar** [comment]
Thanks for raising this! It looks like it might be something to do with `html/kernel.js`. I will investigate further.

**Comment by vaibhavsagar** [comment]
This is because CodeMirror expects to find a `<mode>.js` file corresponding to each mode, and there isn't a corresponding one for `ihaskell`.

**Comment by vaibhavsagar** [comment]
Closing as this is a wart but doesn't otherwise negatively impact the experience. I opened https://github.com/codemirror/CodeMirror/issues/5959 but received no response (as of this writing).
