### ISSUE TITLE
cabal file references head

### ISSUE THREAD

**Issue by JonathanFraser** [gibiansky/IHaskell#787]
The source uri specifed in the cabal file is locked to head, despite the file dictating a version.  This means any attempt to install a specific version of ihaskell is going to have unspecified and buggy behaviour.

**Comment by vaibhavsagar** [comment]
It doesn't look like we're doing anything differently to e.g. [`hgrep`](https://github.com/thumphries/hgrep/blob/28ef6986e0dcdc50560728e2da750a4779b43e14/hgrep.cabal) or [`hlint`](https://github.com/ndmitchell/hlint/blob/d26ea30776af2927ff5689883190240863691473/hlint.cabal). Can you provide an example of a library that does it the way you expect, and has this caused issues for you in practice?

**Comment by JonathanFraser** [comment]
by referencing head, the version number you include in the cabal file becomes meaningless. The version someone gets is always latest even if they try to install an earlier version. 

gentoo-haskell/gentoo-haskell#632

**Comment by vaibhavsagar** [comment]
I had a look at `hlint-2.0.9` and `containers-0.5.10.2`, and both of them do exactly the same thing with `source-repository head` in their `.cabal` files. Can you provide an example of what we should be doing instead?

**Comment by vaibhavsagar** [comment]
According to the [relevant section of the Cabal User Guide](https://www.haskell.org/cabal/users-guide/developing-packages.html#pkg-section-source-repository-source-repository):

> The `head` kind refers to the latest development branch of the package. This may be used for example to track activity of a project or as an indication to outside developers what sources to get for making new contributions.

So it looks like we're doing the right thing.
