### ISSUE TITLE
Please push a new release to Hackage

### ISSUE THREAD

**Issue by vaibhavsagar** [gibiansky/IHaskell#802]
Hi @gibiansky, now that [`lts-10.0`](https://www.stackage.org/lts-10.0) is out, can you push new releases to Hackage for `ihaskell`, `ghc-parser`, `ipython-kernel`, and possibly also the `ihaskell-display` modules? Alternatively, could you add me to the package maintainer group for these packages? My username is [VaibhavSagar](https://hackage.haskell.org/user/VaibhavSagar).

**Comment by gibiansky** [comment]
@vaibhavsagar Thanks! I've added you as a maintainer on all the packages listed [here](https://hackage.haskell.org/packages/search?terms=ihaskell) except for `inline-r` which wasn't uploaded by me.

**Comment by vaibhavsagar** [comment]
Thanks so much! In that case I will close this as soon as I upload a new release 😃.

**Comment by vaibhavsagar** [comment]
- [x] https://hackage.haskell.org/package/ihaskell-0.9.0.2/
- [x] https://hackage.haskell.org/package/ipython-kernel-0.9.0.1/
- [x] https://hackage.haskell.org/package/ghc-parser-0.2.0.1/
- [x] https://hackage.haskell.org/package/ihaskell-aeson-0.3.0.1/
- [x] https://hackage.haskell.org/package/ihaskell-blaze-0.3.0.1/
- [x] https://hackage.haskell.org/package/ihaskell-charts-0.3.0.1/
- [x] https://hackage.haskell.org/package/ihaskell-diagrams-0.3.1.1/
- [x] https://hackage.haskell.org/package/ihaskell-gnuplot-0.1.0.1/
- [x] https://hackage.haskell.org/package/ihaskell-hatex-0.2.1.1/
- [x] https://hackage.haskell.org/package/ihaskell-juicypixels-1.1.0.1/
- [x] https://hackage.haskell.org/package/ihaskell-magic-0.3.0.1/
- [x] https://hackage.haskell.org/package/ihaskell-plot-0.3.0.1/
- [x] https://hackage.haskell.org/package/ihaskell-widgets-0.2.3.2/
