### ISSUE TITLE
Kernel dies immediately

### ISSUE THREAD

**Issue by BlackBrane** [gibiansky/IHaskell#804]
I managed to solve this, but I hope the report can help. 

I followed the installation instructions on my mac(OS 10.12) and when trying to opening a notebook, I immediately got a notice that the kernel had died. Restarting would never be successful.

The interesting line that kept appearing in the terminal output was 

```
ihaskell: Can't parse "$HOME/.stack/programs/x86_64-osx/ghc-8.0.2/lib/ghc-8.0.2/platformConstants"
```
I managed to get it to work after running `ihaskell install` without the `--stack`.

It seemed a bit strange that the path was referencing something for GHC 8.0 after I had installed with the GHC 8.2 configuration. (I did install with the default configuration first, however).

I'm not sure if there are any peculiarities of my environment that may have affected this. For example I have a lot of Haskell stuff installed with cabal, besides also using stack for most projects.

**Comment by vaibhavsagar** [comment]
What is the stack resolver you have set in `~/.stack/global-project/stack.yaml`? It's possible that you have a `lts-9` global resolver which is interfering with a `lts-10` IHaskell install, which has happened to me in the past.

**Comment by vaibhavsagar** [comment]
Alternatively you could be using a GHC 8.2 IHaskell with a GHC 8 project, such as IHaskell itself which is currently on `lts-9.20`.

**Comment by BlackBrane** [comment]
Ah, it was indeed the old resolver in the global config that was messing with things. This actually solved a related problem I was still having: The kernel would work only if it was launched from the IHaskell project folder.

Thanks for the tip! Everything is resolved for me now. 

It does seem like this is some less-than-ideal behavior though. I'll leave to the maintainers to decide if the issue should be closed.

**Comment by vaibhavsagar** [comment]
I'll close this, but if you have any ideas about what to add to the README to address this for future users please feel free to reopen :smiley:

**Comment by BlackBrane** [comment]
Alright cool :)

A note in the README would probably be a good idea. I guess it would say something like "if you have problems running the server, make sure you don't have a stack config in your global resolver different than the one you used to install IHaskell".  Probably under a troubleshooting subheading. Not sure if there's anything more to say on it than that.

**Comment by vaibhavsagar** [comment]
Thanks for the suggestion! I've made a PR at #806. If you have a few minutes please take a look and let me know what you think otherwise I will merge it in the next couple of days.
