### ISSUE TITLE
Kernel dying in a Jupyter sample

### ISSUE THREAD

**Issue by Dmitry-Borodin** [gibiansky/IHaskell#808]
When I run Haskel sample from web https://try.jupyter.org/ and run the code from there, kernel is dying all the time.

**Comment by vaibhavsagar** [comment]
Thanks for raising this! The [Dockerfile](https://github.com/jupyter/docker-demo-images/blob/master/Dockerfile) that provides IHaskell hasn't been updated in quite a while and I think that might be why this is happening. I can't commit to fixing this in the near future but I will have a look as soon as I can.

**Comment by dabro** [comment]
I reported this a year or so ago, before the upgrades to GHC 8 started (as far as I know?). Just mentioning to help troubleshoot...

**Comment by vaibhavsagar** [comment]
https://github.com/jupyter/docker-demo-images/pull/105

**Comment by vaibhavsagar** [comment]
My PR has been merged!
