### ISSUE TITLE
hmatrix crashing iHaskell Kernel

### ISSUE THREAD

**Issue by OscarSouth** [gibiansky/IHaskell#812]
I also posted this here.  After I've realised it might be a wider issue:
https://github.com/albertoruiz/hmatrix/issues/247

It works fine in GHCi (here's a line I took from a tutorial)

GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Prelude> import Numeric.LinearAlgebra
Prelude Numeric.LinearAlgebra> vector [1,2,3] * vector [3,0,-2]
[3.0,0.0,-6.0]
Prelude Numeric.LinearAlgebra> 

In Atom (Hydrogen - iHaskell kernel) or Jupyter notebook it fails horribly, however.

The library will import fine, but once I try and run that same line of code, the iHaskell kernal crashes and the following error is returned.

![image](https://user-images.githubusercontent.com/32574713/35250138-02e16244-ffcd-11e7-90f4-8f5e968c80b0.png)

![image](https://user-images.githubusercontent.com/32574713/35250144-091cc4d2-ffcd-11e7-92d2-c99b41e99c52.png)

Jupyter Notebook also crashes, returning the following error text:
```
[W 23:39:35.748 NotebookApp] 404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js?v=20180122233928 (127.0.0.1) 15.93ms referer=http://localhost:8888/notebooks/Untitled10.ipynb?kernel_name=haskell
[I 23:39:36.431 NotebookApp] Adapting to protocol v5.0 for kernel f76db994-fd53-407c-a74c-4313d9a4a7ed
ihaskell: /home/oscarsouth/.stack/snapshots/x86_64-linux-nopie/lts-8.24/8.0.2/lib/x86_64-linux-ghc-8.0.2/hmatrix-0.18.0.0-IA7RzrKn1o84vo5PLhGcwQ/libHShmatrix-0.18.0.0-IA7RzrKn1o84vo5PLhGcwQ.a: unhandled ELF relocation(RelA) type 42

ihaskell: Could not on-demand load symbol 'vectorScan'

ihaskell: /home/oscarsouth/.stack/snapshots/x86_64-linux-nopie/lts-8.24/8.0.2/lib/x86_64-linux-ghc-8.0.2/hmatrix-0.18.0.0-IA7RzrKn1o84vo5PLhGcwQ/libHShmatrix-0.18.0.0-IA7RzrKn1o84vo5PLhGcwQ.a: unknown symbol `vectorScan'
ihaskell: Could not on-demand load symbol 'hmatrixzm0zi18zi0zi0zmIA7RzzrKn1o84vo5PLhGcwQ_InternalziVectorizzed_cconstantR_closure'

ihaskell: /home/oscarsouth/.stack/snapshots/x86_64-linux-nopie/lts-8.24/8.0.2/lib/x86_64-linux-ghc-8.0.2/hmatrix-0.18.0.0-IA7RzrKn1o84vo5PLhGcwQ/libHShmatrix-0.18.0.0-IA7RzrKn1o84vo5PLhGcwQ.a: unknown symbol `hmatrixzm0zi18zi0zi0zmIA7RzzrKn1o84vo5PLhGcwQ_InternalziVectorizzed_cconstantR_closure'
ihaskell: Could not on-demand load symbol 'hmatrixzm0zi18zi0zi0zmIA7RzzrKn1o84vo5PLhGcwQ_InternalziMatrix_zdfElementDouble_closure'

ihaskell: /home/oscarsouth/.stack/snapshots/x86_64-linux-nopie/lts-8.24/8.0.2/lib/x86_64-linux-ghc-8.0.2/hmatrix-0.18.0.0-IA7RzrKn1o84vo5PLhGcwQ/libHShmatrix-0.18.0.0-IA7RzrKn1o84vo5PLhGcwQ.a: unknown symbol `hmatrixzm0zi18zi0zi0zmIA7RzzrKn1o84vo5PLhGcwQ_InternalziMatrix_zdfElementDouble_closure'
ihaskell: Could not on-demand load symbol 'hmatrixzm0zi18zi0zi0zmIA7RzzrKn1o84vo5PLhGcwQ_InternalziUtil_vector_closure'

ihaskell: /home/oscarsouth/.stack/snapshots/x86_64-linux-nopie/lts-8.24/8.0.2/lib/x86_64-linux-ghc-8.0.2/hmatrix-0.18.0.0-IA7RzrKn1o84vo5PLhGcwQ/libHShmatrix-0.18.0.0-IA7RzrKn1o84vo5PLhGcwQ.a: unhandled ELF relocation(RelA) type 42

```

I've tried the solutions proposed here:
https://github.com/gibiansky/IHaskell/issues/698

Is there any way that I can run hmatrix inline, using Atom/iHaskell/Hydrogen or Jupyter Notebook?

Thanks,
Oscar

**Comment by vaibhavsagar** [comment]
I suspect this might be Stack-related because I don't seem to have this issue when using Nix. You can test this by installing Nix, cloning the IHaskell repo and running the following:

```bash

$ nix-build release.nix --arg packages "h: [ h.hmatrix]"
<...>
$ result/bin/ihaskell-notebook
```

And trying your example.

This is what I see:


![hmatrix](https://user-images.githubusercontent.com/1525767/35253059-87509c38-0037-11e8-86fd-29359478d100.png)

**Comment by OscarSouth** [comment]
Thanks for the insight here.  I will try and sort this out (or get more info) later today.

**Comment by vaibhavsagar** [comment]
Are you still experiencing this issue?

**Comment by OscarSouth** [comment]
I’m not using iHaskell these days but hmatrix is working fine for me in general.

**Comment by vaibhavsagar** [comment]
Closing this, please reopen if necessary.

**Comment by Magalame** [comment]
The example code for fitting in hmatrix crashes in IHaskell but not when executing it with stack (https://github.com/haskell-numerics/hmatrix/blob/master/examples/fitting.hs).
More exactly it crashes when calling `fitModelScaled`.

It does *not* crash when using `vector`:
```
vector [1,2,1] * vector[1,1,1]
```
works fine

Jupyter prints the following error message: `/home/nouey/.local/bin/ihaskell: symbol lookup error: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgsl.so: undefined symbol: cblas_dnrm2`
