### ISSUE TITLE
kernel crash ghc check warning 

### ISSUE THREAD

**Issue by HelioJimeArch** [gibiansky/IHaskell#816]
[I 23:18:38.748 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[I 23:18:45.493 NotebookApp] Creating new notebook in
[W 23:18:47.587 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180203231813 (127.0.0.1) 28.33ms referer=http://localhost:8888/notebooks/Untitled6.ipynb?kernel_name=haskell
[I 23:18:47.835 NotebookApp] Kernel started: 5e28e7bb-bf14-4c82-bd31-25dfc05a7ea4
[W 23:18:48.029 NotebookApp] 404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js?v=20180203231813 (127.0.0.1) 2.97ms referer=http://localhost:8888/notebooks/Untitled6.ipynb?kernel_name=haskell
[W 23:18:57.870 NotebookApp] Timeout waiting for kernel_info reply from 5e28e7bb-bf14-4c82-bd31-25dfc05a7ea4
ihaskell: Failed to load interface for ‘IHaskell.Display’
There are files missing in the ‘ihaskell-0.9.0.2’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display’
There are files missing in the ‘ihaskell-0.9.0.2’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.IPython.Stdin’
There are files missing in the ‘ihaskell-0.9.0.2’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Eval.Widgets’
There are files missing in the ‘ihaskell-0.9.0.2’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Diagrams’
There are files missing in the ‘ihaskell-diagrams-0.3.1.1’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Widgets’
There are files missing in the ‘ihaskell-widgets-0.2.3.2’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Charts’
There are files missing in the ‘ihaskell-charts-0.3.0.1’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.StaticCanvas’
There are files missing in the ‘ihaskell-static-canvas-0.1.0.0’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Plot’
There are files missing in the ‘ihaskell-plot-0.3.0.1’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Magic’
There are files missing in the ‘ihaskell-magic-0.3.0.1’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Juicypixels’
There are files missing in the ‘ihaskell-juicypixels-1.1.0.1’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Hatex’
There are files missing in the ‘ihaskell-hatex-0.2.1.1’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Gnuplot’
There are files missing in the ‘ihaskell-gnuplot-0.1.0.1’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Blaze’
There are files missing in the ‘ihaskell-blaze-0.3.0.1’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Aeson’
There are files missing in the ‘ihaskell-aeson-0.3.0.1’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.

[I 23:19:05.830 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 5e28e7bb-bf14-4c82-bd31-25dfc05a7ea4 restarted
ihaskell: Failed to load interface for ‘IHaskell.Display’
There are files missing in the ‘ihaskell-0.9.0.2’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display’
There are files missing in the ‘ihaskell-0.9.0.2’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.IPython.Stdin’
There are files missing in the ‘ihaskell-0.9.0.2’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Eval.Widgets’
There are files missing in the ‘ihaskell-0.9.0.2’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Diagrams’
There are files missing in the ‘ihaskell-diagrams-0.3.1.1’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Widgets’
There are files missing in the ‘ihaskell-widgets-0.2.3.2’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Charts’
There are files missing in the ‘ihaskell-charts-0.3.0.1’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.StaticCanvas’
There are files missing in the ‘ihaskell-static-canvas-0.1.0.0’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Plot’
There are files missing in the ‘ihaskell-plot-0.3.0.1’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Magic’
There are files missing in the ‘ihaskell-magic-0.3.0.1’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Juicypixels’
There are files missing in the ‘ihaskell-juicypixels-1.1.0.1’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Hatex’
There are files missing in the ‘ihaskell-hatex-0.2.1.1’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Gnuplot’
There are files missing in the ‘ihaskell-gnuplot-0.1.0.1’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Blaze’
There are files missing in the ‘ihaskell-blaze-0.3.0.1’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
Failed to load interface for ‘IHaskell.Display.Aeson’
There are files missing in the ‘ihaskell-aeson-0.3.0.1’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.

**Comment by vaibhavsagar** [comment]
This sounds like an environment/installation issue, how did you install IHaskell?

**Comment by HelioJimeArch** [comment]
i followed the instructions of  the principal page  in my local   directory  /home/ArchiCurry

**Comment by vaibhavsagar** [comment]
I assume this means the `stack` instructions. How are you running IHaskell? `stack exec -- jupyter notebook` or something else?

**Comment by HelioJimeArch** [comment]
yep

**Comment by vaibhavsagar** [comment]
I'll need more information from you to help resolve this issue.

1. Which operating system are you running?
2. Which instructions exactly did you follow, and did you install all the required libraries with `apt-get` or the equivalent on your OS?
3. Have you installed `stack` before, and if so, what is the resolver listed in `~/.stack/global-project/stack.yaml`?
4. Do you have a non-`stack` Haskell installation? That might be interfering with `stack`.
4. Which directory are you running `stack exec -- jupyter notebook` from?
5. What is the output of `which ihaskell`?
6. Can you rerun `ihaskell install --stack` from your home directory, and then go into your clone of the IHaskell repo and run `stack exec -- jupyter notebook` from there? Do you get a different/more interesting error message?

**Comment by HelioJimeArch** [comment]
you can ignore the VcXsrv  crash i all right now but  i could be a problem with this warning in firefox 
"the bookmars and history system will not be functional because one of firefox files is in use by another application . Some security software can cause this problem "

**Comment by vaibhavsagar** [comment]
Okay, this is more useful! Try moving IHaskell's `stack-8.2.yaml` to `stack.yaml`, reinstall IHaskell, and try again:

```bash
$ cd IHaskell
$ mv stack-8.2.yaml stack.yaml
$ stack install ihaskell
$ cd ..
$ ihaskell install --stack
$ cd IHaskell
$ stack exec -- jupyter notebook
```

**Comment by HelioJimeArch** [comment]
thanks!

**Comment by vaibhavsagar** [comment]
Closing this, please reopen if required.
