### ISSUE TITLE
Error when using :hoogle - Irrefutable pattern failed

### ISSUE THREAD

**Issue by SFrijters** [gibiansky/IHaskell#819]
If I try to evaluate `:hoogle id` I get an error `ihaskell: src/IHaskell/Eval/Hoogle.hs:183:11-42: Irrefutable pattern failed for pattern [name, args]`.

This doesn't occur for other Hoogle searches, e.g. `:hoogle replicate` and `:hoogle a -> a` are fine for me.

**Comment by vaibhavsagar** [comment]
Thanks for raising this! I think we weren't handling `newtype`s before and I've just pushed https://github.com/gibiansky/IHaskell/commit/856f64f933a8165700596011d3e6ed602fc7802d which doesn't seem to have this issue, can you try again with the latest `master`?

**Comment by SFrijters** [comment]
Trying this, but I've been using a nix-shell with a pre-built IHaskell so far, and it seems calling nix-build on a clone of the repo is failing for me. I'm falling back to stack - but that takes a while on my single core VM.

**Comment by SFrijters** [comment]
Looks like this indeed fixes the problem.

**Comment by vaibhavsagar** [comment]
Fantastic, closing this.
