### ISSUE TITLE
Choose between Hoogles

### ISSUE THREAD

**Issue by SFrijters** [gibiansky/IHaskell#820]
The `:hoogle` command uses <https://www.haskell.org/hoogle/> as far as I know, but some things are not found on there (e.g. `(&)`), while they do appear correctly when searching <http://hoogle.haskell.org/>. I'm not sure if the "alpha" version warning on the latter is still accurate, but it's giving me consistently better results. It would be nice to be able to configure which API is used.

**Comment by vaibhavsagar** [comment]
Good idea! I will look into what it would take to make this configurable.

**Comment by vaibhavsagar** [comment]
It looks like this is determined by the value of `queryUrl` here: 
https://github.com/gibiansky/IHaskell/blob/856f64f933a8165700596011d3e6ed602fc7802d/src/IHaskell/Eval/Hoogle.hs#L67
I'm not sure how many people use/prefer the old Hoogle, so if you consider the new Hoogle to be better in general it would be much easier to just switch to it for everyone. What do you think?

**Comment by SFrijters** [comment]
Maybe @ndmitchell could weigh in on the current status. It seems the plan was to eventually swap in the new Hoogle: https://github.com/ndmitchell/hoogle/issues/171

**Comment by ndmitchell** [comment]
My preference would be everyone uses the new Hoogle and we shake bugs out of that, rather than using the old one which indexes less stuff. The old one is effectively frozen in time, but the new one updates every night.

**Comment by vaibhavsagar** [comment]
I've started work on this in https://github.com/gibiansky/IHaskell/pull/825 but the new JSON output is different enough that I'm running into https://github.com/gibiansky/IHaskell/issues/819.

**Comment by vaibhavsagar** [comment]
We're now using the new Hoogle.
