### ISSUE TITLE
Enable LaTeX extension

### ISSUE THREAD

**Issue by Tshimanga** [gibiansky/IHaskell#828]
Possibly more a question of how rather than a request for enhancement but here it goes. 

I'd like to use a greater set of latex functionality (\mathcal, \mathbb, etc.) and so an analogous `%load_ext latex` would be great in IHaskell. Not sure how difficult an enhancement that would be, or if I simply haven't found it yet, but I figured I ought to ask here. Cheers!

**Comment by vaibhavsagar** [comment]
Hi, do you mean that you would like to be able to use LaTeX in Markdown cells or something else? I believe we have MathJax support but I'm unsure what the status of LaTeX in IHaskell is beyond that. We do have [HaTeX](https://hackage.haskell.org/package/HaTeX) integration in the form of [ihaskell-hatex](https://github.com/gibiansky/IHaskell/tree/3d5cbb16fa2ba0f4253595c14cf896df80a6b88c/ihaskell-display/ihaskell-hatex) if that helps.

**Comment by leftaroundabout** [comment]
I'm confused by the question. Commands like `\mathcal` and `\mathbb` are supported by MathJax right out of the box, and thus accessible in an IHaskell notebook either via Markdown cells or by using the ihaskell-hatex instance.
[![mathjax-mathcal](https://user-images.githubusercontent.com/1528675/36947598-a8ff55b6-1fce-11e8-8562-846643187239.png)](http://nbviewer.jupyter.org/gist/leftaroundabout/c39339680666bb6a961981ba88d816e7)

**Comment by vaibhavsagar** [comment]
Closing this.
