### ISSUE TITLE
#include non portable path 

### ISSUE THREAD

**Issue by prometheus-bit** [gibiansky/IHaskell#834]
I have been trying to locate the following error in definitions but have not been able to locate it

 error:
     warning: non-portable path to file '".stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/IHaskell/autogen/cabal_macros.h"'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#include ".stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/ihaskell/autogen/cabal_macros.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         ".stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/IHaskell/autogen/cabal_macros.h"

**Comment by vaibhavsagar** [comment]
How did you (try to) install IHaskell and at which stage of the process are you getting this error?

**Comment by vaibhavsagar** [comment]
Possibly related: https://github.com/haskell/cabal/issues/4739

**Comment by prometheus-bit** [comment]
I followed the original build instructions... then used the build scripts. Each time clearing the build to avoid compound errors.  The build process always Failed at the building process of stack install —fast.
When it came time to link up ihaskell.

I did eventually come across the problem with the referential case issue as linked in email.
  You still have to suppress compilation warnings but the build executes.
I am not sure if this happens to all systems.  I run OS X high Sierra Beta with custom sandboxed ghc based on shadowed copy of development git branch.  I do as well run a zsh environment.
The standard library linking issues occurred as does on OS X, but linked them in yaml files.

Best,

Matthew Prussman
Emplid  23217746<tel:23217746>

On Fri, Mar 09, 2018 at 12:48 AM Vaibhav Sagar <Vaibhav Sagar <mailto:Vaibhav%20Sagar%20<notifications@github.com>> > wrote:

Possibly related: haskell/cabal#4739<https://github.com/haskell/cabal/issues/4739>

**Comment by vaibhavsagar** [comment]
This definitely seems like a macOS-specific issue. Can you try adding

```yaml
ghc-options:
    "$locals": -optP-Wno-nonportable-include-path
```

to your copy of `stack.yaml` to see if that resolves the issue for you?

**Comment by prometheus-bit** [comment]
I did.

Best,

Matthew Prussman
Emplid  23217746<tel:23217746>

On Fri, Mar 09, 2018 at 1:34 AM Vaibhav Sagar <Vaibhav Sagar <mailto:Vaibhav%20Sagar%20<notifications@github.com>> > wrote:

This definitely seems like a macOS-specific issue. Can you try adding

ghc-options:
    "$locals": -optP-Wno-nonportable-include-path

to your copy of stack.yaml to see if that resolves the issue for you?

**Comment by vaibhavsagar** [comment]
Closing this. Please reopen if needed.

**Comment by lucasdicioccio** [comment]
FYI just stumbled on the same error on MacOS.

I'm currently willing to progress on my build and I've removed -Werror (worse than the above fix). Though I'm willing to do some more investigation.

One file with such a local path was `./.stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/src/IHaskell/Convert/LhsToIpynb.dump-hi` 

that was containing

```
addDependentFile "/Users/lucasdicioccio/.stack/programs/x86_64-osx/ghc-8.2.2/lib/ghc-8.2.2/include/ghcversion.h"
addDependentFile ".stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/autogen/cabal_macros.h"
```
