### ISSUE TITLE
Example of embedding Vega/VegaLite visualizations with Vega-Embed in IHaskell

### ISSUE THREAD

**Issue by DougBurke** [gibiansky/IHaskell#850]
I have managed to get something working that lets me display VegaLite / Vega visualizations in an IHaskell notebook, which I've detailed at https://gist.github.com/DougBurke/35a944400923a522db5ba7e9a5e3be89 but is not guaranteed to be the best way to do it. The notebook itself can be seen at https://nbviewer.jupyter.org/urls/gist.githubusercontent.com/DougBurke/35a944400923a522db5ba7e9a5e3be89/raw/56b69023fb75ff340aafce7e92c4f7ae379a73c6/VegaLite.ipynb but it doesn't include the actual visualizations (I don't know if this is an issue with my code or the conversion or viewer or ..).

Given that we don't yet have an embedded language/type to describe such visualizations - unless someone wants to port over Elm's https://github.com/gicentre/elm-vega - then it's not obvious what the best way to create a type to contain the visualization. Also, this should be a lot easier once IHaskell updates to JupyterLab and add support for more mime types (since Vega and Vega Lite visualizations are recognized by mime type).

*edited to add* thanks to https://github.com/gibiansky/IHaskell/issues/811 on which this is based.

**edited to add** due to recent changes somewhere in the Vega infrastructure, the latest versions of the modules no longer work here, so explicit versions need to be given - that is we need to use

```haskell
        -- the version is now given as a string
        jsname n v = "'https://cdn.jsdelivr.net/npm/"
                     <> n
                     <> "@" <> v
                     <> "/build/"
                     <> n <> ".min'"

...

        config = "requirejs({paths:{vg:" <> jsname "vega" "3.2.1"
                 <> ",vl:" <> jsname "vega-lite" "2.3.0"
                 <> ",vge:" <> jsname "vega-embed" "3.5.2"
...
```

**Comment by vaibhavsagar** [comment]
What do you mean by this?

> once IHaskell updates to JupyterLab

**Comment by vaibhavsagar** [comment]
Also, AIUI, we implement support for mime types separately in IHaskell and would need to add the appropriate handlers regardless.

**Comment by DougBurke** [comment]
@vaibhavsagar  I was under the impression that IHaskell didn't use the latest version of JupyterLab, but was still using the "old" IPython/Jupyter code base. That is, we don't get
https://github.com/altair-viz/jupyter_vega/issues/35#issuecomment-310494701
"for free" yet.

As to the mimetype comment, The Vega/Vega-Lite JSOn is recognized by different mimetypes - see the table at  https://github.com/jupyterlab/jupyter-renderers - so https://github.com/gibiansky/IHaskell/blob/master/ipython-kernel/src/IHaskell/IPython/Types.hs#L563 will probably have to be expanded to include these mime types, or add a "other" option - e.g. `data MimeType = ... | MimeOther T.Text` . Or at least that's what my 2 minutes of thinking about a code base I know knothing about needs :-)

**Comment by vaibhavsagar** [comment]
I didn't even realise JupyterLab was the successor to Jupyter Notebooks until I saw your comment :smile:. I'd definitely like to keep IHaskell up-to-date with the Jupyter ecosystem, even if it doesn't solve this Vega issue.

**Comment by DougBurke** [comment]
It;s both good and bad that things move so fast ;-)

**Comment by DougBurke** [comment]
I think https://github.com/vega/vega-embed/pull/68 has broken my attempt to get `requirejs` to load in everything (hopefully, the fix is simpler code, as this change was added to address https://github.com/observablehq/vega/issues/8#issuecomment-378389907 )

**Comment by DougBurke** [comment]
For anyone interested, I have just released https://hackage.haskell.org/package/hvega-0.1.0.0 and https://hackage.haskell.org/package/ihaskell-hvega-0.1.0.0 (based off of elm-vega) to allow you to create VegaLite specifications and then display them (the `ihaskell-hvega` package hard-codes the necessary js library versions to avoid the recent problems I report above).

**Comment by vaibhavsagar** [comment]
This is really cool, thanks! Does this mean I can close this issue?

**Comment by DougBurke** [comment]
It can be closed. Ta.
