### ISSUE TITLE
Install on Mac OS X - libiconv is a problem again

### ISSUE THREAD

**Issue by AronT-TLV** [gibiansky/IHaskell#878]
Issue #584 seems to have come alive again on Mac OS X High Sierra 10.13.5. If you use the `brew` version of the `iconv` library you get the error message:
```
Undefined symbols for architecture x86_64:
      "_iconv", referenced from:
          _hs_iconv in libHSbase-4.10.1.0.a(iconv.o)
```

But if you follow the instructions suggested in the ticket and edit `slack.yaml` to include:
```
extra-lib-dirs:
    - /usr/lib
extra-include-dirs:
    - /usr/include
```
you get the error message:
```
dyld: Library not loaded: @rpath/libiconv.2.dylib
      Referenced from: /private/var/folders/zd/g08zsw0158v7fnh39l95n3bm0000gn/T/stack78541/glib-0.13.6.0/.stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/System/Glib/StoreValue_hsc_make
      Reason: Incompatible library version: StoreValue_hsc_make requires version 9.0.0 or later, but libiconv.2.dylib provides version 7.0.0
```
By switching back and forth between the two options everytime I got the error I did manage to reach the end and build `iHaskell`. Not sure how you can fix this, but the above is crazy.

**Comment by vaibhavsagar** [comment]
I don't see how this is an issue with IHaskell.
