### ISSUE TITLE
Fails to compile for Python 3.7 on Mac

### ISSUE THREAD

**Issue by oscarvarto** [gibiansky/IHaskell#880]
I had to add 

```
pyyaml=4.2b4
```

to requirements.txt in order to compile successfully with Python 3.7 (the version bundled with recent homebrew formula)

See:
https://github.com/yaml/pyyaml/issues/126

**Comment by vaibhavsagar** [comment]
Is this still an issue?

**Comment by oscarvarto** [comment]
Hi @vaibhavsagar .
I have just pulled changes from master branch and recompiled. It worked OK.

Closing issue.
Thanks!
