### ISSUE TITLE
jupyterlab: kernel blocks on startup

### ISSUE THREAD

**Issue by MMesch** [gibiansky/IHaskell#884]
If I start a notebook with a Haskell Kernel, the kernel blocks on startup (i.e. the circle next to the kernel name stays greyed out and I can't execute a simple cell). I can unblock the kernel in jupyterlab (!) by logging into it from the outside with the command `jupyter console --existing` .

**Comment by vaibhavsagar** [comment]
I haven't seen any documentation for the kernel protocol used by JupyterLab and how/if it differs from the IPython protocol we implement, so I'm not sure how we'd go about fixing this.

**Comment by MMesch** [comment]
it seems that jupyterlab waits for an initial 'idle' message from the kernel. I am just looking into it ...

**Comment by MMesch** [comment]
at least the python kernel seems to respond to the kernel info message with busy and idle status and the haskell kernel not !?

**Comment by MMesch** [comment]
https://jupyter-client.readthedocs.io/en/stable/messaging.html#messages-on-the-shell-router-dealer-channel

if I read correctly, every message should have a `status` message, but in https://github.com/gibiansky/IHaskell/blob/master/ipython-kernel/src/IHaskell/IPython/Types.hs#L294-L302 the `KernelInfoReply` doesn't have one ... correct me if I'm wrong but this seems to be a bug

**Comment by MMesch** [comment]
this is a fix that also changes syntax highlighting. It breaks compatibility with the notebook right now. I'll add a PR when it doesn't anymore ...

**Comment by MMesch** [comment]
should work now
