### ISSUE TITLE
nix installation fails

### ISSUE THREAD

**Issue by 2mol** [gibiansky/IHaskell#897]
The build fails both for release-8.2.nix and release-8.4.nix.

I'm running the command from the readme, and I'm using macOS. I can't quite figure out why it wouldn't work, since the nixpkgs version is fixed.

Here are the last lines:

```
Using Xcode version , but at least version 7.3 is required to build Qt WebEngine.
QtWebEngine will not be built.
building
build flags: -j1 -l1 SHELL=/nix/store/k5n19ccijsqdi5dwgblcck8x6b7ymlml-bash-4.4-p12/bin/bash
make: Nothing to be done for 'first'.
running tests
check flags: -j1 -l1 SHELL=/nix/store/k5n19ccijsqdi5dwgblcck8x6b7ymlml-bash-4.4-p12/bin/bash VERBOSE=y check
make: Nothing to be done for 'check'.
installing
install flags: install SHELL=/nix/store/k5n19ccijsqdi5dwgblcck8x6b7ymlml-bash-4.4-p12/bin/bash
make: Nothing to be done for 'install'.
/nix/store/bwqg8fnalha8xnarpqpdsg3d2d0nz2l0-stdenv-darwin/setup: line 106: /nix/store/zr76n5pj0s5m8sp3b6xpn1yi2q70rjh6-qtwebengine-5.10.1/libexec/qt.conf: No such file or directory
builder for '/nix/store/lkax1z06kr8nyi4ma8mbfny4m7q3k54d-qtwebengine-5.10.1.drv' failed with exit code 1
cannot build derivation '/nix/store/k9nc8jw1rhir1nbd543raxpp3yhgvwpi-python3.6-PyQt-5.10.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/gldijryyv9qmwzy6ch86gn5v1fmb3i8h-python3-3.6.6-env.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/fpaal2abvac0z5lyn388mb2w72jgbhbg-ihaskell-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/fpaal2abvac0z5lyn388mb2w72jgbhbg-ihaskell-with-packages.drv' failed
```

**Comment by vaibhavsagar** [comment]
Thanks for reporting this! Are you getting the same error with this simpler expression?

```bash
$ nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-18.03.tar.gz -E "with import <nixpkgs> {}; pkgs.python3.withPackages (p: [ p.notebook ])"
```

If so, it might be something that is fixed in `nixos-unstable` but not `nixos-18.03`. In that case, try commenting out [my `haskell-src-exts` override in `release.nix`](https://github.com/gibiansky/IHaskell/blob/01fe16bf3097cad563c5e31c7e999e8e847d392d/release.nix#L56) and doing something like

```bash
$ nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz release-8.4.nix
```

**Comment by 2mol** [comment]
So yes, that first expression builds just fine.

Commenting out your line and executing that second statement results in

```
unpacking 'https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz'...
error: attribute 'ghc841' missing, at /Users/juri/code/IHaskell/release.nix:44:21
```

**Comment by 2mol** [comment]
That one fails on the `zeromq4-haskell-0.7.0` derivation. Want the last bit of the log?

**Comment by vaibhavsagar** [comment]
No, that's fine, although I'm surprised that it doesn't work. Can you try with `release-8.2.nix`?

**Comment by 2mol** [comment]
Oh boy, this one seems to fail on something Qt related again.

I mean, let's not worry too much about it, I'll use ihaskell some other way and I'll try with nix again in a month or so. No need to treat this as a high priority issue!

Just for fun, the last bits of the output:

```
$ nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz release-8.2.nix
[...]
substitute(): ERROR: file 'src/3rdparty/chromium/sandbox/mac/bootstrap_sandbox.cc' does not exist
builder for '/nix/store/yiqkvas8jz1125mmq9adr6rnn7b6ij8s-qtwebengine-5.11.1.drv' failed with exit code 1
cannot build derivation '/nix/store/rn379c9syxb7ggx85sw0s58kl6m7gzqx-python3.6-PyQt-5.10.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/sqybxmbna9vym6r657s77s5hqxrkhi7x-python3-3.6.6-env.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/d5aja99yivyvnz1wjyyfr8a5gpzjaxn3-ihaskell-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/d5aja99yivyvnz1wjyyfr8a5gpzjaxn3-ihaskell-with-packages.drv' failed
```

**Comment by vaibhavsagar** [comment]
I'm glad it's not a dealbreaker for using IHaskell :smile:. If I get access to a macOS computer running Nix soon I'll look into this further.

**Comment by vaibhavsagar** [comment]
Okay, I think i've fixed the problem. I was including `jupyter` as a Python dependency, but it isn't actually required in order to get a notebook environment, so I've removed it now and tested that the command in the `README`, i.e.

```
$ nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-18.03.tar.gz release-8.2.nix
```

works on macOS. Can you do a `git pull` and try that?

**Comment by 2mol** [comment]
Hell yeah, that part works now.

The subsequent command in the readme won't work however, it fails with

```
building '/nix/store/irjk4152hbk8dhk1z4j7mh24n90k7j9y-cabal2nix-ihaskell.drv'...
installing
error: attribute 'haskell-src-exts_1_20_2' missing, at /Users/juri/code/IHaskell/release.nix:56:25
```

**Comment by vaibhavsagar** [comment]
Please try it with `nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-18.03.tar.gz` instead of just `nix-build`. I will update the `README`.

**Comment by 2mol** [comment]
Ok, works great :) Thank you so much for all the help.

One last question: I can't figure out how to do the equivalent of `nix-env --install` with the commands above, it would be nice to have `ihaskell-notebook` in my PATH.

**Comment by vaibhavsagar** [comment]
My pleasure! I think the way to do `nix-env --install` is as follows:

1. Create a file called `default.nix` (or whatever you want, but I'm assuming `default.nix`) with the following contents:

```nix
let
  inherit (import <nixpkgs> {}) lib;
  fetcher = { owner, repo, rev, sha256 }: builtins.fetchTarball {
    inherit sha256;
    url = "https://github.com/${owner}/${repo}/archive/${rev}.tar.gz";
  };
  versions = {
    "ihaskell" = {
      "owner" = "gibiansky";
      "repo" = "IHaskell";
      "rev" = "2c43cffe4f7f2bba44f7edcfcadea5eb7ba2bcf8";
      "sha256" = "0c3vf5pmdpf9bg05w0rmc5f3pc24wdh9xgvjaby0qska2izcfdki";
    };
    "nixpkgs" = {
      "owner" = "NixOS";
      "repo" = "nixpkgs-channels";
      "rev" = "6115f4777031924af1f91a08ed88cd8826fd649f";
      "sha256" = "0fcg12zh3i2ij4ijxmcd7qbvr0mmrng672ll1imwma6h3q9imirp";
    };
  };
  pkgs = lib.mapAttrs (_: fetcher) versions;
in import "${pkgs.ihaskell}/release.nix" {
  compiler = "ghc822";
  nixpkgs  = import pkgs.nixpkgs {};
  packages = self: with self; [ bytestring memory pretty-show timeit vector ];
}
```

This pins `nixpkgs` so we don't have to supply `-I` each time. Adjust the `compiler` and `packages` fields to taste.

2. Run the following command:

```bash
$ nix-env --install -f default.nix
```

My preferred workflow is to use a dedicated [`notebooks`](https://github.com/vaibhavsagar/notebooks/) repo to keep my notebook environments separate from each other, feel free to look at that and use it if you'd like :smiley:.

**Comment by 2mol** [comment]
Super cool, I really appreciate the detailed instructions, expecially as a nix newbie!

Is there something that speaks against packaging this into the repo? That could be a really nice way to install ihaskell, maybe even with something as easy as `nix-env -if https://github.com/gibiansky/IHaskell/tarball/master`.

I also wonder if adding haskell libraries could be made more ergonomic, or at least clearer in the readme. But that's for another day, if I find time I'll make some changes to the readme and send you a PR.

**Comment by vaibhavsagar** [comment]
There's already an [`ihaskell` service](https://github.com/NixOS/nixpkgs/blob/0590b3106b6aadf13b90109a4edd1b5780f75c9a/nixos/modules/services/misc/ihaskell.nix) in `nixpkgs` if you use NixOS. I'm not a fan of this approach, because I'd rather have smaller per-project IHaskell environments instead of a single giant one for everything, but if you have ideas about how to describe this in the `README` I'd be happy to accept a PR!

**Comment by 2mol** [comment]
Oh, I see what you mean. I'll see what wording I can come up with.
