### ISSUE TITLE
ScopedTypeVariables extension

### ISSUE THREAD

**Issue by dleprovost** [gibiansky/IHaskell#901]
Unlike others extensions, `ScopedTypeVariables` seems having no effect in iHaskell.

Here is a minimal repro:
```
:ext ScopedTypeVariables
tmp :: forall a. a -> a
tmp x = x
```
```
Parse error (line 2, column 16): Illegal symbol '.' in type
Perhaps you intended to use RankNTypes or a similar language
extension to enable explicit-forall syntax: forall <tvs>. <type>
```

I also got the same output with `:ext RankNTypes`.

**Comment by vaibhavsagar** [comment]
Try enabling the extension in a separate cell. [Here's](https://github.com/vaibhavsagar/notebooks/blob/1398e15cc32831836ec8bb202317f6fee9103c3e/codensity/Codensity.ipynb) an example of a notebook where I use `RankNTypes` without any issues.

**Comment by dleprovost** [comment]
Indeed.
It requires separate cells, which seems not to be the case for other extensions like `OverloadedStrings` or `TemplateHaskell`.

Thanks for this quick solution!

**Comment by vaibhavsagar** [comment]
My pleasure! I think that's because those other extensions don't change the behaviour of the parser, whereas `RankNTypes` does. May I close this issue?

**Comment by dleprovost** [comment]
I think so, thanks.
