### ISSUE TITLE
Bindings and modules

### ISSUE THREAD

**Issue by nmattia** [gibiansky/IHaskell#905]
I find the behavior of modules a bit surprising. It looks like all bindings disappear, although imports are still around. Is this the expected behavior, and if so, what's the idea behind it?

```haskell
import qualified Data.ByteString.Char8 as BS8

foo :: Int
foo = 2
```

```haskell
module Bar where

bar :: IO ()
bar = putStrLn "Hello"
```

```haskell
foo
```

<span class='err-msg'>&lt;interactive&gt;:1:1: error: Variable not in scope: foo</span>

```haskell
BS8.pack "foo"
```

    "foo"

I'm using the following nixpkgs commit:

```
{
  "owner": "NixOS",
  "repo": "nixpkgs-channels",
  "branch": "nixos-18.03",
  "rev": "aec217852f228fd6f923c0d32b94d78dee4ae5dc",
  "sha256": "1nj6wdg9yi27bmlg2xqa3mlm0zncw0v62b8a13ydrw6vg1a2h5dl"
}
```
[Untitled.ipynb.txt](https://github.com/gibiansky/IHaskell/files/2288271/Untitled.ipynb.txt)

**Comment by vaibhavsagar** [comment]
I can't speak to the motivation behind this behaviour, but it is documented at [IHaskell.ipynb](https://github.com/gibiansky/IHaskell/blob/726d1b11d1c2943fa07c52510c281b2435b7e8be/notebooks/IHaskell.ipynb) (cells 27-30).

**Comment by vaibhavsagar** [comment]
Closing as this behaviour is documented.
