### ISSUE TITLE
add fallback codemirror mode for the notebook and jupyterlab

### ISSUE THREAD

**Issue by MMesch** [gibiansky/IHaskell#911]
_enhancement for jupyterlab_

Right now the kernel uses the codemirror mode 'ihaskell'. This codemirror mode adds  custom defined syntax highlighting for the jupyter commands. In jupyterlab this requires the installation of the jupyterlab extension. *It would be nice to have two codemirror modes, one standard [='ihaskell'] that requires the installation of the extension and one as a fallback [='haskell'] that works immediately*.

This might be possible because the `codemirror_mode` message takes a `dict`, as noted here:
https://jupyter-client.readthedocs.io/en/stable/messaging.html#kernel-info

> Codemirror mode, for for highlighting in the notebook.  Only needed if it differs from the 'name' field. 'codemirror_mode': str or dict,

**Comment by vaibhavsagar** [comment]
Looking at the implementation of `codemirror_mode` it doesn't seem to support fallbacks. Please reopen if you have a workable approach or I'm wrong about this.
