### ISSUE TITLE
Could not find module ‘IHaskell.Display.Demo’

### ISSUE THREAD

**Issue by erikd** [gibiansky/IHaskell#913]
Built IHaskell with stack according to the instructions) and if I then run:
```
stack exec jupyter -- notebook
```
I get:
```
[I 09:45:09.848 NotebookApp] Serving notebooks from local directory: /home/erikd/Git/Haskell/ihaskell-demo
[I 09:45:09.848 NotebookApp] 0 active kernels
[I 09:45:09.848 NotebookApp] The Jupyter Notebook is running at:
[I 09:45:09.848 NotebookApp] http://localhost:8888/?token=347fe1039819e1b0660527461fbc82ebdc6b00fab4fe752c
[I 09:45:09.848 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:45:09.849 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=347fe1039819e1b0660527461fbc82ebdc6b00fab4fe752c
[I 09:45:10.705 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[W 09:45:13.461 NotebookApp] Notebook first.ipynb is not trusted
[I 09:45:13.690 NotebookApp] Kernel started: 62a97285-b025-42f0-a830-ab7e220da7a8
[W 09:45:13.791 NotebookApp] 404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js?v=20180827094509 (::1) 4.50ms referer=http://localhost:8888/notebooks/first.ipynb
ihaskell: Could not find module ‘IHaskell.Display.Demo’
Perhaps you meant
  IHaskell.Display.Plot (from ihaskell-plot-0.3.0.1)
  IHaskell.Display (from ihaskell-0.9.0.3)
Use -v to see a list of the files searched for.
```
I get this whether I open an existing Haskell notebook or create a new Haskell notebook. It does not happen when starting a new Python3 notebook.

**Comment by erikd** [comment]
No, its a different repo. Does it need to be the same?

**Comment by erikd** [comment]
The weird thing is that neither IHaskell nor my project have a module named `IHaskell.Display.Demo`

**Comment by vaibhavsagar** [comment]
Oops, this is a different issue than I thought it might be. As you mentioned, I can't see any references to "IHaskell.Display.Demo" anywhere in the source code. However, the name of your repo matches the `ihaskell-*` naming scheme for the IHaskell display modules. What happens if you rename it to e.g. `foo` and try launching an IHaskell noteook. Do you still see this behaviour?

**Comment by erikd** [comment]
Ah!

Renaming the directory alone did nothing, renaming the cabal file and the project name inside the cabal file got me past that problem only to run into a different problem.

I don't know about anyone else, but it i was going to be doing something in IHaskell, the first thing I would be doing is creating a git repo and the obvious name would "ihaskell-<something>. Surely this is something that could and should be fixed.

**Comment by vaibhavsagar** [comment]
I think I've found [where this is happening](https://github.com/gibiansky/IHaskell/blob/c6ca209a437d1690ef35125599564711962cd7da/src/IHaskell/Eval/Evaluate.hs#L177-L239). Essentially IHaskell loads all (support) libraries that are prefixed with `ihaskell-`. This can be surprising but also seems reasonable, and I can't think of a better approach. I have no plans to change this behaviour, and am closing this issue. If there is a different approach you think would work better in general, feel free to reopen.
