### ISSUE TITLE
Fix warnings thrown up by `-Wall`

### ISSUE THREAD

**Issue by vaibhavsagar** [gibiansky/IHaskell#914]

**Comment by erikd** [comment]
If you just add `-Wall` you will be hit by *huge* numbers of warnings.

A better way to to to find what flags are in `-Wall` (see the GHC docs) and then add them one by one. That way it will seem a little less overwhelming.

**Comment by erikd** [comment]
Another option would be to add `{-# GHC_OPTIONS -Wall #-}` to the top of each file and fix files one my one.

**Comment by vaibhavsagar** [comment]
Fixed by #923 and #928, thanks again!
