### ISSUE TITLE
What would be the parameters for a kernel.spec ?

### ISSUE THREAD

**Issue by teto** [gibiansky/IHaskell#920]
I would like to configure this new jupyter service on nixos with this repository haskell kernel.
 https://github.com/NixOS/nixpkgs/issues/45697

I just wondered what parameters I could use to write a ihaskell kernel spec ?
https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs
I suppose sthg along these lines ?
```
{
 "argv": ["ghc", "-f", "ihaskell",
          "-f", "{connection_file}"],
 "display_name": "Heskell",
 "language": "haskell"
}
```

**Comment by vaibhavsagar** [comment]
Something along those lines, with `ihaskell` instead of `ghc`. Here is the kernel spec that is used by the Docker container at `~/.local/share/jupyter/kernels/haskell/kernel.json`:

```json
{
  "display_name": "Haskell",
  "argv": [
    "/home/jovyan/.local/bin/ihaskell",
    "kernel",
    "{connection_file}",
    "--ghclib",
    "/opt/ghc/8.2.2/lib/ghc-8.2.2",
    "+RTS",
    "-M3g",
    "-N2",
    "-RTS",
    "--stack"
  ],
  "language": "haskell"
}
```

You probably don't want the `--stack` option. I'm open to making changes to IHaskell in order to make generating this `kernel.json` easier.

**Comment by teto** [comment]
Great thanks !!
I had to fiddle a bit to adapt it to nix and came up with :
```
          argv = [
            "${ihaskellEnv}/bin/runhaskell"
            # "kernel"
            "{connection_file}"
            "--ghclib"
            "${ihaskellEnv}/lib/ghc-8.4.3"
            "+RTS"
            "-M3g"
            # "-N2" # requires the program to be compiled with threaded
            "-RTS"
          ];

```

There is one problem that prevents me from using it but I am not sure if it's related, so feel free to close the issue if it isn't.

I am using `The version of the notebook server is: 5.6.0` and on launch with ihaskell I get
```
août 29 02:11:52 jedha jupyter-notebook[16351]: [I 02:11:52.845 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
août 29 02:11:53 jedha jupyter-notebook[16351]: /var/lib/jupyter/.local/share/jupyter/runtime/kernel-d87ab031-dec6-4221-8eb4-4ce07b4f9ce8.json:2:22: error:
août 29 02:11:53 jedha jupyter-notebook[16351]:     parse error on input ‘,’
août 29 02:11:53 jedha jupyter-notebook[16351]:   |
août 29 02:11:53 jedha jupyter-notebook[16351]: 2 |   "shell_port": 40777,
août 29 02:11:53 jedha jupyter-notebook[16351]:   |            
```
with the file looking like
```
sudo cat /var/lib/jupyter/.local/share/jupyter/runtime/kernel-d87ab031-dec6-4221-8eb4-4ce07b4f9ce8.json
{
  "shell_port": 35431,
  "iopub_port": 48005,
  "stdin_port": 42257,
  "control_port": 35039,
  "hb_port": 36053,
  "ip": "127.0.0.1",
  "key": "78c6ca07-b98e02748cb48f815743d1da",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": "haskell"
}
```
Any idea why ?

**Comment by teto** [comment]
hum right. 
I chose to use runhaskell because ihaskell could not find ghc-pkg and runhaskell exported  `NIX_GHCPKG='/nix/store/91bk1ami3ns9l49c8r385psy2ga7b8jm-ghc-8.4.3-with-packages/bin/ghc-pkg'` but it's true runhaskell runs ghc and not ihaskell.  Maybe nix should wrap ihaskell to export the NIX_GHCPKG before launching it.

**Comment by vaibhavsagar** [comment]
I don't think IHaskell respects `$NIX_GHCPKG`, but [we modify `$GHC_PACKAGE_PATH` and `$PATH`](https://github.com/gibiansky/IHaskell/blob/000ea0fbe0b9f8a4c881fca3869239375ec26bde/release.nix#L51-L52) before we launch IHaskell (which was taken directly from the existing Nixpkgs support).

**Comment by teto** [comment]
This is more a nix problem than a ihaskell one, I hope that nix packages can generate a kernel.spec that we would just have to load. Meanwhile I managed to make ihaskell work with the current config:
```
        haskell = let 
          ihaskellEnv = pkgs.haskellPackages.ghcWithPackages (self: [
          self.ihaskell
          (pkgs.haskell.lib.doJailbreak self.ihaskell-blaze)
          (pkgs.haskell.lib.doJailbreak self.ihaskell-diagrams)
          (pkgs.haskell.lib.doJailbreak self.ihaskell-display)
          ]);

          ihaskellSh = pkgs.writeScript "ihaskell-wrapper" ''
            #! ${pkgs.stdenv.shell}
            export GHC_PACKAGE_PATH="$(echo ${ihaskellEnv}/lib/*/package.conf.d| tr ' ' ':'):$GHC_PACKAGE_PATH"
            export PATH="${pkgs.stdenv.lib.makeBinPath ([ ihaskellEnv ])}''${PATH:+:}$PATH"
            ${ihaskellEnv}/bin/ihaskell ''$@
          '';
        in {
          displayName = "Haskell for machine learning";
          # https://github.com/gibiansky/IHaskell/issues/920
          argv = [
            "${ihaskellSh}"
            "kernel"
            "{connection_file}"
            "--ghclib"
            "${ihaskellEnv}/lib/ghc-8.4.3"
            "+RTS"
            "-M3g"
            # "-N2" # requires the program to be compiled with threaded
            "-RTS"
          ];
          language = "haskell";
        };

```

Thank you very much for your help that saved me hours.
