### ISSUE TITLE
Docker image built with lts-12.7 cannot find IHaskell.* module

### ISSUE THREAD

**Issue by kyagrd** [gibiansky/IHaskell#922]
I was successful to build and push a docker image to docker hub with only two lines of modification to the Dockerfile of the master branch. You can find the image here and details of how it was built.

https://hub.docker.com/r/kyagrd/ihaskell/

Basic functions of running Haskell is fine but cannot import any of IHaskell.Display.* modules.
I used the stack-8.4.yaml which does not seem to include all the goodies of ihaskell-display but it clearly seems to build some of the libraries but for some reasons my installation cannot find the module.

Do I need to fix the configuration of ghc installation somehow?

Not sure on details but may be related to this issue #913

**Comment by kyagrd** [comment]
Next time I'll try the alternative way following the "Stack development with Docker" section.
But I'll be really glad to use a docker image based on lts-11.22 so if anyone has a working image with ihaskell-display libraries please pushed to docker hub as a public repo :)

**Comment by vaibhavsagar** [comment]
Some of the `ihaskell-*` packages have been [commented out](https://github.com/gibiansky/IHaskell/blob/049796bc9d2a57ee2eabf5983695e022be9c3502/stack-8.4.yaml) because they weren't working when I created the file. Can you try enabling them and seeing if that fixes your issue?

**Comment by kyagrd** [comment]
@vaibhavsagar , there is a same problem with the repo's master branch Dockerfile with lts-11.22

And here is the fix (a bit of a hack because it seems it only works when the WORKDIR is exactly the copy target directory inside docker, but serves the purpose of running a server anyway):

I updated the Docker Hub image according to the following description

https://hub.docker.com/r/kyagrd/ihaskell/
========================================

May bot be a minimal size image.
Just a made-to-work image from gibiansky's GitHub repo master branch, more specifically,
https://github.com/gibiansky/IHaskell/ 2018-08-22 commit 6919aa67d40b2b7525ddf1ad4e553a2a4f2be5eb


## `latest` Tag

Modified last part of `Dockerfile` as follows
```
# Run the notebook
RUN stack exec ihaskell -- install --stack
RUN mkdir ${HOME}/ihaskell/notebooks
WORKDIR ${HOME}/ihaskell
CMD ["stack","exec","jupyter","--", "notebook", "--NotebookApp.token=''", "--ip", "0.0.0.0", "notebooks"]
```

and then

`$ docker build -t ihaskell:latest .`

Above Dockerfile modification is needed to use IHaskell.Display.* modules

Example command line usage:
```
docker run -it -v "`pwd`":/home/jovyan/ihaskell/notebooks -p 80:8888 kyagrd/ihaskell
```

**Comment by kyagrd** [comment]
I won't close this issue someone may come by and find out a way to make it work for lts-12.7 :)

**Comment by vaibhavsagar** [comment]
Oh, I misunderstood the question earlier, I think this is another manifestation of https://github.com/gibiansky/IHaskell/issues/715. It should work if you launch a notebook from within the `ihaskell` directory because the display packages are only in scope then.

**Comment by vaibhavsagar** [comment]
Closing this.
