### ISSUE TITLE
hoogle can't find a function

### ISSUE THREAD

**Issue by teto** [gibiansky/IHaskell#925]
This might be a naive question but I run `:hoogle getFamilyId` to get the doc 
https://hackage.haskell.org/package/netlink-1.0.0.4/candidate/docs/System-Linux-Netlink-GeNetlink-Control.html and it fails with `No result: no matching identifiers found.`
`:type getFamiliyId` works.

The jupyter kernel I use is configured as 
```
        haskell = let 
          ihaskellEnv = pkgs.haskellPackages.ghcWithHoogle (self: [
          self.ihaskell
          (pkgs.haskell.lib.doJailbreak self.ihaskell-blaze)
          (pkgs.haskell.lib.doJailbreak self.ihaskell-diagrams)
          (pkgs.haskell.lib.doJailbreak self.ihaskell-display)
          self.netlink
          ]);

          # ihaskellSh = pkgs.writeScriptBin "ihaskell-wrapper" ''
          ihaskellSh = pkgs.writeScript "ihaskell-wrapper" ''
            #! ${pkgs.stdenv.shell}
            export GHC_PACKAGE_PATH="$(echo ${ihaskellEnv}/lib/*/package.conf.d| tr ' ' ':'):$GHC_PACKAGE_PATH"
            export PATH="${pkgs.stdenv.lib.makeBinPath ([ ihaskellEnv ])}''${PATH:+:}$PATH"
            ${ihaskellEnv}/bin/ihaskell ''$@
          '';
        in {
          displayName = "Haskell for machine learning";
          # https://github.com/gibiansky/IHaskell/issues/920
          argv = [
            "${ihaskellSh}"
            "kernel"
            "{connection_file}"
            "--ghclib"
            "${ihaskellEnv}/lib/ghc-8.4.3"
            "+RTS"
            "-M3g"
            # "-N2" # requires the program to be compiled with threaded
            "-RTS"
          ];
          language = "haskell";
        };

```
The haskell environment does have an html page with netlink documentation so it should be fine (still new to haskell ecosystem) ?! I wonder if ihaskell doesn't use an internet lookup instead (reading https://github.com/gibiansky/IHaskell/pull/825). In which case, why can't it find getFamilyId ? and secondly (how) can one make it use a local hoogle ?

**Comment by vaibhavsagar** [comment]
1. I think it might be because we're using the old Hoogle: https://github.com/gibiansky/IHaskell/issues/820
2. No, it definitely does an internet lookup.
3. Support for a local Hoogle is not currently implemented.

**Comment by teto** [comment]
Thanks for the prompt answer ! 
I suppose supporting an offline (local) hoogle would be nice but I can imagine some workarounds. Also right now internet access is enough for me so closing.
