### ISSUE TITLE
"Could not find module ..." with nix (NixOS) installation

### ISSUE THREAD

**Issue by vanzef** [gibiansky/IHaskell#941]
I've installed and IHaskell on NixOS with the following lines in my `configuration.nix`:
```
  environment = {
    systemPackages = with pkgs; [
    (with python3Packages; python3.withPackages (ps: with ps; [
         jupyter notebook
      ]))
      ihaskell
    ];
  };

  nixpkgs.config = {
    ihaskell.packages = (self: with self; [
      ihaskell-charts
      ihaskell-diagrams
      # ihaskell-display
      diagrams
      ihaskell-plot
    ]);
  };
```

But IHaskell doesn't see `Diagrams.Prelude` module:
```
<interactive>:1:1: error:
    Could not find module ‘Diagrams.Prelude’
```

Is there something I've forgotten to add?

P.S. `ihaskell-diagrams` is commented since it fails to build on latest `nixos-unstable` channel.

**Comment by vaibhavsagar** [comment]
It doesn't look like you're using the provided `ihaskell` service, can you enable that instead of adding `ihaskell` to your `systemPackages`?

**Comment by vanzef** [comment]
`How did you enable the ihaskell service?`
```
    ihaskell = {
      enable = true;
      extraPackages = (self: with self; [
        diagrams
        ihaskell-diagrams
      ]);
    };
```

`This really seems like a question for the nixpkgs issue tracker rather than this one. `
Well, I guess you are right, I'll ask it there. Thanks!

P.S. If you don't mind, I would like this issue to be open for some time, until I get everything working together.

**Comment by vaibhavsagar** [comment]
Did you try the configuration I provided? You have `ihaskell` instead of `services.ihaskell`.

**Comment by vanzef** [comment]
It is indeed `services.ihaskell`. I just forgot to add this since in my config it is nested.

**Comment by vaibhavsagar** [comment]
Have you gotten this working?

**Comment by vaibhavsagar** [comment]
Closing this, please reopen if necessary.
