### ISSUE TITLE
Missing Documentation: Run it with cabal

### ISSUE THREAD

**Issue by pbarill** [gibiansky/IHaskell#945]
This IHaskell is very interesting. I would like to try it. Question:

How can I get it to work? I can't find any information to that matter for installing through cabal. I see instructions about stack, but as I do not intend to do any development on the package here nor care to get experimental bleeding edge, that is not happening.

I get jupyter working, after installing through pip (listing python3 as the only available choice to create a new notebook), and running `cabal exec ihaskell` returns what seems to be the help for ihaskell.

**Comment by pbarill** [comment]
Actually... I figured out:

    cabal exec bash
    ihaskell install
    jupyter notebook

Then I can create a Haskell workbook, but I can't get working kernel. Message that I get on terminal:

```
ihaskell: 
ByteCodeLink.lookupCE
During interactive linking, GHCi couldn't find the following symbol:
  ihaskellzm0zi9zi1zi0zm56QmBZZKDpY08AUYE4oeuUC_IHaskellziIPythonziStdin_fixStdin_closure
This may be due to you not asking GHCi to load extra object files,
archives or DLLs needed by your current session.  Restart GHCi, specifying
the missing library using the -L/path/to/object/dir and -lmissinglibname
flags, or simply by naming the relevant files on the GHCi command line.

```

**Comment by vaibhavsagar** [comment]
Try something like

```
$ cabal install ihaskell
$ ihaskell install
$ jupyter notebook
```

It's important that the `ihaskell` executable is available to Jupyter.

**Comment by pbarill** [comment]
I tried again on another machine, and the same thing works just fine. The difference? First try was an install of Gentoo x86 (32-bit), second one (successful) with Gentoo amd64. Both are pretty much the same otherwise, with GHC 8.0.2. 

Maybe it's a 32-bit related subtlety, and probably not a high priority for you guys (makes sense!). I'll just fix my old amd64 install on that machine and that should make everyone happy.
