### ISSUE TITLE
Possible bug in easyKernel

### ISSUE THREAD

**Issue by Shimuuar** [gibiansky/IHaskell#947]
Messaging [specification](https://jupyter-client.readthedocs.io/en/stable/messaging.html#messages-on-the-shell-router-dealer-channel) says that message IDs must be unique:

```
  'header' : {
                'msg_id' : str, # typically UUID, must be unique per message
```

but `easyKernel` implementation reuses header for sending output:

```haskell
  outputHeader <- dupHeader replyHeader DisplayDataMessage
  (res, replyStatus, pagerOut) <-
    let clearOutput  = ...
        sendOutput x = send $ PublishDisplayData outputHeader (displayOutput config x)
    in run config (getCode req) clearOutput sendOutput
```

If multiple output `sendOuput` will reuse same header if multiple outputs are sent. It seems to work in practice but it's either bug in `sendOutput` or in documentation which fails to mention that sendOutput must be called only once.

**Comment by vaibhavsagar** [comment]
This is taken care of by `dupHeader`:

```haskell
dupHeader :: MonadIO m => MessageHeader -> MessageType -> m MessageHeader
dupHeader hdr mtype =
  do
    uuid <- liftIO UUID.random
    return hdr { mhMessageId = uuid, mhMsgType = mtype }

```
