### ISSUE TITLE
Installation error in Ubuntu

### ISSUE THREAD

**Issue by mittenchops** [gibiansky/IHaskell#966]
Question asked on [Stackoverflow](https://stackoverflow.com/questions/53136410/installing-ihaskell-kernel-for-jupyter-notebooks-lgmp-error)

Following the Ubuntu installation instructions, get an error on the `gtk2hs-buildtools` step:

```
~/downloads/IHaskell$ stack install gtk2hs-buildtools
Linking /home/user/.stack/setup-exe-cache/x86_64-linux/tmp-Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.4 ...
/home/useranaconda3/envs/envname/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
`x86_64-conda_cos6-linux-gnu-cc' failed in phase `Linker'. (Exit code: 1)

```

**Comment by vaibhavsagar** [comment]
It looks like your `anaconda` installation might not be able to find the `gmp` library.

**Comment by vaibhavsagar** [comment]
This doesn't seem like an IHaskell issue.

**Comment by mittenchops** [comment]
Thanks, @vaibhavsagar  Do the installation instructions for Linux as given work for you to install IHaskell?

```curl -sSL https://get.haskellstack.org/ | sh
git clone https://github.com/gibiansky/IHaskell
cd IHaskell
pip3 install -r requirements.txt
stack install gtk2hs-buildtools```

Fails for me on vanilla Ubuntu.  Can we revise these instructions so it does not fail to install on Ubuntu, or at least mark these instructions as valid only for non-Ubuntu linux flavors?

**Comment by mittenchops** [comment]
My read is that the gcc build instructions in gtk2hs-buildtools set up in the stack config do not contain sufficient compiler flags to install correctly.  They rely on a relative path or something, which fails in Ubuntu (maybe succeeds in arch, idk).

**Comment by vaibhavsagar** [comment]
I don't see how I would fix this beyond making changes to `gtk2hs-buildtools`, which I don't control. What happens if you skip that line?

**Comment by mittenchops** [comment]
Thanks, @vaibhavsagar.  If I skip that line and move to the next stack install, I also get an error on the next:

```
bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status

```
Is it possible something in the project's package.yaml or stack.yaml needs an explicit dependency or build flag?

**Comment by vaibhavsagar** [comment]
No, this definitely looks like an issue with your setup.

**Comment by vaibhavsagar** [comment]
When you say "fresh install", does this mean a fresh Ubuntu install with Conda? Unfortunately we don't support using Conda yet.

**Comment by GregorySchwartz** [comment]
I had this issue with anaconda disrupting all of my tasks. Try `PATH="$HOME/.local/bin:/usr/bin:$PATH" stack install gtk2hs-buildtools`. If that doesn't work, just make sure that the `$PATH` has the paths up front for the preferred location of build tools.

**Comment by vaibhavsagar** [comment]
I'm closing this, as
1. This issue has almost nothing to do with Ubuntu
2. This issue has nothing to do with IHaskell
3. It seems Conda-specific and we don't support Conda

**Comment by thautwarm** [comment]
reinstall build plan without conda environment activated.

```
cd IHaskell
stack setup --reinstall
```
