### ISSUE TITLE
Jupyterlab installalation via nix

### ISSUE THREAD

**Issue by dispanser** [gibiansky/IHaskell#970]
I've been trying get jupyterlab to play nicely with the ihaskell kernel, but I can't get it to work.

Here's what I did:

1. pass `jupyterlab` into `pythonPackages` argument of `release.nix`
1. add `ln -s ${ihaskellSh "lab" "--kernel=haskell"}/bin/ihaskell-lab $out/bin/` to the `release.nix` to create wrapper shell script

The result when opening a notebook: 

```
ihaskell: src/IHaskell/IPython/Message/Parser.hs:62:5-95: Irrefutable pattern failed for pattern Just metadataMap
```

The metadata json format that causes the failure:

```javascript
{
  "deletedCells": [],
  "cellId": "ed393d5d-2ef4-41d0-9950-25fd0bb55a4a"
}
```

I'm not sure what's wrong here. Jupyterlab seems to be talking to the ihaskell
kernel so I assume that the basic installation procedure is OK. It seems that
jupyterlab is sending unexpected messages, but since some people (@MMesch)  seem
to have this running, this can't be a general problem.

Any ideas?

**Comment by vaibhavsagar** [comment]
This is a known issue, see https://github.com/gibiansky/IHaskell/issues/912.

**Comment by dispanser** [comment]
sorry! closed.

**Comment by vaibhavsagar** [comment]
No need to apologise :smile:.
