### ISSUE TITLE
Duplicate module IHaskellPrelude

### ISSUE THREAD

**Issue by dispanser** [gibiansky/IHaskell#971]
The module `IHaskellPrelude` exists twice, with identical content: `main/IHaskellPrelude.hs`, `src/IHaskellPrelude.hs`.

I find this confusing (and `ghcid` does not like it either with my setup). Is there any reason to not just export the module from the library and reuse it in the executable? This change seems to work for me locally, but maybe I'm overlooking something.

```
Error: Multiple files use the same module name:
       * IHaskellPrelude found at the following paths
         * /home/pi/wip/data-haskell/IHaskell/main/IHaskellPrelude.hs (ihaskell:exe:ihaskell)
         * /home/pi/wip/data-haskell/IHaskell/src/IHaskellPrelude.hs (ihaskell:lib)
```

**Comment by vaibhavsagar** [comment]
I'm not sure why we did it that way. If you can remove the duplicate module and have everything work I'm happy to make that change.
