### ISSUE TITLE
Should generate config for jupyter notebook

### ISSUE THREAD

**Issue by fleverest** [gibiansky/IHaskell#977]
Not really sure how to implement this in the dockerfile since I'm quite new to docker, but personally (and I'm sure I'm not the only one) I like to add a password to my notebook instead of using the token every time and this requires a config file to exist. My solution was to run `docker exec -t -i container_name /bin/bash` and in the bash simply run `jupyter notebook --generate-config`. I'm not really sure how the docker file works as I haven't really fiddled around with docker much as I've only recently started using it - I might give it a go in the morning.

Honestly I'm very inexperienced when it comes to project development and as a result I rarely suggest fixes on github, so please forgive me if this is not the kind of issue that should be raised in the issue section.

**Comment by vaibhavsagar** [comment]
I'm concerned that a change like this would make the Dockerfile incompatible with https://mybinder.org/. What do you think?

**Comment by fleverest** [comment]
I can't say I'm familiar enough with how mybinder.org operates, but I'm sure the config is never generated at all in this current state since when I was exploring the file system inside the container the directory of the config file didn't exist. So I think it's safe to assume that generating this file will not really affect how the way the site operates?

**Comment by fleverest** [comment]
By the way, to be clear, the error I came across initially was an internal server error when attempting to create a password on the login page [0.0.0.0:8888/login?](url).

**Comment by vaibhavsagar** [comment]
I've merged a change in that hopefully resolves this issue, please try it and let me know either way.

**Comment by fleverest** [comment]
Sorry I forgot to respond after testing it, this worked exactly as intended! Thanks for that

**Comment by vaibhavsagar** [comment]
Great!
