### ISSUE TITLE
New installation in Mac OS Mojave fails

### ISSUE THREAD

**Issue by freefrancisco** [gibiansky/IHaskell#979]
I just got a new mac and tried to replicate the environment of my work mac, which includes ihaskell. I followed the instructions in the readme, installed it from a git clone. Everything installs fine, but when I try to run it I get a weird error that doesn't happen in my work computer that is not running Mojave. Does that mean that ihaskell doesn't work with Mojave and I should hold off updating the OS in my work computer? 
 
ihaskell:
lookupSymbol failed in relocateSection (RELOC_GOT)
/Users/fg/.stack/programs/x86_64-osx/ghc-8.4.4/lib/ghc-8.4.4/integer-gmp-1.0.2.0/HSinteger-gmp-1.0.2.0.o: unknown symbol `___gmp_rands'
ihaskell: ihaskell: unable to load package `integer-gmp-1.0.2.0'
[I 02:48:32.932 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
ihaskell:
lookupSymbol failed in relocateSection (RELOC_GOT)
/Users/fg/.stack/programs/x86_64-osx/ghc-8.4.4/lib/ghc-8.4.4/integer-gmp-1.0.2.0/HSinteger-gmp-1.0.2.0.o: unknown symbol `___gmp_rands'
ihaskell: ihaskell: unable to load package `integer-gmp-1.0.2.0'
[I 02:48:35.947 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports

**Comment by vaibhavsagar** [comment]
This doesn't look like an IHaskell-specific issue. Try this: https://ghc.haskell.org/trac/ghc/ticket/15105#comment:10

**Comment by freefrancisco** [comment]
That worked, thank you! 
If someone else is having this issue, all you have to do is remove that file, HSinteger-gmp-1.0.2.0.o. and things work fine after that.
