### ISSUE TITLE
Installing a package inside existing docker container

### ISSUE THREAD

**Issue by fleverest** [gibiansky/IHaskell#985]
Is this possible? It would be very convenient since my current approach is to simply alter the stack.yaml file in the git clone and then rebuild the image and run it. Does the ihaskell notebook run a Haskell kernel locally installed in the ~/ihaskell/ directory (inside the container)? If so that should mean that I can just run `stack install packagename-version` in that directory, right? This hasn't been working for me so far, so I'm not really sure how I can do that yet.

**Comment by fleverest** [comment]
For example, if we create a notebook using the mybinder.org app, is there any way that we can install a package and use it in the notebook? My initial attempt is to simply go to New>Kernel inside the notebook, and navigate to the ihaskell directory where I can run `stack install statistics-0.15.0.0` or something. The issue with this approach is that it throws an error and suggests adding a few extra-deps to the stack.yaml folder, which we cannot edit as we have insufficient permissions to `nano stack.yaml`.

**Comment by jamesdbrock** [comment]
For anyone who googled to this issue, here is a Docker file which has answers for these questions: https://github.com/jamesdbrock/ihaskell-notebook
