### ISSUE TITLE
Unicode Math Characters Are Red

### ISSUE THREAD

**Issue by steinitznavican** [gibiansky/IHaskell#992]
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/43856516/50601814-356d5700-0ead-11e9-93c3-7fb0cd116584.png">

**Comment by steinitznavican** [comment]
I inserted \theta in a Julia notebook by typing "\theta" followed by a TAB. It is black but when I paste it into my Haskell notebook it is red. It would be even better if I could do the same in Haskell but obviously get a black theta.

**Comment by vaibhavsagar** [comment]
This looks like an issue with the CodeMirror Haskell mode: https://codemirror.net/mode/haskell/. I tried putting θ in the text box and it was also highlighted red.

**Comment by vaibhavsagar** [comment]
Closing as this isn't an issue with IHaskell.
