### ISSUE TITLE
Does not work outside IHaskell directory

### ISSUE THREAD

**Issue by tiborkiss** [gibiansky/IHaskell#995]
I build IHaskell from source in Ubuntu 16.04.

I was able to build from source in python3 virtual env, then I run from IHaskell directory.
I created some examples and seems to work well, but I would like to have the jupyter working directory outside of IHaskell directory, doesn't seems to work anymore.
I get the following error:

`
 [I 15:54:48.468 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
ihaskell: Bad interface file: /home/tibor/.stack/programs/x86_64-linux/ghc-8.6.3/lib/ghc-8.6.3/base-4.12.0.0/Prelude.hi
    mismatched interface file versions (wanted "8044", got "8063")
Bad interface file: /home/tibor/.stack/programs/x86_64-linux/ghc-8.6.3/lib/ghc-8.6.3/directory-1.3.3.0/System/Directory.hi
    mismatched interface file versions (wanted "8044", got "8063")
Bad interface file: /home/tibor/.stack/programs/x86_64-linux/ghc-8.6.3/lib/ghc-8.6.3/unix-2.7.2.2/System/Posix/IO.hi
    mismatched interface file versions (wanted "8044", got "8063")
Bad interface file: /home/tibor/.stack/programs/x86_64-linux/ghc-8.6.3/lib/ghc-8.6.3/base-4.12.0.0/System/IO.hi
    mismatched interface file versions (wanted "8044", got "8063")
Bad interface file: /home/tibor/.stack/programs/x86_64-linux/ghc-8.6.3/lib/ghc-8.6.3/template-haskell-2.14.0.0/Language/Haskell/TH.hi
    mismatched interface file versions (wanted "8044", got "8063")

[I 15:54:51.484 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
ihaskell: Bad interface file: /home/tibor/.stack/programs/x86_64-linux/ghc-8.6.3/lib/ghc-8.6.3/base-4.12.0.0/Prelude.hi
    mismatched interface file versions (wanted "8044", got "8063")
Bad interface file: /home/tibor/.stack/programs/x86_64-linux/ghc-8.6.3/lib/ghc-8.6.3/directory-1.3.3.0/System/Directory.hi
    mismatched interface file versions (wanted "8044", got "8063")
Bad interface file: /home/tibor/.stack/programs/x86_64-linux/ghc-8.6.3/lib/ghc-8.6.3/unix-2.7.2.2/System/Posix/IO.hi
    mismatched interface file versions (wanted "8044", got "8063")
Bad interface file: /home/tibor/.stack/programs/x86_64-linux/ghc-8.6.3/lib/ghc-8.6.3/base-4.12.0.0/System/IO.hi
    mismatched interface file versions (wanted "8044", got "8063")
Bad interface file: /home/tibor/.stack/programs/x86_64-linux/ghc-8.6.3/lib/ghc-8.6.3/template-haskell-2.14.0.0/Language/Haskell/TH.hi
    mismatched interface file versions (wanted "8044", got "8063")

[W 15:54:54.497 NotebookApp] KernelRestarter: restart failed
[W 15:54:54.498 NotebookApp] Kernel 1807f571-39c2-444e-8885-f4c2986014e1 died, removing from map.
`

My ~/.local/share/jupyter/kernels/haskell/kernel.json is the following:
`
{"display_name":"Haskell","argv":["/home/tibor/.local/bin/ihaskell","kernel","{connection_file}","--ghclib","/home/tibor/.stack/programs/x86_64-linux/ghc-8.4.4/lib/ghc-8.4.4","+RTS","-M3g","-N2","-RTS","--stack"],"language":"haskell"}
`

Since I had a few issues while building, I list here finally how I was able to build and run.

I use Python3 and virtualenv. 
`
virtualenv venv-ihaskell -p /usr/bin/python3
source venv-ihaskell/bin/activate
`
Then as in the main page
`
curl -sSL https://get.haskellstack.org/ | sh
git clone https://github.com/gibiansky/IHaskell
cd IHaskell
pip3 install -r requirements.txt
stack install gtk2hs-buildtools
stack install --fast
ihaskell install --stack
`
While installing, I run in the following 

>  ipython 7.2.0 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.

I found a solution to this described in [jupyter repo.](https://github.com/jupyter/jupyter/issues/370#issuecomment-426270277)

According to that link above, I did the following:

`
pip3 uninstall ipykernel
pip3 install ipykernel==4.10.0
`

Then I repeat the pip3 install -r requirements.txt and continue with stack install.

Then I run in IHaskell directory with:

`
stack exec jupyter -- notebook
`

Maybe is trivial to solve this problem of running outside IHaskell directory. Then please help.
(I also have nix, nixops in my laptop, but for me nix environment seems to be more difficult to understand at this point, maybe later.)

**Comment by tiborkiss** [comment]
I see an[ old, already closed ](https://github.com/gibiansky/IHaskell/issues/690#issuecomment-250997571) issue which seems to touch similar problem.
Currently, I am running with lts-12.26 with GHC 8.4.4.

**Comment by vaibhavsagar** [comment]
As described in https://github.com/gibiansky/IHaskell/issues/986#issuecomment-449752909, please either run IHaskell inside a Stack project directory running `lts-12.*` or upgrade your `~/.stack/global-project/stack.yaml` to `lts-13.1`, move `stack-8.6.yaml` to `stack.yaml`, and reinstall.

**Comment by tiborkiss** [comment]
Thank you. I chose lts-12.15 within a stack project.
